assets/components/src/category-autocomplete/index.js
assets/components/src/category-autocomplete/style.scss
assets/wizards/popups/components/settings-modal/index.js

https://github.com/Automattic/newspack-popups/pull/641 added the ability to specify categories and tags on which a prompt will NOT be shown. However, the fields for these settings exist only in the single prompt block editor, not in the Campaigns wizard UI. This PR adds the fields to the wizard UI.
Closes https://github.com/Automattic/newspack-popups/issues/747.
1. Check out this branch. Go to **Newspack > Campaigns** and click the settings icon to view settings for a prompt. Confirm that there's a new toggle button in the "Targeting" section:
3. Confirm that clicking the button shows and hides the new fields.
4. Start typing category and tag names in each field. Confirm that you're able to search categories and tags, and select one or more for each corresponding field.
5. Save the prompt …

feat(popups): add category/tag exclusion fields to campaigns wizard UI

---

includes/class-donations.php

Updates how the default donations page looks like.
1. Remove the `newspack_donation_page_id` option to reset the default donations page
2. Visit the Reader Revenue wizard, "Donations" tab. Click "Edit Page" in "Donations landing page" section
3. Publish the page and visit it
4. Observe the page uses a template without the sidebar

feat(donations): remove sidebar for default donations page

---

includes/configuration_managers/class-newspack-ads-configuration-manager.php
includes/oauth/class-fivetran-connection.php
includes/wizards/class-advertising-wizard.php

Update Ads methods to match https://github.com/Automattic/newspack-ads/pull/348
1. Without connecting to GAM make sure you are able to edit the network ID and manage legacy ad units
2. Connect to GAM and make sure you are able to edit ad units
3. Modify suppression settings and make sure they are applied

chore: update ads api

---

includes/wizards/class-advertising-wizard.php

Handles GAM error in case the connection status method returns `WP_Error`.
1. Check out https://github.com/Automattic/newspack-ads/pull/348 to make sure the different method names causes an error
2. While on master visit the Ads wizard and confirm the unhandled error
3. Check out this branch and confirm the error message is appropriate (since the method names changed, it doesn't identify that the plugin is installed and active)

fix(ads): handle gam connection error

---

includes/class-plugin-manager.php

Fixes misconfiguration on Ads Add-Ons introduced by #1564.
1. While on master make sure do not having the Add-Ons plugins downloaded (SCAIP and Ad Refresh Control)
2. Attempt to install through the Plugins page, both plugins should be listed and nested inside the Newspack plugin
3. Notice the download error
4. Check out this branch, attempt to download again, and confirm it downloads the latest version from WPOrg

fix(ads): add-ons download methods

---

assets/wizards/advertising/components/ad-refresh-control/index.js

Currently, the Ad Refresh Control settings at the Ads wizard are not clearable due to a falsy check on input values.
1. While on master, visit the Ads wizard -> Add-Ons and make sure you have Ad Refresh Control toggled on
2. Visit the Settings wizard, write some input values and attempt to remove
3. Confirm you are not able to remove the value
4. Check out this branch, run `npm run build` and confirm you are able to remove

fix(ads): allow clearing ad refresh control input

---

includes/class-newspack.php

Re-enable the use of block-based widgets. Should be reviewed along with the following:
- https://github.com/Automattic/super-cool-ad-inserter-plugin/pull/99
- https://github.com/Automattic/newspack-blocks/pull/1066
- https://github.com/Automattic/newspack-ads/pull/322

fix: enable block-based widgets

---

assets/wizards/setup/index.js
assets/wizards/setup/style.scss
assets/wizards/setup/views/completed/index.js

Hides the navigation on the last step of the Setup wizard.
1. On `master`, visit the last step of the Setup wizard (`wp-admin/admin.php?page=newspack-setup-wizard#/completed`)
2. Observe a navigation bar, which should not be there
3. Switch to this branch, rebuild, observe there's no navigation bar on first and last steps of the Setup wizard

fix(setup-wizard): hide header on completed step

---

assets/wizards/readerRevenue/views/stripe-setup/newsletter-settings.js

Small typo on the Newsletters section of the Stripe Settings wizard.

fix(stripe): newsletters wizard typo

---

CHANGELOG.md
includes/popups-analytics/class-popups-analytics-utils.php
newspack.php
package-lock.json
package.json
tests/unit-tests/popups-analytics.php

https://github.com/Automattic/newspack-popups/pull/830 added segment names to the `event_label` strings sent with Google Analytics event reporting. This changed the label from a format like this:
```
Above Header: Spring campaign 2022 banner ad (112982)
```
to this:
```
Above Header: Spring campaign 2022 banner ad (112982) - Everyone
```
With the segment(s) coming after the post ID. However, the Campaigns analytics report expects the post ID in parentheses to be the last item in the label, so it's ignoring rows that have the segment names appended—basically all events after https://github.com/Automattic/newspack-popups/pull/830 got deployed. This PR amends the regex patterns to look for the post ID anywhere in the label, not just at the end, which should fix the reporting view.
It's hard …

fix(popups): analytics popups report label regex

---

assets/wizards/advertising/components/ad-refresh-control/index.js

Update Ad Refresh Control setting help text according to https://github.com/Automattic/newspack-ads/issues/370
Confirm the help text is updated by following the instructions at https://github.com/Automattic/newspack-ads/pull/373

fix(ads): update refresh control help text

---

includes/api/class-plugins-controller.php
includes/wizards/class-setup-wizard.php

Closes #543. 
Note that with `DISALLOW_FILE_MODS` the user still won't be able to complete the Setup wizard in Newspack UI only – they'll have to install the required plugins somehow and come back. But the UI is clear on that:
1. While on `master`, add `define('DISALLOW_FILE_MODS',true);` to `wp-config.php`
2. Observe that the Setup wizard is not loadable, the Site Design wizard is throwing an error, and handoff links* to plugins don't work
3. Switch to this branch, observe the issues are gone
\* e.g. Analytics wizard – there's a handoff link to Site Kit

fix: relax capabilities required to interact with Newspack

---

assets/components/src/notice/index.js
assets/components/src/notice/style.scss
assets/components/src/with-wizard-screen/index.js
assets/components/src/wizard/index.js
assets/wizards/componentsDemo/index.js
assets/wizards/dashboard/index.js
assets/wizards/dashboard/style.scss

Inspired by WPCOM sandboxes, this PR moves the debug notice to the bottom of the screen and changes its position to "fixed".
1. Make sure you have debug mode enabled
2. Check the wizards
4. Check the wizards once again

Update debug mode notice style and position

---

includes/popups-analytics/class-popups-analytics-utils.php
tests/unit-tests/popups-analytics.php

Just a naming/comments refactor. See if it's all clear now. Tests diff is messy since I've moved the tests around, to start with the encoded-events test.

chore: clear up the confusion around "legacy" popups analytics events

---

includes/class-admin-plugins-screen.php
includes/class-handoff-banner.php
includes/class-newspack.php
includes/class-salesforce.php
includes/reader-revenue/class-reader-revenue-emails.php
includes/wizards/class-advertising-wizard.php
includes/wizards/class-analytics-wizard.php
includes/wizards/class-components-demo.php
includes/wizards/class-connections-wizard.php
includes/wizards/class-dashboard.php
includes/wizards/class-engagement-wizard.php
includes/wizards/class-health-check-wizard.php
includes/wizards/class-popups-wizard.php
includes/wizards/class-reader-revenue-wizard.php
includes/wizards/class-seo-wizard.php
includes/wizards/class-setup-wizard.php
includes/wizards/class-site-design-wizard.php
includes/wizards/class-syndication-wizard.php
newspack.php

Closes #99
Visit the wizards and confirm that the JS & CSS assets have the current version appended as the cache-busting parameter.

chore: improve asset cache busting

---

includes/reader-revenue/class-woocommerce-connection.php

Adds integration with `woocommerce-memberships` plugin.
1. Switch to `add/handle-wc-memberships` branch of `newspack-blocks` plugin (https://github.com/Automattic/newspack-blocks/pull/1096)
2. Follow the setup from https://github.com/Automattic/newspack-plugin/pull/1593 (steps 1-3)
3. Activate `woocommerce-memberships` plugin and set up a membership plan* tied to donations
4. In a session as a non-logged-in visitor, confirm the content is restricted (as per membership plan) and make a donation
5. Observe the restricted content is now visible
6. Observe that a user account was created and you're now logged in by visiting `/wp-admin` page
7. In a different session, make a donation as an already logged-on user. Observe the restricted content is now visible as per plan
\* e.g. restrict all …

feat(donations-stripe): integrate w/ woocommerce-memberships

---

assets/components/src/category-autocomplete/index.js
assets/wizards/popups/components/settings-modal/index.js

Fixes two JS errors that result in a hard crash when "selecting" an undefined item in the autocomplete fields in the Campaigns wizard UI. The change to `assets/components/src/category-autocomplete/index.js` will require a new NPM version release to fix in the NPM package.
Closes https://github.com/Automattic/newspack-popups/issues/810.
1. On `master`, visit the **Newspack > Campaigns** wizard. Click the settings icon to open the settings modal:
2. In the Category, Tag, or Category/Tag Exclusion fields, start typing in a term and hit enter without having a term highlighted. Observe that the UI crashes with a JS console error.
3. Check out this branch and repeat, confirming that the UI does not crash and that hitting enter is harmless and doesn't result in changing the autocomplete input's …

fix: crashes with autocomplete inputs in Campaigns wizard and CategoryAutocomplete

---

includes/class-salesforce.php

Fixes a PHP warning on successful Salesforce sync due to an incorrectly named variable that was also causing some post meta to not be saved.
1. Set up a WooCommerce/Salesforce connection via Reader Revenue. DM me if you need credentials.
2. Complete any order (donation, product, self-serve listing, etc.) or manually sync an existing order in the Edit Order dashboard page.
3. Observe a PHP warning upon successful Salesforce sync: 
```
PHP Notice:  Undefined variable: response in /wp-content/plugins/newspack-plugin/includes/class-salesforce.php on line 675
```
4. Check out this branch, repeat step 2, and confirm that the warning isn't thrown. Also confirm that the order has an array of Opportunity IDs stored as `newspack_salesforce_opportunities` post meta (via WP CLI: `wp post meta list …

fix(salesforce): a PHP warning on sync completion due to incorrect variable

---

includes/class-plugin-manager.php

Closes #298
Also adds some GravityForms add-on plugins to the list of supported (but not managed) plugins.
1. Create a dummy plugin called `wordpress-seo-premium`*
2. Deactivate Yoast and visit the SEO wizard
3. Observe a plugin installation prompt for Yoast 
4. Activate the `wordpress-seo-premium` plugin, reload the wizard, observe the wizard loading (with some issues, but that's cause plugin is a dummy)
5. Visit the Health Check wizard, observe that no issue with Yoast are reported there
\* Add a `wordpress-seo-premium/main.php` [file](https://developer.wordpress.org/plugins/plugin-basics/header-requirements/).

fix: handle Yoast Premium as a replacement for Yoast

---

includes/reader-revenue/class-woocommerce-connection.php

Closes #1156
1. On `master`, install & activate WooCommerce
2. Observe a "WooCommerce Setup" item in the main WP dashboard
3. Switch to this branch, observe the item is gone

feat(woocommerce): hide setup task list

---

includes/reader-revenue/class-woocommerce-connection.php

While activating WooCommerce, the `setup` `TaskList` can return `null` and must be checked.
1. On the master branch, deactivate WooCommerce
2. Activate WooCommerce and confirm the fatal error
3. Check out this branch, repeat the steps and confirm the plugin activates without errors

fix(woocommerce): ensure task list exists before hiding

---

includes/reader-revenue/class-woocommerce-connection.php

Because the order was created as completed, an email was sent right away to the site admin, with a 0 as order total.
1. Choose "Stripe" as the Reader Revenue platform and make sure your site is available publicly (so Stripe webhook can be called)
2. On `master`, make a donation using the Donate block
3. Observe an email is sent to site admin with no order details and 0 as total
4. Switch to this branch, observe the email sent has order details and correct amount

fix(reader-revenue): initial order state with total of 0

---

CHANGELOG.md
includes/plugins/class-jetpack.php
newspack.php
package-lock.json
package.json

Fixes an issue with Jetpack – featured images are lazy-loaded in RSS feeds. Yet to submit a bug on Jetpack.
1. Install ["Shoyu RSS/Atom Feed Preview" chrome extension](https://chrome.google.com/webstore/detail/shoyu-rssatom-feed-previe/ilicaedjojicckapfpfdoakbehjpfkah) to preview a feed (other RSS viewers seem to handle the lazy-loaded images)
2. On `master`, with Jetpack configured, preview site's feed (`site.com/feed`) and observe the featured images are missing
3. Switch to this branch, observe the featured images are displayed

fix(rss-feeds): skip Jetpack lazy loading on RSS feeds

---

assets/wizards/advertising/views/ad-units/index.js

Wizard changes to properly handle the default ad units implementation from https://github.com/Automattic/newspack-ads/pull/406
Testing instructions at https://github.com/Automattic/newspack-ads/pull/406

feat(ads): handle gam default ad units

---

includes/oauth/class-google-oauth.php
tests/unit-tests/oauth.php

- Slightly tweaks how Google OAuth credentials retrieval handles failure – always returning an array. 
- Adds some `Logger` statements for easier debugging.
1. Set `NEWSPACK_LOG_LEVEL` env. variable to `2`
1. Configure site to use Google OAuth and complete the OAuth flow
2. Observe the site logs verbose messages along the way

refactor(oauth): google oauth handling

---

includes/oauth/class-google-oauth.php

Fixes handling of failed OAuth credentials saving.
1. On `master`, explicitly return a `WP_Error`* from `save_auth_credentials` – try to connect Google via OAuth and observe it failing silently
2. Switch to this branch, observe the error returned to the front-end
\* Comment out the CSRF condition

fix: oauth error handling

---

CHANGELOG.md
includes/oauth/class-google-oauth.php
newspack.php
package-lock.json
package.json
tests/unit-tests/oauth.php

Combining recently-merged #1682 and #1687 in a hotfix, which improve OAuth error handling and debugging. Also bumping `newspack-scripts` (also merged to `master` in 8e32f7a2e242f3e52fd76bb933f7a7f74a1f597f) – the new version prevents post-hotfix overrides.

Hotfix – OAuth logging and errors

---

assets/wizards/popups/index.js

Not sure why would Jetpack be required to handle Campaigns.

chore(wizards): don't require jetpack for popups (campaigns) wizard

---

includes/class-analytics.php
includes/class-newspack.php
includes/configuration_managers/class-site-kit-configuration-manager.php
includes/plugins/google-site-kit/class-googlesitekit.php
includes/plugins/google-site-kit/class-googlesitekitanalytics.php
tests/class-newspack-unit-tests-bootstrap.php

Adds automatic setup of GA4 property with Site Kit, if the property exists in GA. This is a PR to `alpha`, so it's included with the next release.
_Initially submitted as https://github.com/Automattic/newspack-plugin/pull/1681._
Test on a site with Site Kit configured and Universal GA connected, but GA4 not connected.  
1. Confirm that the page is not sending hits to the GA4 property on `master`*
1. Visit Site Kit's Analytics settings page (`/wp-admin/admin.php?page=googlesitekit-settings#/connected-services/analytics`) and observe that GA4 is connected 
3. Visit an AMP page and confirm the GA4 snippet is inserted (search for `GA4_MEASUREMENT_ID` in the page source) and GA4 property is hit**
\* Just one `POST` request with `pageview` in payload to `google-analytics.com` should be sent
\** …

feat(analytics): automatically link GA4 with Site Kit

---

includes/class-salesforce.php

Fixes an issue where if you had previously set up a Salesforce integration on the Newspack Reader Revenue platform, then changed to a different platform that still uses WooCommerce (e.g. Stripe), the Salesforce webhooks would still fire and attempt to sync, but fail because the orders don't contain the expected data. This fixes the issue by deactivating the webhooks if the wrong Reader Revenue platform is active, which should help clean up the debug log.
1. On `master`, make sure WooCommerce and all required extensions are installed and active. Set your Reader Revenue platform to "Newspack" and set up a [Salesforce integration](https://newspack.pub/support/reader-revenue/salesforce/). Ping me if you need test credentials. 
2. Change your platform to Stripe and complete Stripe …

fix: deactivate Salesforce syncing if RR platform is not Newspack

---

assets/components/src/wizard/store/index.js
assets/wizards/dashboard/index.js
assets/wizards/syndication/views/intro/index.js
includes/class-newspack.php
includes/class-plugin-manager.php
includes/class-wizards.php
includes/optional-modules/class-rss.php
includes/wizards/class-settings.php
tests/unit-tests/settings.php

Incorporates [`newspack-rss-enhancements` plugin](https://github.com/Automattic/newspack-rss-enhancements/) into the core plugin, as an optional module.
1. On a site with no `newspack-rss-enhancements` plugin installed, observe there's no "RSS Feeds" menu item
2. Visit Newspack Settings wizard by following a link in the plugin UI footer
3. Observe the module is turned off by default
4. Turn the module on, after navigating or refreshing the page observe the "RSS Feeds" menu item is available
5. Now on a site with `newspack-rss-enhancements` active, observe the module is turned on by default, but the `newspack-rss-enhancements` plugin has been deactivate on loading admin UI

feat(rss): add RSS Enhancements plugin to the core

---

assets/wizards/advertising/views/ad-units/index.js

Always allow a disconnected GAM client to use service account connection.
Instructions at https://github.com/Automattic/newspack-ads/pull/433

fix(ads): always allow service account credentials

---

assets/components/src/autocomplete-with-suggestions/index.js

Plugs a hole in the functionality of the `AutocompleteWithSuggestions` component. Currently, it shows selected items in the suggestions list based solely on numeric ID; however, it's possible that multiple items in the suggestion list could have the same ID. So this change compares both ID and label values, which should make the selections more accurate.
This is a prerequisite for the fix in https://github.com/Automattic/newspack-blocks/pull/1154. It will need to be released to the `newspack-components` NPM package, and that package will need to be version-bumped in Newspack Blocks.
Follow the testing instructions in https://github.com/Automattic/newspack-blocks/pull/1154 to confirm that you can select a single item in the suggestions list when multiple suggestions share an ID value.

fix: compare both IDs and labels for autocomplete selections

---

includes/class-magic-link.php
includes/class-newspack.php
includes/class-reader-activation.php
tests/unit-tests/magic-link.php

This PR implements magic link functionality that should only be available to a "reader", as implemented by #1655.
Magic links are single-use authentication links that are sent to the user's registered email.
This implementation limits the number of simultaneous valid tokens to 5, which should be a safe amount in case the reader attempts to authenticate multiple devices at once. The limit is also a safety measure, because magic link creation, naturally, does not require authentication.
Also as a safety measure, magic links expire 30 minutes after creation.
This feature should only be available with reader activation enabled.
Magic links can be generated and sent by an anonymous user, these are self-served. Self-served links have a salted client hash attached to them. They are formed by the …

feat: magic links

---

includes/class-plugin-manager.php

Adds `wp-parsely` to the list of "required" plugins for the Newspack platform. Coupled with the PR in the private Manager repository, it makes it difficult to deactivate or delete this plugin from the Plugins dashboard page.
Closes #1702.
Follow instructions in the private manager plugin repository.

feat: disable deactivate and delete for required plugins

---

assets/wizards/readerRevenue/views/stripe-setup/index.js
includes/reader-revenue/class-stripe-connection.php
includes/wizards/class-reader-revenue-wizard.php

Closes #1666.
1. On a site with Stripe set up a the Reader Revenue platform, visit the Reader Revenue wizard
2. If Stripe webhook exists for the site, confirm that another one can't be added ("Create Webhook" button is disabled)
3. If Stripe webhook does not exist, confirm it can be added

feat(reader-revenue): prevent creating duplicate stripe webhooks

---

includes/reader-revenue/class-stripe-connection.php

Closes #1699
1. On `master`, activate WooCommerce and configure Stripe as Reader Revenue platform
2. Make a donation
3. Observe two emails are sent – one from Newspack ("Thank You" subject), and one from WC ("Your <site_title> order is now complete")
4. Switch to this branch, observe only the former is sent

fix(reader-revenue): disable WC email if module will send email

---

assets/components/package.json

Published the fix from #1679 to the [newspack-components NPM package](https://www.npmjs.com/package/newspack-components) as v2.1.0, so bumping the version number here to match.
Nothing to test.

chore: publish v2.1.0 of newspack-components

---

includes/class-reader-activation.php

Extend the cookie expiration length to 1 year for users identified as readers and the auth option set to "remember".
Closes #1750.
1. Make sure you have Reader Activation enabled and with AMP Plus+WC+Stripe setup, while logged out donate through the donate block using a new email
2. Verify the generated cookie and confirm it lasts 1 year
3. Log out and authenticate your admin account with the "Remember" option checked
4. Confirm your auth cookie lasts 2 weeks (WP standard)

feat(reader-activation): extended auth expiration

---

assets/blocks/index.js
assets/blocks/reader-registration/block.json
assets/blocks/reader-registration/edit.js
assets/blocks/reader-registration/editor.scss
assets/blocks/reader-registration/index.js
assets/blocks/reader-registration/index.php
assets/blocks/reader-registration/style.scss
assets/blocks/reader-registration/view.js
assets/reader-activation/index.js
includes/class-blocks.php
includes/class-newspack.php
includes/class-patches.php
includes/class-reader-activation.php
webpack.config.js

Implements a simple reader registration block integrated with a reader activation frontend js library. The block features should be later expanded to include:
- Optional newsletter subscription through API provided by newspack-newsletters with:
- Default list to assign the reader to, or;
- Allow the reader to select from a list
- Social login with Google and Facebook
This PR also introduces a small js library to allow easy communication between current and future reader activation front-end components on XHR requests.
Given the optimistic quality of the reader activation's auth intention, once a reader registers through the block, the `readerActivation.setReader( { email } );` is called regardless of authenticating or not. This method dispatches the `reader` event, which can be listened …

feat(reader-activation): registration block

---

.distignore
includes/class-blocks.php

#1724 introduced releasable files in `assets`, but `assets` was not meant for release (just for file from which to build release files). This PR fixes is by excluding only JS/SCSS from `assets`, so PHP and JSON can make it through.
1. On `master`, build plugin locally (`npm run build && npm run release:archive`), observe it fails to install on a site
1. Build from this branch, observe no installation issues

fix: include blocks' files in release

---

includes/class-amp-enhancements.php

Adds Complianz plugin handling to AMP Plus. 
1. On `master`, enable AMP Plus and set up Complianz plugin
2. In Complianz -> Integrations -> Plugins ensure "AMP" is toggled on
3. Disable AMP on a page
4. Observe that on page with AMP disabled, the non-AMP (more interactive) version of the cookie prompt is displayed 
5. Observe that on an AMP page, the AMP (`amp-consent`) version is displayed
6. Switch to this branch, observe no change in the above behaviour
7. Toggle Complianz's AMP integration off and observe the non-AMP prompt is always displayed

fix(amp-plus): handle complianz-gdpr plugin

---

includes/class-reader-activation.php
tests/unit-tests/reader-activation.php

Restrict specific user roles (admin and editors) from being identified as readers. This could happen if a user is initially created through reader registration and later updated to a different role. This PR ensures that a restricted role check is prioritized over other checks.
Unit test for `Reader_Activation::is_user_reader()` method should pass.

feat(reader-activation): restricted reader roles

---

includes/class-magic-link.php
includes/class-reader-activation.php

Make authentication cookies on registration short-lived and magic links a session refresh.
1. With Reader Activation enabled, make sure you have a page with the Reader Registration block
2. Visit the page anonymously and register with a new email
3. Check your cookies and confirm your auth cookie (`wordpress_logged_in_`) lasts 24 hours and **keep this session open**
4. While logged in as administrator send a magic link to the recently created user (Dashboard -> Users -> Send authentication link)
5. Copy that link and paste it to the reader session
6. Check the cookies and confirm the cookie now lasts 1 year
7. Send another magic link but this time paste it on your admin session
8. Confirm you see an error since a logged-in user can only use a magic link to refresh your existing session

feat(reader-activation): registration auth cookie control

---

assets/wizards/readerRevenue/views/stripe-setup/index.js
includes/reader-revenue/class-stripe-connection.php
includes/wizards/class-reader-revenue-wizard.php
tests/class-stripemockhttpclient.php
tests/unit-tests/stripe-connection.php

Adds auto-setup of Stripe webhook, and validation of it.
1. Test on a site with Stripe configured as Reader Revenue platform
2. Load Reader Revenue wizard –> Stripe Settings and observe all is well
3. Disable the webhook in Stripe, observe error being shown in the wizard
4. Enable the webhook and change its URL, again observe an appropriate error
5. Remove the webhook in Stripe and observe an appropriate error 
6. Click "Reset webhooks" next to the error message to recreate the webhook – observe the page reloading and now displaying errors
7. Observe the webhook recreated in Stripe

feat(stripe): webhook auto-creation and validation

---

assets/wizards/popups/utils.js
includes/wizards/class-popups-wizard.php

Handles new frequency options from https://github.com/Automattic/newspack-popups/pull/908 in the Campaigns dashboard UI.
Eventually we could create UI to manage the "Custom" option settings in the dashboard UI, but since this experimental for now we leave these to be managed in the block editor only.
Follow testing instructions in https://github.com/Automattic/newspack-popups/pull/908.

feat: handle new frequency options in Campaigns dashbaord

---

includes/configuration_managers/class-newspack-newsletters-configuration-manager.php
includes/reader-revenue/class-stripe-connection.php
includes/reader-revenue/class-woocommerce-connection.php

Ensures that the method from https://github.com/Automattic/newspack-popups/pull/922 is used to generate donation events when Stripe transactions sync to WooCommerce orders.
See https://github.com/Automattic/newspack-popups/pull/922.

fix(popups): use new Campaigns method for creating donation events on new orders

---

includes/class-donations.php
includes/reader-revenue/class-woocommerce-connection.php

Readers are registered via Reader Activation when they subscribe to a newsletter, make a recurring WooCommerce donation, or a single or recurring Stripe donation. They are currently NOT registered when making a single WooCommerce donation. This closes that loop and registers those readers as well.
Closes #1791.
1. Check out this branch, ensure that reader activation is enabled on your site.
2. In new browser sessions, make several single and recurring donations with both WooCommerce and Stripe platforms.
3. Ensure that you're registered and pre-authenticated in each case.

feat: register anonymous single donors

---

assets/blocks/reader-registration/edit.js
assets/blocks/reader-registration/editor.scss
assets/blocks/reader-registration/index.php
assets/blocks/reader-registration/style.scss

This is a small PR that adds an icon to the success state.
2. Add reader registration block (don't click on "success")
3. Check front-end
4. On a new page Add reader registration block (and click on "success")
5. Check front-end

feat(registration-block): add success icon

---

assets/blocks/reader-registration/edit.js

`editedState` should never have been a prop on a `Button`, it was here accidentally.

remove unused prop

---

assets/blocks/reader-registration/index.php
assets/blocks/reader-registration/view.js
includes/class-newspack.php
includes/class-reader-activation.php
includes/plugins/class-newspack-newsletters.php
includes/reader-revenue/class-stripe-connection.php

Contact adding/updating (w/ metadata) to ActiveCampaign when registering, updating newsletter preferences, and donating.
Partial of https://github.com/Automattic/newspack-popups/issues/833
1. Switch Newspack Newsletters to `feat/contact-add-filter` branch (https://github.com/Automattic/newspack-newsletters/pull/897)
1. Set up Newsletters to use Active Campaign ESP
2. Subscribe to the newsletter(s) using the Newsletters plugin subscription block
3. Observe the user added in AC, along with metadata:
5. Test with Registration Block (email and Google methods), Signup Block, and Donate block (using Stripe). In all cases supplying an email should result in adding a contact w/ metadata in AC.  
When donating, the following metadata fields should be added as well:
All fields handled in this PR:
- …

Send user metadata to AC

---

assets/blocks/reader-registration/style.scss

Make sure inner blocks (first and last) don't have a margin top/bottom
(Kind of) Related: https://github.com/Automattic/newspack-theme/pull/1888
1. Add registration block to a page
2. Check front-end and register
3. Notice margins around the `p` block
4. Switch to this branch and refresh front-end
5. Margins should be gone

fix(registration-block): margin for success message

---

assets/blocks/reader-registration/edit.js
assets/blocks/reader-registration/editor.scss
assets/blocks/reader-registration/index.js
assets/blocks/reader-registration/index.php
assets/blocks/reader-registration/style.scss
assets/blocks/reader-registration/view.js
assets/reader-activation/auth.js
assets/reader-activation/auth.scss
assets/wizards/connections/views/main/index.js
includes/class-reader-activation.php

Implements an abstraction for third-party login and lists subscription for the generic authentication/registration form.
The customization of text will be tackled next on #1773.
1. Make sure you have reader activation on and AMP Plus (or AMP off)
2. Make sure you have subscription lists enabled and configured on the Engagement wizard
3. Visit the front page of our site anonymously and open the Sign In modal
4. Click "I don't have an account"
5. Register a new email subscribing to newsletters
6. Confirm you are subscribed
7. On a new session, click on Sign In again and use the Google authentication with newsletters selected
8. Confirm you're signed in and subscribed

Reader Activation: auth form with third-party and lists subscriptions

---

includes/class-reader-activation.php

Closes #1809
1. Visit site w/ Reader Activation enabled, as an anonymous reader
2. Click the "Sign In" button in the header
3. Observe that login/password is the initially presented option, with a possibility to sign in using a login link via "Sign in using a link" button

feat(reader-auth): make password login the first option

---

assets/reader-activation/auth.js

Ensure links are selected and have appropriate event listeners attached in case AMP (or any other third-party) updates DOM nodes at page load.
Closes #1792 
1. Make sure you have reader activation enabled and AMP on with AMP Plus
2. Visit the front-page and confirm the "Sign In" link opens the modal and not redirect to the "My Account" page
3. Open new sessions and test a few refreshes to confirm it persists

fix(reader-activation): reinitialize auth links after DOM load

---

assets/reader-activation/auth.scss

Ensure the auth modal renders scrollbar for smaller heights.
1. On the master branch, open the Sign In modal and shrink your browser height
2. Observe the modal is centered and the edges are off-screen
3.  Check out this branch and observe the modal renders a scrollbar

fix(reader-activation): ensure scroll on smaller height for auth modal

---

includes/plugins/class-newspack-newsletters.php

Fixes an issue with AC metadata updating. 
1. On `master` branch of this plugin and Newsletters, 
2. as an anonymous reader subscribe to newsletter/s using the Newsletters plugin subscribe block
3. Observe that the `NP_Newsletter Selection` metadata field in AC is blank
1. Switch Newsletters to `feat/contact-adding-without-lists` branch (https://github.com/Automattic/newspack-newsletters/pull/900)
4. Repeat step 2, observe the `NP_Newsletter Selection` is set to current newsletter selection

feat: handle contact update w/out lists selection

---

includes/reader-revenue/my-account/class-woocommerce-my-account.php
includes/reader-revenue/my-account/style.scss
includes/reader-revenue/templates/myaccount-edit-account.php

We have not yet implemented email address synchronisation with the ESP and Stripe, and reader email remains a unique identifier for Reader Activation features. To prevent reader data getting out of sync, let's for now disable email updating in My Account page. 
1. Enable Reader Activation
2. Observe email is not updatable in My Account page, even if the `disabled` attribute is removed by manipulating the DOM

feat(reader-activation): prevent updating user email in my-account

---

assets/wizards/engagement/views/reader-activation/active-campaign.js
assets/wizards/engagement/views/reader-activation/index.js
includes/class-reader-activation.php
includes/plugins/class-newspack-newsletters.php

Implements ActiveCampaign "master list" support as a reader activation feature.
This PR also implements the necessary changes required by https://github.com/Automattic/newspack-newsletters/pull/902 and renames the class methods to remove redundancy.
1. Make sure you have ActiveCampaign as your ESP
2. Check out this branch and https://github.com/Automattic/newspack-newsletters/pull/902, and visit the Engagement wizard
3. Confirm you see the selection as in the image above
4. Select a list and save
5. Register a reader in a new session and don't select any list
6. Confirm on the ESP that the list is selected
7. Repeat step 5 but select a list
8. Confirm the reader is subscribed to both
9. Manage the reader subscription and deselect lists
10. Confirm the master list remained

feat(reader-activation): activecampaign master list

---

assets/wizards/popups/utils.js

Fixes misleading wording in segmentation descriptions. As it is in the [segment settings](https://github.com/Automattic/newspack-plugin/blob/39a247459b4151901799093e8bcd311d4f97abe7/assets/wizards/popups/views/segments/SingleSegment.js#L279-L280), the has-user-account segmentation should say "has user account" rather than "is logged in".
Verify updated wording in the Campaigns Wizard.

fix(campaigns-wizard): segmentation wording

---

includes/optional-modules/class-rss.php

Adds offset option to the RSS feed.  This allows to display ads "between" stories by offsetting a second feed.
[Post 1]
[Post 2]
[Advertising]
[Post 3]
[Post 4]
1. Under the RSS enhancement settings, you can compare two feeds both containing 2 posts, one of them offset by 1.

Adds offset feature to RSS

---

assets/blocks/reader-registration/index.php
includes/class-reader-activation.php

Fixes an issue with missing lists config.
1. On `master`, with Reader Activation configured
1. In the Engagement wizard, set "Manual" as the Newsletters ESP
2. Visit a page with the registration block, observe a PHP Notice being logged
3. Switch Newsletters to `fix/empty-lists-config` branch (https://github.com/Automattic/newspack-newsletters/pull/904)
4. Switch to this branch, observe no notice logged

fix(reader-activation): handle no lists config available

---

includes/optional-modules/class-rss.php

Closes #1735 
By default `is_plugin_active` is only available after the `admin_init` action. We need to include the `plugin.php` file in other contexts if it hasn't been included yet. The reason it was only crashing when debug mode was active is because [this line calls `::get_installed_plugins` when debug mode is not active](https://github.com/Automattic/newspack-plugin/blob/master/includes/class-plugin-manager.php#L359), and `::get_installed_plugins` loads the `plugin.php` file, masking the issue.
1. Add `define( 'WP_NEWSPACK_DEBUG', true );` to `wp-config.php`.
2. Visit site frontend or backend. Observe fatal error.
3. Apply this patch. Refresh the page. Observe no fatal error.

Fix fatal error when debug mode active

---

assets/components/src/card/style.scss
assets/components/src/select-control/ButtonGroupControl.js
assets/components/src/select-control/index.js
assets/wizards/readerRevenue/components/money-input/style.scss
assets/wizards/readerRevenue/views/donation/index.tsx

I've reorganised the Donations wizards a little bit with the use of a Select/Button Group to switch between tiered and untiered, added a Grid to the various elements
1. Go to Reader Revenue > Donations
2. Switch to this branch and refresh wizard
3. Check if options are still working

Reorganise donations wizard and use buttongroup for donation type

---

includes/class-reader-activation.php

Buttons inside forms must have their `type` explicit in order to not submit the form on click.
Closes #1827.
Check out this branch and confirm that #1827 is not reproducible.

fix: google auth button type

---

includes/class-magic-link.php

URL encode email parameter for the sent authentication link.
Closes #1832 
Check out this branch and confirm that #1832 is no longer reproducible.

fix(magic-links): fix email encoding on sent link

---

assets/blocks/reader-registration/index.php
includes/class-reader-activation.php

The block allows for rich text and they shouldn't be escaped on render.
1. On master, add a registration block to a page and tweak the styling
2. Visit the page and confirm you see HTML code printed on the page
3. Check out this branch, refresh and see the styles applied

fix(registration-block): don't escape html for sign in labels

---

assets/blocks/reader-registration/index.php

Render reader registration block on preview.
1. On master, place a reader registration block to a page and click to preview on a new tab
2. Confirm you see the resolved state
3. Check out this branch and refresh the preview page
4. Confirm you see the block as an unregistered user

fix(registration-block): render on preview

---

includes/class-reader-activation.php

Remove the `async` prop from the reader activation front-end library to ensure it's available as a script dependency.
Closes #1845 
Confirm #1845 is not reproducible.

fix(reader-activation): remove async prop from library

---

includes/plugins/class-newspack-newsletters.php

Legacy contacts handling for ActiveCampaign.
1. Switch Newsletters to `feat/all-details-for-contact` branch
1. Setup a site with ActiveCampaign ESP & Reader Activation
2. Create a contact in AC manually, one which is not on the site
3. Register as this contact
4. Observe the new contact metadata is added in AC – `NP_Account`, registration or signup data, signup page URL

feat(active-campaigns): override is-new-contact for legacy contacts

---

assets/blocks/reader-registration/block.json
assets/blocks/reader-registration/edit.js
assets/blocks/reader-registration/index.php
assets/blocks/reader-registration/view.js
includes/class-reader-activation.php

Follow-up to https://github.com/Automattic/newspack-plugin/pull/1847#pullrequestreview-1061084857.
If you enter an email address that's already been registered into the Register block form, the `Reader_Activation` class recognizes the existing account and sends a magic link to the email address. However, on the front-end the messaging shows no indication that this has happened. This change displays a different message to the reader in this scenario, which can also be edited in a new, third edited state in the block editor:
2. In the Register block, enter an email address that's already been registered and submit the form.
3. Confirm that the default message is displayed (as above in the editor screenshot).
4. Edit the success message in the block editor and …

feat: if registering an email that already has an account, show different message

---

assets/reader-activation/auth.js
assets/reader-activation/auth.scss
includes/class-reader-activation.php
includes/templates/reader-activation/login-form.php

Replaces the native WooCommerce login form with our own, utilizing the same markup as we use for the login modal (but with some additional styles to make it render inline).
To do so, ~we rely a bit on a hack to hijack the rendering of the WooCommerce login form template; when this template is about to be rendered, we replace with an empty template file and instead call our `render_auth_form` method to output the form markup. There may be a more elegant way to do this, but I couldn't find one in the short term (cc @claudiulodro if you have any suggestions).~ @miguelpeixe suggested a bit of a less-hacky way to do this by simply calling the `render_auth_form` method in the template itself.
Closes #1850.
2. In a new session, while not logged in, visit the My Account …

feat: replace WooCommerce’s login form with our own

---

includes/class-magic-link.php

The first implementation of magic links (more details in #1668) introduces a security layer that restricts the usage of self-served magic links to the person that created them.
This security layer can be inconvenient in some situations, for example, a reader accessed an article through Facebook's mobile in-app browser and requested to sign in through a link. Through their email app, the link will open on the default browser and fail to authenticate due to `user_agent` and `secret` (cookie) hash arguments.
This PR adds more filters to determine the usage of the default arguments and defaults `user_agent` and `secret` to false, leaving only the IP as a standard hash argument.
1. Check out this branch and request a magic link to an existing reader account
2. Copy the received link and paste …

fix: tweak arguments for magic link client hash

---

includes/class-donations.php
includes/wizards/class-reader-revenue-wizard.php
tests/unit-tests/donations.php

It's not configurable. See https://github.com/Automattic/newspack-blocks/pull/1218
Observe Donation blocks rendering as expected, taking the defaults from the Reader Revenue -> Donations settings

feat(donations): remove defaultFrequency from the configuration

---

includes/oauth/class-google-services-connection.php

Tiny bug w/ cookie parsing. The `_ga` cookie might have different values than previously expected.
1. Register on a site with Reader Activation & Site Kit w/ GA configured
2. manually set `_ga` cookie to value of `GA1.2.amp-12345`
3. On `master`, observe a `PHP Notice:  Undefined offset: 3` notice logged
4. Switch to this branch, observe no notice logged

fix(ga): cookie parsing

---

includes/oauth/class-oauth.php

Although we want this token to be short-lived, 60 seconds may not be enough if the user is not yet authenticated to the service and needs to go through 2FA.
This PR increases the expiration of the transient to 5 minutes.
1. With reader activation on, click sign in using Google
2. Before resolving the Google popup, wait 3 minutes
3. Resolve the prompt and confirm you are authenticated

fix(oauth): csrf token lifespan

---

assets/reader-activation/auth.js

Make sure to catch and display OAuth potential errors for different steps of the flow.
1. Signing in with Google should continue to work as expected
2. Change line 330 of `assets/reader-activation/auth.js` to a 404 URL and recompile
3. Try to sign in again and confirm JS doesn't break and you see an error message

fix(google-auth): catch and display errors

---

includes/class-reader-activation.php

Creates a new action hook for reader verification and makes a reader verified if using Google authentication.
1. Check out this branch and https://github.com/Automattic/newspack-newsletters/pull/922
2. With reader activation, register a new reader through Google
3. Visit "Account -> Newsletters" and confirm you can manage the subscriptions without having to verify your email

fix: verify reader on google authentication

---

assets/blocks/reader-registration/view.js
assets/reader-activation/auth.js
assets/reader-activation/auth.scss
includes/class-reader-activation.php
includes/oauth/class-google-login.php

#1847 added functionality to optimistically redirect to the My Account page if the reader preauthenticates (by sending a magic link or attempting to register an email that was already registered), then subsequently logs in with a password via the login form. However, #1854 broke this functionality because of how it had to move some event handlers in order to handle multiple login form instances. This PR restores that functionality.
1. On `master`, follow testing instructions from #1847. Observe that after sending a magic link, clicking on the "Account" button results in a JS error and does not open the login modal.
2. Check out this branch and repeat testing instructions from #1847. Confirm that you can now complete the whole flow.
3. Also test the login functionality from an inline login …

fix: redirecting to My Account after logging in while pre-authed

---

includes/class-magic-link.php
includes/class-reader-activation.php

Disables WooCommerce's standard, WC-branded welcome emails that are normally sent to new customers, so that we can send our own verification email instead.
Will not send a verification email to readers who register via SSO, which is considered a secure login method and doesn't require verification.
Closes #1872.
2. Register a new email address via the Register block (via direct email input, not SSO) and confirm that you receive a magic link email with a special subject line and message instead of WooCommerce's "Your Newspack account has been created!" email.
3. Visit the magic link URL in the same session where you registered the email address and confirm that you're redirected to the main My Account dashboard page with a message that your email has been …

feat: disable woocomerce welcome emails in favor of verification email

---

includes/oauth/class-google-services-connection.php

#1857 fixed cookie parsing if it only contains the version number, domain depth and CID string parts, but I noticed in some sessions the cookie string contains _only_ the CID, which still causes the parsing to fail. This PR handles that situation.
I'm not sure if the cookie value can contain other combinations of strings, so @adekbadek may have some insight into this.
1. Register on a site with Reader Activation & Site Kit w/ GA configured
2. manually set `_ga` cookie to value of `amp-12345`
3. On `master`, observe a `PHP Notice:  Undefined offset: 1` notice logged
4. Switch to this branch, observe no notice logged

fix: parse CID from _ga cookie if it only contains CID string

---

assets/reader-activation/auth.js
assets/reader-activation/index.js
includes/class-reader-activation.php

This PR implements a cookie to store the reader's preferred auth strategy, which is updated by switching the strategy on the "Sign In" modal.
This management should be later enhanced to change the auth strategy once a reader sets a password for the first time.
It also updates the account link label from "Account" to "My Account" for authenticated and pre-authenticated readers.
1. Check out this branch, click on Sign In
2. Observe the default method is authentication through a password
3. Switch to authenticate through a link
4. Refresh the page and click on Sign In again
5. Observe the strategy is preserved

feat: cookie reader's preferred auth strategy

---

CHANGELOG.md
assets/wizards/readerRevenue/views/stripe-setup/index.js
includes/reader-revenue/class-stripe-connection.php
includes/wizards/class-reader-revenue-wizard.php
newspack.php
package-lock.json
package.json

Implements UI in the Reader Revenue wizard to enable reCaptcha v3 to secure Stripe donate forms, and enter reCaptcha v3 credentials if enabled. Also exposes a `can_use_captcha` method which can be used to determine if we have all the necessary credentials to process reCaptcah requests upon form submission.
2. Visit Newspack > Reader Revenue and set Stripe as your donation platform.
3. Go to Stripe Settings and confirm there's a new section here:
4. Check the box to enable reCaptcha, and enter credentials into both inputs (for this test, you don't really need to have valid credentials).
5. Save, refresh the wizard page and confirm that your settings are persisted.

feat: recaptcha settings in Reader Revenue

---

includes/class-reader-activation.php
includes/reader-revenue/my-account/class-woocommerce-my-account.php
includes/reader-revenue/templates/myaccount-edit-account.php
includes/reader-revenue/templates/myaccount-verify.php
tests/unit-tests/reader-activation.php

This PR refactors the approach for locking "My Account" access to unverified readers. The approach was changed to hook into the `woocommerce_account_content` instead of the combination of `wc_get_template` hook and URL redirection.
Fixes:
- Log out URL should now work for unverified readers accessing the page
- Strict reader check now allows for a non-RAS customer/subscriber to be interpreted as verified
The new test for the strict reader should pass.
1. Create a regular subscriber and set a password
2. On a new session, authenticate with the subscriber
3. Confirm you can navigate the account page
4. Visit the Newsletters section and confirm you still have to verify for newsletters management
1. Create a new account through RAS (registration block)
2. Access My Account and confirm you …

refactor: "My Account" lock for unverified readers

---

includes/class-magic-link.php
includes/class-reader-activation.php

Tweaks the language of the magic link email that's sent to newly registered readers to be slightly more descriptive.
Because of the placement of the magic link URL in the middle of the message, I had to implement some primitive placeholder logic to populate the link where I wanted it to appear.
1. Check out this branch
2. In a new session, register a new email address
3. Confirm the new language:
```
To manage your account, please verify your email address by visiting the following URL:
[magic link URL]
Once verified, visit [My Account URL] to edit your profile, set a password for easier access, and manage your newsletter subscriptions and billing information.
```
4. Also confirm that the sender name and email is customized to `Site Name <no-reply@sitedomain.com>` from the default …

feat: better welcome email copy for initial verification

---

assets/reader-activation/index.js
includes/class-reader-activation.php

This PR implements the `refreshAuthentication()` method for the RAS front-end library. This method reads a cookie so that third-party backend actions (XHR) that might register/authenticate a reader can more easily refresh the UI.
Instructions at https://github.com/Automattic/newspack-blocks/pull/1236

feat: authenticated reader cookie

---

assets/blocks/reader-registration/index.php
assets/blocks/reader-registration/style.scss
assets/blocks/reader-registration/view.js
assets/reader-activation/auth.js
assets/reader-activation/auth.scss
assets/shared/scss/_mixins.scss
includes/class-reader-activation.php

Implements honeypot fields for Reader Activation auth and registration forms. If one of these visually hidden fields is filled out, the form will respond with a success message/state (hopefully satisfying any bots' conditions for success), but the auth/registration actions will not occur on the back-end and any data inputted will be silently discarded.
1. Check out this branch. Confirm that registration and login forms look and function as normal.
2. Temporarily comment out [this SCSS line](https://github.com/Automattic/newspack-plugin/pull/1896/files#diff-ad8f105e75602587030464b8bc3c60d5f456d371d43c43f76f48e9c21d50886dR158) and [this one](https://github.com/Automattic/newspack-plugin/pull/1896/files#diff-b97350f2168c727d03377092125570004f9fecf32bd45a8ac3433040ab230f4dR34) to unhide the …

feat: honeypot trap for auth and registration forms

---

assets/wizards/readerRevenue/views/stripe-setup/index.js
includes/plugins/class-newspack-newsletters.php
includes/reader-revenue/class-stripe-connection.php
includes/wizards/class-reader-revenue-wizard.php

A few related updates to how Stripe & ESP metadata integration work:
- removes explicit Stripe webhook re-creation, with implicit (behind the scenes) webhook creation and reset
- adds handling of subscription update and cancellation events in the Stripe webhook
- adds subscription-related metadata to ESP integration
- removes ability to pause a subscription via the Stripe billing portal
1. Start with a site with Stripe, ActiveCampaign as ESP, and Reader Activation configured
2. Make a new recurring donation as a reader
3. Observe that the following fields are added in AC:
- `NP_Current Subscription Start Date`
- `NP_Current Subscription End Date` (`-` initially or if subscription cancelled)
- `NP_Membership Status` – `Donor` for one-time donations, `<Montly|Yearly> Donor` for recurring, …

ActiveCampaigns – subscription metadata

---

assets/wizards/engagement/views/reader-activation/index.js
includes/class-reader-activation.php
includes/plugins/class-newspack-newsletters.php
includes/reader-revenue/my-account/class-woocommerce-my-account.php
includes/reader-revenue/templates/myaccount-delete-account.php
includes/reader-revenue/templates/myaccount-edit-account.php
includes/templates/reader-activation/login-form.php

Allow the reader to delete their own account through email confirmation.
This PR also implements ESP synchronization options:
- Reader metadata synchronization
- Delete from ESP on reader deletion
Question for @Automattic/newspack-product: the ESP synced deletion only occurs when readers self-delete their account (which triggers `Reader_Activation::delete_reader()`). The regular `wp_delete_user()`, which is used by admins on the WP dashboard, does not. Should we reconsider this?
1. Check out this branch and https://github.com/Automattic/newspack-newsletters/pull/929
2. Make sure you have RAS activated and Newsletters setup with ActiveCampaign
3. Visit the Engagement wizard and confirm the default options are set (sync and delete enabled)
4. Using a Registration Block, register a new …

feat: reader account deletion and ESP sync options

---

assets/wizards/readerRevenue/components/money-input/index.js
assets/wizards/readerRevenue/components/money-input/style.scss
assets/wizards/readerRevenue/views/donation/index.tsx
includes/class-donations.php
includes/wizards/class-reader-revenue-wizard.php
tests/unit-tests/donations.php

Establishes a new donation setting in the Reader Revenue wizard for "minimum donation", with a default value of `5`. This setting applies to both WC and Stripe platforms and fails donate block form submissions if the donation amount submitted is less than this minimum. Also ensures that the minimum value is updated to `5` automatically for all sites, so that no publisher input will be required for the new default to take effect.
Closes #1886 and https://github.com/Automattic/newspack-blocks/issues/1211.
1. On `master` on a site with Reader Revenue platform set to Stripe, publish a page with a Donate block.
2. Check out this branch and https://github.com/Automattic/newspack-blocks/pull/1239.
3. In the Newspack dashboard, visit **Reader Revenue > Donations**. Confirm there's a new setting …

feat: new option for minimum donation amount

---

CHANGELOG.md
newspack.php
package-lock.json
package.json

Should fix the issue with `NEWSPACK_PLUGIN_VERSION` being out of sync. When it was introduced in #1612, the initial value was not set accordingly (`1.80.0` instead of `1.80.1`), so it started as out of sync and was not updated by [`semantic-release-version-bump`](https://github.com/automattic/semantic-release-version-bump). 
Inspect the `newspack.php` file [in the hotfix release ZIP](https://github.com/Automattic/newspack-plugin/releases/tag/v1.89.1-hotfix.1) – it should have the `NEWSPACK_PLUGIN_VERSION` variable updated accordingly.

fix: version for cache busting

---

assets/reader-activation/auth.scss

Fix horizontal scroll being rendered on the Sign In modal.
1. On master, open the Sign In modal and observe the horizontal scroll as displayed above
2. Check out this branch and confirm the scrollbar is no longer there

fix: x scrollbar on "Sign In" modal

---

assets/reader-activation/auth.scss

Fix the column layout rendering on the editor. The lack of the `box-sizing: border-box;` rule, which is applied to the front end, doesn't allow for the flex sizing to render in the desired column layout.
1. On the master branch, edit a page with the Reader Registration block
2. Make sure the block has newsletters and the column layout is selected
3. Confirm it's not rendered as column
4. Check out this branch, refresh and confirm the layout is rendered as expected

fix(registration-block): column layout in editor

---

assets/blocks/reader-registration/edit.js
assets/blocks/reader-registration/editor.scss
assets/blocks/reader-registration/index.php
assets/blocks/reader-registration/style.scss

This PR moves the "Already have account? Sign in" text right below the SSO/Email input section. Leaving the T&C at the bottom.
It also tweaks the font-size and margins.
Closes https://app.asana.com/0/1202719992789620/1202733224125062/f
2. Check if "Already have account? Sign in" still works

feat: move have account text below SSO and adjust font-size

---

assets/blocks/reader-registration/block.json
assets/blocks/reader-registration/edit.js
assets/blocks/reader-registration/index.php
assets/blocks/reader-registration/view.js

This PR introduces an optional title and description for the registration block. This allows for the success state of the form to not include this content.
There's also a small bug fix to the logged-in success message. It was selecting the node from `document.`, which will select the first from the entire DOM. The correct selector should be `container.`.
1. Check out this branch
2. Place the registration block on a page with title and description configured
3. Register a new email and confirm the success message displays as expected and the title/description is cleared
4. Register an existing email and confirm the above also behaves as expected

feat: title and description for registration block

---

includes/oauth/class-google-login.php

Changes the phrasing for Google OAuth failed authentication.
1. With RAS and Google OAuth enabled, start the sign in flow with Google
2. Close before authorizing
3. Confirm the updated error message on the Sign In modal as above

fix(google-oauth): missing email message

---

assets/blocks/reader-registration/index.php
assets/blocks/reader-registration/view.js
assets/reader-activation/auth.js
assets/reader-activation/index.js
assets/wizards/connections/views/main/index.js
assets/wizards/connections/views/main/recaptcha.js
assets/wizards/engagement/views/reader-activation/index.js
assets/wizards/readerRevenue/views/stripe-setup/index.js
includes/class-newspack.php
includes/class-reader-activation.php
includes/class-recaptcha.php
includes/reader-revenue/class-stripe-connection.php
includes/wizards/class-reader-revenue-wizard.php

Implements reCAPTCHA v3 verification for all Reader Activation-related forms: registration, auth, subscribe (requires https://github.com/Automattic/newspack-newsletters/pull/935), and donation (requires https://github.com/Automattic/newspack-blocks/pull/1244).
As part of this PR, the wizard UI to enable reCAPTCHA and enter credentials have been moved from the **Reader Revenue > Stripe Settings** wizard to the **Engagement > Reader Activation** wizard. However, because reCAPTCHA is also used by the subscribe and streamlined donation blocks whether or not Reader Activation is enabled on the site, the reCAPTCHA script and methods can be enqueued and used even if Reader Activation features are not enabled.
Also note that the UI for the reCAPTCHA settings may look out of place right now, but …

feat: use reCAPTCHA to secure all Reader Activation-related forms

---

includes/class-reader-activation.php

Sets the from name and email to the Reader Activation from name/email (default: `Site Name <no-reply@sitedomain.com>`).
1. Check out this branch, log in or register as a reader.
2. From My Account, click the "Email me a password reset link" button.
3. Confirm that the resulting Password Reset email is sent from the Reader Activation defaults (`Site Name <no-reply@sitedomain.com>`).

feat: set from details for password reset emails

---

includes/reader-revenue/class-stripe-connection.php

Handles the situation when Stripe is set as the RR platform, but WC continues to charge customers via Stripe. 
Closes https://app.asana.com/0/1202719992789620/1202851460071001
1. Set up donations with Newspack (WooCommerce) set as the Reader Revenue platform, using Stripe Gateway for payments
2. Make a recurring donation, which will result in a WC subscription being created
3. Switch the platform to Stripe
4. Edit the subscription, so that the next charge happens ASAP (WC allows a min. of hour from now)
5. Come back after the next charge is made, observe that there is just one order for this charge in WC UI

fix(stripe): handle WC-originating Stripe transactions

---

includes/reader-revenue/my-account/class-woocommerce-my-account.php
includes/reader-revenue/my-account/style.scss

Fixes a bug in some My Account-related flows which should be using our custom My Account templates' messaging UI instead of WooCommerce's default. Also consolidates the styling for WooCommerce's messages so they look the same as ours.
1. On `master`, register a new email address and go to My Account before verifying. Click the "Set a new password" button and observe that the page seems to reload but no message is shown to indicate anything has happened. Repeat several times.
2. Click the "Send me a link" button and observe that a message is shown instructing you to check your email inbox for a link to verify.
3. Follow the link from the verification email to verify your account, and observe that you see several instances of the "Please check your email inbox for instructions on how to set …

fix: show My Account messages using custom messaging instead of WC messaging

---

includes/class-reader-activation.php

Small tweak.
1. Configure Reader Activation
1. Visit site as an anonymous user
3. Click "Sign In" in the header
4. Click "I don't have an account" in the modal
5. Observe the newsletters are checked by default

feat(reader-activation): check lists in auth modal by default

---

includes/reader-revenue/class-stripe-connection.php

Requires https://github.com/Automattic/newspack-blocks/pull/1253.
For better reporting purposes, we should be able to know when a donation happens via a Newspack Campaigns prompt and the details of that prompt. https://github.com/Automattic/newspack-blocks/pull/1253 appends the prompt's unique ID to the payment metadata if a Stripe donation happens from inside a prompt, and this PR picks up that metadata and appends it to the event label sent to GA, for easy reporting.
1. Check out this branch and https://github.com/Automattic/newspack-blocks/pull/1253.
2. On a test site that's connected to Google Analytics (optional—you can also just `error_log` the `\Newspack\Google_Services_Connection::send_custom_event` payload on [this line](https://github.com/Automattic/newspack-plugin/pull/1928/file …

feat: for donations via a prompt, add prompt ID to event label

---

includes/class-reader-activation.php
includes/reader-revenue/my-account/class-woocommerce-my-account.php

Shows a success message upon logout from My Account, and tweaks the auth copy slightly so it makes a bit more sense globally. Note that the new copy may be slightly redundant as it includes links to switch between login methods, but the existing link is tiny and easily missed, so I think it's warranted.
1. Log into My Account with an existing account, then log out.
2. Confirm there's a new message saying that you've successfully logged out.
3. Confirm there's new copy for logging in via a password and logging in via magic link:
via password:
via magic link:

fix: post-logout messaging

---

assets/blocks/reader-registration/style.scss
assets/blocks/reader-registration/view.js
assets/reader-activation/auth.js
assets/reader-activation/auth.scss
includes/class-reader-activation.php
includes/reader-revenue/my-account/style.scss

Tweaks some mobile form styles and front-end behavior for the Register and Login forms. There's a corresponding [Newsletters PR](https://github.com/Automattic/newspack-newsletters/pull/937) with similar fixes, too. The Blocks repo doesn't need these fixes despite also using reCAPTCHA because it uses a different mechanism to capture the captcha token and send it to the server for verification, and because the Donate block's styles are already mobile-friendly.
1. View a Register block in a mobile viewport. Confirm that the "Sign Up" button appears below the email address field, and that both email address field and Sign Up button appear at full-width:
2. View at a desktop viewport and confirm that the styles still look appropriate here too:
1. Go to the My Account page while not logged in. …

fix: register and auth form tweaks

---

assets/blocks/reader-registration/index.php

Fixes a bug introduced in https://github.com/Automattic/newspack-plugin/pull/1924
1. On `master`, insert a Registration block and publish the post
2. Register as a new reader, observe the success state contains only the icon
3. Switch to this branch, repeat the test, observe the success state has the default "thank you" copy

fix(registration-block): fix empty success state

---

assets/blocks/reader-registration/block.json
assets/blocks/reader-registration/edit.js
assets/blocks/reader-registration/index.php

This PR implements an option so that the registration block with only 1 newsletter list can have the list input as a hidden field. This allows for the block to have newsletter subscription messaging.
1. Check out this branch and edit a Reader Registration Block
2. Confirm you see the new "Hide input and always subscribe" option
3. Select only one newsletter and confirm the input is no longer disabled
4. Enable the option
5. Confirm the list is hidden
6. Visit the frontend and confirm the list is hidden and you can register and subscribe to that list
7. Back to the editor, add another list to the block so it has 2
8. Confirm the button is disabled and the block is rendering the 2 lists inputs regardless of the stored option
9. Save and visit the frontend
10. Confirm both lists appear and …

feat(registration-block): hidden input for subscription

---

includes/reader-revenue/my-account/style.scss

This PR ensures that WC error notices get the inherited text color instead of the color applied by WC (white).
1. On the master branch, sign in to a reader account and update the Newsletters preferences without making any change
2. Confirm the error message appears but the text is not visible (select the text to confirm you see "You must select newsletters to update.")
3. Check out this branch and confirm the text is now visible

fix(WooCommerce): error notice text color

---

includes/class-analytics.php
includes/plugins/class-newspack-newsletters.php
tests/unit-tests/newsletters.php

Fixes a small issue.
1. Configure a site w/ ActiveCampagin and set a "Master List" in the Engagement wizard
1. On `master`, register w/out subscribing to any newsletter
2. Observe an "NTG newsletter" event is sent anyway*
3. Switch to this branch, observe the event is not sent
\* This will be logged if `NEWSPACK_LOG_LEVEL` is set to `>= 2`

feat(analytics): prevent sending NTG newsletter event if subscribing to master list

---

includes/reader-revenue/my-account/class-woocommerce-my-account.php
includes/reader-revenue/templates/myaccount-after-delete-account.php

Adds a special page for handling after account deletion flow.
1. With Reader Activation set up, create and then delete an account as a reader
2. Observe that after deletion, this page appears instead of the login screen:

feat: after account deletion message

---

includes/plugins/google-site-kit/class-googlesitekit.php

With Reader Activation, we don't wanna risk preventing GA from reporting data for registered readers.
1. Start with a site with Site Kit (w/ Analytics module) configured
2. Ensure Reader Activation is enabled
1. On `master`, visit the Site Kit settings -> Analytics and set (unless it's already set) "Excluded from Analytics" to "All logged-in users" 
3. Switch to this branch, reload, observe the setting is forced to "Users that can write posts"

Site Kit: prevent excluding logged-in users from GA if RA is enabled

---

assets/blocks/index.js
assets/blocks/reader-registration/index.php
includes/class-blocks.php
includes/reader-activation/class-reader-activation.php

Currently, the Register block is only available in the editor if experimental Reader Activation features are enabled via both an environment constant and a Newspack dashboard setting. However, for transitioning live publisher sites to a Reader Activation model, we need to be able to set up registration prompts and flows prior to activating the features. This PR makes the block available and editable in the editor, but ensures that the block is not rendered and its assets not enqueued on the front-end unless the features are enabled.
2. In Newspack > Engagement > Reader Activation, turn off Reader Activation with the checkbox and save.
3. Edit a post, page, or prompt and confirm that you can still add a Reader Registration block, update it, save, etc.
4. View the …

fix: allow Register block to be edited even if RAS is not enabled

---

includes/reader-revenue/class-stripe-connection.php

Fixes a small data integrity issue. Metadata for AC contacts was added when Reader Activation is enabled, but not in the case when reader donates _and_ signs up for the newsletter. 
1. Set up a site with Reader Activation, Active Campaign as ESP, and Stripe as payment platform
2. Ensure a newsletter list is chosen for in the "Allow donors to sign up to your newsletter when donating." setting in Reader Revenue wizard, Stripe Settings section
3. Make a donation and sign up for a newsletter in the Donate block, observe payment-related metadata fields are added to the contact on AC
4. Disable Reader Activation, again make a donation and sign up, observe the payment-related metadata is not added

fix(reader-activation): send payment contact metadata only if RA is enabled

---

assets/blocks/reader-registration/index.php

Fixes a bug.
1. On `master`, insert a Registration block and then Donate block in its "Registration Sucesss" state
2. Visit the front-end, observe the Donate block not rendering properly post-registration
3. Switch to this branch, observe the block rendering as expected

Registration block: allow any success markup

---

assets/blocks/reader-registration/view.js

Fixes a small UX issue.
2. Start with a site with Reader Activation configured
3. Insert a Reader Registration block on a page
4. Visit the page and use the header auth UI ("Sign In" link) to register
5. Observe the Registration block disappearing on registration
6. Switch to this branch
7. In a fresh session, redo previous steps and observe the Registration block changes to success state

feat(reader-activation): handle global auth success in registration block

---

includes/reader-revenue/my-account/style.scss

* Reduces the padding, font-size
* Standardise the notice to use Gutenberg red/green alert colours
* Removes `before` pseudo-element and use background-colour instead
1. Navigate to /my-account/
2. Update your account, try to generate an error message as well
4. Repeat 2

feat: update woocommerce account message/notice

---

includes/emails/class-emails.php
includes/reader-activation/class-reader-activation-emails.php
includes/reader-activation/class-reader-activation.php

Two changes to password reset flow:
1. For a logged-in reader, the password-reset-request will link to WC's password reset screen (`/my-account/lost-password…`) instead of native WP screen (`/wp-login.php?action=rp&…`)
2. For a non-logged-in reader, the lost-password flow will use Newspack's email instead of WC's email
1. Start with a site with Reader Activation configured
1. Register or log in and use My Account -> Reset Password option to request a password reset link
3. Follow the link, observe it pointing to WC's password reset screen 
4. Reset the password, log in, and then log out
5. Use the "Lost your password?" flow of RA's Registration block or authentication modal* to request a password reset link
6. Observe the email is a Newspack email (not WC email), and complete the password …

feat(reader-activation): improve password reset flow

---

assets/blocks/reader-registration/edit.js
assets/blocks/reader-registration/editor.scss
assets/blocks/reader-registration/index.php
assets/blocks/reader-registration/style.scss
assets/reader-activation/auth.scss

This PR moves the "Already have an account? Sign in" message next to the Title. It makes it more visible for existing users where to sign in.
__After__
__Before__
2. Test in the editor
3. Check front-end

feat: move already have account message above content

---

assets/blocks/reader-registration/index.php
includes/class-analytics.php

This gives each registration form a unique ID that can be picked up by Google Analytics to identify the form while firing submission events. Required for https://github.com/Automattic/newspack-popups/pull/951.
Instructions in https://github.com/Automattic/newspack-popups/pull/951.

feat: give each registration form a unique ID

---

includes/emails/class-emails.php

The `Emails::get_email_config_by_type( $type )` method creates the email post on demand if it's called and the email is not found. This can be problematic if the method is called before `wp-includes/pluggable.php` has not yet been loaded.
This PR prevents the method from creating the post if `is_user_logged_in()` is not defined, which means pluggable functions are not yet loaded.
This change shouldn't prevent the posts from being created because the method is called multiple times and the post should be created as soon as pluggable functions are available.
1. While on master, remove posts from the `newspack_rr_email` post type directly from the database
2. Refresh your dashboard page and confirm the error
3. Check out this branch, remove the posts from the database again
4. Refresh the …

fix(emails): don't create post if pluggable functions are not available

---

assets/reader-activation/auth.scss

Ensures that the inline auth wrapper never displays scrollbars.
1. On `master`, visit the My Account page while not logged in.
2. Observe vertical scrollbars in the auth wrapper:
3. Check out this branch, refresh, confirm that the scrollbars no longer appear.
4. Trigger some messaging (try to log into an account with the wrong password, or send yourself a magic link). Confirm that the auth wrapper still expands as expected to show all contents, but without showing any scrollbar.

style: fix unwanted scrollbar for inline auth wrapper

---

includes/plugins/class-newspack-newsletters.php

It may happen that the master list is set, but the Newsletter provider returns an error when getting list IDs.

fix(ac-master-list): handle empty lists

---

includes/reader-revenue/class-woocommerce-connection.php

This PR syncs more data from WC customers to ActiveCampaign in an attempt to get parity with the sort of reader revenue data that syncs when using the Simplified Donate Block. It also adds some legacy handling and updating for Woo customers, so whenever they log in it'll sync the latest customer data.
The one bit I haven't been able to figure out from the codebase is how the name fields are synced to ActiveCampaign. I'm sure it's a small tweak, but I haven't got that working yet. Most of the other fields are synchronizing nicely, so the data should look the same in ActiveCampaign no matter what (Newspack-supported) reader revenue platform people are using.
1. Set up a site with an ActiveCampaign connection and Reader Revenue.
2. In an incognito window, go to `example.com/product/donate` …

Improved Woo sync to ActiveCampaign

---

includes/class-recaptcha.php
includes/reader-revenue/templates/myaccount-delete-account.php
includes/reader-revenue/templates/myaccount-edit-account.php
includes/reader-revenue/templates/myaccount-verify.php

WooCommerce's My Account dashboard contains many action and filter hooks to allow other plugins and themes to extend and modify its UI. Our custom Reader Activation templates call those same hooks, but in most cases the modifications are probably undesired. This PR retains the hooks in place, but prefixes them with `newspack_`. The effect is that most modifications from other plugins won't take effect, but we can selectively allow certain hooks to run if needed by calling the original action hook on our prefixed ones, e.g.
```php
\add_action(
'newspack_woocommerce_before_edit_account_form,
function() {
\do_action( 'woocommerce_before_edit_account_form' );
}
);
```
1. Install and set up the [Mailchimp for WooCommerce plugin](https://wordpress.org/plugins/mailchimp-for-woocommerce/). This …

fix: prefix WC My Account actions so we can decide which hooks to support

---

includes/wizards/class-setup-wizard.php

Best I can tell, [this `switch_theme()` function](https://github.com/Automattic/newspack-plugin/pull/1500/files#diff-b68d58272a59cbafbe7aae011ee40fb05e17f57faa5bf55a84836cb073898e0cR493) can pass an empty string as the theme value, causing a site's theme to get set to nothing. This happens when any setting is changed on the Dashboard > Newspack > Site Design > Settings tab, but does not cause issues on the Design tab. 
This PR adds an `! empty()` check on the theme, to make sure it's not empty before running `switch_theme()`. While this _seems_ to work in my testing, I'm not sure if it would be better to revisit the original approach in #1500 since there was some question around why it worked in the first place 🙂 
Closes #1976
To recreate the original issue:
1. Start on a site that's …

Site Design: add check to only change theme if not empty

---

includes/class-newspack.php
includes/reader-revenue/class-stripe-connection.php
includes/reader-revenue/class-stripe-sync.php

For various reasons, the data in WC might end up out of sync with Stripe. This PR adds a WP CLI command for synchronising data from Stripe to WC. 
Note that only WC Customers and WC Orders will be created/updated. Newspack does not yet integrate with WC Subscriptions (coming in https://github.com/Automattic/newspack-plugin/pull/1936). 
1. Set up a fresh site, with WC suite installed and linked to ta new Stripe instance
2. Install the whole WC suite (load Reader Revenue wizard to see what's missing)
3. Enable AMP Plus (`NEWSPACK_AMP_PLUS_ENABLED`), but don't enable Reader Activation   
4. Configure Reader Revenue to use Stripe as the platform
5. Visit the front-end and donate using the Donate block
6. Make a one-time donation
7. Observe a WC order is created, but not a WP user. The order …

Stripe to WC sync CLI tool

---

includes/reader-revenue/my-account/class-woocommerce-my-account.php

Fixes a RAS-related bug affecting WooCommerce Subscriptions functionality. When executing a "resubscribe" action, the WC Subscriptions plugin redirects to the root "My Account" dashboard URL, but the RAS class hijacks the request by redirecting to Account Details before the action completes. 
1. On a site without RAS enabled and Newspack set as the Reader Revenue platform, make a recurring donation on the front-end.
2. Switch the platform to Stripe and enable RAS. 
3. In WP admin, go to WooCommerce > Subscriptions and cancel the subscription for the recurring donation you just made.
4. On the front-end, register using the same email address you used to make the legacy donation. Verify the account.
5. In My Account, go to Subscriptions and click "Resubscribe". Observe that you're …

feat: do not redirect resubscribe requests

---

includes/reader-revenue/class-woocommerce-connection.php

When a WC Subscription is terminated, the next payment date is set to 0. We don't want to sync that – the next payment date should remain as it was in the event of cancellation.
1. Set up a site with WC Subscription, add and then terminate a subscription
2. On `master`, observe the `NP_Next Payment Date` metadata field is set to `0` in AC
3. Repeat on this branch, observe the `0` value is not sent

fix(wc-to-ac-metadata): disregard `0` next payment date

---

composer.json
composer.lock
tests/class-newspack-unit-tests-bootstrap.php

This PR updates our phpunit tests dependencies to allow us to run them against the latest version of WordPress

test: update tests dependencies

---

includes/author-filter/class-author-filter.php

Add a namespace to the new Author_Filter class.
Reported in https://github.com/Automattic/newspack-plugin/pull/1985/files#r971009134
1. Check that the author filter still work in the Posts page

refactor: add namespace to author filters

---

CHANGELOG.md
assets/blocks/reader-registration/edit.js
assets/reader-activation/auth.js
includes/reader-activation/class-reader-activation.php
includes/reader-revenue/my-account/class-woocommerce-my-account.php
newspack.php
package-lock.json
package.json

This PR changes the original behavior of reader registration, which sends an account verification as soon as a reader is registered.
The default phrasing for the reader registration block success message was changed to not look for a verification email:
Now the account verification email must be requested on the "My Account" page, until then the account will remain unverified. Mind that magic links and password resets also verify an account, so even if that session is lost, the next session will authenticate **and** verify the account.
This PR also introduces some rate limiting for unverified accounts. Password resets and account verifications must be sent within an interval of at least 10 seconds. Should it be more?
Registrations coming from the Sign In modal will be redirected to the …

feat: stop auto-email on registration and rate limit unverified accounts

---

assets/other-scripts/organic-profile-block/index.js
assets/other-scripts/organic-profile-block/style.scss
includes/class-newspack.php
includes/plugins/class-organic-profile-block.php

Adds styles of organic-profile-block if it's missing. 
1. Switch the theme to `fix/organic-profile-block` branch (https://github.com/Automattic/newspack-theme/pull/1926)
1. Install [`organic-profile-block` plugin](https://wordpress.org/plugins/organic-profile-block/)
2. Insert the profile block on a page and fill in the fields
3. Load the page and observe the block rendering 
4. Deactivate the `organic-profile-block` plugin, reload the page
5. Observe the block still rendering nicely

feat(plugins): handle missing organic-profile-block plugin

---

assets/reader-activation/auth.scss

Fixes the color of the Reader Activation auth trigger:
1. On `master`
1. Enable Reader Activation w/ the header link
2. Set the site header background color to a dark color
3. Observe that on a smaller viewport, the auth link has grey color and thus is hard to see:
4. Apply this PR and rebuild, observe the color is now as the other links' in the header:

fix(reader-activation-auth): header link color

---

includes/reader-revenue/class-stripe-connection.php

The return value of the `get_customer_ltv` can be an error. This PR ensure it's handled.
Closes https://github.com/Automattic/newspack-blocks/issues/1269
1. Set up a site with Stripe as the Reader Revenue platform
2. Cause an error to be thrown in `get_customer_charges` method of `Stipe_Connection` class
3. Observe no PHP notices logged

fix(stripe): handle error if customer LTV is not retrievable

---

includes/reader-revenue/class-woocommerce-connection.php

Adds last payment date field to WC-to-ESP sync.
1. Set Newspack (WooCommerce) as the Reader Revenue platform
2. Set up ActiveCampaign as the ESP in the Newsletters plugin
3. Make a one-time donation
4. Observe the data sent to AC contains the `NP_Last Payment Date` field, with the appropriate value

fix(wc-to-ac-metadata): add last payment date field for one-time donors

---

assets/plugins-screen/plugins-screen.js
assets/plugins-screen/plugins-screen.scss
includes/class-admin-plugins-screen.php

Adds a modal prompting the user to fill out a plugin review form before installing a new plugin.
Closes #532
1. Load the WP admin plugin install screen (`/wp-admin/plugin-install.php`) and observe nothing new
2. Define the `NEWSPACK_PLUGIN_REVIEW_FORM_URL` constant (e.g. `wp config set NEWSPACK_PLUGIN_REVIEW_FORM_URL 'https://forms.gle/ofFmGKqoaPWJm2bm8'`)
3. Reload the plugin install screen and observe the modal
4. Click the link in the modal, observe it links to the site under `NEWSPACK_PLUGIN_REVIEW_FORM_URL`
5. Click the "Close" button and observe the modal is closed

feat(plugins-screen): display a plugin review form, if supplied

---

CHANGELOG.md
includes/class-analytics.php
newspack.php
package-lock.json
package.json

Removed dependence on `googlesitekit_amp_gtag_opt` Site Kit hook firing for reporting custom events on AMP pages. Before, the code depended on this hook firing in order to glean the default config for `amp-analytics`. Now, the config will be created based on settings read from the Site Kit settings.
1. Connect Site Kit & Analytics module
2. Ensure AMP is on and the NTG events enabled in Newspack Analytics wizard 
3. Load a page, observe the NTG events are sent*
\* look for requests with `collect` query and inspect the payload
This can also be tested with Campaigns' custom events, too.

fix(analytics): improve reliability of custom events reporting in AMP

---

includes/reader-revenue/class-stripe-connection.php
includes/reader-revenue/class-stripe-sync.php
includes/reader-revenue/class-woocommerce-connection.php

Adds a CLI command for backfilling data in the ESP from Stripe. 
1. Start with a site connected to ActiveCampaigns ESP and Stripe
2. Remove data from AC
3. Run `wp newspack stripe sync-customers --sync-to-esp`
4. Verify that relevant data from Stripe is added to AC – contacts upserted, with payment metadata

Backfill ESP metadata from Stripe

---

includes/reader-revenue/class-stripe-sync.php

This PR adds a Stripe-to-Stripe migrator which can migrate Stripe subscriptions (even Connect ones) to Newspack Simplified Donate Block Stripe subscriptions. We'll want to figure out how to merge this and https://github.com/Automattic/newspack-plugin/pull/1984, because merge conflicts are gonna happen as soon as one of these is merged.
1. Generate some Stripe Connect orders using this PR: https://github.com/Automattic/newspack-plugin/pull/2031 Make sure after you're done and this branch is checked out, you reset the Stripe keys in the Reader Revenue settings to use the child connected account keys, not the parent account which would be e.g. Pico's Stripe keys.
2. Run `wp newspack stripe sync-stripe-connect-to-stripe --dry-run`. You should see output similar to the following:
``` …
```

Stripe-to-Stripe Migrator

---

includes/class-newspack.php
includes/revisions-control/README.md
includes/revisions-control/class-revisions-control.php
tests/unit-tests/revisions-control.php

Adds a feature to limit the number of revisions kept in the database.
See https://app.asana.com/0/1200550061930446/1200839903666391
Fixes #1731
It's easier to test this if you have a post with many revisions across a period of time. Thankfully I made a little script to set it up for you :) 
* Download this file: [create-revisions.txt](https://github.com/Automattic/newspack-plugin/files/9628347/create-revisions.txt)
* rename it to `create-revisions.php` and save it on the root of your site
* run `wp eval-file create-revisions.php` to run the script
* You should see something like this:
```
Created post with ID 506
Creating revisions .................................................
See revisions at http://localhost/wp-admin/revision.php?revision=555&gutenberg=true
```
OK, now you have a …

Feature: Limit the number of revisions kept in the database

---

assets/wizards/advertising/components/onboarding/index.js
assets/wizards/advertising/index.js
assets/wizards/advertising/views/ad-units/index.js
assets/wizards/advertising/views/ad-units/service-account-connection.js
assets/wizards/advertising/views/providers/index.js
includes/wizards/class-advertising-wizard.php
webpack.config.js

Fixes a long-standing issue with ad-blockers blocking the ad management UI. The API paths and assets sent to the browser are renamed to innocuous "billboard". 
Open to other suggestions, though. 
1. On `master`, install AdBlock Plus extension
2. Load the Ad wizard, notice the fatal error
3. Switch to this branch, rebuild, observe the Ad wizard loading correctly

fix(wizards): rename advertising scripts and API paths to bypass ad blockers

---

assets/plugins-screen/plugins-screen.js
assets/plugins-screen/plugins-screen.scss

#2005 introduces a modal prompting the user to fill out a plugin review form before installing a new plugin. In this PR I simplify the custom button to use the `button-primary` class so we don't need any custom CSS.
We should use default wp admin colours here because we're outside of Newspack Plugin
1. Load the WP admin plugin install screen (/wp-admin/plugin-install.php) and observe the modal
3. Reload the install screen and observe the "Plugin Review Form" button

feat(plugins-screen): update button to use primary style

---

.circleci/config.yml
composer.json
composer.lock
phpunit.xml
tests/unit-tests/api-plugins-controller.php
tests/unit-tests/api-wizards-controller.php
tests/unit-tests/emails.php
tests/unit-tests/magic-link.php
tests/unit-tests/plugin-manager.php
tests/unit-tests/popups-analytics.php
tests/unit-tests/reader-activation.php
tests/unit-tests/settings.php
tests/unit-tests/stripe-connection.php
tests/unit-tests/theme-manager.php

This upgrades the tests so they can run both on php 7.4 and 8.
To test it, load the repo in a php 8 environment and run `composer install`. the run `./vendor/bin/phpunit`
Do the same thing on a php 7.4 environment, but run composer `update` instead of `install`. (Discard the changes to composer.lock afterwards)

Update tests to php8

---

includes/reader-revenue/my-account/style.scss

Tweaks the styles of the Subscription Totals table in My Account to more closely match the My Orders table on the same page. The main subscription info table remains styled as in the default plugin, because this table serves a different purpose and looks more or less okay with the default styles.
cc @thomasguillot in case you wanted to do some further design explorations of this. It's fairly low-priority since it only affects "legacy" WooCommerce subscribers before RAS is rolled out on a wider basis.
Old:
Proposed
1. On a site with the Reader Revenue platform set to Newspack, make a recurring donation in a new session.
2. Go to My Account > Subscriptions and compare styles before and after this PR is applied.

style: update styles of Subscription Totals table in My Account

---

includes/author-filter/class-author-filter.php

Disable Authors filter if Co-Authos Plus plugin is enabled
1. Verify Posts page and see the authors filter
2. Activate CAP
3. See the filter is gone

hotfix: disable author filter for co-authors

---

CHANGELOG.md
assets/wizards/engagement/views/reader-activation/index.js
includes/emails/class-emails.php
includes/reader-activation/class-reader-activation.php
includes/reader-revenue/class-reader-revenue-emails.php
newspack.php
package-lock.json
package.json

This PR implements a customizable sender for RAS emails. The "Contact email address" will be used as Reply-To but also as the `*CONTACT_EMAIL*` placeholder value.
The reader revenue sent email is also changed to `receipts@example.com`. The `Reply-To` header should be preserved to use the configured value. This change is meant to protect this email address from an eventual ESP temporary block to other addresses.
1. Check out this branch and visit the Engagement wizard
2. Confirm the new form fields as displayed above
3. Edit the values and on a new session authenticate a reader through email
4. Confirm the email sender and "Reply-To" header is updated
1. Donate using the simplified donate block
2. Confirm you receive an email from `receipts@yoursite.com` and the `Reply-To` header is the …

feat: custom email sender for reader activation

---

assets/reader-activation/auth.scss

If you look closely, the checkboxes aren't perfectly aligned vertically
This PR adds a specific height of `1.6em` to the checkbox container based on the line-height of the `label`. I then used flexbox to center the whole thing.
1. Preview a prompt with Reader Registration (and display newsletter selection)
2. Notice the checkbox is slightly off
4. Refresh prompt

fix(reader-activation): checkbox alignment

---

includes/reader-revenue/templates/myaccount-edit-account.php

This PR reorganises the Account details section of My account to use "cards" for the password reset and account deletion.
See https://github.com/Automattic/newspack-theme/pull/1945
2. Switch the branch for `newspack-theme` as well
3. Check your "Account details" and see if the buttons still work

feat: update woocommerce account details and use cards

---

assets/reader-activation/auth.js

This PR adjusts the Sign In modal to update the auth method when the reader state changes. If an OTP hash becomes available, means a code has been sent and the method should be OTP.
1. On master and a fresh session, use a registered email on the Reader Registration block
2. Confirm the success message from the block and click "My Account"
3. Confirm you're prompted to put in a password
4. Check out this branch, repeat steps 1 and 2 and confirm you're prompted to put in the OTP code

fix(auth): ensure OTP on reader state changes

---

assets/blocks/reader-registration/index.php

When viewing RAS components as a logged-in editor or admin user, force the UI to show the "unregistered" state.
Instructions in https://github.com/Automattic/newspack-popups/pull/979.

feat: show unregistered RAS UI to admins

---

includes/class-analytics.php

For non-AMP sites, `ini-load` AMP Analytics events are triggered on the [window `load` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event). This event only fires after all of the page's resources have been fully loaded, including HTML content, images, and JS (first and third-party). On live non-AMP pages, it seems that this event is sometimes never fired if any resources fail to fully load for whatever reason, which is more often than might be expected. This PR sidesteps the issue by triggering `ini-load` events on the [`DOMContentLoaded` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event) instead, which fires as soon as the document's HTML is fully loaded. This makes these events much less likely to be blocked by external …

fix: fire ini-load analytics events on DOMContentLoaded, not load

---

includes/reader-revenue/class-stripe-connection.php
includes/reader-revenue/class-woocommerce-connection.php

1. Adds handling of two potential error situations:
1. The result of `Stripe_Connection::get_customer_by_id` may be an error
2. The result of `$order->get_date_paid()` may be `null` 
2. Prevents duplicate WC order creation. This can happen when the Stripe webhook is retired after a failure, but the failure was unrelated to WC order creation. 
Hard to test item 1, so it's more about a sanity check. These situations have been seen in the wild, maybe as results of race conditions.
Testing item 2:
1. Configure a site to use Stripe as the Reader Revenue platform, and make sure it's reachable for webhooks
3. Activate WooCommerce plugins, so transactions are synced to WC
4. On `master`, make a donation and then resend the successful webhook via Stripe dashboard
5. Observe a duplicate WC order is …

Hotfix: donations sync errors

---

assets/reader-activation/auth.js
assets/reader-activation/auth.scss
includes/reader-activation/class-reader-activation.php

This PR implements enhancements to the OTP input UX.
Each digit for the code is treated as a single input. Once a valid number is entered, the next input is focused. It also supports navigating through arrow keys and pasting from the clipboard from any position of the OTP input.
1. Check out this branch and with reader activation enabled, send an authorization code to a reader account
2. Confirm you see the new UI for entering the code
3. Attempt to enter a non-numeric value into any digit
4. Navigate between the OTP code using arrows and confirm it works as expected
5. Navigate between the OTP code using tab and shift+tab and confirm it works as expected
6. Enter numeric values and confirm the values are applied smoothly
7. Use backspace to clear the values
8. Copy the valid OTP code …

feat(reader-auth): improved otp ux

---

assets/blocks/reader-registration/style.scss
assets/reader-activation/auth.scss
assets/shared/scss/_mixins.scss

#2025 introduced a few issues to the Sign In form styles while accessing through the "My Account" page. This PR fixes those issues:
- Dark text color for "I don't have an account" link
- Horizontal scrolling
| Master | This branch |
| --- | --- |
| <img width="836" alt="image" src="https://user-images.githubusercontent.com/820752/195156436-f1ba9cef-f1eb-4d07-9e90-bdf17cc806b9.png"> | <img width="842" alt="image" src="https://user-images.githubusercontent.com/820752/195156323-53a8a13c-1eaa-4ac8-904d-9504a63fc09d.png"> |

fix: "Sign In" page styles

---

includes/configuration_managers/class-newspack-ads-configuration-manager.php

Rename GAM methods for https://github.com/Automattic/newspack-ads/pull/529
Details and instructions at https://github.com/Automattic/newspack-ads/pull/529

fix(ads): rename GAM methods

---

includes/starter_content/class-starter-content-provider.php

I'm not sure when this started or what changed, but I've started seeing an SQL syntax error in the WP dashboard in my local test site. I think this is due to a malformed SQL query due to improper placeholders in a `$wpdb->prepare` statement. There's no need to print `'` single quotes as any strings replacing a placeholder are automatically wrapped in quotes by `$wpdb->prepare`.
Visit the Newspack dashboard and confirm that you don't see any errors like this:
> WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '_newspack_starter_content_post_'%'' at line 1 for query SELECT post_id FROM wp_postmeta WHERE meta_key LIKE '%'_newspack_starter_content_post_'%'; made by …

fix: sql error with starter content queries

---

assets/wizards/engagement/views/reader-activation/index.js
includes/class-plugin-manager.php
includes/reader-activation/class-reader-activation.php
tests/class-newspack-unit-tests-bootstrap.php
tests/unit-tests/reader-activation.php

RAS features will behave unpredictably if WooCommerce or WooCommerce Subscriptions plugins are not active. This PR adds a check for these required plugins before considering RAS enabled  Also adds a plugin installer component to the RAS wizard if either plugin is missing for ease of setup.
Also updates the description for WooCommerce Subscriptions with the correct plugin description from the WP.org repository.
1. On a site with RAS already enabled and configured, check out this branch and deactivate WooCommerce and/or WooCommerce Subscriptions.
2. Confirm on the front-end that no reader-facing RAS features are enabled (no My Account link, no registration block).
3. In the dashboard > Newspack > Engagement Reader Activation, confirm that you see a plugin installer prompt:
4. …

fix: check Woo plugins status before enabling RAS

---

includes/reader-revenue/templates/myaccount-edit-account.php

Updates the custom My Account template to show the user's display name instead of the default first/last name. This is because we take donors' full names as the display name in the Donation block, not first/last name, so we want to be sure to display what the user inputted.
Also fixes an undefined variable error that occurs when updating account details. WooCommerce assumes without checking that `account_email` will be in the form submission, but we disable that field as we use email as a unique identifier. The disabled status means the value isn't submitted to WC's form handler, triggering this error:
```
PHP Notice:  Undefined property: stdClass::$user_email in /Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php on line 331
``` …

fix: show display name in My Account UI

---

assets/wizards/engagement/views/social/index.js
assets/wizards/engagement/views/social/meta-pixel.js
includes/class-meta-pixel.php
includes/class-newspack.php
includes/wizards/class-engagement-wizard.php

Closes #1554 .
Relevant discussion: https://wp.me/pamTN9-3ZQ
Adds an option to the Engagement > Social settings page to allow users to configure Meta (Facebook) pixel.
1. Go to Newspack > Engagement > Social
2. Activate "Meta Pixel"
3. Add a pixel ID
4. Save
5. Test invalid formats
6. Test enabling and disabling the option
7. Check the copy and the link
8. Visit the site and confirm the pixel was added to the page. You can use a browser extension to help you with that if you want: https://href.li/?https://chrome.google.com/webstore/detail/facebook-pixel-helper/fdgfkebogiimcoedlicjlajpkdmockpc?hl=en
9. Visit the site with AMP enabled and confirm the pixel is also there
10. I've only tested this with random IDs. It would be awesome if someone could test it with a real pixel ID in a real …

Adds meta pixel settings section

---

includes/reader-revenue/my-account/class-woocommerce-my-account.php

Conditionally applies RAS template changes and logic to the WC My Account UI only when RAS is active. Non-RAS sites are reporting that customers are confused by UI changes that shouldn't apply to their account pages.
Also checks whether logged-in customers have any available downloads before hiding the "Downloads" item from the menu.
1. Disable RAS.
2. Log into My Account as a WC customer, or set your Reader Revenue platform to Newspack and make a recurring donation via WC.
3. Visit the My Account page. On `master`, observe that the RAS UI is applied (links to send a reset password email, delete account, etc. which will only work if RAS is active).
4. Apply this patch and refresh. Confirm that the My Account page now shows the standard WooCommere UI with all nav menu items, and …

fix: apply My Account template changes only when RAS is active

---

assets/blocks/reader-registration/block.json
assets/blocks/reader-registration/edit.js
assets/blocks/reader-registration/editor.scss
assets/blocks/reader-registration/index.php
includes/class-blocks.php

Uses the global "terms & conditions" text as set in the Reader Activation wizard UI as the default text in the registration block.
2. Visit the Newspack > Engagement > Reader Activation wizard and note or update the terms & conditions text here.
3. Add a Reader Registration block to a post or page. Confirm that the text in the RichText field at the bottom of the block matches the wizard text in step 2.
4. View the block on the front-end and confirm that the text matches here, too.
5. Update the text in the block and update. Confirm that the block now shows the updated text on the front-end.

fix: use default terms text in reg block if no text defined

---

CHANGELOG.md
includes/oauth/class-google-oauth.php
newspack.php
package-lock.json
package.json

Logs any missing Google OAuth scopes for improved debugging.
1. Make sure you are connected to a Newspack Manager instance
2. Make sure you have `define( 'NEWSPACK_LOG_LEVEL', 2 );` in your `wp-config.php`
3. Add the following line to `339` in `includes/oauth/class-google-oauth.php`:
```php
$required_scopes[] = 'test';
```
4. Reconnect with Google
5. Confirm the log

fix(oauth): log missing google scopes

---

includes/plugins/class-newspack-newsletters.php
includes/reader-revenue/class-stripe-connection.php

Prevents a situation where the `NP_Membership Status` field in ESP data is overridden in an undesirable way. This field should have the value denoting a one-time donor only if the donor has _never_ donated in a recurring manner.  
1. Set up a site with RAS enabled and ESP set to ActiveCampaign
2. Make a montly donation, observe the `NP_Membership Status` is set to `Monthly Donor`
3. Make a one-time donation, observe the `NP_Membership Status` field is not changed, but the values of `NP_Total Paid` and ``NP_Last Payment Amount` are updated accordingly

feat(newsletter-contact): disallow overriding membership status field

---

assets/reader-activation/auth.js

Tiny fix to hide the logout success message when trying to log in again.
1. On `master`, log into My Account with a reader account, then log out. You'll be redirected to the login form with a success message:
2. Log in again from this page. Observe that the logout success message remains throughout the login flow.
3. Check out this branch and repeat steps 1-2. Confirm that the logout success message is hidden as soon as you submit the login form.

style: hide logged-out message if submitting login form again

---

includes/reader-revenue/class-stripe-connection.php
includes/reader-revenue/class-woocommerce-connection.php

Currently, if a reader cancels a recurring Stripe subscription, their donor status in the `NP_Membership Status` custom field is updated to "Ex-" donor. However, it's possible for readers to have multiple active recurring subscriptions, so cancelling one while keeping others active should not apply the "ex-donor" status. A contact should be considered an ex-donor only if they've canceled donations and have no currently active donations.
1. Check out this branch, set up RAS, and connect your site to an ActiveCampaign account.
2. As a reader, make a recurring donation.
3. Verify in the connected Stripe account that a subscription is created, and in the ActiveCampaign account that a contact is create with an `NP_Membership Status` like "Monthly Donor" depending on the frequency of the …

fix: apply ex-donor status only if user has no active subscriptions

---

includes/reader-revenue/class-stripe-connection.php

This PR handles when `Newspack\Stripe_Connection::get_invoice()` returns `WP_Error` to avoid fatal errors and logs the error message for debugging.
See #2094 for more information.

fix(stripe): handle failed invoice fatal error

---

CHANGELOG.md
includes/oauth/class-google-oauth.php
newspack.php
package-lock.json
package.json

Some accounts are experiencing a change in the `dfp` granted scope to `admanager`. This is causing a scope check mismatch.
We can assume that Google is changing the `dfp` scope name to `admanager`.
This PR changes requested scope name and ensures that if the granted scope is `dfp` we can interpret as `admanager` to match.
1. Make sure your instance is using the `release` branch
2. Connect with Google using OAuth
3. Confirm you are connected (or you might receive the scope mismatch error - not all accounts are experiencing the issue)
4. Switch to this branch and confirm you remain connected (or don't see the error anymore, if you had an error before)
5. Disconnect
6. Connect again and confirm you are connected without issues
7. Visit the Advertising wizard, edit a GAM ad unit
8. Confirm …

fix(oauth): change Google's `dfp` scope to `admanager`

---

includes/reader-revenue/class-stripe-connection.php

Improve handling of invoice errors for Stripe webhooks.
I've noticed that some transactions might not include the `invoice` ID within the webhook payload. This PR fixes the usage of the `Newspack\Logger`class (there's no `error()` method) and returns an error when the invoice ID is missing, for improved debugging.

fix(Stripe): improve handling of invoice error

---

includes/reader-revenue/class-stripe-connection.php

Related to #2103 and #2094.
Currently, we send the "thank you" receipt email to the customer as part of the Stripe webhook handler, as soon as we get the transaction invoice from Stripe. However, a lot of other code happens in the webhook handler after that. If any error occurs in that other code, the receipt email gets sent anyway, but Stripe will schedule retries for the webhook, which will result in the email getting sent on every retry as well. This fix should avoid that in most cases by delaying the sending of the email until after most of the webhook handler has succeeded. 
1. On `master`, add a forced error somewhere inside the webhook handler after [this line](https://github.com/Automattic/newspack-plugin/blob/master/includes/reader-revenue/class-stripe-connection.php#L546). e.g. …

fix: delay receipt sending until Stripe webhook handler succeeds

---

assets/plugins-screen/plugins-screen.js
assets/plugins-screen/plugins-screen.scss
includes/class-admin-plugins-screen.php

Improves the plugin installation prompt.
1. Define `NEWSPACK_PLUGIN_REVIEW_FORM_URL` as some URL, and `NEWSPACK_PLUGIN_REVIEW_FORM_URL` as another URL
2. Visit the plugins install screen (`/wp-admin/plugin-install.php`)
3. Observe a prompt with three buttons – "Plugin Review Form" should take you to the first URL, "Approved Plugins List" to the second, and "Close this message" should do as it says

feat(plugin-screen): improve the pre-install prompt

---

.circleci/config.yml
package-lock.json
package.json

Update `newspack-scripts` and CI orb. The latest version combo will handle building JS files on CI better:
- version `1.4.2` of the orb adds setting node version according to the project's `.nvmrc` file prior to installing npm modules and building the JS files
- version `4.3.8` of `newspack-scripts` removes a hacky partial fix for issues caused by node version mismatch

update newspack-scripts and CI orb

---

includes/reader-revenue/class-woocommerce-connection.php

The post meta table might be called differently than `wp_postmeta`, depending on the table prefix. 
Just a sanity check.

fix(woo): use variable post meta table name

---

.circleci/config.yml

Last update to the CI orb for now – the new version ensures that the proper node version is used before all node-related jobs

update CI orb, hopefully finally 

---

includes/reader-revenue/class-stripe-connection.php
includes/reader-revenue/templates/myaccount-delete-account.php
includes/reader-revenue/templates/myaccount-edit-account.php

Adds Stripe and newsletter subscriptions cancellation on account deletion.
1. Set up a site with Stripe as the Reader Revenue platform and RAS enabled
3. Donate and subscribe to a newsletter as a new reader  
4. Verify in Stripe and ESP that the reader has a Stripe subscription and is subscribed to the newsletter
5. Complete the account deletion flow, starting on My Account page
6. After the account is deleted, verify that the Stripe subscription has been cancelled and the reader unsubscribed from the newsletters

Remove Stripe subs. on WP account deletion

---

includes/reader-revenue/class-woocommerce-connection.php

Before #1936, Stripe Subscriptions were not resulting in Woo Subscriptions. For any recurring donations created before this change, there will be no Woo Subscription tied. This means that each renewal will be a new Woo order, triggering a "New Order" email. This PR disables the "New Order" email in that situation. 
For a full-fledged test, follow the instructions in #1936, but after pt. 7 unlink the subscriptions by removing the `newspack-stripe-subscription-id` meta from the Woo Subscription post. Then proceed, and observe the "New Order" email is not sent. 
For a small-scale test, just wrap the `create_order` call on line 492, make a one-time donation, observe the "New Order" email is not sent. Just to confirm that the filter works.

fix(woo): disable new order email on subscription renewals

---

assets/reader-activation/auth.js
includes/class-magic-link.php
includes/reader-activation/class-reader-activation.php
tests/unit-tests/magic-link.php

There have been reports from confused publishers about not being able to log into their sites. Turns out, some of them were trying to log into admin/editor accounts using the RAS login forms.
Current behavior: If a non-reader tries to log in via the RAS registration or auth form, the form returns an unhelpful error: `We couldn't find an account registered to this email address. Please confirm that you entered the correct email, or sign up for a new account.`
Proposed behavior: If a non-reader tries to log in via RAS, allow the login to occur, but redirect them to WP admin instead of My Account.
Closes /0/1203349230040139/1203185882657586
Confirm that all magic link and password login flows work for non-reader users, including admins/editors/authors/subscribers, but that you're redirected …

feat: allow non-readers to log in via RAS and send them to WP admin

---

assets/reader-activation/auth.js
includes/class-magic-link.php
includes/reader-activation/class-reader-activation.php
tests/unit-tests/magic-link.php

We had some minor security concerns around #2131, so reverting. Also slightly tweaks the error message in a way that will hopefully hint to confused publishers that this login form is for **reader** accounts only.
Test that you once again can't log in via the RAS auth forms with a non-reader account.

fix: revert non reader login

---

includes/reader-revenue/templates/myaccount-edit-account.php

Fixes a small issue.
1. On `master`, log in to the site as a non-reader user (e.g. an admin)
2. Visit the `/my-account` page and observe the account deletion request button is there. It [won't work](https://github.com/Automattic/newspack-plugin/blob/b6e22cdbc021a475cf2c347513fd9d80b6759082/includes/reader-revenue/my-account/class-woocommerce-my-account.php#L204-L206), and should not.
3. Switch to this branch, reload, observe the account deletion request link is not there anymore

fix(my-account): hide account deletion for non-reader users

---

includes/class-admin-plugins-screen.php
includes/class-donations.php
includes/class-newspack.php
includes/class-nrh.php
includes/emails/class-emails.php
includes/optional-modules/class-rss.php
includes/reader-revenue/my-account/class-woocommerce-my-account.php
includes/wizards/class-advertising-wizard.php
includes/wizards/class-analytics-wizard.php
includes/wizards/class-components-demo.php
includes/wizards/class-connections-wizard.php
includes/wizards/class-dashboard.php
includes/wizards/class-engagement-wizard.php
includes/wizards/class-health-check-wizard.php
includes/wizards/class-popups-wizard.php
includes/wizards/class-reader-revenue-wizard.php
includes/wizards/class-seo-wizard.php
includes/wizards/class-setup-wizard.php
includes/wizards/class-site-design-wizard.php
includes/wizards/class-syndication-wizard.php
includes/wizards/class-wizard.php

A few tweaks needed for this plugin to run on PHP 8.1. It may be a bit too early for that, but won't hurt to be proactive:
- `FILTER_SANITIZE_STRING` is deprecated (updated to use `FILTER_SANITIZE_FULL_SPECIAL_CHARS`)
- `Emails::serialize_email` needed some refactoring, as it caused `str_replace` to be called with `null` as the third argument, which is also deprecated
1. On `master`, set PHP to 8.1 and observe a flurry of deprecation warnings. You might have to deactivate other plugins to get a clearer picture of which errors stem from this plugin.
2. Switch to this branch, observe errors gone and site functioning properly

PHP 8.1 compatibility

---

assets/blocks/reader-registration/index.php

Improves error handling in RAS's `send_form_response` function. 
Not sure how to reproduce, but I've noticed `PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array` on a live site. The changes should be self-explanatory, though – the `$data` argument might be an error, and it's not handled as such in all cases.

chore: error handling in reader registration

---

includes/reader-activation/class-reader-activation.php

In some cases, the honeypot field can be filled with autocomplete suggestions once selected for the actual email field.
This PR ensures that no autocomplete value should be used for this field.
I could not reproduce the issue locally, although it was confirmed with a publisher.
Check out this branch and ensure you can still use autocomplete for signing up with RAS.

fix(auth): prevent autocomplete for honeypot field

---

includes/emails/class-emails.php
tests/unit-tests/emails.php

Fixes an issue with sending test emails.
1. On `master`, edit an email (e.g. Reader Revenue wizard -> emails -> Receipt)
2. Try sending a test email, observe that it fails and an error notice is displayed in the editor
3. Switch to this branch, test again, observe the test email is sent

Fix test emails sending

---

includes/class-analytics.php

https://github.com/Automattic/newspack-plugin/pull/1216 added a guard against unavailable `gtag` object by checking if the GTM module of Site Kit was active. It was assumed that if the GTM module is active, the Analytics module won't be – but as @yogeshbeniwal pointed out [here](https://github.com/Automattic/newspack-popups/pull/657#issuecomment-970275131), this is the case [only if the GTM module contains a GA tag](https://github.com/google/site-kit-wp/blob/8df049f73589fea2ef5de13b711d23bef1ec70fe/includes/Modules/Tag_Manager.php#L654-L658). 
This PR changes the condition so that Newspack's Analytics integration will be conditioned on whether Site Kit's Analytics module inserts its code snippet:
Same steps as in https://github.com/Automattic/newspack-plugin/pull/1216

fix(analytics): improve the condition for using Site Kit's Analytics module

---

assets/wizards/engagement/views/newsletters/index.js

Disables the edit of title and description from the list where we select the active Subscription Lists.
Since they are created locally, there is no need to edit the title and description again. Instead of allowing edits, link to the edit page.
1. Go to Newsletters > Engagement > Newsletters
2. Make sure there are no changes in the UI and no warnings in the terminal
3. Checkout [this PR](https://github.com/Automattic/newspack-newsletters/pull/1035) in the Newsletter plugin
1.Set up Mailchimp or AC as provider
4. Go to Newsletters > Lists and create a couple of lists
5. Go to Newsletters > Engagement > Newsletters
6. Go to the "Subscription Lists" section
7. Make sure the Local lists are marked as such and you can't edit their title and description
8. Make sure the edit links points to the …

Disable local lists in the newsletters wizard

---

CHANGELOG.md
assets/blocks/reader-registration/index.php
includes/reader-activation/class-reader-activation.php
newspack.php
package-lock.json
package.json

Fixes a UX conflict between RAS and WooCommerce Subscriptions. The latter requires that any subscription transaction be associated with a logged-in account, and will prompt the user to log in if it finds an existing account. But the former may have created an account upon newsletter signup, resulting in a lot of unnecessary friction on the user's part in order to complete the donation.
This fix checks if the inputted email address is an existing but not logged-in RAS reader, checks if the transaction normally require a login, and if so, temporarily logs in the reader account to allow the transaction to succeed without user input. Once the transaction is complete, the user is logged out.
Also updates the default success message upon registration. On `master`, the default message instructs …

fix: override woo subscriptions login requirement on checkout

---

includes/reader-activation/class-reader-activation.php

This PR proposes a different approach to the handling that allows existing users to donate without having to log in again. This approach doesn't require logging them in temporarily, so it should be more robust in theory. :)
1. Create a WP user.
2. In an incognito/logged-out window, purchase a donation using WooCommerce and that user's email address during checkout. It should work nicely before and after this PR.

Improved existing Woo user subs handling

---

CHANGELOG.md
assets/blocks/reader-registration/index.php
newspack.php
package-lock.json
package.json

Fixes a fatal error introduced by #2158.
1. On a site with RAS enabled, disable WooCommerce.
2. Visit a page containing a RAS Register block and observe fatal errors.
3. Check out this branch, confirm the fatals are avoided.

fix: fatal if no woo

---

includes/reader-revenue/stripe/class-stripe-webhooks.php

The Stripe webhook handler has logic to update a contact's metadata in the ESP when a subscription is canceled or deleted, but the condition in the code to do so seems to only attempt to make such updates when the contact doesn't already exist, which both doesn't make logical sense in the context of the action, and is the opposite of what the code commenting seems to describe.
Closes `1200550061930446/1203469622245017`.
1. On a site using Stripe + RAS + ActiveCampaign, make a recurring donation as a new reader.
2. Go to My Account, verify your account, go to Billing and open the Stripe billing portal. Cancel your subscription.
3. On `master`, observe in the ActiveCampaign contact info that the contact metadata is not updated with the cancellation date (`NP_Current Subscription End Date` …

fix: logic to update existing contact on subscription cancellation or deletion

---

assets/wizards/readerRevenue/constants.js
assets/wizards/readerRevenue/index.js
assets/wizards/readerRevenue/views/platform/index.js
includes/class-donations.php
includes/wizards/class-reader-revenue-wizard.php

Closes #2059.
1. Visit the Reader Revenue wizard, observe a new option in the platform selection – "Other" 
2. Select it, observe the only available tab is the "Platform" tab
3. Observe any Donate block added will no be rendered on the front-end

feat(reader-revenue): add "other" reader revenue platform

---

includes/reader-revenue/class-woocommerce-connection.php

When a WC Subscriptions fails to be paid, a notice will be displayed in the admin panel:
The Stripe Subscriptions which [are sync'd to WC Subscriptions](https://github.com/Automattic/newspack-plugin/pull/1936) (as read-only) will be processed by Stripe, not by WC Subscriptions (these are "manual renewal" in WCS terms). This error is a false negative, because in reality everything went fine. 
Closes 1203366842368217-as-1203469622245025
1. On a site with WC suite installed, set Stripe as the Reader Revenue platform and make a recurring donation
2. Notice a WC Subscription has been created, note its ID
3. Now create a subscription manually from the admin panel, note its ID
4. Instead of waiting for a month, just add the WP option of name `woocommerce_subscriptions_failed_scheduled_actions` …

Ignore payment error notifications for sync'd subscriptions

---

includes/reader-activation/class-reader-activation.php

Many sites don't have a specific terms & conditions page, and we aren't in a position to require one or to suggest language for such a page. However, almost all Newspack sites should have a privacy policy page, and while not a perfect replacement for terms & conditions, it can serve as a fallback for readers who want to know about how their data is used when registering for an account.
If the site has a published privacy policy page, this patch will use it as a default value.
Closes `1203366842368217/1202728371980722`.
1. Install this branch on a fresh RAS test site, or delete all options prefixed with `newspack_reader_activation_` to reset RAS options to their defaults.
2. Add a Register block to a post or page.
3. Confirm that the default terms text links to the privacy policy page …

feat: use privacy policy URL as default terms URL

---

includes/class-newspack.php
includes/data-events/class-data-events.php
tests/unit-tests/data-events.php

Implements a `Data_Events` class for non-blocking dispatch of data events to registered handlers.
The non-blocking strategy is inspired by [TechCrunch's `wp-async-task`](https://github.com/techcrunch/wp-async-task) and uses an HTTP request to trigger the handlers.
To dispatch an event an action must first be registered with the following:
```php
Newspack\Data_Events::register_action( 'action_name' );
```
Once registered, an array with arbitrary payload can be dispatched:
```php
$data = [ "test" => "data" ];
$use_client_id = true;
Newspack\Data_Events::dispatch( 'action_name', $data, $use_client_id );
```
The use of client ID, which is `true` by default, will send the `Reader_Activation::get_client_id();` as part of the data event payload. This client ID is pulled from the session's …

feat(data-events): agnostic data integration tool

---

CHANGELOG.md
includes/reader-revenue/class-woocommerce-connection.php
newspack.php
package-lock.json
package.json

Fixes an issue with Stripe to WC Subscriptions sychronization. 
1. On `master`
1. Enable RAS, set the Reader Revenue platform to Stripe
2. Make a recurring donation as user A
3. Switch the Reader Revenue platform to Newspack 
4. Log in to `/my-account` as user A
5. Go to "Payment Methods" and add a credit card
6. Check "Update the payment method used for all of my active subscriptions"
7. Now WC Subs will update the payment method on the WC Subscription to the new payment method, because there were no payment methods for this customer before
8. Switch to this branch and repeat the test steps – observe the payment method is not updated on the WC Subscription

Hotfix(stripe): force sync'd subscriptions to manual renewal

---

assets/wizards/engagement/views/newsletters/index.js

This PR with https://github.com/Automattic/newspack-newsletters/pull/1046 closes https://github.com/Automattic/newspack-newsletters/issues/1023
Adds the Constant Contact OAuth flow to the Engagement wizard:
1. Check out this branch and https://github.com/Automattic/newspack-newsletters/pull/1046
2. Make sure to delete these WP options: `newspack_newsletters_constant_contact_api_access_token`, `newspack_newsletters_constant_contact_api_refresh_token`
3. Visit the Engagement -> Newsletters wizard
4. Select the Constant Contact ESP with valid API credentials and save
5. Confirm you see the notice above the form
6. Switch to another ESP
7. Confirm the notice disappears as it's exclusive to ESPs that requires that authorization
8. Switch back to Constant Contact and save
9. Click to Authorize …

feat(newsletters): support constant contact oauth

---

includes/class-analytics.php

As remarked [here](https://github.com/Automattic/newspack-plugin/issues/2085#issuecomment-1346894948), Site Kit will display a notice about tag duplication if any custom events are reported. This notice is a false positive, because the custom events code does not report page views, so there is no duplication. 
This PR will make it so the notice is not displayed by hiding the custom events code when Site Kit is asking.  
1. On `master`
1. Configure Site Kit Analytics module and turn on "News Tagging Guide custom events" in the Analytics wizard
2. Load Site Kit Analytics module (`/wp-admin/admin.php?page=googlesitekit-settings#/connected-services/analytics/edit`) and observe the following notice being displayed:
4. Switch to this branch, reload the Site Kit page, observe no notice displayed

feat(analytics): prevent Site Kit's false positive notice

---

includes/class-plugin-manager.php

These two plugins should not be listed as unsupported in the Health Check wizard.

chore: add perfmatters & onesignal to supported plugins list

---

includes/reader-revenue/stripe/class-stripe-connection.php
includes/reader-revenue/stripe/class-stripe-sync.php

When the CLI command for synchronising Stripe data to WC was created (#1981), the Stripe-to-WC-Subscriptions functionality (#1936) was not ready yet. For this reason, the CLI command will not create WC Subscriptions and a series of one-time charges will be created instead.
This PR updates the CLI command, so that WC Subscriptions are created for corresponding Stripe Subscriptions. 
1. Ensure your Stripe instance has at least:
1. one one-time donation charge, not synced to WC
2. one one-time donation charge, synced to WC*
3. one donation subscription, not synced to WC
4. one donation subscription, synced to WC
5. one-time donation made via WC**
6. recurring donation made via WC**
7. Run `wp newspack stripe sync-customers --sync-to-wc` 
8. Observe that (from pt. 1):
- 1., 3. were synced to …

feat(stripe-sync-cli): create WC subscriptions

---

composer.json
includes/class-newspack.php
includes/cli/class-initializer.php
includes/cli/class-setup.php
newspack.php

Creates a CLI command to quickly set up a new site from scratch, running the onboarding wizard automatically
1. Checkout this branch on a fresh new site
2. Run `wp newspack setup`
3. Verify that the site is configures, with the required plugins and initial content. Then end result should be the same as if you had gone through the Onboarding wizard choosing all default values

feat: add setup cli command

---

includes/cli/class-setup.php

Fixes a typo in the setup command
1. Verify that the fix corrects the file name
2. Run setup command and confirm the file is created with the correct name

fix: typo in setup command

---

assets/components/src/accordion/index.js
assets/components/src/accordion/style.scss
assets/components/src/index.js
assets/components/src/tabbed-navigation/index.js
assets/components/src/utils/index.js
assets/wizards/advertising/index.js
assets/wizards/readerRevenue/index.js
assets/wizards/readerRevenue/views/index.js
assets/wizards/readerRevenue/views/stripe-setup/index.js
assets/wizards/readerRevenue/views/stripe-setup/style.scss
assets/wizards/readerRevenue/views/stripe-setup/webhooks-settings.js
includes/reader-revenue/stripe/class-stripe-connection.php
includes/reader-revenue/stripe/class-stripe-webhooks.php
includes/wizards/class-reader-revenue-wizard.php

Adds webhook management UI for Stripe Reader Revenue platform. 
Closes 1203451787793554-as-1203362361069776
1. Visit Stripe Settings tab in Reader Revenue wizard (set Stripe as the platform first)
2. If Stripe is connected, observe the webhooks list
3. Test that the webhooks can be disabled/enabled and deleted using this UI

Stripe webhooks management

---

assets/blocks/reader-registration/view.js
assets/reader-activation/auth.js
assets/reader-activation/index.js
includes/reader-activation/class-reader-activation.php

Implements a RAS callback strategy to allow the `reader-activation.js` library to load asynchronously.
1. Install Perfmatters and configure so it defers every script by default
2. Make sure you have RAS active
3. While on master, confirm that clicking on "Sign In" redirects you to the My Account page. The event listener that triggers the modal did not run
4. Check out this branch and confirm the modal now renders
5. Place a Reader Registration block and confirm it works as expected

feat: allow RAS library to load async

---

assets/blocks/reader-registration/block.json
assets/blocks/reader-registration/edit.js

Make "Enable newsletter subscription" toggled on by default and improve the UI for when newsletters is not yet properly configured:
| Before | After |
| --- | --- |
| <img width="278" alt="image" src="https://user-images.githubusercontent.com/820752/208171250-679ebb02-19ae-401a-b12d-2c3a508cfe21.png"> | <img width="278" alt="image" src="https://user-images.githubusercontent.com/820752/208171093-40301ffb-8499-48ad-977f-c318db7a9070.png"> |
There's no need to flood the UI with error messages and settings if the lists are not yet configured.
1. Make sure you have newsletters installed but no subscription list configured
2. While on master, place a Reader Registration block on a draft page
3. Confirm the "Enable newsletter subscription" is toggled off
4. Toggle it on and confirm the error …

feat(registration-block): newsletter subscription by default

---

includes/class-newspack.php
includes/data-events/class-data-events.php
includes/data-events/class-webhooks.php
includes/data-events/listeners.php
includes/scheduled-post-checker/scheduled-post-checker.php
tests/unit-tests/data-events.php
tests/unit-tests/webhooks.php

As part of the core Data Events system (#2173), webhooks are responsible for integrating the data events to any API that is capable of interpreting the payload.
The webhook requests are registered as a custom post type. This allows flexibility to log, query, and more efficiently manage the relationship with registered endpoints.
Once a data event is dispatched, webhook requests may be created if there are endpoints registered to receive that type of data.
Requests make use of WP's post scheduling in order to send a request. Once a request is created, its send is scheduled for 1 minute from now. Every webhook request is expected to have a slight delay but the original timestamp is preserved in the payload.
A custom taxonomy for registering the webhook URLs and their configuration.
In the …

feat(data-events): webhooks

---

includes/tracking/class-meta-pixel.php
includes/tracking/class-twitter-pixel.php

Proper usage of action hooks for printing the pixels.
Configuring Twitter and Meta pixels through "Engagement -> Social" wizard should continue to work as expected (#2144).

fix(pixel): proper usage of action hooks

---

includes/analytics/class-analytics-events.php

Fixes a fatal error introduced in #2157 due to a reference to a class property that has been moved to a different class.
1. On a site with Analytics set up, publish a Newspack Campaigns prompt.
2. Visit a post front-end that will render the prompt. Observe a fatal error:
```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: Newspack\Analytics_Events::$block_render_context in /wp-content/plugins/newspack-plugin/includes/analytics/class-analytics-events.php:253
```
3. Check out this branch, refresh, confirm no fatal error.

fix: fatal due to different class property

---

includes/emails/class-emails.php
includes/reader-activation/class-reader-activation.php

Reader revenue email sender configuration currently relies on RAS being active. This PR modifies the defaults so that it checks for RAS before applying RAS values.
It also uses the `admin_email` as the default `Reply-To` since there's currently no other way - outside of RAS - to modify this value.
1. Confirm the issue by disabling RAS and sending a test donation through Stripe platform
2. You should receive an email from `receipts@` with `Reply-To` header set to `no-reply@`
3. Check out this branch and send another test donation
4. Confirm the email is sent by `receipts@` with `Reply-To` set to the configured admin email

fix: handle email sender when not under RAS

---

assets/components/src/accordion/index.js
assets/components/src/accordion/style.scss

Fixes a very weird build issue. For some reason, importing `chevronDown` borks the compiled JS files. When I've inspected the JS file, it turned out that the error in the Design wizard is thrown in the `GroupedSelectControl` component (exactly [here](https://github.com/Automattic/newspack-plugin/blob/39a247459b4151901799093e8bcd311d4f97abe7/assets/components/src/select-control/GroupedSelectControl.js#L70)). Removing the `Icon` component there _or_ in the `Accordion` component fixed the issue. This PR changes the icon used in the `Accordion` to a different chevron and rotates it so it's down 🤷‍♀️. 
1. On `master`, run `npm run build` and visit the design step of the Setup wizard (`wp-admin/admin.php?page=newspack-setup-wizard#/design`)
2. Observe that it does not load!
3. Switch to this …

fix: webpack build issue

---

includes/data-events/class-data-events.php

As a WordPress standard, the more specific hook should be called first ([example](https://github.com/WordPress/wordpress-develop/blob/6.1/src/wp-includes/post.php#L4689-L4717)).
This PR switches the data events' WordPress hooks priority.

chore(data-events): switch wp hooks priority

---

assets/wizards/connections/views/main/webhooks.js
includes/data-events/class-data-events.php
includes/data-events/class-webhooks.php

This PR updates the dispatch of data events and processing of webhook requests to use WooCommerce's Action Scheduler tool if available.
This allows for more sophisticated async handling that won't rely on WP Cron or the non-blocking HTTP request.
1. Make sure you have the following flags on your instance:
```php
define( 'NEWSPACK_AMP_PLUS_ENABLED', true );
define( 'NEWSPACK_EXPERIMENTAL_READER_ACTIVATION', true );
define( 'NEWSPACK_EXPERIMENTAL_WEBHOOKS', true );
define( 'NEWSPACK_LOG_LEVEL', 2 );
```
2. Confirm WooCommerce is installed and active
3. Configure a valid global webhook endpoint at the Connections wizard (see #2182 and #2197 for reference)
4. Register a new reader in another session (incognito window)
5. Confirm the logs show:
``` …
```

feat(data-events): use WC's Action Scheduler if available

---

includes/reader-revenue/class-woocommerce-connection.php

#2175 introduced ignoring WC Subscriptions' scheduled actions errors. It only handled one kind of error, though, but there may be other ones. For subscriptions synchronised from Stripe ("shadow subscriptions", so to speak), all errors should be ignored. 
Follow steps in #2175, but in step 4. replace `"subscription payment"` with another error type, e.g. `"subscription expiration"`

fix(stripe): WC Subs scheduled actions errors suppression

---

assets/wizards/readerRevenue/views/stripe-setup/webhooks-settings.js
includes/reader-revenue/stripe/class-stripe-webhooks.php

Fixes a webhook configuration edge case and updates the UI text to reflect the fact that a webhook might be connected to the site, but is used for a different integration. 
1. Create a new webhook via Stripe dashboard – same as the existing Newspack webhook, but with different protocol (`https` -> `http` or the other way around)
2. On `master`, observe that the duplicated webhook is not listed in `/wp-admin/admin.php?page=newspack-reader-revenue-wizard#/stripe-webhooks` as connected to this site
3. Switch to this branch, observe the webhook is listed and the warning about duplicate webhook is displayed

fix(stripe): webhooks list edge-cases

---

includes/class-donations.php

If the Reader Revenue platform is not set to Newspack (WooCommerce), but the WC suite is active, "buying" the donation products using WC UI should not be possible. 
See 1203536997639429-as-1203626633832534
1. Set the Reader Revenue platform to Newspack 
2. Complete the donation, via the Donate block or by directly buying using a WC product link (e.g. `/product/donate-one-time/`
3. Switch the Reader Revenue platform to a different one
4. Visit the WC product page, add it to cart
5. Navigate to the cart, observe it is empty

Remove donation products from cart if WC is not the donations platform

---

includes/reader-revenue/class-woocommerce-connection.php

Fixes an issue with ESP custom fields computed from a WC transaction.
1. Enable Reader Activation and set up a site with ActiveCampaign ESP and Newspack as the Reader Revenue platform
2. Make two donations, observe the `NP_Total Paid` custom field is set to the amount of the first donation  
3. Switch to this branch, repeat the test (or make a third donation), observe the custom field value reflects the correct amount

fix(wc-to-esp): total amount field value

---

includes/class-donations.php
includes/data-events/README.md
includes/data-events/listeners.php
includes/reader-revenue/class-woocommerce-connection.php

This PR tweaks the hook into `woocommerce_checkout_order_processed` so it's more easily accessible for other parts of the code that might want to reach donation processing. There shouldn't be any change into how the `sync_reader_from_order()` behaves.
The following donation-related listeners are added:
When there's a new donation, either through Stripe or Newspack (WooCommerce) platforms.
| Name            | Type     |
| --------------- | -------- |
| `user_id`       | `int`    |
| `email`         | `string` |
| `amount`        | `float`  |
| `currency`      | `string` |
| `recurrence`    | `string` |
| `platform`      | `string` |
| `platform_data` | `array`  |
When there's a new WooCommerce Subscription. This action does not replace the `donation_new` that create the subscription.
| …

feat(data-events): donation listeners

---

includes/reader-revenue/class-woocommerce-connection.php

For WC Subscriptions which just shadow Stripe subscriptions ("synchronised subscriptions"), there's no need to send emails to the customer and admin on subscription renewal. The customer will receive Newspack-configured "Thank You" email, and for the admin it was reported to be unhelpful to receive an email on renewal.  
1. Follow steps in https://github.com/Automattic/newspack-plugin/pull/1936 to set up Stripe test clock with a subscription
2. Advance time by a month, observe (e.g. via Mailhog) that only one email is sent on subscription renewal – the "Thank You" Newspack-configured email.

Disable WC emails sent on sub. renewal for Stripe sync'd subs

---

includes/class-newspack.php
includes/class-performance.php

Optimises the first two Homepage Posts blocks that appear on a page.
[It's recommended](https://web.dev/top-cwv-2023/#ensure-the-lcp-resource-is-prioritized) to prioritise the Largest Contentful Paint image (the above-the-fold, largest image) by setting a `fetchpriority="high"` attribute on the `img` element, and _not to deprioritize_ it by lazy-loading. 
We already have the block-level setting to disable lazy loading (https://github.com/Automattic/newspack-blocks/pull/970), but this solution goes a step further by forcing it on first two HP blocks rendered on a page. 
0. On `master`, visit the standard Newspack homepage (you can reset the HP layout in the setup wizard, at `/wp-admin/admin.php?page=newspack-setup-wizard#/design`)
1. Load the homepage, observe the image(s) in the first …

feat: optimise the HP block that renders first on a page

---

includes/analytics/class-analytics-events.php
includes/class-performance.php

Minifies inline JS produced by Newspack Ads plugin by removing unnecessary whitespace. 
0. Switch to `feat/optmise-fe-js` branch of `newspack-ads`
1. Configure a site to use GAM for ads
2. Visit a page, look at page source – observe the inline JS (search for e.g. "boundsContainers") is minified (whitespace removed)
3. Observe that ads load fine (the JS is working)

Optimise Newspack Ads' inline JS

---

includes/reader-revenue/templates/myaccount-edit-account.php
includes/templates/reader-activation/login-form.php

Fixes a warning in the WooCommerce status report about outdated templates.
Closes 1203536997639429/1203589724907797.
1. On `master`, visit **WooCommerce > Status** and scroll down to the Templates section. Observe some warnings here about outdated templates (this is due to our custom templates not including any version definition):
```
/wordpress/plugins/newspack-plugin/1.99.1/includes/reader-revenue/templates/myaccount-edit-account.php version - is out of date. The core version is 7.0.1,
/wordpress/plugins/newspack-plugin/1.99.1/includes/templates/reader-activation/login-form.php version - is out of date. The core version is 7.0.1,
```
2. Check out this branch and wait ~24 hours. Confirm that the warnings are cleared. Note that you can try clearing the template cache immediately in …

fix: add template versions to Woo templates

---

includes/optional-modules/class-rss.php

If rendering `<media:thumbnails>` and `<media:description>` tags, ensures that they're nested as sub-elements of `<media:content>`, as specified in the [RSS spec](https://www.rssboard.org/media-rss#media-content).
Also fetches the image mimetype from the attachment ID instead of assuming all images are JPEG (images may be PNG).
Closes 1200550061930446/1203716238122802.
1. In **Newspack > Syndication**, enable the RSS Enhancements module.
2. Go to **RSS Feeds** and create a new feed. In the feed settings, under "Technical Settings" check the **Add post featured images in <media:> tags** and **Add featured image at the top of feed content** boxes. Save the feed.
3. Copy the feed URL and validate at https://validator.w3.org/feed/. Confirm that the feed is valid and that the featured images …

feat: if rendering media tags, ensure proper nesting

---

includes/class-newspack.php
includes/data-events/connectors/class-mailchimp.php
includes/oauth/class-mailchimp-api.php
includes/reader-activation/class-reader-activation.php
includes/reader-revenue/class-woocommerce-connection.php

Implements the Mailchimp connector using Data Events, producing a result similar to what is achieved for ActiveCampaign with RAS.
Just like the AC implementation, this also requires a "master list", or a single audience, to send the data to. It will automatically fetch from the "Mailchimp for WooCommerce" plugin setting if it's not configured in the RAS setting `mailchimp_audience_id`.
The UI for configuring Mailchimp's master list should be built next, not in this PR.
The data transformation borrows the logic from `WooCommerce_Connection`, by moving the contact generation portion to a `get_contact_from_order( $order )` method so it can be reused.
The same logic used for ActiveCampaign in `Newspack\Newspack_Newsletters` is not reproduced, meaning:
- No UTM integration
- `NP_Product Name` …

feat(data-events): mailchimp connector

---

includes/class-newspack.php
includes/data-events/class-data-events.php
includes/data-events/connectors/ga4/class-event.php
includes/data-events/connectors/ga4/class-ga4.php
tests/unit-tests/ga4-connector.php

This pull request bootstraps the GA4 connector for our Data Events api and registers one first handler.
Get the GA4 credentials. You will need your measurement ID and an API secret.
* api_secret - Required. An API SECRET generated in the Google Analytics UI. To create a new secret, navigate to:
Admin > Data Streams > choose your stream > Measurement Protocol > Create
* measurement_id - Required. The measurement ID associated with a stream. Found in the Google Analytics UI under:
Admin > Data Streams > choose your stream > Measurement ID
Store this info in the database:
```
wp option set ga4_measurement_id "G-XXXXXXXXXX"
wp option set ga4_api_secret YYYYYYYYYYYYYYYYYYY
```
Now, let's test:
1. Make sure RAS is active and that you have a registered reader
2. Make sure to add this constant to …

feat: bootstrap GA4 connector

---

assets/wizards/advertising/views/placements/index.js

Remove the Ads' per-placement setting for fixed height.
Further details and instructions at https://github.com/Automattic/newspack-ads/pull/590

fix(ads): remove fixed height setting

---

assets/wizards/engagement/views/reader-activation/index.js
includes/data-events/connectors/class-mailchimp.php
includes/plugins/class-newspack-newsletters.php
includes/reader-activation/class-reader-activation.php
includes/reader-revenue/class-woocommerce-connection.php
includes/reader-revenue/stripe/class-stripe-connection.php
includes/reader-revenue/stripe/class-stripe-sync.php
includes/reader-revenue/stripe/class-stripe-webhooks.php

Adds a field to the RAS settings page to set the prefix for contact metadata field keys. Defaults to `NP_` which ensures continuity on sites already using RAS.
Closes 1200550061930446/1203749513702559.
1. On a site with RAS enabled and connected to ActiveCampaign, visit the **Newspack > Engagement > Reader Activation** dashboard. Confirm there's a new "Metadata Field Prefix" field if the the "Synchronize reader to ESP" is enabled, and that it's set to `NP_`.
2. Without making changes, smoke test the field syncing to ensure that it still works with the default behavior: make a donation and ensure that the contact is created in ActiveCampaign with all the Newspack fields prefixed with `NP_`.
3. Update the "Metadata Field Prefix" field to a new string and save.
4. Make a new donation using …

feat(ras): enable custom contact metadata prefixes

---

.gitignore
includes/class-performance.php
tests/unit-tests/performance.php

Adds minification of all inline CSS. The minification will remove whitespace and comments. 
1. On `master`, load a page and inspect the source
2. Observe that there are `<style>` tags with CSS, which contains unnecessary whitespace and comments
3. Switch to this branch, reload the page
4. Observe the inline CSS is minified
5. Smoke-test how the page renders, to ensure the minification did not break any CSS

feat(performance): minify all inline CSS

---

assets/reader-activation/auth.js

Modifies the RAS' default auth strategy from password to link.
1. Check out this branch and make sure you have AMP Plus and RAS enabled
2. On a fresh session (incognito) click to Sign In
3. Confirm you're prompted to use the "link" authentication strategy
4. Switch to password and close the modal
5. On a new tab (same session) open the "Sign In" modal again and confirm "password" auth strategy is preserved

fix: change default auth strategy to "link"

---

includes/class-donations.php
includes/configuration_managers/class-woocommerce-configuration-manager.php
includes/plugins/class-newspack-newsletters.php
includes/reader-revenue/class-woocommerce-connection.php
includes/reader-revenue/stripe/class-stripe-connection.php
includes/reader-revenue/stripe/class-stripe-webhooks.php
tests/unit-tests/stripe-connection.php

Changes the way Stripe donations are handled, so that it's possible that instead of a Stripe Subscription, a WC Subscriptions' Subscription is created for recurring payments. 
There is an underlying change in how Stripe API is interacted with. The way to charge a customer is either through [Sources](https://stripe.com/docs/api/sources), [Tokens](https://stripe.com/docs/api/tokens), or [Payment Methods](https://stripe.com/docs/api/payment_methods) – the latter [replaces the former two](https://stripe.com/docs/payments/payment-methods/transitioning). This integration has used Payment Methods, but since [WC Stripe Gateway uses a Source to process WC Subscriptions renewals](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/compat/trait-wc-stripe-subscriptions.php# …

Stripe: create native WC Subscriptions (if a flag is set)

---

assets/wizards/advertising/index.js
assets/wizards/advertising/views/ad-unit/index.js

1. On Ad wizard if user wants to edit any ads specification and instead of saving changes he `cancels` the change, still the current change are reflected on the list and are gone once refresh the page.
2. This PR fixes this issue and changes would not be saved in state once user cancel the changes and list would show previous change only.
Closes #1220.
1. Visit the Advertising Wizard
2. Edit an ad unit – add a few sizes
3. Click "Cancel"
4. Observe the sizes are now not listed as unit's sizes on the list
[NewspackIssue1220.webm](https://user-images.githubusercontent.com/58802366/218004851-2d6cb056-30c9-4035-8fa5-bc1656fc23b9.webm)

Fix: Temprory Adunit displayed on the list

---

assets/wizards/connections/style.scss
assets/wizards/connections/views/main/webhooks.js
includes/data-events/class-api.php
includes/data-events/class-webhooks.php
tests/unit-tests/webhooks.php

This PR introduces an optional label to webhook endpoints for easier identification:
1. Checkout this branch and make sure you have `define( 'NEWSPACK_EXPERIMENTAL_WEBHOOKS', true );` set
2. Visit the Connections wizard and create a new webhook
3. Set a label and save
4. Confirm the title includes the label
5. Edit the endpoint to a different label
6. Confirm the it's updated
7. Edit the endpoint and clear the label
8. Confirm it no longer shows a label in its title

feat(webhooks): support label for endpoints

---

includes/data-events/README.md
includes/data-events/listeners.php

This PR standardizes the use of `user_id` and `email` across all existing listeners. This allows for easier integration with general-purpose connections.
1. Make sure you have RAS enabled
2. Add a generic handler for payload debugging:
```php
\Newspack\Data_Events::register_handler(
function( $action_name, $timestamp, $data, $client_id ) {
error_log( "Action $action_name dispatched with data: " . print_r( $data, true ) . " at $timestamp" );
}
);
```
3. On a fresh session perform all the actions changed:
1. Register a new reader
2. Subscribe to a newsletter using the Newspack Newsletters block
3. Update your newsletter subscription through the "My Account" page
5. Confirm all payloads include `user_id` and `email` data

feat(data-events): standardize the use of "user_id" and "email"

---

includes/data-events/class-webhooks.php

Fixes a small webhooks issue. 
1. Create a webhook in the Engagement wizard and then delete it 
2. Trigger an action
3. On `master`, PHP will warn that `$endpoint` is null or empty
4. On this branch, there should be no such warnings

fix(webhooks): check if endpoint exists

---

includes/reader-revenue/class-woocommerce-connection.php
includes/reader-revenue/stripe/class-stripe-connection.php
includes/reader-revenue/stripe/class-stripe-sync.php
includes/reader-revenue/stripe/class-stripe-webhooks.php

WC Stripe Gateway plugin adds little metadata to any Stripe payment. It's not possible to learn that a payment was related to a specific subscription. WCSG only adds the `order_id` metadata and indicates a WC Subscription with a `payment_type='recurring'` metadata.
To make any third-party integrations more aware of what WCS is doing in Stripe:
- `subscription_id` will be added to any payments which are WC Subscriptions renewals
- `subscription_status` will be added, either `created` or `renewed`
- additionally, for Newspack-originating subscriptions, the payment description will be updated to `Newspack <frequency> Donation (Order <id>, Subscription <id>)` (e.g. `Newspack Monthly Donation (Order #756, Subscription #757)`)
1. Set up Stripe, ensure the site is reachable by Stripe webhooks
1. …

WCS & Stripe: add payment metadata and update renewal description

---

assets/wizards/engagement/views/reader-activation/index.js
includes/reader-activation/class-reader-activation.php
includes/wizards/class-engagement-wizard.php
includes/wizards/class-reader-revenue-wizard.php

Separates out the plugin requirements check from options-based RAS settings, and requires all WooCommerce plugins and extensions for RAS.
Closes 1203695565716937/1203706216921098.
1. On a site with Reader Activation enabled, visit **Newspack > Engagement > Reader Activation**.
2. Disable the following plugins one-by-one, and confirm that the Reader Activation settings page is replaced by a plugin installer component if any of them is missing:
3. Confirm that the settings page reappears automatically after installing/activating all required plugins.

feat: require all woo plugins for RAS

---

includes/reader-revenue/my-account/class-woocommerce-my-account.php

Current behavior: The Stripe billing portal link is only shown if Stripe is the current active Reader Revenue platform. This means if the platform was Stripe at one point but subsequently changed, readers who donated via Stripe can no longer self-serve their own subscription management.
Desired behavior: Rather than tie the portal link to the active RR platform, the logic should check whether the currently logged-in reader has any Stripe subscriptions associated with their account.
Closes 1203869877018965-as-1203870488073009
1. Set RR platform to Stripe and make a recurring donation. Log to "My Account" page 
2. Observe the "Billing" link is among the menu items
3. Switch RR platform to Newspack
4. As the logged-in donor, observe the "Billing" item is missing
5. Switch to …

feat(my-account): display stripe billing link regardless of RR platform

---

includes/class-logger.php

When debugging Async actions in the back-end, sometimes it's useful to be able to easily identify events that are happening across multiple requests. One way of doing this is by looking at the PHP process ID. A different process ID will mean a different request. All log entries under the same pid mean they happened during the same request.
This has been useful while debugging our new Data Events API
1. Inspect your log
2. Browse the site and perform actions that will generate logs
3. See the pid added to the log prefix

feat: add pid to Logger

---

assets/blocks/reader-registration/index.php
includes/class-newspack.php
includes/data-events/class-popups.php

This PR adds new events to the Data Events API to track interaction with Campaigns on the back-end.
In order to track the "lifecycle" of a campaign, we trigger a series of the same event, called "campaign_interaction", with `action` values for each state. It can be 
* `rendered`: for when the campaign is rendered in the page (not necessarily seen by the user)
*  `form_submission`: for when there's a submission to a form inside a popup. We are adding a `newspack_popup_id` to forms inside a popup to be able to identify it. We'll need to handle all forms we need to to track in this way. This PR does it for the Registration and Newsletter Subscription blocks.
* `form_submission_success`: for when the form submission returns success
* `form_submission_failure`: for when the form submission …

feat: campaigns listeners for the data events api

---

includes/data-events/class-popups.php

We should not trigger an event when a campaign is rendered.
1. This happens all the time, and since we are using Action Scheduler to trigger events, this could overflow our database with events
2. This event does not tell us anything useful. The campaigns are rendered all the time, even when the user doesn't match the segment and won't see the popup. So we can't use this to build funnels and calculating conversion rates.
3. The page output will be cached. So the counts of renders will not match the times the campaign was rendered for users. Again, this count won't be useful in our analytics to build funnels.
1. Nothing really. Just make sure you don't see `[NEWSPACK-DATA-EVENTS][Newspack\Data_Events::dispatch]: Dispatching action "campaign_interaction" via Action Scheduler.` in the logs …

feat: Remove the campaign rendered event

---

includes/class-performance.php

Though I could not reproduce the issue locally, #2236 has caused issues on AMP pages on live sites. The optimisation from that PR is not necessary on AMP pages anyway, because AMP filters out the `fetchpriority` attribute. 
This PR skips the optimisation if the rendered page is AMP. 
1. Insert a Homepage Posts Block as the first block on a page, observe that the images are rendered in AMP and without AMP.

fix: skip HPB optimisations on AMP

---

includes/reader-revenue/class-woocommerce-connection.php

With this change, donors will always be able to switch subscription amounts, unless the `NEWSPACK_PREVENT_FORCE_ALLOW_SWITCHING` env. flag is set. 
See 1203981098043663-as-1204007355707594
1. On `master`, 
1. Set the Reader Revenue platform to Newspack
2. Remove the `woocommerce_subscriptions_allow_switching_nyp_price` option from the DB, if present
3. Make a recurring donation, log in to `/my-account`, and observe that in "My Subscriptions" -> "Subscription totals" table there is no "Change price" button
4. Switch to this branch, reload the page, observe the button is there (the subscription amount can be updated)
5. Add `NEWSPACK_PREVENT_FORCE_ALLOW_SWITCHING` env. flag to the site, reload the page, observe the button is gone now

feat(wc): force allowing subscription switching

---

includes/configuration_managers/class-woocommerce-configuration-manager.php
includes/reader-revenue/class-woocommerce-connection.php
includes/reader-revenue/stripe/class-stripe-sync.php

A migration script that turns Stripe Subscriptions into WooCommerce Subscriptions.
Closes 1204005426582602-as-1203870488073017
1. Set up the site to use Stripe as the Reader Revenue platform and ensure the test site is reachable for webhooks
2. Ensure the WooCommerce suite is active, so the Stripe data will be synchronised to WC
3. Make a recurring donation twice, observe two WC Subscriptions were created to shadow (sync) the Stripe subscriptions
4. Delete one of the WC Subscriptions (ideally via CLI – `$ wp post delete <sub-id>`)
5. Run the migration in dry-run mode – `$ wp newspack stripe sync-stripe-subscriptions-to-wc --dry-run`
6. Observe the output and note that neither Stripe nor WooCommerce subscriptions were updated
7. Now run the migration for real – `$ wp newspack stripe …

Stripe Subscriptions to WC subscriptions migrator

---

includes/plugins/class-perfmatters.php

Tweak Perfmatters baseline config: 
- all Newspack Blocks CSS should be loaded immediately
- `adsrvr.org` scripts should not be deferred – this makes some ads not display

feat(perfmatters): improve config

---

assets/wizards/dashboard/views/dashboardCard.js
includes/wizards/class-dashboard.php

Allows the dashboard links to be filterable, so a plugin may add something.
Ping me for specific instructions.

feat: allow external links in dashboard via a filter

---

assets/wizards/engagement/views/newsletters/index.js
includes/wizards/class-engagement-wizard.php

Adds an "Add new" button to the Subscription Lists
1. Checkout https://github.com/Automattic/newspack-newsletters/pull/1102 on the newsletters plugin
2. Go to Newspack > Engagement > Newsletters
3. See that there's a Add new button in the Subscription Lists settings (if Active Campaign, Constant Contact or Mailchimp are selected)
4. Click the add new button and confirm you are able to create a list
5. Click the "Back to Subscription Lists management" and confirm you go back to the wizard
6. Known issue: when you change the provider, the button is not updated immediately, it needs a refresh (example: if you change from Mailchimp to Campaign Monitor, the button will still be there, even though this provider does not support it

feat: add a Add new button to subscription lists

---

includes/plugins/class-perfmatters.php

Only show the Perfmatters notice if defaults are actually being used.
1. Load Perfmatters settings, see notice at top.
2. Add `define( 'NEWSPACK_IGNORE_PERFMATTERS_DEFAULTS', true );` to `wp-config.php`
3. Load Perfmatters settings, don't see notice at the top

fix: only show perfmatters notice if defaults are used

---

includes/cli/class-setup.php

The `wp-config.php` might not always be where the `setup` CLI command assumed!
1. Run the CLI setup command (`wp newspack setup`) observe that it properly updates the `wp-config.php` regardless of whether it's run on the development environment or on a live site

fix(cli): setup config path

---

includes/class-newspack.php
includes/polyfills/class-amp-polyfills.php
includes/polyfills/class-polyfills.php
tests/unit-tests/amp-polyfills.php

If a site relied on AMP, it may have some AMP tags in content. When the AMP plugin is deactivated, these tags won't render anymore, since AMP is not HTML. 
This PR adds a few light polyfills for most commonly used (and easy-to-replace) AMP tags. These polyfills are not 1:1 replacements for AMP tags – AMP-specific attributes like `layout` will not be handled. This is because AMP tags were never meant to be inserted on pages (AMP plugin should convert HTML into AMP-HTML), but if that happened for some reason, Newspack should ensure at least something is rendered when it's possible.   
1. Ensure AMP plugin is deactivated on the site
2. With a HTML block (or code editor) insert the following content into a page or post:
<details>
<summary>Click to expand code</summary>
<code> …

feat(amp-deprecation): polyfills for some AMP tags

---

includes/data-events/README.md

Add docs to data events Campaigns' listeners

chore(data-events): add docs for campaigns listeners

---

includes/data-events/connectors/ga4/class-ga4.php
includes/data-events/listeners.php

Connects the Donation events to GA4.
Get the GA4 credentials. You will need your measurement ID and an API secret.
* api_secret - Required. An API SECRET generated in the Google Analytics UI. To create a new secret, navigate to:
Admin > Data Streams > choose your stream > Measurement Protocol > Create
* measurement_id - Required. The measurement ID associated with a stream. Found in the Google Analytics UI under:
Admin > Data Streams > choose your stream > Measurement ID
Store this info in the database:
```
wp option set ga4_measurement_id "G-XXXXXXXXXX"
wp option set ga4_api_secret YYYYYYYYYYYYYYYYYYY
```
Now, let's test:
1. Make sure RAS is active and that you have a registered reader
2. Make sure to add this constant to wp-config
```
define( 'NEWSPACK_LOG_LEVEL', 2 );
define( …
```

feat: Add GA4 Newsletters subscriptions events

---

includes/reader-revenue/class-woocommerce-connection.php

With the new modal checkout, the URL metadata will be derived from the `/checkout` page (rendered in a modal), and not the conversion URL. This PR fixes that.
1. On `master`, with Newspack set as the RR platform, RAS enabled, and AC connected as the ESP, make a donation
2. Observe that the contact created has `NP_Payment Page` and `NP_Signup page` set to the checkout page
3. Switch to this branch, visit the page with the Donate block and add some UTM params (e.g. `my-site.com/donate?utm_campaign=spring23`)
4. Observe that the contact created has the correct `NP_Payment Page` and `NP_Signup page` fields set, as well as the appropriate `NP_Payment UTM: *`

fix(modal-checkout): provide conversion URL for ESP

---

assets/wizards/connections/views/main/webhooks.js

Fixes the label of the endpoint name while viewing its requests modal.
1. Make sure you have `define( 'NEWSPACK_EXPERIMENTAL_WEBHOOKS', true );`
2. While in the master branch, visit the Newspack -> Connections page and set up an endpoint with a **Label** if you haven't already
3. Click on the 3 dots menu and click "View requests"
4. Confirm the `[object Object]` in the text
5. Check out this branch and confirm the text has a proper label for the endpoint
6. Edit the endpoint, leave **Label** blank and save
7. View the requests and confirm the label is replaced with the shortened URL

fix(webhooks): endpoint requests modal label

---

includes/data-events/connectors/class-mailchimp.php

Since #2249, the way `Newspack_Newsletters::$metadata_keys` are handled is a little different and the Mailchimp connector was not parsing them properly.
This PR tweaks it so the keys are properly parsed for updating Mailchimp contacts.
1. While in the master branch, add `error_log( print_r( $metadata, true ) );` to line 205
2. Make sure you have Mailchimp connected and the following constant: `define( 'NEWSPACK_DATA_EVENTS_MAILCHIMP', true );`
3. Make a donation through the Donate Block and wait for the data event to get processed
4. Confirm the error logged is an empty array
5. Check out this branch, add `error_log( print_r( $metadata, true ) );` to line 211
6. Repeat step 3 and confirm the error logged contains all the meta

fix(data-events): mailchimp metadata keys

---

includes/class-handoff-banner.php

Prevents the handoff banner to complete Newspack setup from being displayed in WP admin if Newspack setup has already been completed. Note that this doesn't fix a related issue in which the handoff banner causes non-block-editor admin pages to be unscrollable.
Closes `1204068745367915/1204165700596247`.
1. On `master`, on a site that's already been setup with Newspack, force the handoff banner to be displayed by setting an option via WP CLI: `wp option set newspack_handoff 1`
2. Observe in the WP admin dashboard that the banner appears and prevents non-block-editor pages from scrolling.
3. Check out this branch, confirm that the banner no longer appears and that all admin pages are scrollable.

fix: show handoff to finish Newspack setup only if setup is incomplete

---

assets/wizards/advertising/components/ad-refresh-control/index.js
assets/wizards/advertising/views/placements/index.js
assets/wizards/advertising/views/suppression/index.js

This PR fixes an incorrect usage of the `useEffect` hook in some instances of the Advertising wizard. The return of the hook must be either `undefined` or a valid cleanup function.
Related #2269
No changes should be visible on the latest stable version of WP (6.1.1):
1. Visit the Advertising wizard and navigate through all the tabs
2. Confirm all data from the wizards are loaded and rendered as expected

fix(ads): proper usage of useEffect cleanup function

---

assets/reader-activation/auth.js

Fixes an issue that was reported on one live site, but may appear on more. 
The RAS JS was focusing on an input on page load. If the input was hidden with CSS, it would not be focused on, but if for some reason the CSS was delayed or stripped, the input would be focused on and the page would scroll to where the input was – in this case the bottom of the page. 
1. On `master`, ensure RAS is enabled and the header sign-in link is rendered
2. Visit the page, and block the `/wp-content/plugins/newspack-plugin/dist/reader-auth.css` file from loading in the devtools network tab, reload and observe the page is scrolled to bottom on load
3. Switch to this branch, observe the issue cannot be reproduced
4. Open the sign-in modal by clicking the header link and ensure that the input is focused when …

fix: prevent page auto-scroll when RAS is enabled

---

assets/blocks/reader-registration/index.php
includes/data-events/README.md
includes/data-events/class-popups.php
includes/data-events/connectors/ga4/README.md
includes/data-events/connectors/ga4/class-ga4.php
includes/reader-revenue/class-woocommerce-connection.php
includes/reader-revenue/stripe/class-stripe-connection.php
includes/reader-revenue/stripe/class-stripe-webhooks.php

Connects the Popup events to GA4.
Note that the Popup events have already been tested. This only connects them to GA4. It also adds a little more detail to the newsletter subscription events.
This PR also fixes a bug in the `donation_new` event and the `form_submission_success` event for donations. Both when using Stripe as platform.
Since the new donation in Stripe is triggered when Stripe server hits our webhook, the GA Client and Session IDs were not bein fetched by the cookie. So I had to add these information in the payment metadata and retrieve them for the order when they are marked as completed.
Since we changed the structure of the data and also fixed a bug, we should do an extensive tests of as many events as possible.
Get the GA4 credentials. You will need your measurement ID …

feat: Add popup events to GA4

---

includes/plugins/class-perfmatters.php

Adds twitter.com to JS delay list. 
1. Load a post with a twitter.com embed, observe that the embed loads as expected

hotfix(perfmatters): add twitter.com to JS delay list

---

includes/polyfills/class-amp-polyfills.php
tests/unit-tests/amp-polyfills.php

Building on #2308, this polyfills [`amp-vimeo`](https://amp.dev/documentation/components/websites/amp-vimeo) tag. 
Ideally, these changes should also be released as hotfix after https://github.com/Automattic/newspack-plugin/pull/2371 is merged.
1. Same protocol as in https://github.com/Automattic/newspack-plugin/pull/2308, but insert an `amp-vimeo` tag (e.g. `<amp-vimeo data-videoid="27246366" layout="responsive" width="480" height="270"></amp-vimeo>`)
2. Ensure the tag loads a vimeo embed when AMP plugin is off.

feat(amp-deprecation): polyfill amp-vimeo tag

---

assets/other-scripts/lightbox/index.js
assets/other-scripts/lightbox/style.scss
includes/polyfills/class-amp-polyfills.php

Polyfills AMP's "Add lightbox effect" feature of the core image block:
Note that a similar feature [exists in Jetpack](https://jetpack.com/support/carousel/) (if the image links to the attachment page), but it causes the page to load a lot of markup and carousel-related JS, which is not optimal from a performance standpoint. 
1. Ensure AMP is enabled, insert an image block in a post or page, and toggle "Add lightbox effect" in the block settings in the sidebar ("AMP Settings" panel)
2. Deactivate the AMP plugin, load the frontend 
3. Click on the image, observe it goes full-screen with a black background and a close icon in the top-right corner
4. Click the close icon, observe the full-screen view disappearing

feat(amp): polyfill lightbox effect

---

assets/reader-activation/index.js

When the reCAPTCHA library is loaded, RAS' library assumes it should be used and renders an error when submitting a form if the connection is not configured.
This PR tweaks the token fetch to bail silently when a site key is not set.
1. While on the master branch, make sure you have RAS configured and reCAPTCHA **not** configured
2. Install the [reCAPTCHA for WooCommerce](https://wordpress.org/plugins/recaptcha-woo/) plugin
3. Place a "Reader Registration" block
4. Submit the form and confirm you see a reCAPTCHA error
5. Check out this branch, repeat step 4, and confirm the error is gone
6. Enable and configure reCAPTCHA in the Connections wizard
7. Repeat step 4 and confirm it also works with reCAPTCHA

fix: bail silently when recaptcha key is not set

---

includes/reader-revenue/stripe/class-stripe-sync.php

The Stripe sync scripts should process only customers who have at least one successful transaction. This will prevent customers resulting from card-testing attempts from polluting WC or ESP DBs. 
1. Ensure the connected* Stripe account has some customer with no successful transactions, and some with
2. Run the script: `wp newspack stripe sync-customers --sync-to-esp`
3. Notice that for the customers with no successful transactions are ignored 
\* Either via Stripe RR or WC Stripe Payment Gateway

fix(stripe-sync-script): process only customers with successful transactions

---

includes/plugins/class-perfmatters.php

Adds [local Google Fonts hosting](https://perfmatters.io/docs/host-google-fonts-locally/) and [Display Swap](https://perfmatters.io/docs/font-display-swap/) settings to Perfmatters baseline settings.
Verify that (unless `NEWSPACK_IGNORE_PERFMATTERS_DEFAULTS` env. variable is set) the aforementioned settings are turned on in Perfmatters settings by default.

feat(perfmatters): add fonts settings to defaults

---

includes/reader-activation/class-reader-activation.php

A redo of #2333 without the unwanted Composer changes. The "Sign In"/"My Account" button from RAS isn't showing up in the Customizer preview at large viewport sizes (when the content area of the preview minus the sidebar is >960px). I figure it probably should since it likely has a largeish impact on how the header appears. The mobile version does appear at smaller sizes; it's just the larger button that doesn't appear.
1. On `master`, enable RAS and the "Enable Sign In/Account link" option.
2. At a large viewport size, observe that the button appears in the header on the front-end in a new session, but not in the Customizer while logged in as an admin.
3. Check out this branch and confirm that now it does appear in the Customizer.

fix: if My Account is set to shown in RAS, show in Customizer at all breakpoints

---

assets/wizards/readerRevenue/views/donation/index.tsx

Adds a check to avoid the wizard to break if the site is in a specific state.
I don't really know how to reproduce the state in which the site would error without this fix, but I do have a database dump that reproduces it. Ask me if you want it.

fix: Avoid falal error on Reader Revenue wizard

---

assets/memberships-gate/editor.js
assets/memberships-gate/editor.scss
assets/reader-activation/auth.js
assets/wizards/engagement/views/reader-activation/index.js
assets/wizards/readerRevenue/views/donation/index.tsx
includes/class-newspack.php
includes/plugins/class-wc-memberships.php
includes/reader-activation/class-reader-activation.php
includes/wizards/class-engagement-wizard.php
webpack.config.js

Scaffolds a new page layout for the RAS settings page according to the latest i2 designs. The list of prerequisites and all copy/links are TBD, so this PR contains a list of a few known requirements and a boilerplate config object to serve as a template to add more.
Because discussions are ongoing about what to do about the existing RAS settings on this page, these are simply hidden behind an "advanced settings" flag to show/hide those settings. This advanced settings section will need to be redesigned in a future PR.
The `ActionCard` component to kick off the Campaigns default prompts/segments setup is a placeholder, and is non-interactive for now.
1. Visit the **Newspack > Engagement > Reader Activation** admin page and ensure that the prerequisites are shown according to the config …

feat: start new RAS settings page

---

assets/memberships-gate/editor.js
includes/plugins/class-wc-memberships.php

This is a hotfix for the current alpha release.
Prevents an infinite loop on Woo Memberships when the restricted content uses the "Query Loop" block or "Homepage Posts" block.
**UPDATE**: Catching a ride in this hotfix, 44ea11517575e3b9abd4b3933d9669f146b831be updates the location of the "Newspack Campaigns" notice from the native notices API to post status info:
1. While in the alpha or master branch edit a restricted post to include a Homepage Posts block
2. Access the post anonymously and confirm the infinite loop
3. Check out this branch and confirm the post renders and is restricted
4. With Newspack Campaigns installed and active confirm you see the notice above

fix(memberships): remove content filters from excerpt

---

assets/components/src/action-card/index.js
assets/components/src/action-card/style.scss
assets/wizards/componentsDemo/index.js
assets/wizards/engagement/views/reader-activation/index.js
includes/emails/class-emails.php
includes/reader-activation/class-reader-activation.php
includes/wizards/class-engagement-wizard.php

Updates the design of the new RAS settings page to the latest i3 designs. This PR covers only the first settings page in **Newspack > Engagement > Reader Activation**. The setup wizard for Campaigns defaults will come in a future PR.
1. Start with a fresh test site (JN). Install the plugin from this branch and run `wp newspack setup` to scaffold the site with default Newspack settings.
2. Visit **Newspack > Engagement > Reader Activation** to view the checklist of prerequisites that need to be completed before RAS Campaigns defaults can be configured.
3. Expand each card and complete the setup.
- For cards that contain fields and a "Save settings" button, fill out the required fields and click "Save" (note that some fields will be prepopulated with suggested settings, but you still need …

feat: update RAS settings layout to i3 designs

---

includes/plugins/class-wc-memberships.php

An alpha hotfix. Fixes some weird content gate behavior in the current alpha version, so needs to be merged before the alphas are deployed.
When a WC Membership plan is created and associated with a taxonomy term, a notice is displayed when a query for that term shows its posts. This causes the content gate to be displayed in, for example, Homepage Posts blocks that query that term.
This PR simply hides the gate entirely, but an alternative solution would be to retain the WC Memberships plugin's default behavior and show the default message instead of replacing with our own gate.
1. Create a membership plan related to a specific category or tag.
2. On a post, add a Homepage Posts block targeting that term.
3. On the front-end, on `alpha` or `master`, observe that the content gate is …

fix: don't show gate unless attached to a specific post

---

includes/plugins/class-perfmatters.php

Remove CSS delay from Jetpack's sharing buttons and Newspack Newsletters (Subscription Form block)
1. Make sure you have Perfmatters installed and active
2. Configure JP's sharing buttons on your instance and confirm the CSS is rendered immediately
3. Add a Newsletters Subscription Form block to page, visit and confirm the `subscribeBlock.css` is loaded immediately

fix(perfmatters): exclude Jetpack and Newsletters css delay

---

assets/memberships-gate/overlay.scss
assets/reader-activation/auth.js

Support opening the sign-in modal through a hash: `https://example.com/#signin_modal`. This allows for more flexible placement of sign-in links.
To also increase coverage, any link to `/my-account` will also trigger the modal.
Also simplifies how we hide other overlays when in the modal by using a body class.
1. Check out this branch and visit your site with the `#signin_modal` hash at the end
2. Confirm the modal is rendered
3. Close the modal and confirm the hash is updated and empty
4. Confirm RAS and Memberships are enabled and configure the content gate with "Overlay" style and a link to `#signin_modal`
5. Visit the gated content, click the created link, and confirm the gate overlay hides
6. Edit the content gate and replace the link href to the "My Account" page
7. Repeat step 5 and …

feat(sign-in): body class when in modal and url hash

---

assets/wizards/engagement/components/prerequisite.tsx
assets/wizards/engagement/components/prompt.tsx
assets/wizards/engagement/components/types.ts
assets/wizards/engagement/views/reader-activation/style.scss

Adds static help copy and screenshots according to the latest i3 designs.
1. Check out this branch and https://github.com/Automattic/newspack-popups/pull/1096.
2. Proceed to the default prompt setup wizard as in #2399.
3. Expand each card and confirm that the right side of the card displays relevant help info and screenshots.
4. Also confirm that the "Preview" buttons in each card have a new :eye: icon.

feat: add help info for preset prompts

---

assets/wizards/popups/utils.js

Add a filter to the check for prompt conflicts.
See https://github.com/Automattic/newspack-multibranded-site/pull/19

fix: add filter to prompt conflicts check

---

.distignore

Currently, `.hooks` is being included in the release archive. This change ensures it isn't.
1. Run `npm run release:archive`
2. Open the built archive
3. Confirm it does not contain a `.hooks` directory

Ensure .hooks is excluded from the dist ZIP

---

assets/components/src/action-card/index.js
assets/components/src/action-card/style.scss
assets/components/src/consts.js
assets/components/src/notice/index.js
assets/components/src/notice/style.scss
assets/components/src/with-wizard-screen/index.js
assets/components/src/wizard/index.js
assets/wizards/engagement/components/prerequisite.tsx
assets/wizards/engagement/components/prompt.tsx
assets/wizards/engagement/components/types.ts
assets/wizards/engagement/index.js
assets/wizards/engagement/views/newsletters/index.js
assets/wizards/engagement/views/reader-activation/complete.js
assets/wizards/engagement/views/reader-activation/index.js
includes/reader-activation/class-reader-activation.php
includes/wizards/class-engagement-wizard.php

For prerequisites that link out to another wizard page, shows a hand-off message with some instructions on what needs to be configured, and a link back to the Reader Activation wizard. The message will be displayed when clicking a button in the Reader Activation wizard that links out to another wizard page, and will persist until you revisit the Reader Activation wizard.
Separately but related, this PR also revamps the UI for the **Engagement > Newsletters** wizard screen so that it makes a bit more sense in context of the RAS messaging.
Lastly, also updates the copy for the UI to the latest copy-edited version along with [this PR](https://github.com/Automattic/newspack-popups/pull/1102).
1. Check out this branch and https://github.com/Automattic/newspack-popups/pull/1102. Visit …

feat: add handoff message for prerequisites

---

assets/reader-activation/auth.js

Similar to #2414, implements a hash that opens the Sign In modal but in the `register` action state. This allows for shortcut links to this state of the form.
1. Check out this branch
2. Edit or draft a new page, add a link to `#register_modal` and another link to `#signin_modal`, and save
3. Visit the page, click the `#register_modal` link and confirm it opens the modal in the register state
4. Click to close and confirm the hash is cleared from the URL
5. Click on the `#signin_modal` link and confirm the form opens in sign in state
6. Click to close and confirm the hash is cleared from the URL

feat(sign-in): support "register modal" hash url

---

assets/components/src/notice/style.scss
assets/components/src/section-header/index.js
assets/wizards/connections/views/main/recaptcha.js
assets/wizards/engagement/components/prerequisite.tsx
assets/wizards/engagement/components/prompt.tsx
assets/wizards/engagement/components/types.ts
assets/wizards/engagement/views/reader-activation/style.scss
includes/reader-activation/class-reader-activation.php

Implements the following changes:
* Makes the legal pages section optional (you can save with empty values to skip this step) and adds a warning if the fields are empty
* The link to the reCAPTCHA settings page will automatically scroll to that section of the Connections wizard page
* (with https://github.com/Automattic/newspack-popups/pull/1109) Increases the max-length of Heading and Button Label input fields for all default RAS prompts
1. Check out https://github.com/Automattic/newspack-popups/pull/1109 and delete the Terms options: `wp option delete newspack_reader_activation_terms_text && wp option delete newspack_reader_activation_terms_url`
2. Visit the **Engagement > Reader Activation** wizard. Confirm that the Legal Pages card is in a Pending state.
3. Expand the Legal Pages card …

fix(ras-defaults): feedback from QA

---

includes/data-events/connectors/ga4/class-ga4.php

Fixes a small typo that causes a warning if `ga_client_id` is not set. The entire conditional statement is inside the `empty()` check, which looks unintentional.

fix(ga4): donation event conditional typo

---

includes/reader-revenue/stripe/class-stripe-sync.php

Closes [this issue](https://app.asana.com/0/1200133283755575/1204276644179086)
After running [the command](https://github.com/Automattic/newspack-plugin/blob/fix/trial-sync/includes/reader-revenue/stripe/class-stripe-sync.php#L712) to cancel Stripe subscriptions and re-create them as Stripe Donate Block subscriptions, the re-created subscriptions are in 'trialing' status until their next renewal date in Stripe (so we don't charge the customers until they would normally have been charged). 
Then, when we run [the ESP backfill command](https://github.com/Automattic/newspack-plugin/blob/fix/trial-sync/includes/reader-revenue/stripe/class-stripe-sync.php#L684), these customers incorrectly show up in the ESP with the 'Ex-Monthly Donor' or 'Ex-Yearly Donor' status because the backfill checks …

Improved handling of trial subscriptions in ESP sync

---

assets/wizards/engagement/components/types.ts
assets/wizards/engagement/views/reader-activation/index.js
includes/reader-activation/class-reader-activation.php

Adds a required plugin check to the RAS setup wizard, and if any are missing, presents a UI to install and/or activate them before showing the setup wizard.
1. Check out this branch. Deactivate or uninstall some or all of the following plugins:
- Newspack Blocks
- Newspack Newsletters
- Newspack Campaigns
- WooCommerce
- WooCommerce Subscriptions
- WooCommerce Name Your Price
2. Visit the **Newspack > Engagement > Reader Activation** page.
3. Confirm that the UI prompts you to activate the required plugins before proceeding:
4. Install and/or activate all of the required plugins. Confirm that after a few seconds, the usual prerequisite checklist UI becomes available and allows you to proceed with RAS setup.

fix(ras-defaults): check for required plugins in RAS setup wizard

---

includes/reader-revenue/class-woocommerce-connection.php
includes/reader-revenue/stripe/class-stripe-sync.php

Plugs a hole in the migration script for migrating Stripe subscriptions to WooCommerce. When programmatically creating subscriptions via code, Woo does not automatically schedule next payment dates—this must be done explicitly. This PR ensures this is done, and also implements a script to retroactively look up any previously migrated subscriptions and schedule next payment dates for any that are missing them. 
~Note that the scheduled next payment date won't always be in line with the start date of the subscription (e.g. if started April 3, the next payment would normally be May 3), but it should fall within 2 weeks of that date. This is because the calculate_date method is based on the current timetamp rather than the subscription's start date.~ We were able to get around this in d4978df …

fix: ensure migrated Stripe subs have next_payment scheduled

---

assets/wizards/connections/views/main/webhooks.js
includes/data-events/class-data-events.php
includes/data-events/class-webhooks.php
tests/unit-tests/webhooks.php

Allows other plugins to programatically register endpoints.
1. Add this snippet to your site:
```PHP
add_action( 'init', function() {
\Newspack\Data_Events\Webhooks::register_system_endpoint( 'my-id', 'https://my-url.com', [], true );
} );
```
3. Perform some actions that will dispatch events (register to a newsletters for example)
4. Confirm you see the new endopint on the Connection webhooks -> UI
5. Confirm you can't disable, edit or delete this endpoint
6. Confirm the requests are created and sent
7. Bonus point for testing the filter on the event body

feat: filter existing webhooks endpoints

---

includes/plugins/class-perfmatters.php

Excludes CSS from Newspack Campaigns and Perfmatters' own Google Fonts cache from being delayed upon pageload. Should help prevent CLS (cumulative layout shift) resulting from those styles being delayed, which should in theory generally improve PSI scores across the board. In one test site these changes alone resulted in a PSI improvement from 15 to 49 on the same page.
Closes `1204323000227084/1204483195828244`.
This one might be tough to test positively because it depends on a lot of site-specific factors. But let's give it a try:
1. Make sure you test on a site that can be accessed by the [PSI testing tool](https://pagespeed.web.dev).
2. Publish a Campaigns prompt with an Above-Header placement and make sure it it's pretty vertically large, so that if it were to be displayed it would …

fix(perfmatters): do not delay CSS from Newspack Campaigns or Perfmatters’ own cache

---

includes/plugins/class-perfmatters.php

Excludes front-end stylesheets from the Newspack main plugin from being delayed by Perfmatters. Delaying our own CSS can result in unexpected styles for RAS-related elements in the header and nav menus, especially noticeable at mobile breakpoints.
1. On a site with RAS and Perfmatters enabled, visit the site in a fresh session while in a mobile viewport.
2. Without interacting with the site at all, observe that the My Account link looks improperly styled on page load. Specifically, it will appear without contrast checking (so it'll look grey instead of white on a dark header background color), the "Sign In" label will be displayed when it should be hidden, and the entire button will appear on its own line below the site logo and hamburger menu icon instead of in line with them.
3. If you …

fix(perfmatters): exlcude Newspack CSS from being delayed

---

assets/blocks/reader-registration/index.php
assets/wizards/engagement/index.js
includes/class-blocks.php
includes/cli/class-setup.php
includes/data-events/connectors/class-mailchimp.php
includes/reader-activation/class-reader-activation.php
includes/wizards/class-engagement-wizard.php

Removes the requirement for a `NEWSPACK_EXPERIMENTAL_READER_ACTIVATION` environment flag to access the RAS setup wizard. Any site can now self-enable RAS features by completing the setup wizard.
1. Remove the `NEWSPACK_EXPERIMENTAL_READER_ACTIVATION` flag from `wp-config.php`, if present. Also remove the RAS option if present to reset your site to a pre-RAS state: `wp option delete newspack_reader_activation_enabled`
2. Edit a post or page and confirm that you cannot insert a Reader Registration block (this block is only available once RAS is enabled).
3. Visit **Newspack > Engagement** and confirm that the default page is the Reader Activation dashboard.
4. Visit the prompt wizard of this dashboard and confirm you can edit and preview all prompts, including the Registration prompt (the …

feat(ras): remove env flag requirements for RAS functionality

---

assets/wizards/engagement/components/mailchimp.js
assets/wizards/engagement/views/reader-activation/index.js
includes/data-events/connectors/class-mailchimp.php

Allow the Mailchimp audience to be configured for RAS integration. Also removes the `NEWSPACK_DATA_EVENTS_MAILCHIMP` feature flag.
1. Check out this branch and make sure you have Mailchimp as your ESP and RAS properly configured
2. Navigate to the "Newspack -> Engagement" page and while in the "Reader Activation" tab, click on "Show Advanced Settings"
3. Scroll down and confirm you see the Mailchimp integration section like in the image above
4. Select an audience and save
5. Refresh the page and confirm the saved audience persists
6. In a new session, register a new reader and make a donation
7. Wait until the event dispatches execute the handlers (with `define( 'NEWSPACK_LOG_LEVEL', 2 );` you should see:
```
[NEWSPACK-DATA-EVENTS][Newspack\Data_Events::handle]: Executing global action …
```

feat(ras): mailchimp audience config

---

includes/reader-revenue/class-woocommerce-connection.php

Fixes a possible race condition when calculating the total amount paid per donor when syncing the donor's info to the connected ESP. At the `woocommerce_checkout_order_processed` hook, the order status may be `pending` or `complete`, so the `$customer->get_total_spent()` method may or may not already include the order being processed in the total amount. This fix checks whether the status is `pending` and only adds the processing order amount to the total if it's still pending.
1. On `release`, with your reader revenue platform set to Newspack, ensure that RAS is setup and that the `NEWSPACK_EXPERIMENTAL_READER_ACTIVATION` and `NEWSPACK_DATA_EVENTS_MAILCHIMP` flags are set in wp-config. Test the following with ActiveCampaign.
2. On the front-end, make a one-time donation as a new reader. …

fix(ras): total paid sum race condition

---

includes/class-recaptcha.php

Implements reCAPTCHA v3 to WooCommerce checkout.
1. Checkout this branch and change the [reCAPTCHA threshold](https://github.com/Automattic/newspack-plugin/blob/2b0af0b41addac3e47b67c3833af2daa2c9410f6/includes/class-recaptcha.php#L17) to `1.0`
2. Visit the Newspack -> Connections page and make sure you have reCAPTCHA v3 enabled and configured
3. Deactivate any other reCAPTCHA related plugin you may have
4. With the Reader Revenue set to "Newspack" attempt to donate
5. Confirm you get a captcha error
6. Change the threshold back to `0.5`
7. Donate again and confirm it works as expected

feat: hook reCAPTCHA v3 to WooCommerce checkout

---

includes/plugins/class-perfmatters.php

The bundled `jetpack/css/jetpack.css` includes rules that were previously in `plugins/jetpack/modules/sharedaddy` and `plugins/jetpack/_inc/social-logos`. This excludes the bundled CSS from the delay strategy so it renders on load time.

fix(performance): exclude main jetpack css from delay

---

includes/plugins/class-jetpack.php

Implements additional `srcset` sizes for Jetpack Photon to resize. These should cover common mobile viewports and improve load time.
1. Confirm you have Jetpack configured with `✅ Enable site accelerator` and `✅ Speed up image load times` under the **Performance** tab
2. Visit a post with images and inspect the source
3. Confirm the `srcset` attribute includes images with the sizes 370 and 400
4. Disable photon, refresh the page and confirm the image renders without issues and without the additional `srcset`

feat(jetpack-photon): additional srcset sizes

---

assets/wizards/engagement/components/prompt.tsx
assets/wizards/engagement/components/types.ts
assets/wizards/engagement/views/reader-activation/campaign.js

If you make changes to the prompt settings in the RAS setup prompt wizard and try to navigate away from the wizard without saving, this will pop up a browser warning.
**Note:** For some reason, unlike the same feature in the **Campaigns > Segmentation** dashboard, React Router will not reset the route if you block the navigation by selecting "cancel" when prompted. I couldn't figure out why, but if someone can help me figure it out I'm happy to update the PR.
1. Delete the `newspack_reader_activation_enabled` option on your test site.
2. Navigate to `<domain>/wp-admin/admin.php?page=newspack-engagement-wizard#/reader-activation/campaign` and make some changes to prompts without saving. Confirm that the prompt's status changes to indicate that there are "Unsaved changes", and if the prompt …

feat(ras-defaults): warn if navigating away from wizard with unsaved changes

---

assets/wizards/readerRevenue/index.js
assets/wizards/readerRevenue/views/emails/index.js
includes/emails/class-emails.php
includes/reader-revenue/class-woocommerce-connection.php
includes/wizards/class-reader-revenue-wizard.php

Allows the customizable Newspack receipt email to be used in place of WooCommerce's default receipt email. Also provides a toggle switch to enable or disable this behavior. It's enabled by default, but if turned off, the default WooCommerce or Stripe receipt emails will be sent instead (in case the publisher wants to keep those default receipts for whatever reason).
Closes `1204005426582602/1204087028603366`.
1. On a test site using the "Newspack" reader revenue platform, check out this branch.
2. Visit **Newspack > Reader Revenue > Emails** in WP admin and confirm you see the Receipt email as an option here.
3. Confirm you can edit the email, update its content, and save.
4. On the front-end, make a donation.
5. Confirm that the receipt email received at the donor's email address is the …

feat: customizable receipt emails for Woo

---

includes/author-filter/class-author-filter.php

When first introduced in https://github.com/Automattic/newspack-plugin/pull/1985, it seemed a good idea to enable this filter for custom post types, but now it looks (at least to me) that we are interfering in other plugins behavior.
Posts page is where this filter is most useful anyway. Plugins that register custom post types might not want to have this filter on their CPT page.
1. Confirm that the filter still shows for posts and work
2. Confirm it does not show up for Pages or other custom post types

Only display author filter for posts

---

assets/wizards/engagement/components/prompt.tsx

Fixes an intermittent error introduced by #2453. Sometimes the `hooks.usePrompt` method doesn't return a function before the `savePrompt` method is called and attempts to call `unblock`. This avoids a JS error in that case.
1. Follow testing instructions in #2453. Observe that if you make changes and save a prompt ASAP quickly, you'll sometimes see a JS error: `Uncaught (in promise) TypeError: unblock is not a function`
2. Check out this branch and repeat. Confirm that you don't see the error, and that the prompt still works when you try to navigate away from the page with unsaved changes.

fix(ras): check that unblock exists before calling it

---

assets/components/src/autocomplete-with-suggestions/style.scss
assets/components/src/handoff-message/index.js
assets/wizards/engagement/components/prerequisite.tsx
assets/wizards/readerRevenue/views/nrh-settings/index.js
includes/class-nrh.php
includes/reader-activation/class-reader-activation.php
includes/util.php
includes/wizards/class-reader-revenue-wizard.php

Along with https://github.com/Automattic/newspack-popups/pull/1124, allows sites using NRH as the reader revenue platform to enable RAS via the setup wizard, as long as they have an org ID and a donor landing page (for Campaigns segmentation) specified. Because the setting for Donor Landing Page is somewhat hidden in the Campaigns plugin settings page, but the setting is mostly relevant for sites using NRH or "Other' platforms, this PR duplicates the field in NRH settings so that all RAS prerequisites can be satisfied in one place.
Also fixes a minor bug where the hand-off message shown when visiting other settings pages from the RAS prerequisites page persists a little too long.
1. To start, check out https://github.com/Automattic/newspack-popups/pull/1124, then **deactivate** the …

feat(ras): add NRH support for setup wizard

---

includes/class-recaptcha.php
includes/data-events/class-popups.php
includes/data-events/connectors/ga4/class-ga4.php

https://github.com/Automattic/newspack-popups/pull/1136 moves the method to normalize Newspack Campaigns prompt analytics data to the Newspack Campaigns plugin. This PR updates the Data Events class that handles Campaigns-related events to use that method.
Closes `1204238302518911/1204772076279088`.
Smoke test the GA4 events sent in [`class-popups.php`](https://github.com/Automattic/newspack-plugin/blob/master/includes/data-events/class-popups.php). The data should be the same, with the addition of some donation-related metadata added to an `action_value` param for donation events ([details](https://github.com/Automattic/newspack-popups/pull/1134)).

refactor: use get_popup_metadata method from Campaigns plugin

---

assets/components/src/action-card/index.js
assets/components/src/plugin-installer/index.js
includes/wizards/class-wizard.php

A small tweak to the PluginInstaller component that disables the "Install" action button if the plugin can't be installed programmatically (e.g. if the plugin is a premium plugin without a public download link). Previously the component would attempt to install but fail with an error message due to lacking a URL to install from, which is a subpar user experience.
Also tweaks the message shown while activating a plugin to "Activating...". Previously this said "Installing..." whether installing or activating a plugin.
Closes `1204498218048567/1204685119775505`.
This applies to any instance of the PluginInstaller and any plugin that lacks a `Download` property in [`class-plugin-manager.php`](https://github.com/Automattic/newspack-plugin/blob/master/includes/class-plugin-manager.php#L39), but …

feat(plugin-installer): handle premium plugins in PluginInstaller

---

includes/class-donations.php

Clearing out just donation products when creating the donation checkout can create a weird experience when combined with subscription products that may have been previously added to cart.
This change implements emptying the cart when creating a donation checkout instead of just clearing donation products.
1. While on master, make sure you have a subscription product and attach it to a Checkout Button block in a page
2. Visit the page, click the button to checkout the subscription and exit the modal
3. Visit a page with the donate block and click to donate
4. Confirm you have both products on checkout
5. Check out this branch, repeat steps 2 and 3 and confirm the checkout consists only of the donation product

fix(donations): empty cart on donation checkout

---

includes/plugins/class-jetpack.php

Preserves the incoming image src when filtering new srcset values.
Fixes an issue when a cropped version of the image is being rendered, which should have the desired crop preserved when generating the new srcset URL.
1. Check out this branch and visit a page with Homepage Posts Block with square thumbnails (confirm the source image is not 1:1)
3. Inspect the image and open the URL for 370 width size from the srcset in a new window
4. Confirm the image is square

fix(jetpack): preserve image src for photon srcset filter

---

assets/memberships-gate/metering.js
includes/plugins/wc-memberships/class-memberships.php
includes/plugins/wc-memberships/class-metering.php

When the metering functionality allows content restricted by WC Memberships to render, it doesn't account for campaign prompts, which are still suppressed.
This PR and https://github.com/Automattic/newspack-popups/pull/1152 makes the prompts suppression aware of metering logic.
If the content is locked through front-end metering, the metering script will remove prompts from the DOM.
1. Check out this branch and https://github.com/Automattic/newspack-popups/pull/1152
2. Make sure you have WC Memberships and RAS prompts configured
3. Configure the gate to have 1 anonymous and 1 registered view
4. Visit an article in incognito and confirm it renders the prompts
5. Visit another article and confirm you render the gate and no prompts render
6. Register, visit another article and confirm it …

fix: allow campaign prompts to render on metered content

---

includes/plugins/class-perfmatters.php

This is a quick fix to satisfy a publisher request to force Perfmatters to use high-resolution YouTube thumbnails in YT embeds. The reason we're doing this via a constant is that it's a tradeoff—it will result in a slight decrease in CWV scores, so it's not clear that it should be a default behavior. And it's also unclear whether this is something most sites would want the ability to set, so there's no need to implement UI for now.
1. On a site with Perfmatters enabled, embed a YouTube video into a post. Try this one, which is easy to see the difference in resolution because of the high-contrast text: https://www.youtube.com/watch?v=XZxWRaxqxGI
2. View on the front-end in a large desktop browser window. Observe that the thumbnail looks a bit pixelated and blurry.
3. Check out this branch …

fix: allow high-res youtube thumbs via constant

---

includes/reader-revenue/my-account/class-woocommerce-my-account.php

Fixes a silly bug that prevents the account details from being editable in the My Account page. Currently only the Display Name is available to edit, but when saving any changes to that field, an error message prevents the changes from persisting despite the First Name and Last Name fields not existing on the page:
1. On `release` or `master`, log into a reader account and go to the My Account page. Try to update your Display Name to something else and observe that you can't (see screenshot above).
2. Check out this branch and confirm that you now can.

fix: update required fields for editing My Account details

---

includes/class-plugin-manager.php

Since #2447 our reCAPTCHA v3 implementation is automatically added to the WC checkout flow. Having another plugin like reCaptcha for WooCommerce simultaneously may cause unexpected behavior and should be discouraged.
This PR removes the suggestion to use a 3rd party plugin to prioritize our implementation.
Check out this branch, visit the Plugins page and confirm the reCaptcha for WooCommerce plugin is no longer nested inside "Newspack".

fix: remove reCaptcha for WC plugin

---

includes/data-events/connectors/ga4/class-ga4.php
includes/data-events/listeners.php
includes/reader-activation/class-reader-activation.php

Changes the `reader_registered` action to listen to WP's `user_register` action hook instead of the hook coming from `Reader_Activation:register_reader()`.
This allows for broader coverage of reader registrations, like from WC product purchases.
The original metadata coming from `Reader_Activation:register_reader()` is preserved by storing its entire value as a `np_registration_metadata` user meta.
Note: tests were initially failing because the `user_register` will trigger on mock users created during unit testing. This triggers a filter inside the GA4 connector that calls for `wp_get_current_user()`, which fails the `is_reader()` check. 47469878b56ab3416dac27d85e5c05dc4cf4aebd (with a fix at 999622040a36f72df7f3f1c0e339f3d3b1e51986) fixes that behavior by preventing GA4 connector logic …

feat(data-events): broader coverage for 'reader_registered'

---

assets/reader-activation/auth.js

The authentication modal is redirecting all registration flows to the "My Account" page in order to indicate the reader to verify their account. We want to prevent that when the registration comes from custom flows like the reg. wall, where the page should just refresh to allow the reader to continue reading after registering.
This prevents the redirection to occur if the source of the auth modal is a hash link.
1. Check out this branch, confirm you have RAS enabled and configured and edit a page to include a link to `#register_modal`
2. In an anonymous session, visit the page and click on the link
3. Register a new account and confirm you are not redirected to the "My Account" page
4. Start another fresh session and go through the same registration flow but from the "Sign In" button …

fix(auth): prevent registration redirect from hash link

---

assets/blocks/reader-registration/index.php

Preserves the order of the Newsletters Lists in the Registration block
1. While on the `release` branch, select different Newsletters lists on a "Reader Registration block block
2. Make sure to select a list on the bottom first, and another at the top
3. Confirm that the bottom list is rendered first in the editor
4. Visit the page and confirm it's not reflected on the page
5. Check out this branch, refresh, and confirm it's rendering in the expected order.

fix: preserve newsletters lists order on reg block

---

includes/plugins/wc-memberships/class-memberships.php

Implements [`force_balance_tags()`](https://developer.wordpress.org/reference/functions/force_balance_tags/) to the generated excerpt so the inline gate is never caught inside a blockquote or other parent tags the final `<p />` may be in. Also adds a clearfix to clear from any floating elements it may encounter.
1. While on master setup memberships and a gate without metering (so the backend strategy is used for locking content)
2. Set the gate number of paragraphs to 2
3. Create an article that will be gated and add a paragraph block and a blockquote block second with sample content, e.g.:
```html
<p>First Paragraph</p>
<blockquote class="wp-block-quote is-style-default has-large-font-size" style="font-style:normal;font-weight:700">
<p>Testing Quote</p>
<cite>Mary</cite></blockquote>
``` …

fix(content-gate): close excerpt tags before inline gate

---

assets/reader-activation/index.js
includes/reader-activation/class-reader-data.php

Similar to #2520 and #2539, set the referrer store data item if coming from an external source.
1. Create a link to your instance from a different domain (use Google Drive, Gmail, or any code playground)
2. Click on the link to visit the site and confirm the referrer is stored (`newspackReaderActivation.store.get( 'referrer' )`)
3. Navigate on the site and confirm the referrer persists (not replaced by referring itself)

feat(reader-data): set referrer

---

includes/reader-activation/class-reader-data.php

Implements the following common reader data:
- `is_newsletter_subscriber`
- `is_donor`
- `is_former_donor`
1. Check out this branch and subscribe to a newsletter in a fresh session (either through Newsletter Subscription Form block or Reader Registration block)
2. Confirm the next page render have the `is_newsletter_subscriber` store item set as true either by running `newspackReaderActivation.store.get('is_newsletter_subscriber')` on the frontend or checking the localStorage items in devtools
3. Do a one-time donation through the Donate block
4. Confirm the next page render has the `is_donor` set as true and `is_former_donor` set as false
5. Subscribe to a recurring donation
6. Cancel the subscription through "My Account" (it'll be set as pending and not canceled just yet)
7. Expedite …

feat(reader-data): add newsletter subscription and donation

---

assets/memberships-gate/block-patterns.scss
includes/plugins/wc-memberships/block-patterns/pay-wall-one-tier-metering.php

This PR, along with https://github.com/Automattic/newspack-theme/pull/2157, aim to improve how the content gate patterns look on mobile. The specific changes I made for this were:
* Hiding empty columns in the gate on smaller screen sizes -- this reduces some vertical spacing.
* Applying padding to a columns block instead of letting it fallback to the default padding that's added when the block has a background -- the latter doesn't change for smaller screen sizes, but thanks to https://github.com/Automattic/newspack-theme/pull/2157, the former will.
I also removed the secondary colour from a paragraph in the Paywall One Tier Metering pattern -- there isn't a way to make sure the contrast is sufficient for this colour in all cases, so it seems safer to leave it out. 
Lastly, I had to add …

fix: tweak content gate styles for mobile

---

assets/reader-activation/auth.js
includes/reader-activation/class-reader-activation.php

Improves the authentication flow when a reader attempts to register with an existing account. It's currently not working as expected but could also be improved to allow the OTP code to be entered directly.
| Current | Expected | Proposed |
| --- | --- | --- |
| <img width="565" alt="image" src="https://github.com/Automattic/newspack-plugin/assets/820752/e139e56e-90c3-4c7f-9a2d-55c0b159da59"> | <img width="564" alt="image" src="https://github.com/Automattic/newspack-plugin/assets/820752/a1a27279-b4ea-4df1-bc4e-71769afdbd21"> | <img width="578" alt="image" src="https://github.com/Automattic/newspack-plugin/assets/820752/eacf3f64-95a3-4d85-bce2-e7a244d39b98"> |
1. While on the master branch make sure you have RAS enabled and register a new reader account
2. Start a fresh session in click on …

fix(auth): render otp when registering with existing account

---

assets/blocks/reader-registration/view.js
assets/reader-activation/auth.js
assets/wizards/connections/views/main/recaptcha.js

Ensures that the `input` elements used by reCAPTCHA is not autofilled by the browser, in both admin and front-end contexts.
Note that I wasn't able to replicate the autofilling issue in either case, but adding the `autocomplete="off"` attribute _should_ prevent the field from getting autofilled by most browsers. See also https://github.com/Automattic/newspack-newsletters/pull/1203
Closes `1204751246381643/1204838932706810`.
1. Turn on autofill for your browser and ensure that there is a saved email address that will automatically autofill any email inputs.
2. Delete prior credentials: `wp option delete newspack_recaptcha_site_key && wp option delete newspack_recaptcha_site_secret`
3. Test on `master` first, with reCAPTCHA v3 enabled in the Connections wizard.
4. In the admin, go to …

fix: disable autofill for recaptcha inputs

---

includes/reader-activation/class-reader-data.php

At some point during revisions of #2520 the strategy to push activities in the front-end changed from `newspackRAS.push( [ action, data ] );` to `ras.dispatchActivity( { action, data } );` but the activity setup didn't account for that change.
This PR changes the setup to create an array of objects with `action` and `data` properties instead of an array with the values.
Same instructions as in #2520

fix(reader-data): format of activity push array

---

includes/plugins/class-perfmatters.php

Adds The Event Calendar and The Event Calendar Pro plugins to the list of excluded stylesheets in default Perfmatters settings. Otherwise, the search, filter, and subscribe UIs are not visible on the calendar page.
Closes `1200550061930446/1205011966811759`.
1. Install `the-events-calendar` and view your calendar page.
2. On `master` or `release`, observe that parts of the UI are missing:
3. Check out this branch. You may have to go to Settings > Perfmatters > Assets and click the "Clear Used CSS" at this point, too.
4. Refresh the calendar page and confirm that the full UI is visible:

fix(perfmatters): add TEC CSS to excluded stylesheets

---

assets/reader-activation/utils.js
assets/reader-activation/utils.test.js

Using the `Math.random()` strategy there's a small chance the result does not have enough length to fetch using substring.
This PR changes the ID generation strategy to ensure its length.
1. Confirm 82b7d4f21287b091466a9d467356bdf4dfd8b45d, which introduces a new test, fails
2. Confirm the test passes with 14571aa19326c2c15c59bd01eb6f867280b2178f
3. Confirm the entropy test introduced by 3b9bb585014a499214ad567894eff430763d26f2 also passes

fix: ensure generated id always have given length

---

includes/class-rss-add-image.php

We recently switched the RSS feed to use the large image rather than the medium image size. Unfortunately, this has caused email layout issues on sites using Active Campaign -- the email layouts look bad, and there isn't an option in Active Campaign itself to scale the image down. As a compromise between the two, this PR adds an RSS image size control to the Media Settings page. It still defaults to the standard WordPress large size (1024), but can be changed from there.
Note: this will be a breaking change for any publications with non-standard large image sizes; we may at least want to make a more noticeable announcement when this goes out.
See: 1200550061930446-as-1204959665169392
1. Apply the PR.
2. Create and publish a new post with a featured image that's newly uploaded to your …

Feat: add an image size control for the RSS images

---

includes/class-newspack.php
includes/data-events/class-woo-user-registration.php
includes/data-events/listeners.php
includes/reader-activation/class-reader-activation.php

https://github.com/Automattic/newspack-plugin/pull/2526 didn't actually work well. The metadata was being added after the user was registered, so the event was never sending any metadata.
This PR reverts the event to listen to the `newspack_registered_reader` hook and creates a new hook specifically for the readers registered during a Woocommerce checkout.
1. Setup a webhook using https://webhook.site/ to get all incoming data events 
2. Purchase a product anonymously and confirm that the created account triggers a `reader_registered` event and it reaches the webhook
3. On a fresh session, register through a RAS prompt with a reader registration block
4. Confirm the event reaches the webhook with no regression on the metadata contents
5. Test purchasing products and making donations via …

feat: trigger reader_registered for Woo checkout

---

includes/class-recaptcha.php

Regenerates the reCAPTCHA token every 30 seconds to make sure it's valid when an order is placed.
1. While on `release`,  go through the donate block flow and wait a little bit over 2 minutes before clicking "Place order"
2. Confirm you get captcha error
3. Check out this branch, repeat step 1, and confirm the order is placed without errors

fix(recaptcha): prevent token timeout on WC

---

includes/class-pwa.php

Tweaks the "offline server" message from PWA to be more vague. Failing to fetch the server shouldn't immediately suggest that the server is down.
Before: The server appears to be down, or your connection isn't working as expected. Please try again later.
After: There has been a problem connecting with the server. Please check your internet connection or try again later.
1. Check out this branch and visit your website (make sure the PWA plugin is enabled)
2. Make your website offline (via /etc/hosts or shutting down nginx/apache)
3. Refresh and confirm it shows: "There has been a problem connecting with the server. Please check your internet connection or try again later."

fix(pwa): improve "server offline" message

---

assets/wizards/connections/views/main/fivetran.js

Since GA3 is gone, we are removing the Fivetran connection for it
1. Go to Newspack Connections
2. Make sure there's no longer an item to connect Google Analytics

feat: Remove GA Fivetran connection

---

includes/plugins/wc-memberships/class-memberships.php

When using `the_content` to parse the gate contents it may pick up additional markup meant to be rendered in the article. This implements a new `newspack_gate_content` filter, which allows better control of [which filters](https://github.com/WordPress/WordPress/blob/fe75c1b12f94fdb1deb37dd6ba1f29f639357a35/wp-includes/default-filters.php#L192-L199) should be applied.
1. Make sure you have WC Memberships with content gate
2. Add all block patterns from the category "Memberships" to the content gate to test their rendering
3. Visit a gated article and confirm all blocks render as expected

fix(content-gate): use custom filter for gate content

---

assets/memberships-gate/editor.js
assets/memberships-gate/metering.js
includes/plugins/wc-memberships/class-memberships.php
includes/plugins/wc-memberships/class-metering.php

Support custom gates for content restricted behind a specific membership plan.
Primary gate:
Plan gate:
1. Make sure you have at least 2 plans with WC Memberships. One targets a group of categories, and the other targets a specific category (not included in the prior plan).
2. Visit the Content Gate editor (Newspack -> Engagement -> Advanced Settings)
3. Confirm you see the WooCommerce Memberships panel in the sidebar of the editor (as the image above)
4. Create a gate that should target the group of categories and save
5. Click to create a gate for the plan that targets a specific category
6. Save the gate with different content
7. In a fresh session, navigate the site and confirm you see the gate for every content (outside the category) and the specific category gate for content inside …

feat(content-gate): support gate per plan

---

includes/plugins/class-perfmatters.php

Makes two changes to the way we set Perfmatters defaults:
1. Ensures that the "fastclick" option is enabled to avoid a bug affecting iOS, where the first page interaction sometimes take two taps to trigger
2. Persists our Newspack default settings to the database, so that if the `NEWSPACK_IGNORE_PERFMATTERS_DEFAULTS` option is added to wp-config.php, those settings can be tweaked without reverting back to Perfmatters' own defaults.
Closes `1200550061930446/1204481257627340` and `1204616440912018/1204616586582340`.
1. On `master` or `release`, using an iPhone browser, visit a front-end page that will render an overlay prompt.
2. Wait until the overlay pops up. You may have to scroll the page to get it to appear on iOS; this appears to be an OS-level performance feature.
3. Tap on the close …

fix: perfmatters default settings updates

---

assets/reader-activation/auth.js

Fixes a regression introduced by #2542.
The OTP UI is no longer rendering when attempting to sign in. This is because the form handler interprets the status `200` as a form resolution and clears the UI.
1. While on the `release` branch, click to Sign In using email and confirm the form shows empty on submit
2. Check out this branch, Sign In and confirm OTP renders and works as expected
3. Start the auth flow again, click "I don't have an account", enter an existing reader email and confirm the OTP input also renders

fix(auth): restore sign-in otp ui

---

__mocks__/@wordpress/api-fetch.js
assets/components/src/settings/MinMaxSetting.js
assets/components/src/settings/style.scss
assets/wizards/popups/components/segment-group/index.js
assets/wizards/popups/utils.js
assets/wizards/popups/views/campaigns/index.js
assets/wizards/popups/views/segments/SegmentsList.js
assets/wizards/popups/views/segments/SingleSegment.js
assets/wizards/popups/views/segments/SingleSegment.test.js
includes/configuration_managers/class-newspack-popups-configuration-manager.php
includes/wizards/class-popups-wizard.php
includes/wizards/class-wizard.php

1204189396255901-as-1204857763418497
Changes the Segments UI to use the new criteria system and updated schema.
Confirm updated tests are passing and have appropriate coverage.
1. Checkout this branch and https://github.com/Automattic/newspack-popups/tree/epic/rearchitecture
2. Create, edit and delete segments and confirm everything works as expected
3. Create a segment using all available criteria
4. Visit the "Segments" home and confirm the description renders correctly for every item
5. Visit the "Campaigns" home and confirm the same description also renders correctly

feat: segments criteria ui

---

includes/class-donations.php

Very minor fix :-D 
I didn't have the Woo plugin on my local install and I was getting a `Deprecated: html_entity_decode(): Passing null to parameter #1 ($string) of type string is deprecated in newspack-plugin/includes/class-donations.php on line 291`.
The switch didn't correctly handle cases where Woo is not installed and would install null in that case. This PR fixes that.
1. On a site with no Woo installed, go to `wp-admin/admin.php?page=newspack` and `WP_DEBUG_DISPLAY` set to true you should not see the deprecation notice (and you should without this patch).
2.
3.

fix: ensure not null in currency string

---

assets/blocks/reader-registration/edit.js
assets/components/src/autocomplete-tokenfield/index.js
assets/components/src/category-autocomplete/index.js
assets/components/src/handoff/index.js
assets/components/src/hooks/useObjectState.js
assets/components/src/select-control/GroupedSelectControl.js
assets/components/src/tabbed-navigation/index.js
assets/components/src/wizard/store/index.js
assets/shared/js/button-props.js
assets/wizards/advertising/components/ad-unit-size-control/index.js
assets/wizards/advertising/views/placements/index.js
assets/wizards/analytics/views/custom-events/index.js
assets/wizards/connections/views/main/fivetran.js
assets/wizards/engagement/views/newsletters/index.js
assets/wizards/popups/utils.js
assets/wizards/popups/views/analytics/Info.js
assets/wizards/popups/views/analytics/utils.js
assets/wizards/popups/views/campaigns/index.js
assets/wizards/popups/views/segments/SingleSegment.js
assets/wizards/readerRevenue/index.js
assets/wizards/readerRevenue/views/emails/index.js
assets/wizards/readerRevenue/views/stripe-setup/index.js
assets/wizards/seo/index.js
assets/wizards/setup/views/services/ReaderRevenue.js
assets/wizards/setup/views/services/index.js
assets/wizards/setup/views/welcome/index.js
assets/wizards/site-design/views/main/index.js
includes/oauth/class-google-oauth.php

Fixes a fatal error that prevents Newspack admin dashboard screens from rendering. For some reason, WP 6.3 does not like our use of destructured module imports from the main `lodash` NPM package. This also only seems to affect the main plugin and not our other repos.
1. On a site running `release` and WP [6.3-RC1](https://wordpress.org/news/2023/07/wordpress-6-3-release-candidate-1/), visit any of the Newspack wizard screens and observe a JS error that prevents the UI from rendering:
```
Uncaught TypeError: __webpack_require__.nmd is not a function
```
2. Check out this branch and confirm that all Newspack wizard screens load without errors. Also check that the block editor works with Newspack blocks (Registration, Subscribe, Donate, Homepage Posts, Carousel, etc.)
3. Gut check a test …

fix(wp-6.3): destructured lodash module import error

---

includes/data-events/class-webhooks.php

Closes https://github.com/Automattic/newspack-popups/issues/1164 .
1. Set up a webhook in https://webhook.site
2. In Newspack > Connections, create a new webhook with the endpoint created above
3. Select only the `prompt_interaction` event for this webhook
4. Make a donation via a campaign prompt
5. on `master` confirm that the json received is broken
6. Checkout this branch and repeat the process, confirm the json looks ok

fix: avoid webhooks to break with json encoded data

---

assets/wizards/analytics/index.js
assets/wizards/analytics/style.scss
assets/wizards/analytics/views/index.js
assets/wizards/analytics/views/newspack-custom-events/index.js
includes/data-events/connectors/ga4/class-ga4.php
includes/wizards/class-analytics-wizard.php

This PR updates the Analytics wizard by removing the tabs handling UA's custom dimensions and events and replacing with a tab where the users can add the credentials to enable GA4 back-end events tracking.
This PR does NOT deprecates or removes several back-end classes, hooks and methods that uses those custom dimensions and other UA plus AMP event tracking. I think there should be a dedicated effort for that.
1. Go to Newspack > Analytics
2. Confirm you see only one tab other than Plugins
3. Go to that tab
4. Check that you can save your credentials and they persist
5. Try to add a Measurement ID that don't start with "G-" and confirm you see an error
6. Perform a donation or newsletter subscription in your site
7. confirm you see a [corresponding …

feat: update analytics wizard

---

includes/reader-activation/class-reader-data.php

Changes the `Newspack\Reader_Data::update_item()` method to public.

fix(reader-data): make the 'update_item()' method public

---

includes/data-events/connectors/ga4/class-ga4.php
tests/unit-tests/ga4-connector.php

Fixes a regression that was preventing ga4 events to be sent
1. Check that events are sent when only the credentials added via filter (newspack manager) exist

fix: check for the ga4 connector

---

includes/reader-activation/class-reader-data.php

The `activity_view` data setup runs before the `get_the_author()` function is able to return the author's display name. The function uses the global `$authordata`, which for single posts is only registered when `setup_postdata()` is called.
This changes the author property to use the post's `post_author` directly.
1. While on the master branch, navigate to an article and confirm the pushed `article_view` has author empty
2. Checkout this branch, refresh and confirm the new push contains the author ID

fix(reader-data): ensure author on 'article_view' push

---

includes/class-newspack.php

Fixes a minor pet peeve which should mainly affect only devs and Newspack team members. The redirect to the setup wizard upon plugin activation should only happen if setup hasn't already been completed.
2. On a fresh site, install and activate this plugin. Confirm that on the next visit to any page within WP admin, you're redirected to the Newspack setup wizard.
3. On a site that has already completed the setup wizard, deactivate and reactivate this plugin. Confirm that you're NOT redirected to the setup wizard when visiting WP admin.

fix: only redirect to setup if not completed already

---

assets/wizards/popups/utils.js

Moves the try/catch so other favorite categories that might be part of the segment render their names if one fails.
1. Checkout https://github.com/Automattic/newspack-plugin/tree/epic/campaigns-rearchitecture, https://github.com/Automattic/newspack-popups/tree/epic/rearchitecture and https://github.com/Automattic/newspack-blocks/tree/epic/campaigns-rearchitecture
2. Create a segment that matches 2 favorite categories
3. Delete one of the categories
4. Visit the "Segments" wizard and confirm the "Favorite Categories: " description shows empty
5. Check out this branch, refresh, and confirm it shows the remaining category

fix(campaigns): move try/catch while fetching fav cat names

---

includes/class-donations.php
languages/newspack-plugin.pot

This PR corrects the text domain in a 'thank you' donation string, and adds a long-overdue update to the plugin's POT file. 
See 1200550061930446-as-1204849686104010
1. Apply the PR.
2. Confirm that the text domain for the "Thank you for your donation!" string is now for this plugin, and not the blocks.
3. Confirm the POT file is up to date (the plugin doesn't have any translations bundled with it, so there isn't much to test!).

fix: correct thank you message text domain

---

assets/wizards/advertising/views/ad-unit/index.js

Details and instructions at https://github.com/Automattic/newspack-ads/pull/701

feat(ads): display parent ad unit path on ad unit editor

---

assets/reader-activation/store.js
assets/wizards/popups/components/segmentation-preview/index.js
assets/wizards/popups/components/settings-modal/index.js
includes/reader-activation/class-reader-data.php

Adds a filter which lets us set a reader data store session as temporary. If set, reader data will be written to and read from `sessionStorage` intead of `localStorage`, and will not be synced to nor rehydrated from the server. This is to support preview sessions in https://github.com/Automattic/newspack-popups/pull/1178.
See testing instructions in https://github.com/Automattic/newspack-popups/pull/1178.

fix: support temporary preview sessions for reader data store

---

assets/components/package.json

Bumps the version number of the `newspack-components` package to the latest published version, `2.2.1`.
Nothing to test. Simply sets the baseline to determine the next package version.

chore: bump version of newspack-components NPM package

---

assets/wizards/popups/views/analytics/index.js

Deprecates the UA-driven Campaigns Analytics dashboard and replaces it with a temporary placeholder message. I didn't remove the other views or components from the codebase in case we want to re-use those in the future to show GA4 data.
1. Check out this branch, visit **Newspack > Campaigns > Analytics**. Check that the links lead to the [right page](https://help.newspack.com/analytics/).

feat: campaigns analytics placeholder

---

includes/wizards/class-setup-wizard.php

As a natural follow-up to https://github.com/Automattic/newspack-plugin/pull/2593, this PR ensures that Akismet is activated and defaults to the "on" position upon site creation.
1. Create a new Newspack site.
2. Verify that Akismet, a symlinked plugin, is automatically activated.

Activate Akismet upon site creation

---

includes/reader-activation/class-reader-data.php

If a contact is already signed up for a list in the ESP, then somehow registers for the site with the same email address, they are not segmented as a newsletter subscriber until they update their subscriptions (by either signing up for a new list or unsubscribing from one in My Account).
TL;DR the segmentation update isn't triggered until you edit subscriptions on the site
Closes `1200550061930446/1205326345667208`.
1. Check out `master`.
2. Either turn off RAS temporarily on your site and sign up for a newsletter, or manually add a contact to a list directly in the connected ESP.
3. On the Newspack site, register for an account using the same email address. without signing up for newsletters. This can be done via a Registration block if multiple lists are available and you deselect them …

feat(reader-data): check newsletter subscription on login

---

assets/wizards/engagement/index.js
assets/wizards/engagement/views/reader-activation/index.js
includes/plugins/wc-memberships/class-memberships.php
includes/wizards/class-engagement-wizard.php

Some publishers want to gate most articles behind a metered reg wall, but gate some smaller subset of those articles (e.g. those with a "Premium" category) behind a hard paywall. Free registrants should get access to most articles, but not to paywalled articles until they purchase the necessary membership. This is a common content gating strategy used by many large-scale publishing sites but which we currently can't support without the proposed change.
We do have the ability to show different paywalls for these two "tiers" of restricted content. This is done by creating two membership plans: Plan 1 restricts all posts with a metered reg wall. Plan 2 restricts Premium articles with a paywall.
However, the way WooCommerce Memberships works, if multiple different membership plans have …

feat: new option to require all membership plans for restricted content

---

includes/reader-activation/class-reader-data.php

fix(reader-data): `gettype` typo while checking newsletter subscription

---

includes/class-newspack.php
includes/reader-revenue/stripe/class-stripe-sync.php
includes/reader-revenue/stripe/class-stripe-webhooks.php
includes/reader-revenue/woocommerce/class-woocommerce-connection.php
includes/reader-revenue/woocommerce/class-woocommerce-sync.php

Fixes some lingering issues with the Stripe-to-Woo migration script. Also adds a new script that allows us to trigger a resync of contact data to the connected ESP, in case the ESP's synced data has diverged from the source of truth (WooCommerce).
1. On `master`, set your Reader Revenue platform to Stripe and make sure your wp-config.php doesn't have the `NEWSPACK_USE_WC_SUBSCRIPTIONS_WITH_STRIPE_PLATFORM` constant. Also make sure that RAS is enabled and that your connected ESP is either ActiveCampaign or Mailchimp (the ESPs to which we sync RAS data).
2. Make a recurring donation as a new reader. Confirm that the contact is synced to the connected ESP with our usual Newspack metadata. Take special note of the `NP_Membership Status` value: it should be something like "Monthly Donor", …

fix: sync scripts for Stripe-to-Woo migrations

---

assets/components/src/tabbed-navigation/index.js
assets/wizards/advertising/index.js
assets/wizards/engagement/index.js
assets/wizards/popups/index.js

Fixes a minor pet peeve of mine in the tabbed Newspack wizard UI. Allows for a `/pathname/*` pattern to be included in the `activeTabPaths` prop used in the tabbed wizard navigation, so that a tab can be highlighted as long as the current route path contains the non-* parts of the pattern. This is so that we can highlight tabs even if the route path contains dynamic parts.
Branched off of #2628 because that PR introduces a whole new section that can make use of this new feature.
1.  View some wizard pages that use the `activeTabPaths` prop (Advertising > Providers, Advertising > Marketplace, Campaigns > Segments, Engagement > Reader Activation, and their subpages, including dynamic routes like editing an existing segment or GAM ad unit).
2. Confirm that the right tab is highlighted in the …

fix: allow for /* modifier in activeTabPaths prop

---

assets/wizards/engagement/components/mailchimp.js

https://github.com/Automattic/newspack-newsletters/pull/1255 introduced a change in the Newsletters' subscription lists schema which caused a regression in Mailchimp's audience selector for RAS' data sync settings wizard.
This PR restores the selector options.
1. While in the `release` branch, make sure you have RAS and Mailchimp as your ESP
2. Visit "Engagement -> Reader Activation -> Show Advanced Settings" and scroll down to "Mailchimp"
3. Confirm "Audience ID" is "None" and there are no options available
4. Check out this branch, build, refresh the page, and confirm you're now presented with the available audiences
5. Select an audience, save, refresh, and confirm the audience persists

fix: restore audience selector for mailchimp data sync

---

includes/class-plugin-manager.php

Adds `akismet` to the list of "required" plugins for the Newspack platform. Coupled with the PR in the private Manager repository, it makes it difficult to deactivate or delete this plugin from the Plugins dashboard page.
Follow instructions in the private manager plugin repository.

feat: disable deactivate and delete for Akismet

---

includes/class-plugin-manager.php

Adds 10up's Ads.txt Manager plugin to Newspack's list of approved/recommended/default plugins.
Adds 10up's [Ads.txt Manager](https://wordpress.org/plugins/ads-txt/) plugin to Newspack's list of approved/recommended/default plugins. See 1204015893379290-as-1204159745402806.
1. Navigate to `/wp-admin/plugins.php`
2. Note that Ads.txt Manager is among the default plugins listed with a hyphen prefix.
3. Install and activate the plugin.

Adds ads.txt manager to plugin manager

---

includes/class-plugin-manager.php

For when we're ready to switch from recommending [WP GDPR Cookie Notice](https://wordpress.org/plugins/wp-gdpr-cookie-notice/) to [Complianz](https://wordpress.org/plugins/complianz-gdpr/).
Context: pamTN9-4wk-p2

feat: replace recommended cookie plugin

---

includes/class-plugin-manager.php

Newspack Plugin maintains a list of plugins that will not be added to the WP Admin plugins screen, but installing them will not raise any issues in Newspack > Health Check.
Historically, this list has included AMP, which has been retired from our platform (and will likely soon be blocked entirely). This PR removes AMP from that list.
Adds `super-cool-ad-inserter-plugin` to the allowed list, while we're at it!
1. Navigate to `/wp-admin/plugin-install.php`
2. Search for, install, and activate [AMP](https://wordpress.org/plugins/amp/).
3. Visit `/wp-admin/admin.php?page=newspack-health-check-wizard#/` and confirm that AMP is listed as an unsupported plugin.
* [Z] Have you added an explanation of what your changes do and why you'd like us to include them?

feat(amp-deprecation): Remove AMP from supported list

---

assets/components/src/tabbed-navigation/index.js
assets/wizards/advertising/index.js
assets/wizards/advertising/views/marketplace/index.js
assets/wizards/advertising/views/marketplace/products/index.js
assets/wizards/advertising/views/marketplace/settings/index.js
assets/wizards/engagement/index.js
assets/wizards/popups/index.js
includes/wizards/class-advertising-wizard.php

Details and instructions at https://github.com/Automattic/newspack-ads/pull/718

feat(ads): marketplace settings wizard

---

includes/reader-revenue/stripe/class-stripe-sync.php

The `wp newspack stripe set-next-payment-dates-for-migrated-subscriptions` script sets next payment dates for active migrated subscriptions that lack them, but it didn't account for migrated subscriptions that have next payment dates in the _past_. This fixes that.
1. On a WC subscription, set the next payment date to a date in the past. The UI doesn't let you do this, so you'll need to do it via code: e.g. `update_post_meta( 341, '_schedule_next_payment', '2022-12-04 14:44:30' );`
2. Run the `wp newspack stripe set-next-payment-dates-for-migrated-subscriptions` CLI script. Observe that it skips the subscription with the past date.
3. Check out this branch and repeat step 2. Confirm that it resets the next payment date for the subscription to the next future date based on the period and …

fix: let set-next-payment-dates-for-migrated-subscriptions reset past dates

---

includes/plugins/class-perfmatters.php

Fixes an issue with applying Perfmatters' defaults.
Closes 1200550061930446-as-1205578729475972
1. Start afresh by removing the `perfmatters_options` option
2. Ensure the `NEWSPACK_IGNORE_PERFMATTERS_DEFAULTS` env. variable is **not** set
3. Visit the Perfmatters settings, observe the defaults are applied
4. Update one of the toggled off options (e.g. "Disable Embeds") to make sure the options are saved to the DB
5. Now set the `NEWSPACK_IGNORE_PERFMATTERS_DEFAULTS` env. variable to `true`
6. Update the one of the _toggled on_ options (e.g. "Disable Emojis")
7. Observe the option can't be toggled off!
8. Switch to this branch, try to disable the toggled on option again, observe it now can be toggled off

fix(perfmatters): handling false values when applying defaults

---

includes/reader-revenue/woocommerce/class-woocommerce-connection.php
includes/reader-revenue/woocommerce/class-woocommerce-order-utm.php

Adds UTM parameters as order meta and render in the order details:
1. Check out this branch and https://github.com/Automattic/newspack-blocks/pull/1540
2. Visit a page that contains a Donate block with these parameters: `?utm_source=new+subscribers&utm_medium=email&utm_campaign=black+friday+sale&utm_content=first+cta+button&utm_term=test`
3. Make a donation and visit the order details at WooCommerce -> Orders
4. Confirm the UTM parameters are displayed like in the image above
5. Repeat the steps above but with a page that has a Checkout Button block

feat(woocommerce): add UTM parameters as order meta

---

includes/reader-revenue/woocommerce/class-woocommerce-order-utm.php

The feature implemented in #2665 might not work as expected if the reader is prompted to go through the 2-step checkout (new readers).
This PR ensures the UTM inputs are rendered in a hook that is not conditioned to any checkout step, fixing the issue.
1. While on the master branch, visit a page with the Donate block and the `?utm_campaign=test` query param anonymously
2. Confirm the order is placed without the UTM param
3. Check out this branch, repeat the anonymous purchase and confirm the UTM param is stored

fix(woocommerce): hook for rendering UTM inputs

---

assets/wizards/advertising/views/placements/index.js

Fixes the "Stick to top" toggle when editing the "Sidebar" ad placement.
#2578 [accidentally removed](https://github.com/Automattic/newspack-plugin/pull/2578/files#diff-47fb0b82e6a1f192e1bddc4a8c5402e2d94367b906c71cc7b0422ecfae456b13) the `set()` we were using (from fp to the regular `set()`). This fix changes to no longer use the fp approach.
1. While on the `release` branch, visit Newspack -> Advertising -> Placements
2. Enable and edit the Sidebar placement and toggle "Stick to top"
3. Confirm the placement data breaks and the UI appears broken
4. Check out this branch, refresh the page, and try again
5. Confirm you are able to toggle and save the setting

fix(ads): stick to top toggle

---

assets/components/src/autocomplete-tokenfield/index.js
assets/components/src/settings/style.scss
assets/components/src/subscription-lists-control/index.js
assets/reader-activation/store.js
assets/wizards/popups/utils.js
assets/wizards/popups/views/segments/SingleSegment.js
includes/reader-activation/class-reader-data.php

Changes required for https://github.com/Automattic/newspack-popups/pull/1218:
- Implements a new `newsletter_subscribed_lists` store data item
- Adds the necessary changes to the campaigns' wizard to support the new criteria
- Creates a `SubscriptionListsControl` component to select newsletter subscription lists from the API using the `AutocompleteTokenField` component
1. Follow instructions at https://github.com/Automattic/newspack-popups/pull/1218
2. Make sure the `newsletter_subscribed_lists` data item updates on different occasions:
1. subscribe a fresh account and confirm the selected lists are stored
2. unsubscribe to a list from "My Account -> Newsletters" and confirm it updates the item
3. subscribe to another list from "My Account -> Newsletters" and confirm it updates the item

feat(campaigns): newsletter subscription list criteria

---

includes/reader-activation/class-reader-activation.php

We've seen reports from readers that the honeypot field sometimes gets autofilled by Chrome's built-in password manager, despite the `autocomplete="off"` attribute. (Probably because Chrome [intentionally ignores this attribute](https://adamsilver.io/blog/stopping-chrome-from-ignoring-autocomplete-off/)). There's not much we can do to prevent this frustrating behavior, but since the honeypot is kind of redundant/unnecessary if protecting forms with reCAPTCHA, this PR proposes we only render the honeypot if reCAPTCHA is not on, as a sort of fallback security measure. Since most Newspack sites enable reCAPTCHA to protect their form inputs, this should sidestep the autocomplete issue for most readers.
See also https://github.com/Automattic/newspack-newsletters/pull/1301
1. Check out this …

fix: remove honeypot field if using reCAPTCHA

---

includes/reader-revenue/woocommerce/class-woocommerce-connection.php

Check if the Newspack Newsletters method is available before syncing the reader on WooCommerce orders.
1. While on the master branch, make sure you have RAS configured and deactivate the Newspack Newsletters plugin
2. Donate using the donate block and confirm you get a fatal error
3. Checkout this branch, donate again, and confirm it works without errors
4. Activate Newspack Newsletters and donate again
5. Confirm the contact syncs to the ESP

fix(woocommerce): check method exists before syncing reader

---

assets/wizards/connections/views/main/index.js
assets/wizards/seo/index.js

The `deep-map-keys` NPM package is throwing a lodash dependency error. Since this package hasn't received an update in 5+ years, let's not rely on it anymore.
1. On `release`, visit Newspack > SEO and observe a JS error: 
2. Check out this branch, refresh, confirm no error.
3. Update values for each setting, save, refresh, confirm all values are persisted.
1. Go to Newspack > Connections
2. Force an error in any of the third-party connection components (Google, Mailchimp, Fivetran, reCAPTCHA) by adding a `setError( 'TEST' );` call in the component render function
3. Confirm that the error message is prefixed with the name of the service:

fix: avoid deepMapKeys NPM package

---

includes/data-events/class-webhooks.php

Registers webhook hooks earlier for https://github.com/Automattic/newspack-newsletters/pull/1314

fix(data-events): earlier priority for webhook registration

---

includes/class-plugin-manager.php

Adds Perfmatters to our list of managed plugins.
Adds Perfmatters to our list of managed plugins.
Also deletes Perfmatters, Super Cool Ad Inserter Plugin, and Ads.txt Manager from our list of "supported, but not managed" plugins, since they are in fact managed (SCAIP as of https://github.com/Automattic/newspack-plugin/pull/246 and Ads.txt Manager as of https://github.com/Automattic/newspack-plugin/pull/2639).
2. Ensure the Newspack plugin is active.
3. Visit `/wp-admin/plugins.php`
4. Verify that Perfmatters, whether or not it's installed, is nested under "Newspack" and prefixed with a hyphen.

feat: add Perfmatters to managed plugins

---

includes/plugins/class-perfmatters.php

https://github.com/Automattic/newspack-plugin/pull/2360 was supposed to be a hotfix, but the base branch was erroneously set to `master`.

fix(perfmatters): add twitter.com to JS delay list

---

includes/wizards/class-wizard.php

Updates the last (hopefully) instance of a support link that hasn't been updated to the new URL.
1. Check out this branch, visit any Newspack wizard page in the admin.
2. Confirm that the "Documentation" link at the bottom of the page leads to help.newspack.com, not newspack.com/support.

fix: update support link to help site

---

assets/blocks/reader-registration/block.json
assets/blocks/reader-registration/edit.js
assets/blocks/reader-registration/index.php

1200550061930446-as-1205543124448992
Similar to https://github.com/Automattic/newspack-newsletters/pull/1313, support toggling and storing the checkbox state for defining the initial form state:
1. Draft a new page and add a Newsletter Subscription Form block
2. Enable multiple lists and toggle their checkbox state in the editor
3. Save, refresh, and confirm the selected state is preserved
4. Visit the page and confirm the selected state is also reflected on the page

feat(reader-registration): custom checkbox state for lists

---

assets/components/src/sortable-newsletter-list-control/index.js
assets/components/src/sortable-newsletter-list-control/style.scss
assets/wizards/engagement/views/reader-activation/index.js
includes/reader-activation/class-reader-activation.php
includes/wizards/class-engagement-wizard.php

Implements a RAS advanced setting for selecting custom newsletter lists, their order and default `checked` state when rendering in the registration modal.
1. Check out this branch and make sure you have RAS enabled and Newspack Newsletters connected with an ESP and enabled with subscription lists
2. Navigate to Newspack -> Engagement -> Reader Activation -> Advanced settings
3. Scroll to the "Newsletter Subscription Lists" section and toggle the "Custom newsletter lists on registration"
4. Confirm you can click on multiple available lists
5. Sort by clicking on the chevrons, make some checked by default and others not and save
6. Visit your site anonymously, click "Sign in" -> "I don't have an account" and confirm the configured lists and rendered in the defined order with the defined …

feat(ras): custom newsletter list selection on registration

---

includes/plugins/class-perfmatters.php

Fixes an edge case encountered on live sites. Before some Perfmatters' defaults were applied, the plugin already had a chance to create the "used CSS" stylesheet and save it. Later, when CSS used by our software was updated, the out-of-date copy was still kept in Perfmatters' file. 
In practice, this has resulted in Newspack Campaigns' prompts not being displayed. 
This PR forces our unused CSS exclusion array regardless of the settings. After clearing unused CSS (`wp eval "\Perfmatters\CSS::clear_used_css();"`, this change should ensure this never happens again. 
1. On `release`
1. Set the `NEWSPACK_IGNORE_PERFMATTERS_DEFAULTS` env. variable, so Perfmatters settings can be changed
2. Go to Settings -> Perfmatters -> Assets and remove all lines but one from the CSS -> Excluded Stylesheets …

Hotfix (perfmatters): force stylesheet exclusion in unused CSS feature

---

includes/class-plugin-manager.php

Removes MC4WP from our managed plugins, per Tracy in Slack:
> The campaigns refactor removed support for targeting readers via the MC4WP plugin so we should no longer recommend that for pubs. And we need to communicate to those using it that we are no longer supporting.
2. Visit `/wp-admin/plugins.php`.
3. Note that "MC4WP: Mailchimp for WordPress" is no longer among the default plugins available.

Removes MC4WP from managed plugins

---

includes/reader-revenue/woocommerce/class-woocommerce-connection.php

Adds a method to migrate a subscription from Stripe to Woo using a specific Woo product by SKU.
2. In WP admin, go to Products and create a new subscription-type product. Set the SKU to some string, e.g. `TEST-PRODUCT-SKU`.
3. SSH into your test site and run `wp shell`.
4. Create some fake order data. You can use this to test:
```php
$order_data = [ 'status' => 'completed', 'subscription_status' => 'created', 'wc_subscription_status' => 'active', 'email' => 'test@email.com', 'name' => 'Test Customer Name', 'date' => 1698796940, 'amount' => 100, 'frequency' => 'year', 'currency' => 'USD', 'client_id' => '', 'user_id' => '' ];
```
5. Create a transaction using the SKU you created in step 2:
```php
\Newspack\WooCommerce_Connection::create_transaction( $order_data, …
```

feat(stripe-migration): support mapping of products by SKU

---

includes/reader-revenue/class-reader-revenue-emails.php
includes/reader-revenue/stripe/class-stripe-connection.php
includes/reader-revenue/woocommerce/class-woocommerce-connection.php

1200550061930446-as-1205661051657369
Implements support for displaying the customer's billing name in reader revenue's receipt email.
1. Check out this branch and make sure you have "Newspack" as your RR platform
2. Edit the Receipt email in "Newspack -> Reader Revenue -> Emails" and confirm you see the new `*BILLING_NAME*` placeholder option
3. Add the `*BILLING_NAME*` to the email body and save
4. Donate using the donate block and confirm the sent email includes the customer's billing name
5. Switch your RR platform to Stripe and donate again
6. Confirm the email body includes the customer name from Stripe

feat(emails): support billing name on receipt email

---

includes/reader-revenue/woocommerce/class-woocommerce-connection.php

**Note**: this is a hotfix since the issue is affecting client ActiveCampaign automations.
This PR fixes an issue discovered by a client earlier this week. On new orders the "Last Payment Date" field is not getting synced. This is because: 
1. That field uses `$order->get_date_paid()`
2. We were hooked into `woocommerce_checkout_order_processed`
3. [The payment happens immediately **after** that hook](https://github.com/woocommerce/woocommerce/blob/6b44a969d0855702bd685a2b988d9f2825a59878/plugins/woocommerce/includes/class-wc-checkout.php#L1272-L1284), so `$order->get_date_paid()` would always return `NULL` because the order hadn't been paid yet.
This PR updates the hook to one that fires immediately after the order has been paid, so the payment date will be available.
1. Set up a site …

Sync order to ESP *after* payment goes through

---

includes/reader-revenue/woocommerce/class-woocommerce-connection.php

Restores a method that was accidentally removed in #2663. This method is needed for migration scripts.
Confirm that the method is restored exactly as it was when it was [first added](https://github.com/Automattic/newspack-plugin/pull/2632/files#diff-b1dbb7bb086f4afe9581e4edecca68795028891e7d380656342dc169973ad5a5R170). You can test with WP shell:
```
> $customer = new WC_Customer( 42 ) // ID for a WC customer account
> Newspack\WooCommerce_Connection::get_contact_from_customer( $customer )
= [
"email" => "donor@test.co",
"name" => "Test Donor",
"metadata" => [
"NP_Account" => 42,
"NP_Registration Date" => "2023-11-03",
],
]
```

fix: restore method used by migration scripts

---

includes/reader-activation/class-reader-activation-emails.php

The default password reset flow with WooCommerce redirects the user to the `my-account` page. Because we replace the authentication form on that page with a flow that is restricted to reader accounts only, non-readers get stuck in a form they can't use after a password reset.
This PR redirects non-readers to the regular `wp-login.php` page after a password reset.
1. Check out this branch and go through password reset for an admin account
2. Reset the password and confirm you're redirected to `wp-login.php`
3. Do the same but with a reader account
4. Reset the password and confirm you're redirect to `my-account`

fix(password-reset): redirect non-readers to WP login

---

assets/reader-activation/auth.scss

Handle very long lists of newsletter lists. 
See 1200133283036252-as-1205829529414334
1. On `master`, go to Engagement -> Newsletters -> Subscription Lists and edit a list description to something super long. Can be your favourite book, for example. 
2. Visit the site, click on the "My Account" in top-right corner, then "I don't have an account"
3. Observe the lists are making the modal assume the window height, with the CTAs pushed below the fold
4. Switch to this branch, observe the newsletters lists list is scrollable

fix(auth-modal): handle very long newsletter lists list

---

includes/reader-revenue/woocommerce/class-woocommerce-connection.php

Note: created as an "alpha hotfix" because it's needed for the next round of releases but not immediately.
Fixes a method used by a migration script to fetch reader data to sync to the connected ESP. This method checks for subscriptions related to a given order using the [`wcs_get_subscriptions_for_order`](https://woo.com/document/subscriptions/develop/functions/order-cart-functions/#section-5) method, but this method by default only returns subscriptions if the order is the subscription's parent order, not if the order is a renewal order for the subscription.
This PR fixes the issue by passing an `[ 'order_type' => 'any' ]` arg, which will allow the method to return related subscriptions for any order regardless of order type.
1. As a reader, complete a new recurring donation. In WP …

fix: get subscriptions from any order type

---

includes/reader-revenue/woocommerce/class-woocommerce-cover-fees.php

Replaces the lengthy `2.9% + $0.3` with a flat percentage, e.g. `3%`:
1. Initiate a donate with the modal checkout
2. Observe the transaction fee in the "Cover transaction fees?" is expressed as percentage only
3. Try with different amounts, you can verify the calculation by checking the option (so the total amount is updated in the UI and computing the percentage of the initial amount)

feat(modal-checkout): display flat percentage fee when offering to cover stripe fees

---

assets/wizards/readerRevenue/views/stripe-setup/index.js
includes/configuration_managers/class-woocommerce-configuration-manager.php
includes/reader-revenue/woocommerce/class-woocommerce-cover-fees.php
includes/wizards/class-reader-revenue-wizard.php

Adds two new configuration options for the "Stripe fees" option introduced in https://github.com/Automattic/newspack-plugin/pull/2695:
- Make the checkbox checked by default (opt-out instead of opt-in): This is configurable by publisher because some sites want it to be opt-out, but others must follow regulations to make such options opt-in.
- Custom fee message. Also tweaks the default message to the slightly more reader-friendly:
> I’d like to cover the [fee percentage] transaction fee to ensure my full donation goes towards [site name]'s mission.
Also integrates the flat percentage fee display from #2746 for better readability in the default messaging.
Closes `1205451924709234/1205912365838338`.
2. Visit Newspack > Reader Revenue > Stripe Gateway (make sure …

feat: new options for Stripe fees

---

assets/memberships-gate/metering.js
includes/plugins/wc-memberships/class-memberships.php
includes/plugins/wc-memberships/class-metering.php

WC Memberships restricts comments when a post is restricted. Our custom content restriction strategy to handle metering is not handling comments, so you'll get a gated article with comments being rendered below the gate.
This PR ensures that content gated through the front-end metering strategy also removes the comments from the page.
It also changes how metering renders the gated content excerpt. Instead of duplicating the truncation logic in javascript, the backend sends the formatted excerpt from `\Newspack\Membershis::get_restricted_post_excerpt()`. This ensures that gating an article through the backend or the frontend always produces the same excerpt.
1. While on the master branch, make sure you have WC Memberships configured with a plan restricting posts
2. Edit your content gate …

fix(metering): restrict comments on gated content

---

includes/class-donations.php
includes/reader-revenue/woocommerce/class-woocommerce-connection.php

The current schema for syncing WC data to the ESP contact expects only donation products. There are 2 sync calls that push data from any order or subscription update, which causes the ESP contact data to be misleading.
This hotfix PR ensures the order is from a donation before syncing and is part of a 3-step approach in order to fully support multiple products' data sync through data events:
1. Hotfix to prevent the sync in which non-donation product orders are being pushed to the ESP from `WooCommerce_Connection::sync_reader_on_customer_login` and `WooCommerce_Connection::sync_reader_on_subscription_update`
2. Unify the syncing strategy to use the existing data events connectors and no longer the `WooCommerce_Connection::sync_reader_from_order` for better maintainability and to avoid …

fix: don't sync non-donation purchases to the ESP

---

assets/reader-activation/auth.js
includes/class-magic-link.php
includes/reader-activation/class-reader-activation.php
tests/unit-tests/magic-link.php

Implement a 60-second interval for rate-limiting the generation of magic links and OTPs.
87144f4c3899bab8644f007e5111018a1217430c changes the validation check so that it can return `invalid_hash` and `invalid_otp` early. The tests started to fail because it is now cleaning all tokens per test, meaning there are no tokens when testing OTP expiration. This change allows the expected `invalid_hash` to return.
1. Check out this branch and make sure you have RAS enabled
2. On a fresh session, click the "Sign In" button on the header
3. Enter an existing reader account's email
4. Click "Try a different email" and proceed to send to the same email
5. Confirm you get the following error: "You must wait before you can issue another authorization code."

feat(authentication): rate limit magic links and OTP generation

---

includes/data-events/class-data-events.php
includes/data-events/class-webhooks.php
includes/data-events/connectors/ga4/class-ga4.php

Removes the use of ActionScheduler for dispatching data events. It should use the fallback strategy in place for when AS is not available, which is to send an unblocking HTTP request.
The reason for this change is that the amount of data events we dispatch drastically increased, especially with Newspack Newsletters' tracking functionality. This can be too much for AS' queue to handle.
This change shouldn't impact the processing or reliability of data events, since this is already the strategy in place for sites without AS available (without WooCommerce installed).
Update: 30ff7642fb84d141b43efb53b9fd6147eee28fdd adds a check for a WC function on the GA4 connector so it doesn't fatal if WC is not installed.
1. Checkout this branch, make sure you have GA4 connected and `define( …

fix(data-events): no longer use ActionScheduler for dispatches

---

assets/wizards/popups/views/segments/segments-list.js

Adds "DUPLICATE" badge if a segment is duplicated. 
See 1200133283036252-as-1205733927102145
_Follow instructions in https://github.com/Automattic/newspack-popups/pull/1244_

feat(campaigns): mark duplicate segments

---

includes/class-donations.php

Coupons should never be rendered when donating. This change ensures coupons are disabled for donation carts.
1. Make sure you have coupons enabled
2. Start a donation checkout through the Donate block and confirm the coupon form doesn't render
3. Checkout a different product and confirm the coupon form renders

feat(donations): disable coupons for donation checkout

---

includes/class-recaptcha.php

When going through checkout and the submission fails, the next attempt might send the same token, which is not allowed by reCAPTCHA.
This change ensures the captcha token is regenerated on checkout updates and errors to prevent duplicate tokens while placing the order.
1. While on the master branch, add an item to cart and visit the regular WC checkout page (/checkout/)
2. Place order without entering the required billing fields and confirm you get a regular WC error
3. Place the order again and confirm you get a `reCaptcha error: timeout-or-duplicate` along with the other validation errors
4. Check out this branch, repeat steps 2 and 3 and confirm you only get the validation errors
5. Without refreshing, fill the required fields and confirm you are able to place the order

fix(recaptcha): refresh token on checkout error

---

includes/reader-revenue/woocommerce/class-woocommerce-connection.php

Don't try to sync contact fields if we don't have any reader data for those fields to sync. Some publishers who have imported reader accounts to Woo have preexisting reader data in their ESP that is getting overwritten if the corresponding Woo reader has less data than the ESP.
1. In Newspack > Reader Revenue > Donations, disable all billing fields except for email.
2. On `master`, make a new donation as a new reader.
3. Find the reader's corresponding contact in your ESP (I tested with ActiveCampaign). Manually add some values to certain fields such as First/Last Name, NP_Current Subscription End Date, etc. and save in the ESP
4. In a new session, log in as the user created in step 2 to trigger a reader data sync. Observe in the ESP that the preexisting values in the fields you manually …

fix: don’t sync empty contact fields to ESP

---

includes/data-events/connectors/class-mailchimp.php
includes/oauth/class-mailchimp-api.php
includes/plugins/class-newspack-newsletters.php
includes/reader-activation/class-reader-activation.php
includes/reader-revenue/woocommerce/class-woocommerce-connection.php

Adds `Registration Method` and `Registration Page` metadata to `reader_registered` data events fired by the auth form. Currently new registrations via this method aren't capturing this info.
1. On `master`, visit any page in a new session and click the "Sign In" button in the header, then "I don't have an account". Register a new account via this form.
2. In the connected ESP, observe that the synced contact doesn't have any `NP_Registration Page` or `NP_Registration Method` values.
3. Check out this branch and https://github.com/Automattic/newspack-newsletters/pull/1370, repeat with a different email address, and confirm that the synced contact has a `NP_Registration Page` with the URL of the page you were viewing when you clicked "Sign In", and a `NP_Registration Method` of `auth-form`. …

fix: more fixes for Mailchimp RAS data sync

---

includes/reader-revenue/woocommerce/class-woocommerce-connection.php

#2305 added a feature to force the "Subscription Switching" option for Name Your Price products to on unless a `NEWSPACK_PREVENT_FORCE_ALLOW_SWITCHING` constant is added to wp-config.php. However, this didn't quite go far enough. The filter used to force the value is only fired if the option exists, so if a publisher has never saved that page before, the option wouldn't exist and the feature wouldn't take effect. Also there are additional "Subscription Switching" options that remain off by default. 
This PR updates the feature so that all Subscription Switching feature are turned on unless the constant is present, and also adds filters for `default_option_{option_name}` so that the features are turned on even if the option hasn't ever been changed.
1. While on `master`, if your wp-config …

feat: force allow subscription switching

---

includes/class-donations.php
includes/reader-revenue/my-account/class-woocommerce-my-account.php

Adds support for seeing and editing billing and shipping addresses in My Account, if the user account has any address info.
1. Enable address fields in Reader Revenue > Donations.
2. As a new reader, make a purchase and input address info.
3. Go to My Account and confirm that there's an "Addresses" menu item and that clicking on it allows you to see/edit the billing address you entered during checkout.
4. Confirm you can update the billing address and that it's pre-populated when you make new purchases while logged in.

feat(my-account): support edit address

---

includes/data-events/connectors/class-mailchimp.php

This fetch may fail if the audience does not exist in Mailchimp (Resource not found). This change prevents this error from throwing a fatal error and breaking the donation flow.
1. Make sure you have RAS enabled and Newspack Newsletters is connected Mailchimp
2. Confirm you have `define( 'NEWSPACK_LOG_LEVEL', 2 );`
3. While on the `release` branch confirm the error by adding `$audience_id = 'foo';` to line 53 of `includes/data-events/connectors/class-mailchimp.php`
4. Go through the donation flow and confirm the donation order goes through but you get an unhandled error in the UI
5. Check out this branch, apply the same `$audience_id = 'foo';` line, and got through the donation flow again
6. Confirm the donation succeeds and the logs shows: …

fix(mailchimp): prevent merge fields fetch throwing fatal error

---

includes/plugins/class-newspack-newsletters.php
tests/unit-tests/reader-activation.php

#2780 added a filter to normalize RAS contact data synced to the connected ESP. However, this filter didn't account for some meta keys being dynamic (namely all the UTM ones). This PR fixes that.
Also fixes the order in which we split out the full name into First/Last Names for Mailchimp. These meta fields were getting stripped because they weren't passing the validation check. Moving this to after validation ensures the names aren't dropped.
1. On `master` or `release` with `NEWSPACK_LOG_LEVEL` at `2` or more: As a new reader, visit a post or page containing a Donate or Checkout Button block. Add UTM params to the URL, e.g. `?utm_source=marketinglist&utm_medium=email&utm_campaign=2023-Newspack-Campaign` and complete a transaction.
2. Confirm that the order created in Woo has the UTM …

fix(ras): handle UTM metadata field keys with arbitrary suffixes

---

includes/reader-activation/class-reader-activation.php

A smallish tweak to the preauth flow in a specific user scenario.
Right now, it's possible to sign up for new newsletter lists via Newsletter Subscription Form blocks using an email address that's already been registered in the past, but while not logged into the account for that email address. 
We've gone back and forth on this in the past, but we've decided on a product strategy level that we should continue to allow this, for the time being.
However, when you do this, we currently send an OTP email to the email address to log into the account. This email feels unexpected because it's not part of the intent of the newsletter signup flow, which doesn't require an account login. We should not send the OTP email in this scenario.
Closes `1205865273809972/1205933702651178`.
1. On a site …

feat: don’t send OTP via preauth flow when signing up for newsletter

---

includes/class-donations.php
includes/wizards/class-wizard.php

Avoid Warnings to be thrown when using php 8.1
1. Make sure you are running php 8.1
2. On `master` visit the admin dashboard
3. Confirm you see the following warnings:
```
[01-Dec-2023 14:00:37 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/wp-includes/functions.php on line 7241
[01-Dec-2023 14:00:37 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/wp-includes/functions.php on line 2187
```
4. Visit one of the hidden pages. Example: `/wp-admin/admin.php?page=newspack-components-demo`
5. Confirm you see the following warning:
```
PHP Deprecated:  strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in …
```

chore: avoid warnings on php 8.1

---

includes/reader-revenue/class-reader-revenue-emails.php
includes/reader-revenue/woocommerce/class-woocommerce-connection.php

Add support for the following new template variables to the RR receipt email:
- First name
- Last name
- Product name
- Billing frequency
This change should only impact the "Newspack" (WC) platform. Customers using Stripe should not support the new variables.
Along with the new values, the `*AMOUNT*` has changed so it uses a Woo function to determine the formatted value.
This PR also corrects the textdomain for the modified files so it uses `newspack-plugin` instead of `newspack`.
1. Checkout this branch and make sure you have Newspack as your RR platform
2. Edit the Receipt email (Newspack -> Reader Revenue -> Emails)
3. Confirm you see the new variables as above
4. Edit your content to include these variables (see example above)
5. Go through the donation flow for each type (one-time, …

feat(donation): additional receipt email template variables

---

includes/plugins/wc-memberships/class-memberships.php

Allow editors to see content locked behind a membership
1. Create a user with the `editor` role and make sure they don't have any memberships
2. Set up a content gate
3. Visit the site anonymously and confirm the content is restricted
4. on `master`, log in as the editor and confirm the content is still restricted
5. Checkout this branch and confirm the content is allowed for the Editor, but still restricted for other logged in users in other roles (except admins)
Dev notes:
I just want to clarify something that may show up during review.
As you'll see, I changed the `if` statement with a `select`, so I could catch many other capabilities all at once.
The original code had a `break;` at the end of the `if`, meaning that the `foreach` was not continuing in case `$caps[0]` was the cap we …

feat: give editors permission for restricted content

---

assets/wizards/engagement/views/newsletters/index.js

Fixes a regression created by https://github.com/Automattic/newspack-newsletters/pull/1255 that broke changes introduced by https://github.com/Automattic/newspack-plugin/pull/2424. In the Newsletters PR, the group is no longer returned with `type=mailchimp-group`.
1. Make sure you have Mailchimp set up and there are some groups
2. Visit Newspack Engagement
3. See that the groups are indented under their Audiences

fix: newsletters Lists indentation

---

assets/other-scripts/wc-cover-fees/index.js
includes/reader-revenue/woocommerce/class-woocommerce-cover-fees.php

Refactors the "cover fee" strategy to use  `WC()->cart->add_fee()` instead of modifying the order total directly.
This PR also changes the UI to show the fee through the order review table and and no longer modify the top summary value. This consolidates how we handle additional values added to the order (coupons, fees, and taxes excluded from the total).
1. Check out this branch and https://github.com/Automattic/newspack-blocks/pull/1633
2. Through the Donate block, start a one-time donation flow and confirm you can toggle the "I’d like to cover the {percentage}% transaction fee to ensure my full donation goes towards {site name}'s mission." checkbox
3. Confirm toggling the checkbox updates the fee as shown in the image above
4. Confirm you can place the order
5. Visit the order details …

fix: use Woo's cart fee for covering transaction fees

---

includes/reader-revenue/woocommerce/class-woocommerce-connection.php

Forces the WooCommerce Subscriptions option to "Retry Failed Payments" to ON unless the `NEWSPACK_PREVENT_WC_ALLOW_FAILED_PAYMENT_RETRIES_OVERRIDE` constant is enabled in wp-config.php.
2. Similarly to #2784, go to **WP admin > WooCommerce > Settings > Subscriptions** and test that "Retry Failed Payments" is enabled by default and can't be turned off.
3. Optionally, find an existing subscription ID on your site and update or delete the `_stripe_source_id` meta value to force the next renewal payment to fail (`wp post meta update <subscription_id> _stripe_source_id fake_token`) then trigger a manual renewal for that subscription in WP admin and confirm that it enters renewal retry mode (note the "**Renewal Payment Retry:** In 12 hours" in the Schedule panel):
4. …

feat: force option to enble retries of failed payments

---

includes/reader-revenue/woocommerce/class-woocommerce-cover-fees.php

We've seen some orders where the order note was added, but the total not updated. While it's not clear what's causing the issue, it's a good practice to call `save()` on the order after updating it. 
Make a donation and opt in to cover the fees, observe that it goes through as expected

fix(cover-fees): save order after setting total

---

includes/plugins/wc-memberships/class-memberships.php

To be consistent with https://github.com/Automattic/newspack-popups/pull/1250, this PR adds support for revisions to the `np_memberships_gate` custom post type (CPT).
1. Make a change to a content gate. Observe that there is no "Revisions" box in the post settings.
3. Make a change to a content gate. Observe that there is a "Revisions" box in the post settings.
4. Confirm that the previous version of the content gate is visible in (and can be restored from) the revisions timeline.

feat: add support for revisions to content gate CPT

---

includes/reader-revenue/my-account/class-woocommerce-my-account.php
includes/reader-revenue/woocommerce/class-woocommerce-cover-fees.php

Fixes some issues resulting from a bad hotfix merge.
1. Follow testing instructions in #2820 and make sure they work
2. Follow testing instructions in #2733 and make sure they work
3. Re: [this comment](https://github.com/Automattic/newspack-plugin/pull/2835#pullrequestreview-1805563860), enable some but not all billing address fields in **Newspack > Reader Revenue > Donations**. 
4. Complete a purchase of a shippable product, then log into/verify My Account, then visit Addresses.
5. Confirm that when editing the **billing** address, only the fields enabled in Reader Revenue in step 3 are required, and that you can save with empty "optional" fields (but not with empty "required" fields).
6. Confirm that when editing the **shipping** address, all default address fields are still required.

fix: alpha fixes

---

includes/class-plugin-manager.php

Add a method to retrieve all approved plugins. Test by running `\Newspack\Plugin_Manager::get_approved_plugins_slugs();` in a `wp shell` session.

feat: approved plugins list retrieval method

---

assets/wizards/connections/views/main/index.js

Fixes an issue with false-positive error display in the Connections wizard. 
See 1200550061930446-as-1206088853297652
1. Mock the Google OAuth status response by returning early from `Google_OAuth::api_google_auth_status` – start with a success message (`return \rest_ensure_response($response)`
2. Load the Connections wizard, observe a `Google: undefined` error notice at the top of the view
4. Reload the wizard, observe no error
5. Mock an error response (`return new \WP_Error(…)`), observe it correctly displayed in the wizard
---
- https://app.asana.com/0/0/1206088853297652

fix(connections-wizard): error display

---

includes/data-events/class-memberships.php
includes/data-events/listeners.php
includes/reader-revenue/woocommerce/class-woocommerce-connection.php

When a subscription is switched to a different amount, WC creates a "switch order", which is an order of 0 value. This order should not be synchronised to third parties, as it's not a real order.  
1. Allow subscription switching in WC Settings -> Subscriptions
2. Ensure logging is enabled (`NEWSPACK_LOG_LEVEL` set to `2`)
3. Run through the process of starting a donation subscription and updating its amount*
5. Observe in the logs that events are being dispatched, most importantly and ESP contact update
6. Switch to this branch, repeat, observe that the events are not being dispatched**
7. Make another recurring donation, observe events being dispatched as before
\* It's a confusing process – go to /my-account page, Subscriptions, then click "Change price", update the …

fix: prevent switch order synchronisation

---

includes/reader-revenue/woocommerce/class-woocommerce-cli.php
includes/reader-revenue/woocommerce/class-woocommerce-connection.php
includes/reader-revenue/woocommerce/class-woocommerce-cover-fees.php

Since https://github.com/Automattic/newspack-plugin/pull/2820 we use an actual woocommerce Fee to add the Stripe fee to the order. Before that, we would manually add the fee to the order total if a metadata was present.
We didn't take into account the need to update existing subscriptions so that renewal orders will also get the fee added. (we assumed they would copy from the Sub's parent order, but they don't).
This PR adds a CLI command to migrate the subscriptions that had fees added the old way to the new way.
It's a CLI command because it should affect few subscriptions in a few sites.
1. Checkout the plugin in the version prior to #2820 `git checkout v2.12.0`
2. Make sure the option for the donor to cover fees is enabled
3. Make a recurring donation covering Stripe fees
4. Checkout …

feat: add cli command to fix stripe covered fees

---

includes/data-events/README.md
includes/data-events/class-data-events.php
includes/data-events/class-woo-user-registration.php
includes/data-events/connectors/class-activecampaign.php
includes/data-events/connectors/class-mailchimp.php
includes/data-events/listeners.php
includes/plugins/class-newspack-newsletters.php
includes/reader-activation/class-reader-data.php
includes/reader-revenue/woocommerce/class-woocommerce-connection.php

#2804 fixed syncing of contact metadata for UTM data via purchases, but did not fix for registration via non-transactions. This PR fixes syncing of UTM fields for all registration and purchase-related events, and also does a bit of refactoring to consolidate data syncs in general into the ActiveCampaign and Mailchimp Data Events connectors. Currently, the data syncs are happening in a few different places using different triggers (a mix of Woo hooks, regular WP hooks, Newspack Newsletter hooks, and data events throughout different files). Consolidating them in data events should make it easier to see and control what triggers an ESP sync going forward. As part of this we've added some new data event listeners and tweaked some existing ones to make them a bit more standardized.
In new …

fix(ras): consolidate RAS <> ESP data syncs in data event connectors

---

includes/optional-modules/class-media-partners.php
includes/optional-modules/class-rss.php

The standalone plugins have been removed from our live environment, so this code can be removed.
1. Ensure both optional modules are active by calling 
1. `\Newspack\Settings::activate_optional_module( 'media-partners' )`
2. `\Newspack\Settings::activate_optional_module( 'rss' )`
3. Load the admin panel, observe a "Media Partners" menu sub-item in "Posts" menu item 
4. Observe a "RSS Feeds"

feat(optional-modules): remove switching from standalone plugin versions

---

includes/reader-revenue/my-account/class-woocommerce-my-account.php
includes/reader-revenue/my-account/index.js

Adds a browser-based confirmation prompt when cancelling a subscription in My Account. Adds a tiny bit of friction to prevent accidental cancellations.
Closes `1206098184615535/1205860975049753`.
See also https://github.com/Automattic/newspack-theme/pull/2221
2. As a reader, purchase a subscription.
3. Visit My Account and verify if needed.
4. Visit Subscriptions and click "View" to view details for the subscription.
5. Click "Cancel" (or highlight with the keyboard and hit "Enter") and confirm there's a new prompt asking for confirmation:
6. Click "Cancel" (in the prompt) and confirm that the cancellation does not occur.
7. Click the "Cancel" button again and this time click "OK". Confirm that the subscription is cancelled as requested.

feat(my-account): require confirmation before cancelling subscription

---

includes/class-newspack-image-credits.php

Automatically populates the Newspack custom "Credit" attachment meta field with the credit present in the image metadata (EXIF or IPTC)
1. Upload a new image that has one of the following exif/iptc fields filled: (check the asana task for a sample image)
IPTC Credit field (2#110)
IPTC Creator field (2#080)
EXIF Artist field
EXIF Author field
2. Check that our "Credit" field was automatically filled
---
- https://app.asana.com/0/0/1205675205413421

feat: automatically fill the credit meta for images

---

includes/reader-revenue/woocommerce/class-woocommerce-connection.php

Fixes a fatal that can happen if `\Newspack\WooCommerce_Connection::sync_reader_from_order()` is called without a valid `$order` arg.
1. Run `wp shell` and then `\Newspack\WooCommerce_Connection::sync_reader_from_order( false )`. Observe a fatal error
2. Check out this branch, repeat, and observe no error.

fix(ras): handle invalid order sync request

---

includes/reader-activation/class-reader-activation.php
includes/reader-revenue/my-account/class-woocommerce-my-account.php
includes/reader-revenue/templates/myaccount-edit-account.php
includes/reader-revenue/woocommerce/class-woocommerce-connection.php

Tweaks and standardizes the logic that generates default user display names (updatable by the user), nicenames (the slug used for author archive pages, which shouldn't affect reader accounts unless they're upgraded to an author/editor/admin role), and login strings (never updatable) when registering a new RAS reader account. This only affects newly registered accounts going forward, not preexisting accounts unless they make a purchase and provide a billing name to reset the display name.
Also adds support for a new environment constant, mainly for dev convenience, but could also be used by publishers if the behavior is desired. If `NEWSPACK_ALLOW_MY_ACCOUNT_ACCESS_WITHOUT_VERIFICATION` is defined and true, My Account will allow logged-in users to access and update account settings without …

feat(ras): better reader display/nice names

---

includes/reader-activation/class-reader-activation.php

Fixes a fatal error I discovered when testing another feature. I don't think this warrants a hotfix as it's an edge case that shouldn't occur for live sites unless they're switching from a supported ESP to a "other/manual" in Newsletters.
1. Make sure RAS is set up and enabled.
2. In **Newspack > Engagement > Newsletters**, set the active ESP to "Manual/Other" and save.
3. On `master`, visit a page on the front-end that will render the "Sign In" button and auth modal, and observe a fatal error that affects the front-end render:
```
PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /newspack-repos/newspack-plugin/includes/reader-activation/class-reader-activation.php:338
Stack trace:
#0 /newspack-repos/newspack-plugin/includes/reader-activation/class-reader-ac …
```

fix(auth-modal): fatal error in auth modal with "other" ESP

---

includes/class-donations.php

Adds a `Donations::get_recurrence_of_order` method. This will be used by another plugin, should be available for testing quickly – hence the hotfix.  
1. Run `wp eval "echo \Newspack\Donations::get_recurrence_of_order(\wc_get_order(<order-id>));"` (replace `<order-id>` with a real order ID
2. For an order tied to a donation, observe the recurrence (`'once'`, `'month'`, or `'year'`) is printed

feat: add get_recurrence_of_order method

---

assets/wizards/connections/views/main/fivetran.js
includes/oauth/class-fivetran-connection.php

In preparation for deprecating support for FiveTran connectors other than Stripe, this removes them from the Newspack > Connections wizard UI.
Closes `1206197591054328/1206413031827389`
1. If on a dev site, you may need to add an environment variable to be able to see the FiveTran connector options in the Connections wizard. Let me know if you don't know how to do this or what to set it to.
2. Visit **Newspack > Connections** and confirm that only Stripe appears under the FiveTran section:
---
- https://app.asana.com/0/0/1206413031827389

feat(fivetran): remove FiveTran connectors other than Stripe

---

includes/class-plugin-manager.php

Brings the plugin description in alignment with https://github.com/Automattic/newspack-popups/pull/1182.
Updates the plugin description for `newspack-popups`, bringing it in alignment with https://github.com/Automattic/newspack-popups/pull/1182.
1. Visit `/wp-admin/plugins.php`
2. Note the description for Newspack Campaigns is "AMP-compatible overlay and inline Campaigns."
4. Visit `/wp-admin/plugins.php`
5. Note the description for Newspack Campaigns is "Build persuasive call-to-action prompts from scratch and display them as overlays, inline with the story, or above the site header."

fix: update Campaigns plugin description

---

includes/class-recaptcha.php
includes/reader-activation/class-reader-activation.php
includes/reader-revenue/my-account/class-woocommerce-my-account.php
includes/reader-revenue/templates/myaccount-delete-account.php
includes/reader-revenue/woocommerce/class-woocommerce-connection.php

Adds an additional check when triggering a WC notice. 
When testing, an error with the following stack trace was encountered:
```
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-notice-functions.php:80
Stack trace:
#0 /srv/htdocs/wp-content/plugins/newspack-plugin/includes/reader-activation/class-reader-activation.php(728): wc_add_notice('Thank you for v...', 'success')
#1 /srv/htdocs/wp-content/plugins/newspack-plugin/includes/reader-activation/class-reader-activation.php(1684): Newspack\Reader_Activation::set_reader_verified(3)
```
The `get()` mentioned is called on `WC()->session`. In order to prevent this issue, all calls to `wc_add_notice` are now wrapped in a `WooCommerce_Connection::add_wc_notice` …

fix: ensure WC session is present if triggering WC notice

---

includes/plugins/class-organic-profile-block.php
includes/reader-activation/class-reader-activation.php

Closes # .
**For the Organic Profile issue:**
Installing this version of the plugin on a JN site caused a fatal error:
```
PHP Fatal error: Uncaught Error: Call to undefined function Newspack\is_plugin_active() in /srv/htdocs/wp-content/plugins/newspack-plugin/includes/plugins/class-organic-profile-block.php:30
```
To fix, we replaced the `is_plugin_active` check for one that looks for a function from the plugin. To test:
1. Set up a JN site with this PR; confirm you don't get any fatal errors/errors on the front-end. 
2. Install and activate copy of the [Profile Block](https://wordpress.org/plugins/organic-profile-block/).
3. Add a profile to a post or page and publish.
4. Deactivate the plugin.
5. Confirm that your profile block is still styled (for example, the fonts match how they …

fix: fixes for prod release feb 5

---

includes/data-events/class-data-events.php

A Data Event logger throws a fatal if a data event is dispatched without any data.
1. In WP admin > Newsletters > Tracking, turn on pixel tracking.
2. On `release`, visit a front-end page of your site with a bunch of UTM params. e.g.
```
https://site-domain/?np_newsletters_click=1&id=12345&url=https%3A%2F%2Fsite-domain%2F2023%2F08%2F22%2Ftortor-posuere-vitae-eget-finibus-praesent-sem-interdum-phasellus%2F%3Futm_medium%3Demail&em=test@email.com&utm_source=Newspack+Mailing+List+(including+Members)&utm_campaign=00000000-EMAIL_CAMPAIGN_2024_01_26_07_08&utm_medium=email&utm_term=0_-00000000-[LIST_EMAIL_ID]
```
where the `&url=` param is a URL with UTM params attached and run through `encodeURIComponent()`.
4. Observe a fatal:
```
PHP Fatal error:  Uncaught ArgumentCountError: 4 arguments are …
```

fix: prevent fatal when redirecting for pixel tracking
