- assets/src/components/inputText/index.js
- assets/src/components/inputText/style.scss
- assets/src/wizards/subscriptions/index.js
Closes #20 .
1. the Input component is demoed in the Subscription wizzard page, in its 3 states: containing a pre-entered value, containing no (empty) value, and disabled
> Muriel-styled Text/Number Input component.

- babel.config.js
- package-lock.json
- package.json
I've added some rules to package.json and a babel file to get the jest tests working again. Everything should build and test the JS properly now. The babel file is based on the [calypso-build](https://github.com/Automattic/wp-calypso/blob/master/packages/calypso-build/babel/default.js) one.
1. `npm ci` and `npm run test`
2. Tests should run and pass.
> Fix jest tests

- package.json
Fix to make the NPM clean script delete the `dist ` directory.
1. Run  `npm run build:webpack`
2. Observe the existence of `assets/dist`
3. Run `npm run clean`
4. Observe that `assets/dist` is deleted.
> Bug fix: corrected the path in the clean script.

- assets/src/components/imageUpload/imageUpload.test.js
- assets/src/components/imageUpload/image_upload_24px.svg
- assets/src/components/imageUpload/index.js
- assets/src/components/imageUpload/style.scss
- assets/src/wizards/subscriptions/index.js
- includes/wizards/class-subscriptions-wizard.php
- package-lock.json
- package.json
Closes #23 .
This PR introduces a media modal component. The component allows uploading images or selecting existing images using the media modal, and can be pre-populated with an image. I've also added a couple tests for it.
No good pre-existing component exists for us to use, so this is a React wrapper over the standard WP media modal functionality. This should work well for our use.
1. `npm ci` and `npm run build:webpack`
2. On the Subscriptions page you should see a card with prompt to "Add an image".
3. Test adding and removing images.
- i18n. Should we do it right from the get-go? How should we do it? [Similar to how wc-admin does it](https://github.com/woocommerce/woocommerce-admin/blob/master/package.json#L34)?
- What should it look like once an image has been uploaded? We need to …
> Image upload/media modal component

- package-lock.json
- package.json
Bumps `@automattic/calypso-build` to v2. 
1. Execute `npm run clean && npm ci && npm run build:webpack`
2. Observe no errors in the build process.
3. Observe `/wp-admin/admin.php?page=newspack-subscriptions-wizard` loads normally on a test site with various form elements.
4. Execute `npm test`. The `ImageUpload` test will fail based on a className issue which will be resolved in a future PR, but all three tests should run successfully and 2/3 should pass.
> Bump calypso-build To v2

- assets/src/components/imageUpload/imageUpload.test.js
Fixes the Image Uploader test. 
1. `npm test`
2. Verify that all three tests pass.
> Fix ImageUpload Tests

- assets/src/components/progressBar/index.js
- assets/src/components/progressBar/progressBar.test.js
- assets/src/components/progressBar/style.scss
- assets/src/wizards/subscriptions/index.js
Closes #35  .
Adds a Muriel progress bar component. I've followed the Muriel style for this instead of the rounded style in the screenshot in #32.
1. `npm ci` `npm run build:webpack` `npm run test`
2. Go to Subscriptions page and observe the varieties of progress bar available:
> Progress Bar component

- assets/src/components/selectControl/arrow_down.svg
- assets/src/components/selectControl/index.js
- assets/src/components/selectControl/style.scss
- assets/src/wizards/subscriptions/index.js
Closes #21  .
The Select components in different states added to the Subsciptions Wizzard page.
> Add Muriel-styled Select dropdown component

- .editorconfig
- .prettierrc
- assets/src/components/button/style.scss
- assets/src/components/checklist/index.js
- assets/src/components/checklist/style.scss
- assets/src/components/task/index.js
- assets/src/components/task/style.scss
- assets/src/wizards/subscriptions/index.js
- assets/src/wizards/subscriptions/style.scss
Introduces a checklist component, based somewhat on https://github.com/Automattic/wp-calypso/tree/master/client/components/checklist. The component displays a list of tasks, each with a `title`, `description`, `buttonText`, and `completedTitle` which is displayed when the task has been committed. Each `Task` has `onClick` and `onSkip` events which fire when the primary or "Skip" buttons are clicked. The `Checklist` takes a `currentTask` integer as a prop which determines how far along in the list the user has gotten. In addition to visual differences between upcoming/active/complete `Task` there is a `ProgressBar` element that visualizes the user's progress. 
This is the mockup the Component was built to match:
Some questions for discussion:
1) In the example implementation, the `onClick` …
> Checklist Component

- assets/src/components/checkboxControl/style.scss
- assets/src/components/infoButton/index.js
Closes #33.
2. Navigate to `/wp-admin/admin.php?page=newspack-subscriptions-wizard`
3. Observe checkboxes
> Checkbox Visual Fixes

- includes/util.php
This PR adds a function that activates the Newspack theme, installing it first if needed. Currently it will install the master branch of the theme repo, but it can be easily updated to install the latest GitHub release or .org release in the future.
1. Switch to a theme other than the Newspack theme. Delete the `newspack-theme` directory from your `themes` directory.
2. Add the following code snippet somewhere:
```
add_action( 'admin_init', function(){
// Make sure there is only one installation/activation going on at once.
// Shouldn't be an issue when actually using in wizards, as the install won't be hooked to 'admin_init'.
$installing = get_option( 'newspack_theme_attempting_install', false );
if ( ! $installing ) {
update_option( 'newspack_theme_attempting_install', true ); …
```
> Function for installing + activating Newspack theme

- assets/components/src/card/style.scss
- assets/components/src/checklist/index.js
- assets/components/src/formatted-header/style.scss
- assets/components/src/grid/index.js
- assets/components/src/grid/style.scss
- assets/components/src/index.js
- assets/components/src/with-wizard-screen/index.js
- assets/shared/scss/_muriel-component.scss
- assets/wizards/checklist/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/componentsDemo/style.scss
- assets/wizards/performance/views/intro/index.js
Introduces an approach to address #171 using CSS grid to size and position components to the Muriel grid.
Before:
After: 
2. Navigate to `Newspack -> Components demo`
3. Verify that the components align to the grid at all viewport sizes
Note that these changes attempt to scope this to the `Components demo` page only. Thus having to add the `muriel-grid-item` classname to each card component in the components demo.
> Use CSS grid to implement the Muriel grid

- assets/components/src/tabbed-navigation/style.scss
As described in https://github.com/Automattic/newspack-plugin/issues/201, according to Material Design guidelines tabbed navigation should expand to fill the full width available. This PR implements this visual change.
Closes #201.
1. As described in https://github.com/Automattic/newspack-plugin/pull/194, the best way to test this is to add `tabbedNavigation` props to a `wizardScreen` in one of the Wizards.
2. To verify, try code snippets that add 2, 3, and 4 tabs:
```
tabbedNavigation={ [
{
label: __( 'Step 1' ),
path: '/',
exact: true,
},
{
label: __( 'Step 2' ),
path: '/stripe',
},
] }
```
```
tabbedNavigation={ [
{
label: __( 'Step 1' ),
path: '/',
exact: true,
},
{
label: __( 'Step 2' ),
path: '/stripe',
},
{
label: __( 'Step 3' ),
path: '/stripe',
},
] }
```
```
tabbedNavigation={ [ …
```
> Tabbed Navigation: Fill Available Area

- assets/wizards/membershipsPage/views/manageMembershipsPage.js
- assets/wizards/readerRevenue/components/index.js
- assets/wizards/readerRevenue/components/money-input/index.js
- assets/wizards/readerRevenue/components/money-input/style.scss
- assets/wizards/readerRevenue/index.js
- assets/wizards/readerRevenue/views/configure-landing-page/index.js
- assets/wizards/readerRevenue/views/configure-landing-page/style.scss
- assets/wizards/readerRevenue/views/donation/index.js
- assets/wizards/readerRevenue/views/donation/style.scss
- assets/wizards/readerRevenue/views/index.js
- assets/wizards/readerRevenue/views/location-setup/index.js
- assets/wizards/readerRevenue/views/payment-setup/index.js
- assets/wizards/readerRevenue/views/revenue-main/index.js
- assets/wizards/readerRevenue/views/stripe-setup/index.js
- assets/wizards/readerRevenue/views/stripe-setup/style.scss
- includes/class-checklists.php
- includes/class-donations.php
- includes/class-newspack.php
- includes/class-plugin-manager.php
- includes/class-wizards.php
- includes/configuration_managers/class-woocommerce-configuration-manager.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-donations-wizard.php
- includes/wizards/class-reader-revenue-wizard.php
- tests/unit-tests/api-wizards-controller.php
Work In Progress to pull together Reader Revenue Onboarding Wizard, Donations Wizard, and soon [Membership Landing Page Wizard](https://github.com/Automattic/newspack-plugin/pull/173) into a single unified Wizard.
> WIP: Unified Revenue Wizard

- includes/wizards/class-advertising-wizard.php
This PR connects the dots between Newspack Plugin, Newspack Ads, and Newspack Theme to make the global ad functionality work. 
There will be a little styling needed in the theme after this PR is merged to make things centered and look nice. The search results/archive global ads need some further scoping to see what those settings are exactly supposed to do, so they'll be addressed in a follow-up PR in the future.
1. Set up an ad unit in Newspack Ads.
2. Test setting the unit in above header/below header/above footer and previewing on the frontend. Currently it should look something like this:
Below header:
Above header:
Above footer:
Do we want the ability to set global ads in the top and bottom of the sidebar? Those seem like common ad placements on sites and aren't currently supported …
> Hook up global ad injection for Google Ads

- assets/wizards/readerRevenue/views/stripe-setup/index.js
Include ExternalLink to WC Gateways
Closes #223.
> Include ExternalLink to WC Gateways

- includes/class-plugin-manager.php
This PR adds 'WP User Avatar' as a recommended plugin; it will allow sites to upload specific images for each author (instead of using Gravatar), as well as set their  own custom fallback image.
This covers requests from specific publications, and also replaces functionality baked into the Largo theme.
This plugin has previously been reviewed by VIP.
1. Apply PR.
2. Go to Plugins screen, install and activate WP User Avatar from the Newspack managed plugins section.
3. Go to Settings > Users, and edit an individual user. You should see an option to add an avatar for them, below the 'change password' field:
4. Pick a new image for them -- either from your Media Library or by uploading a new one -- and click 'Update User' at the bottom of the page. 
5. Navigate to a post written by that …
> Add WP User Avatar as recommended plugin

- assets/components/src/action-card/style.scss
- assets/components/src/button/style.scss
- assets/shared/scss/_muriel-component.scss
* Simplify Lighter and Darker Primary Colors by using SASS's `lighten`/`darken`
* Add a disable style to `is-primary`
* New background color on `hover` for `is-primary`
* Make sure `is-tertiary` has the proper color
* Make sure the Action Card `is-link` has the proper color
1. Go through the different screens of the plugins.
2. Use the components demo
3. Do the buttons look ok?
> Update the color of the buttons

- includes/class-plugin-manager.php
We need a solution for inserting newsletter signup forms, ads, donation CTAs etc. into the content on all posts. INN's Super Cool Ad Inserter is already used by a few of our charter customers for this, and it seems like a solid and powerful solution to recommend as the standard.
It lets site owners insert any widget at customizable periodic intervals into the content. To make it work with Newspack Ads we just need to make the ads block available as a widget (which is something we probably want to do anyways, since sidebar ads are super common). When the newsletter signup widgets are AMP-compatible, they should just work nicely with this.
The plugin is fully AMP-compatible (all the insertion happens server-side).
The one downside to this plugin is that it's not super intuitive to set up. …
> Add Super Cool Ad Inserter to managed plugins

- assets/components/src/button/index.js
- assets/components/src/button/style.scss
- assets/components/src/handoff/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/componentsDemo/style.scss
* Reworked/Simplified the Button component to behave in a similar way as Core, with the Newspack styles (removed Muriel styles/classes)
* Applied changes to the Handoff button with `Waiting` instead of `Spinner`
* Updated the Demo accordingly
__Before:__
__After:__
1. Check every pages with a button.
3. Re-check all the pages. Notice any bugs?
> Update Button (and Handoff) component with BaseComponent

- assets/components/src/card/style.scss
- assets/components/src/checkbox-control/style.scss
- assets/wizards/setup/views/newsroom/index.js
- assets/wizards/setup/views/newsroom/style.scss
* Newsroom: Update classes to paragraph and checkbox wrapper
* Newsroom: Split checkboxes into 2 columns and update margins
* Card: Add new `is-dark` option to paragraphs
* Checkbox Control: Update the label so it looks like a regular text 
__Before:__
__After:__
1. Go to Setup > Tell us about your Newsroom. Notice the checkboxes.
3. Refresh the page. The checkboxes should be displayed in 2 columns.
> Update the Newsroom view checkboxes into 2 columns

- assets/components/src/action-card/index.js
- assets/components/src/index.js
- assets/components/src/toggle-control/index.js
- assets/components/src/toggle-control/style.scss
- assets/components/src/toggle-group/index.js
- assets/components/src/toggle-group/style.scss
- assets/wizards/readerRevenue/views/donation/index.js
- assets/wizards/readerRevenue/views/donation/style.scss
- assets/wizards/readerRevenue/views/stripe-setup/index.js
- assets/wizards/readerRevenue/views/stripe-setup/style.scss
This PR adds a new Toggle Control component using `BaseComponent`. We then replace all the WordPress's `ToggleControl` with Newspack's.
Also fixes a few visual issues with the Reader Revenue and toggles (Donation / Stripe).
__Before:__
__After:__
1. Check every pages you can think of that has a toggle.
3. Re-check the pages.
> Toggle Components: Add new `ToggleControl` and update `ToggleGroup`

- assets/components/src/checklist/index.js
- assets/components/src/checklist/style.scss
- assets/components/src/progress-bar/index.js
- assets/components/src/progress-bar/style.scss
- assets/components/src/task/index.js
- assets/components/src/task/style.scss
- assets/wizards/componentsDemo/index.js
I removed Muriel and Dashicon for all 3 components (Checklist, Task, and Progress).
It now looks similar to the rest of the plugin, kind of like the Action Card.
Also, I updated the Components Demo accordingly.
__Before:__
__After:__
1. At the moment, the only place you can see it in action is via the Components Demo.
2. The current style looks out of place. 
4. You're welcome.
> Rework the Checklist, Task and Progress components

- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/ad-unit/index.js
- assets/wizards/advertising/views/adsense/index.js
- assets/wizards/advertising/views/header-code/index.js
- assets/wizards/advertising/views/placements/index.js
* Added `subHeaderText` to all pages
* Make sure `secondaryButtonStyle` is set to default
* Removed unused links
* Used `Notice` instead of `Dashicon`
* Allowed text to be translatable
2. Go to Newspack > Advertising. Check all the pages.
3. Anything looks broken or out of place? (except for the TextareaControl which will be updated in a separate PR 😊)
> Advertising Wizard: Update content throughout the different pages

- assets/wizards/engagement/views/social/index.js
Update the string for the description of the plugin.
Copied from https://jetpack.com/support/publicize/
1. Go to Engagement > Social
2. Jetpack Publicize's description should simply say "Description TK.".
4. You should see the new description.
> Engagement: Update the Jetpack Publicize description

- includes/class-newspack.php
After activating the Newspack plugin, redirect to the Setup Wizard. This will happen only once.
1. Deactivate and reactivate the Newspack Plugin.
2. Verify the redirect to the Setup Wizard.
3. Navigate away without completing setup, and verify the redirect does not happen again.
> Redirect To Setup Wizard After Activation

- newspack.php
This PR bumps the plugin's version to `1.0.0-alpha.15` for a new release.
1. Apply the PR.
2. Verify that the plugin's version is now `1.0.0-alpha.15`.
> Bump version number

- includes/configuration_managers/class-newspack-ads-configuration-manager.php
- includes/wizards/class-advertising-wizard.php
Complete testing instructions here: https://github.com/Automattic/newspack-ads/pull/19
> Pass Placement To Ads Plugin

- assets/components/package.json
Bump the version number of the components so we can update the NPM package: https://www.npmjs.com/package/newspack-components
> Newspack Components: Bump version number to update npm

- .circleci/config.yml
- commitlint.config.js
- composer.json
- package-lock.json
- package.json
This configures:
1. commit message linting, adhering to [Angular's convention](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commit-message-format)
2. CircleCI:
1. run linting 
1. release automatically, with [semantic-release](https://semantic-release.gitbook.io/) (from branch `release`, which we will not use until March)
Run `./vendor/brainmaestro/composer-git-hooks/cghooks update` to update git hooks after this is merged 🙏
1. update git hooks: `./vendor/brainmaestro/composer-git-hooks/cghooks update`
1. add some changes to git staging
2. try to commit with a useless message (e.g. `git commit -m "hehe"`)
3. observe that this shall not pass
4. try to commit with a standardized message (e.g. `git commit -m "feat: increase life span"`)
> Configure CircleCI for linting & releasing

- .circleci/config.yml
- bin/install-wp-tests.sh
- includes/api/class-wizards-controller.php
- includes/class-admin-plugins-screen.php
- includes/class-handoff-banner.php
- includes/class-newspack.php
- includes/configuration_managers/class-newspack-ads-configuration-manager.php
- includes/wizards/class-advertising-wizard.php
- newspack.php
- tests/class-newspack-unit-tests-bootstrap.php
- tests/unit-tests/api-wizards-controller.php
1. Set up CircleCI to run PHPUnit tests and PHP linting. Added `bin/install-wp-tests.sh` file, which was generated by running `wp scaffold plugin-tests …`
2. Fix linting errors
1. Look at the code changes - these should only be refactoring changes to fix linting errors.
1. Take a look [at CircleCI](https://app.circleci.com/github/Automattic/newspack-plugin/pipelines) - PHP tests should be ran there
1. Results should be reported (as success) in this PR (below, "Status checks")
> CI: run PHP tests & linting; fix PHP linting errors

- assets/components/src/button/style.scss
- assets/components/src/index.js
- assets/components/src/radio-control/index.js
- assets/components/src/radio-control/style.scss
- assets/components/src/toggle-control/style.scss
- assets/wizards/site-design/index.js
- assets/wizards/site-design/views/index.js
- assets/wizards/site-design/views/theme-mods/index.js
- assets/wizards/site-design/views/theme-mods/style.scss
- composer.lock
- includes/wizards/class-setup-wizard.php
- includes/wizards/class-site-design-wizard.php
Adds a 2nd tab to the Site Design Wizard with the Theme Options.
2. Navigate to Site Design > Settings
3. Change the different options and check if they are being applied.
4. Check the Customizer if the 2 matches.
> Site Design Wizard: Theme Mod Controls

- assets/wizards/support/index.js
- assets/wizards/support/views/create-ticket/index.js
- assets/wizards/support/views/create-ticket/style.scss
- assets/wizards/support/views/index.js
- includes/class-newspack.php
- includes/class-wizards.php
- includes/wizards/class-support-wizard.php
- package-lock.json
- package.json
A support form, which will submit a ticket to Zendesk. 
1. observe that there is no "support" submenu item in Newspack menu in admin 
1. add necessary environment variables to `wp-config.php`:
```
define('NEWSPACK_SUPPORT_API_URL', 'https://my-super-support.zendesk.com/api/v2');
define('NEWSPACK_SUPPORT_EMAIL', 'support@site.com');
```
3. observe that there is a "support" submenu item in Newspack menu in admin 
4. visit the support wizard, you should see a form
5. fill in subject and message and submit the form 
6. a success message should greet you 
7. a ticket should appear in the Zendesk instance
> Add support screen

- includes/wizards/class-payment-wizard.php
Use WPCOM endpoints to protect Stripe keys from exposure.
Moves endpoints for Stripe API activity to WP.com, to avoid risk of API key exposure. Complete testing instructions in `D39588-code`.
> WP.com Stripe Endpoints

- includes/class-starter-content.php
- includes/wizards/class-setup-wizard.php
The starter content feature recently began failing because the API we use to generate lorem ipsum (https://www.lipsum.com/) often times out. This PR switches to https://loripsum.net/ (thank you @adekbadek for the suggestion!)
Closes https://github.com/Automattic/newspack-plugin/issues/446
1. On test instance, delete all posts.
2. Navigate to Settings->Newspack and click "Setup" link.
3. Step through Set Up Wizard. At the end, click to create Starter Content.
4. After Wizard completes, check that ~40 posts were created with appropriate lorem ipsum title and body text.
> Fix Starter Content Lorem Ipsum Generation

- composer.json
- composer.lock
- includes/class-starter-content.php
- package-lock.json
- package.json
The starter content feature generates lorem ipsum text using third party APIs. This approach is slow and failure prone. In this branch the [php-loremipsum](https://github.com/joshtronic/php-loremipsum) library is installed and used instead. 
From the php-loremipsum docs:
> The first string generated will always start with the traditional "Lorem ipsum dolor sit amet, consectetur adipiscing elit". Subsequent strings may contain those words but will not explicitly start with them.
This is problematic because it means all titles will be identical, and the point of starter content is to display a random, realistic-looking body of content. To beat this, this branch strips out the identical opening bits of generated lorem ipsum to make each string unique. In the case of paragraphs, the first one …
> Use php-loremipsum For Starter Content Text

- assets/wizards/support/index.js
- assets/wizards/support/views/chat/index.js
- assets/wizards/support/views/chat/style.scss
- assets/wizards/support/views/index.js
- assets/wizards/support/views/loading/index.js
- assets/wizards/support/views/loading/style.scss
- includes/wizards/class-support-wizard.php
- package-lock.json
- package.json
This introduces a Chat tab to the Support view:
There is one problem with the approach introduced here. 
A WPCOM auth token is needed for authentication to interact with Happychat, so [WPCOM app](https://developer.wordpress.com/apps/) needs to be set up for that. The problem is that such an app has to have a whitelist of request origin and redirect URLs. This list will have to be updated with each new site using the support feature.
The chat window is an iframe, so the only way of styling it's contents is via adding new code to the [`happychat-client`](https://github.com/Automattic/happychat-client). Bare in mind that it might take time.
1. Create [a WPCOM app](https://developer.wordpress.com/apps/) and set:
1. "Javascript Origins" to your test site URL
1. "Redirect URLs" to `<your test …
> Support: add Happychat

- assets/wizards/support/views/create-ticket/index.js
- assets/wizards/support/views/loading/index.js
As our [support docs](https://newspack.blog/support/) are live now, we should nudge the users to try to find a solution themselves before contacting support.
1. Visit the support screen
2. Observe a notice with link to the support docs
3. Click the link, which should navigate to https://newspack.blog/support
> Support: add a link to support docs

- README.md
Readme update:
- info about environment variables necessary for support and payment features
- release-related badges
> Docs: add info about env vars, badges

- includes/wizards/class-support-wizard.php
The [Newspack] string was too generic.
1. Create a ticket via support view form
2. Observe that the ticket's subject starts with `[Newspack Support]`
> Support: update subject string for support tickets

- includes/class-handoff-banner.php
- includes/wizards/class-seo-wizard.php
Out of usual release cadence in order to ship bugfixes.
> Release 3/19/20

- .eslintrc.js
- assets/components/src/style-card/index.js
- assets/wizards/setup/index.js
- assets/wizards/setup/views/starter-content/index.js
- assets/wizards/site-design/views/theme-selection/index.js
- includes/class-starter-content.php
- includes/wizards/class-health-check-wizard.php
- includes/wizards/class-setup-wizard.php
- includes/wizards/class-wizard.php
> Release 3/24/2020

- assets/components/src/card/index.js
- assets/components/src/card/style.scss
- assets/wizards/componentsDemo/index.js
- assets/wizards/dashboard/index.js
- assets/wizards/dashboard/style.scss
> Release 3/31/2020

- assets/components/package.json
- assets/components/src/button/style.scss
- assets/components/src/color-picker/style.scss
- assets/components/src/modal/style.scss
- assets/components/src/toggle-control/style.scss
- assets/components/src/web-preview/style.scss
- assets/components/src/wizard-pagination/index.js
- assets/components/src/wizard-pagination/style.scss
- assets/wizards/dashboard/index.js
- assets/wizards/dashboard/style.scss
> Release 4/21/2020

- assets/wizards/support/components/withWPCOMAuth.js
- assets/wizards/support/index.js
- assets/wizards/support/utils/index.js
- assets/wizards/support/views/chat/index.js
- assets/wizards/support/views/create-ticket/index.js
- assets/wizards/support/views/index.js
- assets/wizards/support/views/list-tickets/index.js
- assets/wizards/support/views/list-tickets/style.scss
- includes/wizards/class-support-wizard.php
Add a tickets list view to the Support wizard.
1. Set up a [WPCOM app for OAuth](https://developer.wordpress.com/apps)
2. Ensure support-related env variables are present (as per README.md)
3. Visit the Support wizard in the Newspack plugin
4. Authenticate, if necessary, with a WPCOM account 
5. Observe a list of open and closed tickets tickets, or a message informing about no tickets
> Add tickets list in Support wizard

- .circleci/config.yml
- .github/workflows/main.yml
- assets/components/src/action-card/index.js
- assets/components/src/action-card/style.scss
- assets/components/src/card/style.scss
- assets/components/src/plugin-installer/index.js
- assets/components/src/with-wizard/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/popups/components/popup-action-card/index.js
- assets/wizards/popups/views/popup-group/index.js
- assets/wizards/popups/views/popup-group/style.scss
- assets/wizards/support/components/withWPCOMAuth.js
- assets/wizards/support/index.js
- assets/wizards/support/utils/index.js
- assets/wizards/support/views/chat/index.js
- assets/wizards/support/views/create-ticket/index.js
- assets/wizards/support/views/index.js
- assets/wizards/support/views/list-tickets/index.js
- assets/wizards/support/views/list-tickets/style.scss
- includes/class-newspack.php
- includes/class-settings.php
- includes/wizards/class-support-wizard.php
> Release 03/06/2020

- README.md
> Add information about News Consumer Insights integration

- assets/wizards/popups/views/analytics/index.js
- includes/popups-analytics/class-popups-analytics-utils.php
Improve Campaign Analytics error handling:
1. Visit Campaign wizard, Analytics view on a site without Site Kit connected. Observe that a helpful notice is displayed with link to Site Kit setup
2. On a site where Site Kit is connected:
2. Visit the Analytics view, but log in as a different user than the one who set up the connection. Observe that a helpful notice is displayed with link to Site Kit setup.
3. Visit the Analytics view, as the user who set up the Site Kit connection. Observe the view rendered as expected (with a chart)
> Campaign Analytics: better error handling

- README.md
- assets/wizards/popups/views/analytics/index.js
- includes/popups-analytics/class-popups-analytics-utils.php
> Release 18/06/2020

- includes/class-analytics.php
> Release 23/06/2020

- includes/class-analytics.php
Adds NTG newsletter events (signup and visibility). Replaces #557. This approach uses the `render_block` hook to alter Mailchimp block markup for AMP analytics compatibility, and also uses new hooks from https://github.com/Automattic/newspack-popups/pull/164 to determine the context of the block (inline campaign, overlay campaign, or other).
Closes #559.
1. Check out https://github.com/Automattic/newspack-popups/pull/164 in the campaigns plugin or make sure the changes in there are merged to master and active in your local environment.
2. Create at least two different campaigns: 1.) Overlay, site-wide default, and 2.) Inline, Every Page. Both should be Active (not test mode) and both should contain a Mailchimp newsletter signup block.
3. Create a new page or post and insert a Mailchimp …
> feat: ntg mailing list events in amp

- includes/class-analytics.php
A new release – to get bounce rate fix out there.
> Release 09/07/2020

- README.md
- assets/wizards/support/components/withWPCOMAuth.js
- assets/wizards/support/index.js
- assets/wizards/support/views/create-ticket/index.js
- includes/wizards/class-support-wizard.php
- package-lock.json
- package.json
Adds pre-launch tickets feature. Also adds features that will be available for regular tickets submission:
- Setting priority
- Rich text editing in message input
Closes #548 – *without* the TAM-assignment feature, because setting an assignee is not supported for anonymous tickets.
1. Add a `NEWSPACK_SUPPORT_IS_PRE_LAUNCH` environment variable with value of `true`
2. Visit the Support wizard (authenticate with WPCOM if asked)
3. Observe that the chat tab is not available and that there's no notice about visiting support docs before sending a ticket
3. Submit a ticket
3. Observe that the ticket was sent with `[Newspack Pre-launch]` prefix, which should trigger apppriate actions in Zendesk
> Add pre-launch tickets

- includes/class-analytics.php
Adds NTG event triggers for user account login and registration as described in the [NTG Playbook](https://newsinitiative.withgoogle.com/training/states/ntg/assets/ntg-playbook.pdf).
Leverages WooCommerce hooks as [described here](https://docs.woocommerce.com/wc-apidocs/hook-docs.html).
This PR replaces #569 with a better, hooks-based approach. Testing instructions remain more or less the same.
Closes #560.
1. In the WP dashboard, go to **WooCommerce > Settings > Accounts & Privacy** and make sure the " Allow customers to create an account during checkout" and "Allow customers to create an account on the 'My account' page" options are checked.
2. In the dashboard, go to Pages and edit the WooCommerce Donate Page, Account Page and Checkout Page. Make sure to disable AMP for all.
3. Visit …
> (Refactor) Add NTG event triggers for user account login/registration

- assets/components/package.json
- assets/components/src/index.js
- assets/components/src/with-wizard/index.js
- assets/wizards/analytics/index.js
- assets/wizards/analytics/views/configuration/index.js
- assets/wizards/analytics/views/configuration/style.scss
- assets/wizards/analytics/views/index.js
- assets/wizards/analytics/views/plugins/index.js
- assets/wizards/dashboard/views/dashboardCard.js
- assets/wizards/updates/index.js
- assets/wizards/updates/views/devInfo/index.js
- assets/wizards/updates/views/devInfo/style.scss
- assets/wizards/updates/views/index.js
- includes/class-analytics.php
- includes/class-newspack.php
- includes/class-plugin-manager.php
- includes/class-wizards.php
- includes/wizards/class-analytics-wizard.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-updates-wizard.php
- package-lock.json
- package.json
> Release Jul 22

- assets/wizards/analytics/index.js
- assets/wizards/analytics/views/configuration/index.js
- assets/wizards/analytics/views/configuration/style.scss
- assets/wizards/analytics/views/index.js
- assets/wizards/analytics/views/plugins/index.js
- includes/class-analytics.php
- includes/wizards/class-analytics-wizard.php
> Release Jul 28

- assets/wizards/dashboard/views/dashboardCard.js
- assets/wizards/updates/index.js
- assets/wizards/updates/views/devInfo/index.js
- assets/wizards/updates/views/devInfo/style.scss
* New wizard icon (Updates)
* New expand more/less icon (ExpandMore)
* Adjust margins/paddings of details/summary
1. Navigate to Newspack > Updates and Newspack > Dashboard
3. Do you see the changes proposed?
5. Do you see the new icon?
> Update updates wizard details style

- .circleci/config.yml
- assets/components/src/consts.js
- assets/components/src/text-control/index.js
- assets/components/src/text-control/style.scss
- assets/components/src/with-wizard/index.js
- assets/wizards/analytics/index.js
- assets/wizards/analytics/style.scss
- assets/wizards/analytics/views/custom-dimensions/index.js
- assets/wizards/analytics/views/custom-events/index.js
- assets/wizards/analytics/views/index.js
- assets/wizards/dashboard/views/dashboardCard.js
- assets/wizards/engagement/index.js
- assets/wizards/engagement/views/index.js
- assets/wizards/engagement/views/related-content/index.js
- assets/wizards/engagement/views/related-content/style.scss
- assets/wizards/updates/index.js
- assets/wizards/updates/views/devInfo/index.js
- assets/wizards/updates/views/devInfo/style.scss
- includes/amp-enhancements/class-newspack-cookie-notice-amp-markup.php
- includes/amp-enhancements/class-wp-gdpr-cookie-notice-performance.php
- includes/class-amp-enhancements.php
- includes/class-analytics.php
- includes/class-plugin-manager.php
- includes/class-webhooks.php
- includes/configuration_managers/class-jetpack-configuration-manager.php
- includes/wizards/class-analytics-wizard.php
- includes/wizards/class-engagement-wizard.php
- package.json
> Release Aug 11

- assets/wizards/analytics/views/custom-events/index.js
> Alpha release Aug 14

- includes/class-plugin-manager.php
This PR adds AutomateWoo and AutomateWoo - Refer A Friend to the list of vetted plugin
1. Stay on `master`, install both plugins
2. Go to Newspack > Health Check - they shouldn't be supported
4. Refresh Health Check page - they should now be supported
5. Go to Plugins > Installed Plugins, check that both plugins are under "Newspack"
> feat: add AutomateWoo and AW Refer Friend to the list of vetted plugins

- assets/wizards/dashboard/index.js
- includes/class-plugin-manager.php
> Alpha release Aug 18

- assets/wizards/analytics/views/custom-events/index.js
- assets/wizards/dashboard/index.js
- includes/class-plugin-manager.php
> Release Aug 18

- includes/class-plugin-manager.php
Adds the Newspack Sponsors plugin as a whitelisted/managed plugin. This allows the plugin to be displayed by default on the Plugins page, and easily installed and activated in a couple of clicks.
Adds the Newspack Sponsors plugin as a whitelisted/managed plugin. This allows the plugin to be displayed by default on the Plugins page, and easily installed and activated in a couple of clicks.
1. Apply this PR branch. If you have previously installed a dev version of Newspack Sponsors, deactivate and delete it first.
2. Go to the plugins page in WP admin.
3. Observe that there's a row for Newspack Sponsors with a one-click "Install" link.
4. Click "Install", then activate the plugin. Confirm that the plugin version installed matches the "latest" release version at …
> feat: add newspack-sponsors as a managed plugin

- assets/wizards/syndication/index.js
- assets/wizards/syndication/views/intro/index.js
- includes/class-plugin-manager.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-syndication-wizard.php
This PR adds [Distributor](https://distributorplugin.com/) to the Syndication Wizard. It's using the `PluginToggle` component` to make it optional.
1. Navigate to Newspack > Syndication
2. Switch to this branch then refresh page
3. You should see an Action Card with a Toggle for Distributor
4. Enable it and test the plugin 😊
> feat: add support to distributor

- assets/wizards/dashboard/views/dashboardCard.js
- assets/wizards/support/index.js
- includes/wizards/class-dashboard.php
- includes/wizards/class-popups-wizard.php
- includes/wizards/class-support-wizard.php
- includes/wizards/class-updates-wizard.php
This PR add a Support card to thee Dashboard
2. Navigate to Newspack > Dashboard
3. Do you see the Support card?
4. Click on it, are you taken to the Support Wizard?
> Add support wizard to dashboard

- assets/wizards/dashboard/views/dashboardCard.js
- assets/wizards/support/index.js
- includes/class-donations.php
- includes/class-salesforce.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-popups-wizard.php
- includes/wizards/class-support-wizard.php
- includes/wizards/class-updates-wizard.php
> Alpha release Sep 08

- assets/wizards/dashboard/views/dashboardCard.js
- assets/wizards/support/index.js
- includes/class-donations.php
- includes/class-salesforce.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-popups-wizard.php
- includes/wizards/class-support-wizard.php
- includes/wizards/class-updates-wizard.php
> Release Sep 08

- includes/class-analytics.php
Enables using the [User ID feature](https://support.google.com/analytics/answer/3123666) of Google Analytics.
1. In Site Kit -> Settings -> Analytics, edit the "Excluded from Analytics" setting to not exclude logged-in users
2. In your GA account, enable User ID by following steps 1 and 3 from [this docs page](https://support.google.com/analytics/answer/3123666)
3. Visit the site as a logged in user, verify that the visit is reported in the new GA reporting view
> Analytics: report User ID

- assets/components/src/action-card-sections/index.js
- assets/components/src/action-card-sections/style.scss
- assets/components/src/select-control/style.scss
- assets/wizards/advertising/views/placements/ad-picker/style.scss
- assets/wizards/analytics/style.scss
Fixes some `select`-related styling issues introduced with recent changes to Gutenberg.
1. On `master`, visit Advertising, Campaigns, Analytics wizard and see the following styling issues:
2. Switch to this branch, rebuild, confirm the issues are no more
> Styling: fix selects in wizards

- assets/components/src/action-card-sections/index.js
- assets/components/src/action-card-sections/style.scss
- assets/components/src/select-control/style.scss
- assets/wizards/advertising/views/placements/ad-picker/style.scss
- assets/wizards/analytics/style.scss
- assets/wizards/analytics/views/custom-dimensions/index.js
- includes/class-amp-enhancements.php
- includes/class-analytics.php
- includes/wizards/class-analytics-wizard.php
- package-lock.json
- package.json
> Alpha release Sep 15

- assets/components/src/action-card-sections/index.js
- assets/components/src/action-card-sections/style.scss
- assets/components/src/select-control/style.scss
- assets/wizards/advertising/views/placements/ad-picker/style.scss
- assets/wizards/analytics/style.scss
- assets/wizards/analytics/views/custom-dimensions/index.js
- includes/class-amp-enhancements.php
- includes/class-analytics.php
- includes/wizards/class-analytics-wizard.php
- includes/wizards/class-seo-wizard.php
- package-lock.json
- package.json
> Release Sep 15

- assets/wizards/popups/components/popup-popover/index.js
- assets/wizards/popups/views/popup-group/index.js
> Alpha release Sep 22

- assets/wizards/popups/components/popup-popover/index.js
- assets/wizards/popups/views/popup-group/index.js
> Release Sep 22

- assets/components/package.json
- assets/components/src/autocomplete-tokenfield/index.js
- assets/components/src/autocomplete-tokenfield/style.scss
- assets/components/src/index.js
- includes/class-donations.php
- includes/class-plugin-manager.php
- includes/class-salesforce.php
- includes/class-webhooks.php
> Alpha release – Oct. 7

- includes/class-salesforce.php
> Alpha release #2 – Oct. 7

- assets/components/package.json
- assets/components/src/autocomplete-tokenfield/index.js
- assets/components/src/autocomplete-tokenfield/style.scss
- assets/components/src/index.js
- includes/class-donations.php
- includes/class-plugin-manager.php
- includes/class-salesforce.php
- includes/class-webhooks.php
> Release – Oct. 7

- assets/components/src/tabbed-navigation/index.js
- assets/wizards/popups/index.js
- assets/wizards/popups/views/index.js
- assets/wizards/popups/views/segmentation/SegmentsList.js
- assets/wizards/popups/views/segmentation/SingleSegment.js
- assets/wizards/popups/views/segmentation/index.js
- assets/wizards/popups/views/segmentation/style.scss
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-popups-wizard.php
- package-lock.json
- package.json
Segmentation UI for Campaigns plugin.
_Follow testing steps in https://github.com/Automattic/newspack-popups/pull/289_
> Add segmentation UI in Campaigns wizard

- package-lock.json
- package.json
Update `react-router-dom` to v5.2.0
This fixes a potential error with `useHistory`
1. Make sure you have an old version of `react-router-dom` (e.g. 5.0.1)
2. Try to open Newspack > Campaigns
3. You should get an error `useHistory is not a function at TabbedNavigation`
5. Refresh Newspack > Campaigns
> Update React Router Dom to its latest version

- assets/components/src/action-card-sections/index.js
- assets/components/src/select-control/style.scss
- assets/components/src/tabbed-navigation/index.js
- assets/wizards/popups/components/popup-popover/index.js
- assets/wizards/popups/components/popup-popover/style.scss
- assets/wizards/popups/index.js
- assets/wizards/popups/views/index.js
- assets/wizards/popups/views/popup-group/index.js
- assets/wizards/popups/views/segmentation/SegmentsList.js
- assets/wizards/popups/views/segmentation/SingleSegment.js
- assets/wizards/popups/views/segmentation/index.js
- assets/wizards/popups/views/segmentation/style.scss
- includes/amp-sanitizers/class-amp-sanitizer-gam.php
- includes/class-amp-enhancements.php
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-advertising-wizard.php
- includes/wizards/class-popups-wizard.php
- package-lock.json
- package.json
> Alpha release Nov 11

- assets/components/src/action-card-sections/index.js
- assets/components/src/select-control/style.scss
- assets/components/src/tabbed-navigation/index.js
- assets/wizards/popups/components/popup-popover/index.js
- assets/wizards/popups/components/popup-popover/style.scss
- assets/wizards/popups/index.js
- assets/wizards/popups/views/index.js
- assets/wizards/popups/views/popup-group/index.js
- assets/wizards/popups/views/segmentation/SegmentsList.js
- assets/wizards/popups/views/segmentation/SingleSegment.js
- assets/wizards/popups/views/segmentation/index.js
- assets/wizards/popups/views/segmentation/style.scss
- includes/amp-sanitizers/class-amp-sanitizer-gam.php
- includes/class-amp-enhancements.php
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-advertising-wizard.php
- includes/wizards/class-popups-wizard.php
- package-lock.json
- package.json
> Release Nov 11

- assets/wizards/popups/views/segmentation/SingleSegment.js
Updating React is always a good idea, but this is about something else.
> Fix freudian slip

- includes/configuration_managers/class-woocommerce-configuration-manager.php
Updates WooComm settings during content migration to ensure that the Checkout will work well:
- turns off AMP for the Checkout page
- checks ON two options in WooComm > Settings
The Wizard should apply these two settings if WooComm is installed and set up.
> feat: necessary WooComm settings for Checkout to work correctly

- includes/class-newspack.php
Update constant name after changes in https://github.com/Automattic/newspack-popups/pull/343
> Update newspack-popups constant name

- assets/components/src/with-wizard-screen/index.js
- assets/components/src/with-wizard-screen/style.scss
- includes/class-newspack.php
- includes/class-plugin-manager.php
- includes/configuration_managers/class-configuration-managers.php
- includes/configuration_managers/class-jetpack-configuration-manager.php
- includes/configuration_managers/class-site-kit-configuration-manager.php
- includes/wizards/class-wizard.php
> Alpha release Dec 15

- assets/components/src/button/style.scss
This PR slightly updates the style of the `Button` component.
* Increased the height of the `isSmall`, from 32px to 36px
* New text colour for `isSecondary`
* Reworked the `:focus` state
1. Check the components demo
3. Have a look at the buttons
> Increase button small height, adjust secondary and focus

- assets/components/src/with-wizard/index.js
- assets/components/src/with-wizard/style.scss
- assets/wizards/popups/index.js
This branch introduces a "quiet" loading style. This style is applied when changing categories or any settings in the Popover. It also introduce a new animation, specific to the quiet loading style.
1. Go to Campaigns
2. Change the frequency or segment in the popover menu
> feat: quiet loading class

- assets/wizards/popups/components/segmentation-preview/index.js
- assets/wizards/popups/views/segmentation/SingleSegment.js
- assets/wizards/readerRevenue/views/salesforce/index.js
- includes/wizards/class-reader-revenue-wizard.php
> Alpha release Jan 14

- assets/components/src/grid/style.scss
- assets/components/src/style-card/index.js
- assets/components/src/style-card/style.scss
- assets/components/src/web-preview/index.js
- assets/wizards/site-design/index.js
- assets/wizards/site-design/views/theme-selection/index.js
To be in line with the new onboarding design, this PR updates the style of `StyleCard` and the Theme Wizard. 
__After:__
__Before:__
1. Go to Site Design, check the old style
2. Switch to this branch and refresh wizard
3. Do you see the new style? Can you view demo/activate properly?
> Update style card design

- assets/wizards/seo/views/tools/index.js
- includes/class-admin-plugins-screen.php
- includes/class-plugin-manager.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-support-wizard.php
- languages/newspack-plugin.pot
- newspack.php
Ensures all translatable strings are using the textdomain, loads the textdomain and creates the initial pot file.
N/A
> Make the Newspack plugin translation ready

- assets/components/src/wizard-pagination/index.js
- assets/components/src/wizard-pagination/style.scss
This PR slightly adjusts the design of the Wizard Pagination (see pamTN9-23F-p2#comment-2645)
* No more separator
* Uses icons for the menu on small screens
* New vertical alignment on large screens to match Tabbed Navigation
2. Go through the Setup Wizard
3. Resize your screen and start again
> Update the Wizard Pagination design

- includes/class-plugin-manager.php
This PR adds Bing URL Submissions to the managed plugins list. 
[Developed by Microsoft's Bing team, this plugin](https://wordpress.org/plugins/bing-webmaster-tools/) enables WordPress sites, once connected to Bing Webmaster Tools, to automatically notify Bing whenever new content is published. The advantage of a **push-based** approach is that a Newspack publisher can ensure their articles are submitted to Bing's index for inclusion just as soon as they are live on their site, rather than waiting for Bingbot to show up at some point and _pull_ the content into the index. 
All news sites have a need for speed, and Bing URL Submissions caters to this need. 
Newspack's distribution already contains plugins that interface with Google, Apple News, and Facebook; now we'll have a tool for …
> Add Bing URL Submissions to supported plugins list

- assets/wizards/popups/components/segment-group/index.js
- assets/wizards/popups/components/segment-group/style.scss
- assets/wizards/popups/components/segmentation-preview/index.js
- assets/wizards/popups/views/campaigns/index.js
- includes/class-nrh.php
> Alpha release Feb 10

- assets/wizards/popups/components/prompt-popovers/secondary.js
- assets/wizards/popups/utils.js
> Alpha release Feb 16

- assets/wizards/popups/components/prompt-popovers/secondary.js
- assets/wizards/popups/utils.js
> Release Feb 16

- assets/components/package.json
- assets/components/src/footer/index.js
- assets/components/src/global-notices/index.js
- assets/components/src/index.js
- assets/wizards/dashboard/index.js
- includes/class-newspack.php
- includes/class-starter-content.php
- includes/wizards/class-wizard.php
Starter content removal.
Closes #805
1. Visit the Setup wizard on a fresh site (`/wp-admin/admin.php?page=newspack-setup-wizard#/`)
2. After completing the setup, observe a "Remove Starter Content" link at the bottom of the Newspack dashboard; click it
3. Observe that the starter content has been removed
> Starter content removal

- includes/wizards/class-advertising-wizard.php
> Alpha release Feb 23

- assets/components/src/action-card/style.scss
- assets/components/src/card/style.scss
- assets/components/src/modal/style.scss
- assets/components/src/popover/style.scss
- assets/components/src/web-preview/index.js
- assets/components/src/web-preview/style.scss
- assets/wizards/popups/components/prompt-action-card/index.js
- assets/wizards/popups/components/prompt-action-card/style.scss
- assets/wizards/popups/components/segment-group/icons.js
- assets/wizards/popups/components/segment-group/index.js
- assets/wizards/popups/components/segment-group/style.scss
- assets/wizards/popups/views/campaigns/index.js
* Move the "Add New Prompt" button to the Segment header section (original idea by @adekbadek)
* Rework the margins/paddings within a segment
1. Navigate to Campaigns
> feat: update style of the segments and prompts

- assets/wizards/setup/views/integrations/index.js
- assets/wizards/setup/views/integrations/style.scss
* Use of: Grid, Card, SectionHeader
* Reworked status style
1. Run the onboarding until the Integrations step
3. Notice the changes
> Visually update the Integrations step

- assets/wizards/dashboard/index.js
- assets/wizards/dashboard/style.scss
- assets/wizards/dashboard/views/dashboardCard.js
* Rework the `DashboardCard` and remove chevron
* Increase and center `NewspackLogo`
1. Go to the Dashboard
3. Notice the changes
> Update design dashboard

- assets/wizards/popups/views/segments/SegmentsList.js
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-popups-wizard.php
> Alpha release Feb 24

- assets/components/src/web-preview/index.js
- assets/components/src/web-preview/style.scss
Small visual update to the `WebPreview` component:
* Thinner toolbar
* Use of `ButtonGroup`
* Correct use of icon-only buttons
* Overall reorganisation of the stylesheet
1. Navigate to a Wizard with a `WebPreview` (e.g. Campaigns or Site Design)
2. Open a preview
4. Open a preview and notice the differences
> Update design WebPreview

- assets/components/src/toggle-control/index.js
- assets/wizards/analytics/views/custom-events/index.js
- includes/class-analytics.php
- includes/wizards/class-analytics-wizard.php
For various reasons a user might not want to use NTG events reporting. This PR adds an option to disable it.
1. Visit site as a non-logged in user, observe NTG events being sent to GA*
2. Visit the Analytics Wizard, "Custom Events" tab. Disable NTG events reporting
3. Redo step 1, this time observe the NTG events not reported 
\* example: article read milestone at 25%. View the reported events by filtering the requests in the network tab by `collect`.
> Allow disabling NTG events reporting

- assets/components/src/checkbox-control/index.js
- assets/wizards/popups/views/segments/style.scss
- assets/wizards/popups/views/settings/index.js
> Alpha release Mar 09

- assets/components/src/hooks/useObjectState.js
- assets/components/src/hooks/useObjectState.test.js
- includes/class-newspack.php
- includes/class-patches.php
> Alpha release Mar 16

- assets/components/src/hooks/useObjectState.js
- assets/components/src/hooks/useObjectState.test.js
- includes/class-newspack.php
- includes/class-patches.php
> Release Mar 16

- assets/components/src/with-wizard/style.scss
- assets/wizards/setup/views/welcome/index.js
Small adjustments to the "footer" of the welcome card:
* switched to `Card`
* better margins
* new wording for the primary `Button`
2. Open the Setup Wizard
3. Test with and without installing the demo content
> Update welcome wizard card footer

- includes/popups-analytics/class-popups-analytics-utils.php
> Alpha release Mar 30

- includes/class-plugin-manager.php
- includes/wizards/class-analytics-wizard.php
> Alpha release Apr 06

- includes/popups-analytics/class-popups-analytics-utils.php
Never underestimate the amount of data.
1. Connect Site Kit Analytics module to an account with _a lot_* of Campaigns events reported
2. Visit the Campaigns wizard, Analytics screen. Set the date range to 90 days
3. On `master`, you should see a cutoff - most recent data would not be included
4. On this branch, all data should be visible
\* The one I used had ~20k events reported per day
> Campaigns Analytics: fetch all pages of analytics report

- includes/class-plugin-manager.php
- includes/popups-analytics/class-popups-analytics-utils.php
- includes/wizards/class-analytics-wizard.php
> Release Apr 06

- assets/wizards/site-design/views/main/index.js
- includes/wizards/class-reader-revenue-wizard.php
- includes/wizards/class-setup-wizard.php
Fixes two issues.
1. On `master`, 
2. Visit the Design step of the onboarding. Observe that after clicking "Preview" you're redirected to Newspack dashboard
3. Visit the Services step of the onboarding. Observe the donation amounts and Stripe settings inserted there are not reflected in the Reader Revenue wizard
4. Switch to this branch, observe both issues resolved
> Fix onboarding issues

- includes/class-analytics.php
In #914, GA config size was made smaller in order to mitigate gtag-config-rewriter [payload limitation issue](https://github.com/ampproject/amphtml/issues/32911). This is an improved solution - batching the custom events in groups of 10 and inserting them as separate `amp-analytics` tags, resulting in separate (smaller in payload size) calls to the `gtag` endpoint. 
1. Enable NTG events in the Analytics wizard, and visit a page with plenty of prompts (Newspack Campaigns plugin)
2. Observe the GA custom events reported as expected* 
3. Observe just one `pageview` sent
4. Observe multiple calls to `https://www.googletagmanager.com/gtag/amp` (the [config rewriter](https://amp.dev/documentation/components/amp-analytics/#dynamically-rewrite-a-configuration)), each with 10 `triggers` defined at …
> Batch amp-analytics events

- includes/class-analytics.php
- includes/class-newspack.php
- includes/class-patches.php
- includes/scheduled-post-checker/scheduled-post-checker.php
> Alpha release May 04

- assets/wizards/setup/views/welcome/index.js
- assets/wizards/site-design/views/main/index.js
- includes/class-profile.php
- includes/configuration_managers/class-newspack-newsletters-configuration-manager.php
- includes/wizards/class-setup-wizard.php
Some onboarding enhancements & bugfixes.
Closes #876.
1. Services step issue
1. Using `master`, trigger the onboarding on a new site. Observe that in the Services step, "Newsletters" is toggled on by default 
2. Switch to this branch, observe it's not - all services should be off by default
1. Observe #876 not reproducible anymore
1. Social links menu creation
1. Create a menu and assign to "Social Links Menu" in the Customizer
5. Complete the Settings step of the onboarding, inserting values in the social accounts inputs
6. Observe the original social menu is not overwrittern
7. Remove the social menu (in Customizer, changes have to be publisher after removing a menu)
8. Complete the Settings step again, observe a new menu is created and assigner to the "Social Links Menu" position
9. …
> Onboarding enhancements

- assets/wizards/setup/views/welcome/index.js
- assets/wizards/site-design/views/main/index.js
- includes/class-analytics.php
- includes/class-newspack.php
- includes/class-patches.php
- includes/class-profile.php
- includes/configuration_managers/class-newspack-newsletters-configuration-manager.php
- includes/scheduled-post-checker/scheduled-post-checker.php
- includes/wizards/class-setup-wizard.php
> Release May 04

- includes/popups-analytics/class-popups-analytics-utils.php
- tests/unit-tests/popups-analytics.php
> Alpha release May 07

- includes/popups-analytics/class-popups-analytics-utils.php
- tests/unit-tests/popups-analytics.php
A new release to fix an error with campaigns analytics display.
> Hotfix release May 07

- includes/class-patches.php
> Alpha release May 13

- includes/class-patches.php
> Release May 13

- assets/components/src/button-card/index.js
- assets/components/src/button-card/style.scss
- assets/components/src/card/style.scss
- assets/components/src/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/dashboard/index.js
- assets/wizards/dashboard/style.scss
- assets/wizards/dashboard/views/dashboardCard.js
This PR adds a brand new component: `ButtonCard` to be used in the Dashboard and the Onboarding (for the upcoming migration step).
2. Check the components demo
3. Check the dashboard
> Add new ButtonCard component

- assets/components/package.json
- assets/components/src/autocomplete-tokenfield/index.js
- assets/components/src/autocomplete-with-suggestions/index.js
- assets/components/src/autocomplete-with-suggestions/style.scss
- assets/components/src/button-card/index.js
- assets/components/src/button-card/style.scss
- assets/components/src/card/style.scss
- assets/components/src/index.js
- assets/components/src/progress-bar/index.js
- assets/components/src/progress-bar/style.scss
- assets/components/src/with-wizard/style.scss
- assets/wizards/componentsDemo/index.js
- assets/wizards/dashboard/index.js
- assets/wizards/dashboard/style.scss
- assets/wizards/dashboard/views/dashboardCard.js
- includes/class-plugin-manager.php
- includes/wizards/class-components-demo.php
- includes/wizards/class-support-wizard.php
> Alpha release May 18

- assets/components/package.json
- assets/components/src/autocomplete-tokenfield/index.js
- assets/components/src/autocomplete-with-suggestions/index.js
- assets/components/src/autocomplete-with-suggestions/style.scss
- assets/components/src/button-card/index.js
- assets/components/src/button-card/style.scss
- assets/components/src/card/style.scss
- assets/components/src/index.js
- assets/components/src/progress-bar/index.js
- assets/components/src/progress-bar/style.scss
- assets/components/src/with-wizard/style.scss
- assets/wizards/componentsDemo/index.js
- assets/wizards/dashboard/index.js
- assets/wizards/dashboard/style.scss
- assets/wizards/dashboard/views/dashboardCard.js
- includes/class-plugin-manager.php
- includes/wizards/class-components-demo.php
- includes/wizards/class-support-wizard.php
> Release May 18

- assets/wizards/popups/views/analytics/Filters.js
- languages/newspack-plugin.pot
Update "Campaigns" to "Prompts".
> feat: update campaigns wording

- assets/wizards/popups/views/analytics/Filters.js
- languages/newspack-plugin.pot
> Alpha release Jun 08

- assets/wizards/popups/views/analytics/Chart.js
- assets/wizards/popups/views/analytics/Filters.js
- assets/wizards/popups/views/analytics/style.scss
Small visual update to the Campaigns' Analytics wizard.
* Use Newspack's `SelectControl` instead of WordPress's.
* Updated colours and margins
2. Navigate to Campaigns > Analytics
> Campaign Analytics update design

- assets/components/src/popover/style.scss
- assets/wizards/popups/components/prompt-popovers/primary.js
- assets/wizards/popups/index.js
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-popups-wizard.php
Closes https://github.com/Automattic/newspack-popups/issues/554.
Follow instructions in https://github.com/Automattic/newspack-popups/pull/558.
> feat: duplicate a prompt

- assets/components/src/action-card/index.js
Bugfix.
1. On `master`, visit the Analytics wizard, Custom Events view
2. Observe a blank screen and error logged in JS console
3. Switch to this branch, rebuild. Observe wizard screen loading
> fix: handle no description in action card component

- assets/components/src/button/style.scss
- assets/wizards/popups/components/segment-group/icons.js
- assets/wizards/popups/components/segment-group/index.js
- includes/class-plugin-manager.php
> Alpha release Jun 22

- assets/components/src/button/style.scss
- assets/wizards/popups/components/segment-group/icons.js
- assets/wizards/popups/components/segment-group/index.js
- includes/class-plugin-manager.php
> Release Jun 22

- includes/class-donations.php
- includes/class-patches.php
> Alpha release Jun 29

- includes/class-donations.php
- includes/class-patches.php
> Release Jun 29

- assets/components/src/notice/style.scss
- assets/wizards/popups/components/prompt-action-card/index.js
- assets/wizards/popups/components/prompt-popovers/primary.js
- assets/wizards/popups/index.js
- assets/wizards/popups/views/campaigns/index.js
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-popups-wizard.php
> Alpha release Jun 30

- assets/components/src/notice/style.scss
- assets/wizards/popups/components/prompt-action-card/index.js
- assets/wizards/popups/components/prompt-popovers/primary.js
- assets/wizards/popups/index.js
- assets/wizards/popups/views/campaigns/index.js
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-popups-wizard.php
> Release Jun 30

- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/placements/index.js
- includes/wizards/class-advertising-wizard.php
Removed unused global ad placements.
1. Visit the Ads Wizard, Global Settings tab
2. Observe there are no "Search Results" and "Archives" ad placements
> feat: remove unused global ad placements

- assets/components/src/card/style.scss
- assets/components/src/handoff/index.js
- assets/components/src/modal/style.scss
- assets/components/src/with-wizard/index.js
- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/placements/index.js
- assets/wizards/analytics/views/custom-events/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/popups/components/prompt-action-card/index.js
- assets/wizards/popups/components/segment-group/index.js
- assets/wizards/popups/components/segment-group/style.scss
- assets/wizards/popups/views/campaigns/index.js
- assets/wizards/popups/views/campaigns/style.scss
- assets/wizards/popups/views/segments/style.scss
- includes/class-patches.php
- includes/oauth/class-google-oauth.php
- includes/wizards/class-advertising-wizard.php
- includes/wizards/class-analytics-wizard.php
> Alpha release Jul 06

- assets/components/src/card/style.scss
- assets/components/src/handoff/index.js
- assets/components/src/modal/style.scss
- assets/components/src/with-wizard/index.js
- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/placements/index.js
- assets/wizards/analytics/views/custom-events/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/popups/components/prompt-action-card/index.js
- assets/wizards/popups/components/segment-group/index.js
- assets/wizards/popups/components/segment-group/style.scss
- assets/wizards/popups/views/campaigns/index.js
- assets/wizards/popups/views/campaigns/style.scss
- assets/wizards/popups/views/segments/style.scss
- includes/class-patches.php
- includes/class-plugin-manager.php
- includes/oauth/class-google-oauth.php
- includes/wizards/class-advertising-wizard.php
- includes/wizards/class-analytics-wizard.php
> Release Jul 06

- assets/wizards/syndication/views/intro/index.js
> Alpha release Jul 13

- assets/wizards/syndication/views/intro/index.js
> Release Jul 13

- assets/wizards/site-design/index.js
Tiny bug.
1. On `master`, visit the Site Design wizard. Go to Settings tab and observe that they are not updateable
2. Switch to this branch, rebuild, observe the settings updateable
> fix(design-wizard): correct path to update theme mods

- assets/components/src/autocomplete-tokenfield/style.scss
- assets/components/src/autocomplete-with-suggestions/style.scss
Design tweaks to the component
1. Check the Components Demo
3. Refresh
4. You can also manually import the new style to the editor to check the component in real action
> Update style of the autocomplete with suggestions component

- assets/wizards/readerRevenue/index.js
- assets/wizards/readerRevenue/views/donation/index.js
- includes/class-donations.php
- includes/class-nrh.php
- includes/wizards/class-reader-revenue-wizard.php
> Alpha release Jul 19

- includes/class-donations.php
Closes #967.
1. Ensure your Reader Revenue platform is Newspack
2. Ensure your WC checkout page has AMP **enabled** in the editor sidebar
2. Try to make a donation, observe the "Payment Info" section not interactive
3. Switch to this branch, observe the "Payment Info" section is interactive
> feat(amp): skip AMP on WC pages

- includes/class-starter-content.php
Closes #682.
1. Install Newspack on a new site
2. Observe the new posts have primary category set
> feat(starter-content): set primary category on posts

- assets/wizards/setup/views/welcome/index.js
- includes/wizards/class-setup-wizard.php
Closes #186, and improves the speed of the initial checks in the Setup Wizard by moving plugin checks wholly to the backend.
1. Try to install Newspack on a non-HTTPS site (or change the [value of `is_ssl`](https://github.com/Automattic/newspack-plugin/blob/681a0e419e7ff7a670bb758f84bc5fbec6f84ad1/includes/wizards/class-setup-wizard.php#L214) manually)
2. Observe that on launching Setup Wizard, the "Get Started" button will be disabled, and an error notice displayed
3. Observe that installing Newspack on a HTTPS site works fine
> feat(setup-wizard): prevent installation on non-HTTPS sites

- assets/wizards/popups/components/prompt-action-card/index.js
- assets/wizards/popups/components/prompt-action-card/style.scss
This PR slightly changes the style of the Analytics data within the Action Card
1. Go to Newspack > Campaigns
2. Notice the style of the data
3. Switch to this branch then refresh screen
4. New style should be visible, more inline with the rest of the page
> Update campaigns action card style for analytics data

- assets/components/src/select-control/index.js
- assets/components/src/select-control/style.scss
- assets/components/src/text-control/index.js
- assets/components/src/text-control/style.scss
- assets/wizards/componentsDemo/index.js
- assets/wizards/engagement/views/newsletters/index.js
- assets/wizards/handoff-banner/style.scss
- assets/wizards/popups/components/prompt-action-card/index.js
- assets/wizards/popups/components/prompt-action-card/style.scss
- assets/wizards/popups/components/prompt-popovers/primary.js
- assets/wizards/popups/index.js
- assets/wizards/popups/utils.js
- assets/wizards/popups/views/analytics/Info.js
- assets/wizards/popups/views/campaigns/index.js
- assets/wizards/readerRevenue/views/stripe-setup/index.js
- assets/wizards/setup/views/welcome/index.js
- includes/class-donations.php
- includes/class-starter-content.php
- includes/class-stripe-connection.php
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/popups-analytics/class-popups-analytics-utils.php
- includes/wizards/class-popups-wizard.php
- includes/wizards/class-setup-wizard.php
- tests/unit-tests/popups-analytics.php
> Release Jul 27

- includes/class-stripe-connection.php
> Release July 27 (2)

- assets/wizards/readerRevenue/views/donation/index.js
Closes #457.
1. Visit the Reader Revenue wizard
2. Observe clearer messaging of the tiers settings
> feat(reader-revenue-wizard): clarify donation tiers description

- includes/popups-analytics/class-popups-analytics-utils.php
- includes/wizards/class-analytics-wizard.php
> Alpha release Aug 04

- assets/components/src/custom-select-control/style.scss
- assets/wizards/popups/views/analytics/Filters.js
- assets/wizards/popups/views/analytics/style.scss
- assets/wizards/popups/views/campaigns/style.scss
* Update button so it looks similar to the dropdown in Campaigns
* Reduce height of the 2 filters (prompts/events) to match the height of the button
* Increase chevron width and adjust paddings to match `SelectControl`
1. Navigate to Campaigns > Analytics
3. Refresh
> Update campaigns analytics style

- assets/components/src/custom-select-control/style.scss
- assets/wizards/popups/views/analytics/Filters.js
- assets/wizards/popups/views/analytics/style.scss
- assets/wizards/popups/views/campaigns/style.scss
> Alpha release Aug 10

- assets/components/src/custom-select-control/style.scss
- assets/wizards/popups/views/analytics/Filters.js
- assets/wizards/popups/views/analytics/style.scss
- assets/wizards/popups/views/campaigns/style.scss
> Release Aug 10

- assets/wizards/handoff-banner/style.scss
- includes/class-handoff-banner.php
- includes/class-nrh.php
- includes/class-stripe-connection.php
- includes/wizards/class-engagement-wizard.php
> Alpha release Aug 17

- assets/wizards/handoff-banner/style.scss
- includes/class-handoff-banner.php
- includes/class-nrh.php
- includes/class-pwa.php
- includes/class-stripe-connection.php
- includes/wizards/class-engagement-wizard.php
> Release Aug 17

- assets/wizards/engagement/views/newsletters/index.js
- assets/wizards/readerRevenue/views/stripe-setup/index.js
- assets/wizards/readerRevenue/views/stripe-setup/newsletter-settings.js
- includes/class-stripe-connection.php
- includes/configuration_managers/class-newspack-newsletters-configuration-manager.php
- includes/wizards/class-engagement-wizard.php
- includes/wizards/class-reader-revenue-wizard.php
> Alpha release Aug 31

- assets/wizards/engagement/views/newsletters/index.js
- assets/wizards/readerRevenue/views/stripe-setup/index.js
- assets/wizards/readerRevenue/views/stripe-setup/newsletter-settings.js
- includes/class-stripe-connection.php
- includes/configuration_managers/class-newspack-newsletters-configuration-manager.php
- includes/wizards/class-engagement-wizard.php
- includes/wizards/class-reader-revenue-wizard.php
> Release Aug 31

- includes/class-stripe-connection.php
When a Stripe webhook comes in, the data sent to Campaigns plugin should also contain the subscription status.
Note: to test locally, you might have to bypass SSL check for the Campaigns API:
```php
add_filter('http_request_args', function($r) {
$r['sslverify'] = false;
return $r;
});
```
1. Create two Campaings segments, targeting donors and subscribers 
2. Create two prompts, set to each segment
3. Configure Reader Revenue to use Stripe as platform, and use AMP Plus mode (`define( 'NEWSPACK_AMP_PLUS_ENABLED', true );`)
4. Configure Newsletters plugin with either Mailchimp or Campaign Monitor as the ESP
5. Choose a list to allow the donors to subscribe to in Reader Revenue wizard
3. Add a Donate block somewhere
4. Ensure the site will receive Stripe webhooks (use `ngrok` or test on a …
> feat(stripe): handle subscriber status in campaigns data update

- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/ad-units/index.js
- assets/wizards/popups/components/prompt-popovers/primary.js
- includes/class-newspack.php
- includes/class-stripe-connection.php
- includes/wizards/class-advertising-wizard.php
> Alpha release Sep 07

- assets/wizards/readerRevenue/views/stripe-setup/index.js
- includes/class-stripe-connection.php
- includes/wizards/class-reader-revenue-wizard.php
Early release to test stripe error handling.
> Alpha release Sep 13

- assets/wizards/readerRevenue/views/stripe-setup/index.js
- includes/class-stripe-connection.php
- includes/wizards/class-reader-revenue-wizard.php
> Release Sep 14

- includes/wizards/class-advertising-wizard.php
Closes #1112.
Edit the suppression settings in Ads wizard, observe all settings can be edited & saved
> feat(ads-wizard): sanitize ads suppression config

- assets/wizards/advertising/index.js
- assets/wizards/advertising/style.scss
- assets/wizards/advertising/views/ad-units/index.js
- assets/wizards/advertising/views/services/index.js
- includes/configuration_managers/class-newspack-ads-configuration-manager.php
- includes/wizards/class-advertising-wizard.php
Improves notices for Ads GAM integration and adds custom targeting keys update.
Testing instructions are over at https://github.com/Automattic/newspack-ads/pull/172.
> Feat: Ads GAM custom targeting keys integration

- assets/wizards/advertising/index.js
- assets/wizards/advertising/style.scss
- assets/wizards/advertising/views/ad-unit/index.js
- assets/wizards/advertising/views/ad-units/index.js
- assets/wizards/advertising/views/services/index.js
- includes/configuration_managers/class-newspack-ads-configuration-manager.php
- includes/wizards/class-advertising-wizard.php
Allow the user to upload Service Account credentials to connect GAM to Newspack Ads.
Checkout this branch and run `npm run build`. Instructions continue at https://github.com/Automattic/newspack-ads/pull/181
> feat(ads): gam service account credentials upload

- assets/components/src/with-wizard-screen/index.js
> Alpha release Sep 28

- assets/components/src/with-wizard-screen/index.js
- assets/wizards/engagement/views/commenting/index.js
- assets/wizards/health-check/index.js
- assets/wizards/health-check/views/configuration/index.js
- includes/class-plugin-manager.php
- includes/configuration_managers/class-amp-configuration-manager.php
> Release Sep 28

- assets/components/src/action-card/index.js
- assets/components/src/action-card/style.scss
- assets/components/src/footer/index.js
- assets/components/src/waiting/index.js
- assets/components/src/waiting/style.scss
- assets/components/src/with-wizard-screen/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/connections/index.js
- assets/wizards/connections/views/index.js
- assets/wizards/connections/views/main/google.js
- assets/wizards/connections/views/main/index.js
- assets/wizards/connections/views/main/wpcom.js
- assets/wizards/dashboard/index.js
- assets/wizards/dashboard/views/dashboardCard.js
- assets/wizards/support/components/withWPCOMAuth.js
- assets/wizards/support/index.js
- assets/wizards/support/views/create-ticket/index.js
- includes/class-newspack.php
- includes/class-wizards.php
- includes/oauth/class-google-oauth.php
- includes/wizards/class-connections-wizard.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-support-wizard.php
- includes/wizards/class-wizard.php
- tests/unit-tests/oauth.php
> Alpha release Sep 30

- assets/components/src/action-card/index.js
- assets/components/src/action-card/style.scss
- assets/components/src/footer/index.js
- assets/components/src/waiting/index.js
- assets/components/src/waiting/style.scss
- assets/components/src/with-wizard-screen/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/connections/index.js
- assets/wizards/connections/views/index.js
- assets/wizards/connections/views/main/google.js
- assets/wizards/connections/views/main/index.js
- assets/wizards/connections/views/main/wpcom.js
- assets/wizards/dashboard/index.js
- assets/wizards/dashboard/views/dashboardCard.js
- assets/wizards/support/components/withWPCOMAuth.js
- assets/wizards/support/index.js
- assets/wizards/support/views/create-ticket/index.js
- includes/class-newspack.php
- includes/class-wizards.php
- includes/oauth/class-google-oauth.php
- includes/wizards/class-connections-wizard.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-support-wizard.php
- includes/wizards/class-wizard.php
- tests/unit-tests/oauth.php
> Release Sep 30

- assets/components/src/footer/index.js
- assets/components/src/footer/style.scss
- assets/components/src/index.js
- assets/components/src/newspack-icon/index.js
- assets/components/src/newspack-icon/style.scss
- assets/components/src/patrons-logo/index.js
- assets/components/src/tabbed-navigation/style.scss
- assets/components/src/with-wizard-screen/index.js
- assets/components/src/with-wizard-screen/style.scss
- assets/components/src/with-wizard/index.js
- assets/components/src/with-wizard/style.scss
- assets/components/src/wizard-pagination/index.js
- assets/components/src/wizard-pagination/style.scss
- assets/wizards/componentsDemo/index.js
- assets/wizards/dashboard/index.js
- assets/wizards/popups/views/segments/SingleSegment.js
- assets/wizards/setup/style.scss
- package-lock.json
> Alpha release Oct 05

- assets/components/src/button/style.scss
- assets/wizards/advertising/style.scss
- assets/wizards/advertising/views/ad-units/index.js
* Adjust network code section
* Add chevron to `ButtonCard`
* Update `is-destructive` button
1. Navigate to Advertising > GAM
3. Remove creds and reconnect
> Update GAM wizard design

- assets/components/src/button/style.scss
- assets/components/src/footer/index.js
- assets/components/src/footer/style.scss
- assets/components/src/index.js
- assets/components/src/newspack-icon/index.js
- assets/components/src/newspack-icon/style.scss
- assets/components/src/patrons-logo/index.js
- assets/components/src/tabbed-navigation/style.scss
- assets/components/src/with-wizard-screen/index.js
- assets/components/src/with-wizard-screen/style.scss
- assets/components/src/with-wizard/index.js
- assets/components/src/with-wizard/style.scss
- assets/components/src/wizard-pagination/index.js
- assets/components/src/wizard-pagination/style.scss
- assets/wizards/advertising/style.scss
- assets/wizards/advertising/views/ad-units/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/dashboard/index.js
- assets/wizards/popups/views/segments/SingleSegment.js
- assets/wizards/setup/style.scss
- package-lock.json
> Release Oct 05

- includes/class-analytics.php
- includes/configuration_managers/class-configuration-managers.php
- includes/configuration_managers/class-parsely-configuration-manager.php
> Alpha release Nov 02

- assets/components/src/category-autocomplete/style.scss
- assets/components/src/grid/index.js
- assets/components/src/grid/style.scss
- assets/wizards/advertising/views/suppression/index.js
Use Grid and SectionHeader rather than a Card to display the various options
1. Go to Advertising > Suppression
3. Refresh page and test if the options are still working
> Update ad suppression layout

- assets/components/package.json
> Alpha release Nov 18

- assets/components/src/button/style.scss
- assets/wizards/connections/views/main/mailchimp.js
* Destructive link had a grey background on hover
* Update the API link to correct documentation and standardise it for logged in/out users
1. Go to Newspack > Connections
2. Check the Mailchimp connect/disconnect
4. Refresh page and test again
> Fix Mailchimp connection destructive link and update external link

- composer.lock
Updates composer lockfile, I've merged https://github.com/Automattic/newspack-plugin/pull/1246 too hastily.
Observe composer packages install nicely (`composer install`)
> chore: update composer lockfile

- assets/components/src/action-card/style.scss
- assets/components/src/button-card/style.scss
- assets/components/src/style-card/index.js
- assets/components/src/style-card/style.scss
- assets/wizards/engagement/views/newsletters/index.js
- assets/wizards/readerRevenue/views/stripe-setup/index.js
- assets/wizards/setup/index.js
- assets/wizards/setup/style.scss
- assets/wizards/setup/views/integrations/index.js
- assets/wizards/setup/views/services/index.js
- assets/wizards/setup/views/settings/index.js
- assets/wizards/site-design/views/main/index.js
- assets/wizards/site-design/views/main/style.scss
See https://github.com/Automattic/newspack-plugin/pull/1257 and https://github.com/Automattic/newspack-plugin/pull/1269
2. Test the Setup Wizard
> Update various elements of the onboarding wizard

- assets/components/src/plugin-settings/SettingsSection.js
> Alpha release Dec 01

- CHANGELOG.md
- assets/components/src/plugin-settings/SettingsSection.js
- newspack.php
- package-lock.json
- package.json
> Release Dec 01

- assets/wizards/connections/views/main/fivetran.js
- assets/wizards/connections/views/main/google.js
- assets/wizards/connections/views/main/index.js
- assets/wizards/connections/views/main/wpcom.js
- includes/class-newspack.php
- includes/oauth/class-fivetran-connection.php
- includes/oauth/class-google-oauth.php
- includes/oauth/class-oauth.php
- includes/wizards/class-connections-wizard.php
- tests/class-newspack-unit-tests-bootstrap.php
- tests/unit-tests/oauth.php
Changes how the Google OAuth and Fivetran proxies authenticate. Not by passing a WPCOM token anymore, but with an API key.
Note that this requires corresponding changes in the proxies.
1. Ensure you have the option* set to the correct value
2. Observe the Google and Fivetran connections working as expected
3. Remove the option, observe the aforementioned connections are not available in the Connections wizard
4. Change the option value to an invalid one, observe the proxies return error and disallow connection
5. Disconnect WPCOM. Observe the other services can be connected regardless of WPCOM connection status
\* Name is defined in another part of the software, as `NEWSPACK_MANAGER_API_KEY_OPTION_NAME` env variable
---
- To see the specific tasks where the Asana app for GitHub is being …
> feat: use newspack manager plugin for authentication

- assets/components/src/settings/SettingsCard.js
- assets/components/src/settings/style.scss
- assets/wizards/popups/views/segments/SingleSegment.js
- assets/wizards/popups/views/segments/style.scss
This PR slightly tweaks the overall look of the "Add New Segment" screen
* Move buttons-card to the bottom
* Change title input to full-width
* Add noBorder prop to settings-card
1. Go to Campaigns > Segments
2. Add New Segment
4. Refresh
> Reorganise Add New Segment wizard 

- assets/components/src/plugin-settings/SettingsSection.js
- assets/components/src/plugin-settings/style.scss
- assets/wizards/advertising/components/placement-control/index.js
- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/placements/index.js
> Alpha release Dec 10

- assets/components/src/category-autocomplete/index.js
- assets/wizards/engagement/views/newsletters/index.js
- includes/wizards/class-setup-wizard.php
Closes #1126
Closes #1148
Closes https://github.com/Automattic/newspack-newsletters/issues/645
1. On `master`, observe #1126 and another bug: when a campaign, tag, or category is assigned in the prompt edit modal, it still does show up in the autocomplete suggestions
2. Switch to this branch, observe that both bugs are fixed
3. Observe that during onboarding (Setup wizard), the footer copyright is not set to site tagline (as the default) (#1148)
> assorted bugfixes

- CHANGELOG.md
- assets/components/src/plugin-settings/SettingsSection.js
- assets/components/src/plugin-settings/index.js
- newspack.php
- package-lock.json
- package.json
> hotfix: settings section hooks

- assets/components/src/wizard/store/utils.js
- assets/wizards/engagement/views/newsletters/index.js
- assets/wizards/readerRevenue/index.js
- assets/wizards/readerRevenue/views/donation/index.js
- assets/wizards/readerRevenue/views/location-setup/index.js
- assets/wizards/readerRevenue/views/nrh-settings/index.js
- assets/wizards/readerRevenue/views/platform/index.js
- assets/wizards/readerRevenue/views/salesforce/index.js
- assets/wizards/readerRevenue/views/stripe-setup/index.js
- assets/wizards/setup/views/services/ReaderRevenue.js
- assets/wizards/setup/views/services/index.js
- includes/configuration_managers/class-woocommerce-configuration-manager.php
- includes/wizards/class-setup-wizard.php
Fixes a Setup wizard issue.
Also updates the useWizardData hook, so it can use multiple wizards. Before, the hook was using the Reader Revenue wizard data only.
1. On `master`, visit the Setup wizard, "Services" step
2. Enable "Reader Revenue" and set some donation values (e.g. suggested donation amount)
3. Save by navigating to the next setup step
4. Open the Reader Revenue wizard and observe that the inserted values have not been updated
5. Switch to this branch, redo steps 2 & 3, observe the updated values in Reader Revenue wizard
---
- https://app.asana.com/0/0/1201745193114476
> fix(setup-wizard): donation data

- includes/class-starter-content.php
- includes/wizards/class-setup-wizard.php
Slight adjustments for [end-to-end testing](https://github.com/Automattic/newspack-e2e-tests).
> test(e2e): update env var name; skip SSL check in E2E tests

- includes/reader-revenue/class-stripe-connection.php
Fixes a bug introduced in #1483 (not yet released).
1. On `master`, delete the `woocommerce_currency` and `newspack_stripe_data` options
2. Load the Reader Revenue Wizard, "Donations" tab
3. Observe the "Suggested donations" are missing the currency symbol
4. Switch to this branch, observe the currency is `$`
> fix: stripe data setting

- assets/wizards/advertising/components/placement-control/index.js
- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/placements/index.js
Implements providers for the placement control.
Instructions at https://github.com/Automattic/newspack-ads/pull/313
> feat(ads): placement providers

- composer.lock
- includes/class-plugin-manager.php
- package-lock.json
- package.json
> Alpha release Apr 04

- includes/class-donations.php
- includes/class-newspack.php
- includes/reader-revenue/class-stripe-connection.php
- includes/reader-revenue/class-woocommerce-connection.php
Adds WC synchronisation to Stripe donations processing.
1. Set up the site to use the streamlined Donate block – turn on AMP Plus* and choose "Stripe" as platform in Reader Revenue wizard
2. Ensure your site can ingest Stripe webhooks – it has to be publicly available and webhook has to be active
3. Activate WooCommerce and WooCommerce Stripe Gateway plugins
4. Make a donation using the Donate block
5. Observe an order is created in WC "Orders" view, 
- with an order note saying what kind of donation is it
- if opted in to newsletter, another order note should state it
- there should be a link to payment in Stripe dashboard, below "Order … details" header
7. Try with a few different options and observe that the order data checks out:
1. with/without newsletter opt-in
2. with/without …
> feat(stripe-donations): update WooCommerce on successful donation

- includes/starter_content/class-starter-content-generated.php
Closes #514
Generate starter content, observe the posts have excerpts & subtitles assigned.
> feat(starter-content): add excerpt & subtitle

- includes/reader-revenue/class-woocommerce-connection.php
> Alpha release May 05

- composer.lock
- includes/wizards/class-advertising-wizard.php
- package-lock.json
- package.json
> Alpha release May 17

- CHANGELOG.md
- composer.lock
- includes/reader-revenue/class-woocommerce-connection.php
- includes/wizards/class-advertising-wizard.php
- newspack.php
- package-lock.json
- package.json
> Release May 17

- assets/wizards/popups/utils.js
https://github.com/Automattic/newspack-popups/pull/866 removes readers' ability to dismiss prompts, so this small change renames the "Until dismissed" option to "Every page view."
In the Campaigns wizard UI, open the settings modal for a prompt and confirm the new label under Frequency Settings.
> refactor: rename "until dismissed" option based on removal of permanent suppression

- CHANGELOG.md
- assets/wizards/popups/utils.js
- newspack.php
- package-lock.json
- package.json
> Release May 30

- includes/class-analytics.php
_Note: supersedes #1725._
Reporting of Google Analytics events in non-AMP environments has an async problem. When reporting events that are triggered by an action that causes a server refresh (either refreshing the current page or navigating to a new page or site, such as a form submission or link click), most browsers will stop execution of JS on the current page as soon as it unloads. This creates a race condition where any async calls to `gtag` for reporting events at the same time a server refresh happens may not complete the page unloads. When the page unloads before the request to report the event completes, the event is not reported. This can result in artificially low metrics for these events.
This can be mitigated by telling Analytics to use …
> fix: set HTTPS transport mode to "beacon" for non-AMP GA

- includes/class-nrh.php
Closes #1650
Observe #1650 is not reproducible
> fix(donations): numbers formatting if NRH is the platform

- includes/reader-revenue/class-woocommerce-connection.php
Closes #1700.
1. Make a donation using Stripe platform, when WC plugin is active
2. Observe no PHP logs about incorrect use of WC meta methods are logged
> chore(wc): use proper metadata setters

- assets/components/src/button/index.js
- assets/components/src/section-header/index.js
- assets/wizards/readerRevenue/components/money-input/index.js
- assets/wizards/readerRevenue/components/money-input/style.scss
- assets/wizards/readerRevenue/views/donation/index.js
- assets/wizards/readerRevenue/views/donation/index.tsx
- includes/class-donations.php
- includes/class-nrh.php
- includes/wizards/class-reader-revenue-wizard.php
- tests/unit-tests/donations.php
- Adds the ability to customise each default donation amount, as well as toggle default donation frequencies
- Centralises the donations settings – before the settings were stored as product meta when WC was used as platform
- Removes cross-domain tracking for NRH platform (https://github.com/Automattic/newspack-plugin/pull/810), since it requires a full rewrite of the Donate block
Closes https://github.com/Automattic/newspack-blocks/issues/741
1. On `master`, edit the Donations settings in Reader Revenue wizard and take note of these settings 
2. Insert a couple of Donate blocks – 
- default
- manual mode – changing the donation amounts
- manual mode – changing if tiered  
3. Switch to this branch, observe the blocks render as before
4. Make a donation to verify it works as before 
5. …
> Donations – amounts and frequencies customisation

- assets/components/src/button/index.js
- assets/wizards/readerRevenue/views/donation/index.tsx
Fixed an unreleased bug on `master`.
1. On `master`, visit the last step of the Setup wizard (`/wp-admin/admin.php?page=newspack-setup-wizard#/completed`) and click the "Go to the Dashboard" link
2. Observe JS errors logged and blank screen
3. Switch to this branch, observe the link redirects to the dashboard
> fix: linking buttons

- includes/class-reader-activation.php
Fixes a bug with email to username conversion.
1. On `master`, register a reader with a `+` in email address (`something+test@mail.com`)
2. Observe the registration failing on username validation
3. Switch to this branch, observe the registration succeeding
> fix: email to username handling

- assets/blocks/reader-registration/style.scss
Fits the column layout of Registration block in a prompt. 
1. On `master`, put a Registration block set to column layout in an overlay prompt
2. Observe that the column layout does not kick in, because there's just baaaarely too little space in a prompt (784px wide by default) for the columns not to stack
3. Switch to this branch, observe column layout visible
> feat: tweak registration block styling

- includes/class-logger.php
_Follow instructions in https://github.com/Automattic/newspack-newsletters/pull/899_
> chore: logger update

- includes/plugins/class-newspack-newsletters.php
- includes/reader-revenue/my-account/class-woocommerce-my-account.php
Handling WC legacy data, and smaller tweaks.
1. On a site with Reader Activation configured, register as a new reader and navigate to "My Account" page
2. Observe there are no payment-related items in the page nav
3. Make a donation via the streamlined Donate block, there should be the additional "Billing" nav item
4. Create a manual order on the backend and assign it to the logged-in user. Observe the "Orders" item is now in the nav
5. Create a subscription manually via the backend, and observe the "Subscriptions" item now in the nav
> My Account – handle legacy data

- assets/reader-activation/auth.js
Implements a more optimistic experience for the header account link. If the reader is pre-authenticated it shows "Account" instead of "Sign In", just like an authenticated reader. Once you click on Account, you're prompted to sign in with a pre-filled email.
A successful authentication in this case redirects the reader to the account page, as it's expected by clicking on a link labeled "Account".
There's also a small tweak to not `endLoginFlow()` on `finally()` and use `catch()` instead, to not duplicate the action that is already fired at `.then()`.
1. With an existing reader account, make sure you have a password set
2. While logged out, use a registration block to pre-authenticate to this account 
3. Observe the header nav changed to "Account"
4. Click and confirm you see the "Sign In" …
> feat(reader-activation): optimistic account link

- includes/plugins/class-newspack-newsletters.php
Details and instructions at https://github.com/Automattic/newspack-newsletters/pull/914
> fix(newsletters): use international date format

- includes/plugins/class-newspack-newsletters.php
Fixes a regression introduced in https://github.com/Automattic/newspack-plugin/pull/1840
2. Register as a new reader or use an existing account
3. Trigger any update to AC data (e.g. by making a donation), observe the signup page and registration date are overwritten 
4. Switch to this branch, observe these metadata are not overwritten
> fix(active-campaign): legacy contacts detection

- assets/blocks/reader-registration/index.php
- assets/blocks/reader-registration/style.scss
- assets/reader-activation/auth.scss
- includes/class-reader-activation.php
This PR tweaks the design a little bit. Mainly the typography/vertical rhythm to follow an 8px baseline. There's probably more to tweak but this is a first pass 🙂
I also moved the text for the magic link sign up, hopefully it'll be sufficient to fix https://app.asana.com/0/1202719992789620/1202723823068199/f
1. Test the front-end
3. Re-test
> Update reader registration design

- CHANGELOG.md
- assets/blocks/reader-registration/index.php
- assets/blocks/reader-registration/style.scss
- assets/blocks/reader-registration/view.js
- assets/reader-activation/auth.js
- assets/reader-activation/auth.scss
- assets/reader-activation/index.js
- assets/wizards/readerRevenue/views/stripe-setup/index.js
- includes/class-magic-link.php
- includes/class-reader-activation.php
- includes/oauth/class-google-login.php
- includes/oauth/class-google-services-connection.php
- includes/oauth/class-oauth.php
- includes/reader-revenue/class-stripe-connection.php
- includes/reader-revenue/my-account/class-woocommerce-my-account.php
- includes/reader-revenue/templates/myaccount-edit-account.php
- includes/reader-revenue/templates/myaccount-verify.php
- includes/wizards/class-reader-revenue-wizard.php
- newspack.php
- package-lock.json
- package.json
- tests/unit-tests/reader-activation.php
> Alpha release Aug 12

- includes/class-plugin-manager.php
Adds I13 Web Solution's premium reCaptcha for WooCommerce plugin to the Newspack plugin manager:
```
'recaptcha-for-woocommerce'     => [
'Name'        => esc_html__( 'reCaptcha for WooCommerce', 'newspack' ),
'Description' => esc_html__( 'Protect your eCommerce store from malicious and automated attacks by using reCaptcha for WooCommerce.', 'newspack' ),
'Author'      => esc_html__( 'I13 Web Solution', 'newspack' ),
'PluginURI'   => esc_url( 'https://woocommerce.com/products/recaptcha-for-woocommerce/' ),
'AuthorURI'   => esc_url( 'https://woocommerce.com/vendor/i13-web-solution/' ),
],
```
I opted not to link `AuthorURI` directly to the vendor's website (https://i13websolution.com/product-category/woocommerce/), because their site is outdated and does not list the reCaptcha plugin.
This …
> Adds reCaptcha for WooCommerce to plugin manager

- includes/reader-revenue/class-stripe-connection.php
- includes/reader-revenue/my-account/class-woocommerce-my-account.php
Closes #1853.
1. Start with a site with Reader Activation enabled and Stripe configured
2. Add a customer in Stripe dashboard, with an email that does not exist in the WP DB
3. Register on the site as this reader
4. Visit My Account -> Billing and observe you can access the Stripe billing portal
> feat(stripe): lookup stripe customer ID on registration

- includes/reader-revenue/my-account/style.scss
Some style tweaks to make our custom WC message styling more consistent.
1. Log into My Account and go to Newsletters. Try to submit without making any changes and observe that the error message has inconsistent margins and padding:
2. Check out this branch and repeat step 1. Confirm that the message now has better-looking spacing:
3. Visit the Account Details page and request a password reset. Confirm that the message here has the same spacing:
> style: more consistent margins and padding for custom WC message styles

- includes/reader-revenue/templates/myaccount-billing.php
Updates Billing portal link copy. It was reported that the language suggests recurring payments can be managed, meaning their frequency can be updated. 
:)
> feat: update billing portal copy

- assets/other-scripts/emails/index.js
See https://github.com/Automattic/newspack-plugin/pull/1937#discussion_r959724912
> fix(emails): editor message

- includes/plugins/class-newspack-newsletters.php
- includes/reader-activation/class-reader-activation.php
- includes/reader-revenue/class-stripe-connection.php
Adds two metadata fields to AC integration.
1. Set up Reader Activation and set ActiveCampaign as the ESP 
2. Register with Google, observe a `NP_Connected Account` field of value `google` is assigned 
3. Make a donation, and then another one as the same reader. After both verify the `NP_Total Paid` field is assigned with expected value
> AC metadata – SSO provider name; donor LTV

- includes/class-magic-link.php
Minor update to some reader-facing messaging in the event a magic link is no longer valid.
No functional changes. To test, try to follow an invalid magic link while not logged in (e.g. `https://sitedomain/?action=np_auth_link&email=email&token=invalid_token`).
> feat: update reader-facing language on auth fail

- includes/class-profile.php
Closes #1931
1. On `master`, load the Settings step of the Setup wizard (`/wp-admin/admin.php?page=newspack-setup-wizard#/settings`)
2. Note the settings and switch to this branch
3. Reload, observe the settings haven't changed
> refactor: profile fields getting

- includes/reader-revenue/templates/myaccount-billing.php
Improves the UI of the Billing section:
**Before:**
**After:**
* Make a donation in a new browser session
* Go directly to My Account
* Click "Send me a link" or "Set a new password" and complete the flow to verify
* Click the new "Billing" link in My Account
* Confirm you see the new layout
* Confirm the button works and takes you to your billing information in Stripe
> style: RAS - Improve billing template

- CHANGELOG.md
- assets/plugins-screen/plugins-screen.js
- assets/plugins-screen/plugins-screen.scss
- assets/reader-activation/auth.scss
- assets/wizards/popups/utils.js
- composer.lock
- includes/class-admin-plugins-screen.php
- includes/class-analytics.php
- includes/class-newspack.php
- includes/reader-revenue/class-stripe-connection.php
- includes/reader-revenue/class-stripe-sync.php
- includes/reader-revenue/class-woocommerce-connection.php
- includes/reader-revenue/templates/myaccount-billing.php
- includes/revisions-control/README.md
- includes/revisions-control/class-revisions-control.php
- newspack.php
- package-lock.json
- package.json
- tests/unit-tests/revisions-control.php
> Alpha release Sep 26

- assets/reader-activation/auth.scss
If you look closely, the Avatar icon isn't perfectly aligned vertically
This PR fixes it!
1. Make sure you have RAS active and visit your site without being logged in
2. Notice the misalignment (quite subtle!)
4. Refresh page
5. Test if the button still works
> fix(reader-activation): vertical alignment of the icon

- assets/wizards/advertising/components/add-ons/index.js
- includes/class-plugin-manager.php
- includes/wizards/class-advertising-wizard.php
Adds [Publisher Media Kit](https://wordpress.org/plugins/publisher-media-kit/) as an Ads add-on
Closes https://github.com/Automattic/newspack-ads/issues/466
1. Check out this branch and visit Newspack -> Advertising -> Add-Ons
2. Confirm the new add-on
3. Toggle it on and confirm the plugin is now installed
4. Click "Edit Media Kit" and confirm you're redirected to edit the draft page created by the plugin
> feat(ads): publisher media kit add-on

- assets/blocks/reader-registration/style.scss
- assets/reader-activation/auth.scss
- assets/shared/scss/_mixins.scss
> fix: "Sign In" page styles

- includes/reader-revenue/class-stripe-connection.php
#2112, #2117 and #2103 into a hotfix
> fix(stripe): invoice error handling

- .circleci/config.yml
- assets/plugins-screen/plugins-screen.js
- assets/plugins-screen/plugins-screen.scss
- assets/reader-activation/auth.js
- composer.lock
- includes/class-admin-plugins-screen.php
- includes/class-magic-link.php
- includes/reader-activation/class-reader-activation.php
- includes/reader-revenue/class-stripe-connection.php
- includes/reader-revenue/class-woocommerce-connection.php
- includes/reader-revenue/templates/myaccount-delete-account.php
- includes/reader-revenue/templates/myaccount-edit-account.php
- package-lock.json
- package.json
- tests/unit-tests/magic-link.php
> Alpha release Nov 17

- assets/wizards/setup/views/welcome/index.js
One small change:
Closes #1701
> feat(setup-wizard): disambiguate starter vs. demo content

- includes/class-analytics.php
Adds filtering of the custom dimensions' values sent to GA. 
_Follow steps in https://github.com/Automattic/newspack-popups/pull/1014_
> feat(analytics): allow adding custom dimensions' values via filter

- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/index.js
- assets/wizards/advertising/views/marketplace/index.js
Details and instructions at https://github.com/Automattic/newspack-ads/pull/566
PRs regarding this feature should always be merged to `epic/ads-marketplace`.
> feat(ads): marketplace wizard ui

- .circleci/config.yml
- CHANGELOG.md
- assets/plugins-screen/plugins-screen.js
- assets/plugins-screen/plugins-screen.scss
- composer.lock
- includes/class-admin-plugins-screen.php
- includes/reader-activation/class-reader-activation.php
- includes/reader-revenue/class-stripe-connection.php
- includes/reader-revenue/class-woocommerce-connection.php
- includes/reader-revenue/templates/myaccount-delete-account.php
- includes/reader-revenue/templates/myaccount-edit-account.php
- newspack.php
- package-lock.json
- package.json
> Release Nov 28

- composer.json
- includes/class-newspack.php
- includes/cli/class-initializer.php
- newspack.php
This reverts commit 8bd8c9b709612afc9080648ad1d248fd65fed46a that was accidentally merged into master
> Revert "remove autoloader dependency"

- CHANGELOG.md
- includes/tracking/class-meta-pixel.php
- includes/tracking/class-twitter-pixel.php
- newspack.php
- package-lock.json
- package.json
The CI task that merges a release back to the master branch is [currently broken](https://app.circleci.com/pipelines/github/Automattic/newspack-plugin/5877/workflows/93bf5921-56dc-4f8e-aac7-bbc23351ad93/jobs/27623) because of enforced branch protection rules.
This PR is for approval to satisfy the branch rule.
> Post-release merge

- assets/components/src/accordion/index.js
- assets/components/src/accordion/style.scss
- assets/components/src/card/style.scss
- assets/components/src/modal/style.scss
- assets/components/src/popover/style.scss
- assets/wizards/connections/index.js
- assets/wizards/connections/style.scss
- assets/wizards/connections/views/main/index.js
- assets/wizards/connections/views/main/webhooks.js
- includes/class-newspack.php
- includes/data-events/class-api.php
- includes/data-events/class-webhooks.php
- includes/emails/class-emails.php
- includes/reader-activation/class-reader-activation.php
- includes/wizards/class-connections-wizard.php
- tests/unit-tests/webhooks.php
> Alpha release Dec 22

- composer.lock
- includes/analytics/class-analytics-events.php
- includes/class-donations.php
- includes/class-newspack.php
- includes/class-performance.php
- includes/data-events/README.md
- includes/data-events/listeners.php
- includes/plugins/class-perfmatters.php
- includes/reader-revenue/class-woocommerce-connection.php
- includes/reader-revenue/templates/myaccount-edit-account.php
- includes/templates/reader-activation/login-form.php
- package-lock.json
- package.json
> Alpha release Jan 26

- includes/data-events/class-data-events.php
> chore(data-events): lint

- composer.json
- composer.lock
- package.json
- Removes `xwp/wp-dev-lib` dependency
- Adds PHP & JS linting of staged files
1. Reinstall git hooks by running `composer install`
1. Make linting-breaking changes to an SCSS, a JS, and a PHP file
2. Try to commit, observe it failing on the three linting errors
3. Fix the errors, commit again, observe it succeeding
> Changes to git commit hooks

- package-lock.json
- package.json
This PR resolves some conflicts between release and master.
> fix: update package.json to resolve a merge conflict with master

- includes/plugins/class-perfmatters.php
https://github.com/Automattic/newspack-plugin/pull/2271 as a hotfix, so these changes are available earlier on.
> feat(perfmatters): defaults adjustments, remove feature flag (#2271)

- assets/wizards/advertising/views/providers/index.js
- includes/wizards/class-advertising-wizard.php
Further details and instructions at https://github.com/Automattic/newspack-ads/pull/601
> fix(ads): gam api availability according to error type

- CHANGELOG.md
- includes/plugins/class-perfmatters.php
- newspack.php
- package-lock.json
- package.json
Remove some rules from the Perfmatters, which were found to be causing issues on live sites.
> hotfix (perfmatters): adjust defaults

- assets/wizards/connections/views/main/webhooks.js
Fixes layout of webhook editing UI.
1. Enable webhooks (`NEWSPACK_EXPERIMENTAL_WEBHOOKS`)
1. On `master`, visit Connections Wizard and scroll to the bottom
2. Click on "Add New Endpoint" button and observe a broken layout:
3. Switch to this branch, observe better layout:
> fix(webhooks): grid layout

- includes/class-plugin-manager.php
Adds a few plugins to the "supported plugins" list.
Install one of the plugins added in this changeset, observe that it's not marked as "unsupported" in the Health Check wizard
> feat(health-check): mark some plugins as supported

- includes/class-newspack.php
- includes/polyfills/class-amp-polyfills.php
- tests/unit-tests/amp-polyfills.php
https://github.com/Automattic/newspack-plugin/pull/2308 as a hotfix. These changes were supposed to be live now, but I've neglected to make sure they make it into the release.
> feat(amp-deprecation): polyfills for amp-img, amp-iframe, amp-fit-text, amp-youtube

- .circleci/config.yml
This is a test run. The new orb version does not have any changes.
All CI tasks should run as expected
> chore(ci): update orb version

- .circleci/config.yml
- assets/memberships-gate/editor.js
- assets/memberships-gate/editor.scss
- assets/other-scripts/lightbox/index.js
- assets/other-scripts/lightbox/style.scss
- assets/reader-activation/auth.js
- assets/reader-activation/index.js
- assets/wizards/engagement/views/reader-activation/index.js
- assets/wizards/popups/components/segment-group/index.js
- assets/wizards/popups/utils.js
- assets/wizards/popups/views/campaigns/index.js
- assets/wizards/popups/views/segments/SegmentsList.js
- assets/wizards/popups/views/segments/SingleSegment.js
- assets/wizards/popups/views/segments/SingleSegment.test.js
- composer.lock
- includes/class-newspack.php
- includes/plugins/class-wc-memberships.php
- includes/polyfills/class-amp-polyfills.php
- includes/reader-activation/class-reader-activation.php
- includes/reader-revenue/stripe/class-stripe-sync.php
- includes/wizards/class-engagement-wizard.php
- tests/unit-tests/amp-polyfills.php
- webpack.config.js
> Alpha release Mar 31

- includes/polyfills/class-amp-polyfills.php
- tests/unit-tests/amp-polyfills.php
This PR fixes the `amp-iframe` polyfill so it also properly transforms iframes with inner HTML in their markup.
Confirm new test case of nested `<amp-iframe><amp-img></amp-img></amp-iframe>` passes.
Use the below code and repeat steps from #2308 and confirm it works as described:
<details>
<summary>Click to expand code</summary>
<code>
&lt;!-- wp:html -->
&lt;h1>amp-youtube&lt;/h1>
&lt;amp-youtube data-videoid="mGENRKrdoGY" layout="responsive" width="480" height="270">&lt;/amp-youtube>
&lt;h1>amp-fit-text&lt;/h1>
&lt;amp-fit-text layout="fixed-height" min-font-size="6" max-font-size="72" height="80">&lt;h3 id="h-subscribe">Subscribe:&lt;/h3>&lt;/amp-fit-text>
&lt;h1>amp-image&lt;/h1>
&lt;amp-img width="428" height="642" layout="fixed" …
> fix(amp): improved iframe polyfill

- includes/reader-revenue/class-woocommerce-connection.php
When a subscription is cancelled via Woo Subscriptions, the cancellation isn't reflected in the connected ESP until the cancellation date occurs (at the end of the current billing cycle). This change updates the status to "cancelled" immediately when the subscription is cancelled, without waiting for the billing cycle to end.
Fixes `1204166503564710/1204251107764387`
1. On `master` on a site connected to ActiveCampaign, make a recurring donation as a reader.
2. Log into My Account and cancel the subscription.
3. Log into the connected AC account and find the synced reader's contact. Observe that the contact still appears to be an active subscriber (no `NP_Current Subscription End Date` value, and a `NP_Membership Status` of "Monthly Donor", no "ex-").
4. Check out this branch. Reactivate …
> fix: sync reader to ESP on subscription update

- assets/blocks/reader-registration/edit.js
- composer.lock
- includes/class-blocks.php
- package-lock.json
- package.json
> Alpha release Apr 13

- assets/wizards/engagement/views/newsletters/index.js
The token verification is meant for validating short and long-lived tokens from OAuth-based ESPs. Currently, this is only the case for Constant Contact and we are sending unnecessary requests that fail whenever the settings are saved with a different provider.
This is just to ensure that the request is only sent when Constant Contact is the provider.
To improve the UX, 6abd1302c194adcd7978041b22b032bf7eef1498 adds an in-flight state that disables form fields while saving. Although this doesn't mean a success message, it indicates that something happened.
1. While on the master branch, visit the Engagement -> Newsletters wizard
2. Save the settings with a valid Mailchimp API with your DevTools Network tab open
3. Confirm you see the successful …
> fix(newsletters): only attempt token verification for Constant Contact

- CHANGELOG.md
- assets/blocks/reader-registration/edit.js
- composer.lock
- includes/class-blocks.php
- newspack.php
- package-lock.json
- package.json
> Release Apr 24

- assets/wizards/readerRevenue/index.js
- assets/wizards/readerRevenue/views/nrh-settings/index.js
- includes/class-nrh.php
- includes/wizards/class-reader-revenue-wizard.php
Updates the News Revenue Hub default redirect URL to the latest schema. Also revamps the NRH settings page slightly and adds a new field for custom domain, which NRH will soon start supporting.
Note that the redirect will 404 if the org ID and/or custom domains are not also set up on the NRH side; this is expected.
Closes `1200133283801628/1204490226165899`.
1. Visit **Newspack > Reader Revenue** and set your platform to "News Revenue Hub".
2. Visit the News Revenue Hub tab and confirm you see the new layout (with any preexisting values retained) and the new "Custom Domain" field. Ensure that the Organization ID and Salesforce Campaign ID fields are filled in, but leave the Custom Domain field blank.
3. Visit the site front-end and make donations via the Donate block, testing different …
> feat: update NRH settings page and redirect behavior

- assets/wizards/engagement/components/prompt.tsx
- assets/wizards/readerRevenue/index.js
- assets/wizards/readerRevenue/views/nrh-settings/index.js
- includes/class-nrh.php
- includes/wizards/class-reader-revenue-wizard.php
- package-lock.json
- package.json
> Alpha release May 03

- assets/memberships-gate/block-patterns.js
- assets/memberships-gate/block-patterns.scss
- includes/plugins/wc-memberships/block-patterns/donation-wall.php
- includes/plugins/wc-memberships/block-patterns/pay-wall-one-tier-metering.php
- includes/plugins/wc-memberships/block-patterns/pay-wall-one-tier.php
- includes/plugins/wc-memberships/block-patterns/pay-wall-two-tiers.php
- includes/plugins/wc-memberships/block-patterns/registration-wall.php
- includes/plugins/wc-memberships/class-block-patterns.php
- webpack.config.js
Implements new design to the content gate block patterns.
1. Make sure you have WC Memberships active
2. Draft a new page and navigate to add a new block pattern in the "Memberships" category
3. Add each block pattern to the page, save, and visit the page in a new session
4. Confirm the rendered design reflects the editor and the images above
> feat(content-gate): updated block patterns

- includes/class-newspack.php
- includes/class-rss-add-image.php
- includes/optional-modules/class-rss.php
This PR moves the function to add the Featured Image from the Newspack Theme to the Plugin, and increases the size from `medium` to `large`. 
See 1200550061930446-as-1204091471563476
1. Apply this PR and the [complementary theme PR](https://github.com/Automattic/newspack-theme/pull/2139) that removes the matching function from there.
2. Make sure RSS Enhancements is disabled under Newspack > Syndication to start.
3. Check your site's RSS feed and confirm it's including the featured image using the large size set in Settings > Media -- one way to do this is to subscribe to your feed from an RSS Reader. (Some readers may shrink the image down a bit -- for example the Old Reader scales it down to 800 -- in this case you just have to make sure it's bigger than the medium size). 
4. Active RSS …
> Move RSS featured image to the plugin and bump up the size

- assets/memberships-gate/metering.js
- assets/reader-activation/article-view.js
- assets/reader-activation/index.js
- assets/reader-activation/index.test.js
- assets/wizards/engagement/views/reader-activation/campaign.js
- assets/wizards/engagement/views/reader-activation/complete.js
- composer.lock
- includes/class-plugin-manager.php
- includes/data-events/connectors/ga4/class-ga4.php
- includes/data-events/listeners.php
- includes/plugins/wc-memberships/class-memberships.php
- includes/plugins/wc-memberships/class-metering.php
- includes/reader-activation/class-reader-activation.php
- includes/reader-activation/class-reader-data.php
- package-lock.json
- package.json
> Alpha release Jul 07

- assets/memberships-gate/editor.js
- assets/memberships-gate/metering.js
- assets/reader-activation/utils.js
- assets/reader-activation/utils.test.js
- composer.lock
- includes/class-newspack.php
- includes/class-pwa.php
- includes/class-rss-add-image.php
- includes/data-events/class-woo-user-registration.php
- includes/data-events/listeners.php
- includes/plugins/wc-memberships/class-memberships.php
- includes/plugins/wc-memberships/class-metering.php
- includes/reader-activation/class-reader-activation.php
- includes/reader-activation/class-reader-data.php
- package-lock.json
- package.json
> Alpha release Jul 20

- includes/plugins/wc-memberships/class-memberships.php
Fixes an oversight in #2551. The [`do_blocks()` function](https://github.com/WordPress/wordpress-develop/blob/20806d4d7fed387f26deb134085f59e91ee66364/src/wp-includes/blocks.php#L1158-L1182) removes the `wpautop` filter if necessary, which is unable to if the filter is attached to `newspack_gate_content` instead of `the_content`.
A custom implementation of do_blocks(), replacing the filter name, fixes the issue.
| Before | After |
| --- | --- |
| <img width="833" alt="image" src="https://github.com/Automattic/newspack-plugin/assets/820752/7dd5c000-6397-4a62-9471-30c62435c0bd"> | <img width="839" alt="image" src="https://github.com/Automattic/newspack-plugin/assets/820752/ffb8b1db-a0e3-43ad-be49-3d5152cd30a5"> |
1. While on the master branch, add a Reader Registration block to a content …
> fix(content-gate): custom filter for 'do_blocks()'

- includes/class-magic-link.php
Replaces Newspack Newsletters' native email verification with RAS' account verification email when RAS is enabled.
This allows the verification email to take advantage of RAS' customization and the reader to verify their account in a different session/device, which is currently unsupported in Newspack Newsletters' implementation.
1. With RAS enabled and Newsletters configured with subscription lists, create a new account and verify the account's email
2. Delete the Newspack Newsletter's verification meta: `wp user meta delete {user_id} newspack_newsletters_email_verified`
3. Visit the "Newsletters" page of "My Account" and click to verify
4. Log out
5. Check the received email and confirm it's RAS' verification email
6. Visit the link in a fresh (unauthenticated) session and confirm you …
> feat(ras): replace newsletters verification email

- includes/data-events/connectors/ga4/README.md
- includes/data-events/connectors/ga4/class-ga4.php
Adds an anonymized email para to GA4 events.
1. Set up a site with GA4 back end events (Newspack > Analytics > Newspack Custom Events)
2. Fire a back-end event by registering via the registration block, making a donation or subscribing to a newsletter
3. In GA, confirm you see the event coming through and that it has the new `user_hash` param
> feat: add anonymized email to ga4 events

- includes/reader-activation/class-reader-activation.php
Adds a filter to the lists available in the registration block
See https://github.com/Automattic/newspack-newsletters/pull/1238
> feat: add filter to the lists in the reg block

- assets/wizards/advertising/index.js
- assets/wizards/advertising/style.scss
- assets/wizards/advertising/views/marketplace/components/order/index.js
- assets/wizards/advertising/views/marketplace/index.js
- assets/wizards/advertising/views/marketplace/orders/index.js
- assets/wizards/advertising/views/marketplace/products/index.js
1203270678582143-as-1204470726175919
Implements a sample dashboard for Ads Marketplace with ad order listing and management.
The "Settings" is a placeholder that will later allow:
- Triggering email when an ad order is placed
- Which email address should receive the email
The "Overview" section is a placeholder/sample for later integration with GAM data.
1. Check out this branch and https://github.com/Automattic/newspack-ads/pull/694
2. Visit Newspack -> Advertising -> Marketplace and confirm it renders a dashboard as in the image above
3. Click "Products" and confirm you can see and create products
4. Make sure you have valid Ad products
5. Add the "Marketplace" block on a page, visit and place an ad order
6. Confirm the order is placed and it's visible on the dashboard
7. Click on the …
> feat: ads marketplace orders ui

- assets/wizards/engagement/index.js
- assets/wizards/engagement/views/reader-activation/index.js
- composer.lock
- includes/data-events/connectors/ga4/README.md
- includes/data-events/connectors/ga4/class-ga4.php
- includes/plugins/wc-memberships/class-memberships.php
- includes/reader-activation/class-reader-activation.php
- includes/wizards/class-engagement-wizard.php
- includes/wizards/class-setup-wizard.php
- package-lock.json
- package.json
> Alpha release Sep 06

- composer.lock
- includes/class-newspack.php
- includes/reader-revenue/stripe/class-stripe-sync.php
- includes/reader-revenue/stripe/class-stripe-webhooks.php
- includes/reader-revenue/woocommerce/class-woocommerce-connection.php
- includes/reader-revenue/woocommerce/class-woocommerce-sync.php
- package-lock.json
- package.json
> Alpha release Sep 11

- CHANGELOG.md
- assets/wizards/engagement/index.js
- assets/wizards/engagement/views/reader-activation/index.js
- composer.lock
- includes/class-newspack.php
- includes/data-events/connectors/ga4/README.md
- includes/data-events/connectors/ga4/class-ga4.php
- includes/plugins/wc-memberships/class-memberships.php
- includes/reader-activation/class-reader-activation.php
- includes/reader-revenue/stripe/class-stripe-sync.php
- includes/reader-revenue/stripe/class-stripe-webhooks.php
- includes/reader-revenue/woocommerce/class-woocommerce-connection.php
- includes/reader-revenue/woocommerce/class-woocommerce-sync.php
- includes/wizards/class-engagement-wizard.php
- includes/wizards/class-setup-wizard.php
- newspack.php
- package-lock.json
- package.json
> Release Sep 13

- CHANGELOG.md
- assets/components/src/autocomplete-tokenfield/index.js
- assets/components/src/settings/style.scss
- assets/components/src/subscription-lists-control/index.js
- assets/wizards/advertising/views/placements/index.js
- assets/wizards/popups/utils.js
- assets/wizards/popups/views/segments/SingleSegment.js
- includes/reader-activation/class-reader-activation.php
- includes/reader-activation/class-reader-data.php
- includes/reader-revenue/woocommerce/class-woocommerce-connection.php
- newspack.php
- package-lock.json
- package.json
> Alpha release Sep 29

- includes/class-donations.php
See https://github.com/Automattic/newspack-popups/pull/1224
> fix: inline documentation for `Donations::get_donation_settings()`

- includes/class-newspack-image-credits.php
A different strategy for #2691 by selecting post IDs from the post meta table instead of using joins.
Same as #2691
> fix(media-credit): use post ids selection for search query

- assets/wizards/connections/views/main/recaptcha.js
- includes/class-recaptcha.php
Makes reCAPTCHA settings configurable in the Connections wizard. 
See 1200133283036252-as-1205129530451107
1. Make sure reCAPTCHA works as expected before changing anything via the UI
2. Visit the Connections wizard, edit the "Threshold" value in the reCAPTCHA settings
3. Observe the value is used by logging it in `verify_captcha` method
> feat(recaptcha): make recaptcha threshold configurable

- includes/class-donations.php
Adds handling of the post-checkout-button to the Donate block processing.
_Follow testing steps in https://github.com/Automattic/newspack-blocks/pull/1571_
> feat(donations): process after-checkout-button params

- includes/class-donations.php
- includes/class-recaptcha.php
Adds filters for donation-related cart item data and captcha verification. 
_Follow instructions in https://github.com/Automattic/newspack-blocks/pull/1573_
> feat: add donation processing filters

- assets/blocks/reader-registration/style.scss
- assets/components/src/autocomplete-with-suggestions/style.scss
- composer.json
- composer.lock
- includes/class-donations.php
- includes/class-plugin-manager.php
- includes/class-recaptcha.php
- includes/reader-revenue/woocommerce/class-woocommerce-connection.php
- package-lock.json
- package.json
> Alpha release Nov 01

- assets/wizards/readerRevenue/views/stripe-setup/index.js
- includes/configuration_managers/class-woocommerce-configuration-manager.php
- includes/reader-revenue/class-reader-revenue-emails.php
- includes/reader-revenue/stripe/class-stripe-connection.php
- includes/reader-revenue/woocommerce/class-woocommerce-connection.php
- includes/reader-revenue/woocommerce/class-woocommerce-cover-fees.php
- includes/wizards/class-reader-revenue-wizard.php
> Alpha release Nov 03

- includes/data-events/connectors/ga4/README.md
Just  a new link in the docs. Test if the link works
> docs: add link in the docs

- includes/reader-revenue/woocommerce/class-woocommerce-connection.php
Testing #2758, I have an alternative proposal. When a reader completes a non-donation order, we should still sync relevant reader and transaction details such as the reader's billing details, total spend, last order amount and product, etc. These transactions should factor into total spend. We just don't need to update the "Donor" or "Ex-Donor" membership status fields, because these transactions shouldn't affect the reader's donor status at all.
This proposal shouldn't change anything about the other next steps we discussed in the other PR:
> 2. Unify the syncing strategy to use the existing data events connectors and no longer the `WooCommerce_Connection::sync_reader_from_order` for better maintainability and to avoid confusion.
> 3. Discuss/decide how we'd like the schema and implement …
> fix: sync non-donation data to ESP, but not donor status

- includes/cli/class-setup.php
Removes some legacy and unused code.
> chore: remove legacy code in setup

- includes/class-plugin-manager.php
Changes Distributor's GitHub download link from `https://github.com/10up/distributor/archive/stable.zip` to `https://github.com/10up/distributor/releases/latest/download/distributor.zip`, ensuring the plugin is installed with the slug `distributor` instead of `distributor-stable`, consistent with how the folder is symlinked on the Atomic platform. See p9o2xV-p2-3Em for more details.
1. Navigate to `/wp-admin/plugins.php`
2. Install Distributor
3. Verify that the plugin was installed into a folder named `distributor-stable`
4. Uninstall Distributor
5. Switch to this branch
6. Navigate to `/wp-admin/plugins.php`
7. Install Distributor
8. Verify that the plugin was installed into a folder named `distributor`
> fix: update Distributor download link

- includes/class-plugin-manager.php
Adds Team 51's [Safety Net](https://github.com/a8cteam51/safety-net/) to our list of supported plugins.
2. Install the Safety Net plugin.
3. Go to Newspack > Health Check and confirm that Safety Net is not raising any alerts.
> feat: adds support for Safety Net plugin

- includes/reader-revenue/woocommerce/class-woocommerce-cli.php
Quick fix for https://github.com/Automattic/newspack-plugin/pull/2848
> fix: make CLI comand more reliable

- README.md
- package-lock.json
- package.json
This is a PR for testing purposes only.
> fix: test epic release workflow
