- includes/class-newspack.php
- includes/class-plugin-manager.php
- tests/unit-tests/core.php
- tests/unit-tests/plugin-manager.php
Closes #3 .
I've developed a class to handle general plugin management tasks: install/uninstall, activate/deactivate, etc. The class is designed so that we can just use it without having to worry about whether the underlying host is VIP Go or a different host:
- It handles installation from both WordPress.org repos and from URLs.
- The class is designed to work in all environments, including VIP Go.
- The `activate` method will install a plugin first if needed (when possible), so the idea is to just use `activate` in the OBW and that will automatically handle installation and activation of plugins.
- The class checks to make sure plugins installation is allowed in order to prevent issues with VIP Go. If plugin installation is not allowed, it gracefully falls back to only managing …
> Plugin management utility class

- includes/api/class-plugins-controller.php
- includes/class-api.php
- includes/class-newspack.php
- includes/class-plugin-manager.php
- tests/unit-tests/api-plugins-controller.php
- tests/unit-tests/plugin-manager.php
Closes #4.
This PR adds the following REST API endpoints for users with the correct capabilities:
- GET `newspack/v1/plugins`
- GET `newspack/v1/plugins/{some-plugin}`
- POST `newspack/v1/plugins/{some-plugin}/activate`
- POST `newspack/v1/plugins/{some-plugin}/deactivate`
- POST `newspack/v1/plugins/{some-plugin}/install`
- POST `newspack/v1/plugins/{some-plugin}/uninstall`
The GET endpoints retrieve info about plugins and their installation status. The POST endpoints can be used to activate/deactivate/etc. a plugin. See the unit tests for usage.
I've also added a minimal way to get information about the managed plugins, since that was required for the GET endpoints. See my comment below, and please let me know if there's a better way you know (loading from a config file?).
1. …
> Plugin management endpoints

- package-lock.json
- package.json
- postcss.config.js
Related to https://github.com/Automattic/newspack-plugin/pull/13/files#r275358960
I've broken out the package.json stuff into a separate PR for easier reviewing. This config is basically the same as [the one from the newspack-theme repo](https://github.com/Automattic/newspack-theme/blob/master/package.json)
> Set up package.json

- assets/css/plugins-screen-rtl.css
- assets/css/plugins-screen.css
- assets/css/sass/plugins-screen.scss
- assets/js/plugins-screen.js
- includes/class-admin-plugins-screen.php
- includes/class-newspack.php
- includes/class-plugin-manager.php
- package-lock.json
- package.json
- postcss.config.js
Closes #10 .
Adds plugin recommendations/management through the admin Plugins screen. This interface is designed for power users or self-hosted users to be able to take advantage of and easily install our recommended plugins without requiring a Jetpack connection or hosting plan.
This initial implementation only recommends AMP and Jetpack; we should add other managed plugins after this is merged as a separate PR for easier reviewing.
1. Go to Plugins screen. Install and manage recommended plugins on the screen.
2. Activate Jetpack. On the plugins screen, add `?calypsoify=1` to the URL. Install and manage recommended plugins on the Calypsoified screen.
> Basic plugin management through Plugins screen

- assets/src/wizards/subscriptions/index.js
The [@wordpress/element](https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-element/) package is wrapper for React and ReactDOM. In this Pull Request use of React and ReactDOM are replaced with the package.
1. As per usual run `npm ci && npm run build:webpack`
2. Verify there are no  errors.
3. In a test environment with the Newspack plugin installed, navigate to Newspack->Subscriptions, and verify that the page loads with a single checkbox component.
> Replace React and ReactDOM with @wordpress/element

- assets/src/components/card/card.test.js
- assets/src/components/card/index.js
- assets/src/components/card/style.scss
- assets/src/setupTests.js
- assets/src/wizards/subscriptions/index.js
- package-lock.json
- package.json
Closes #17.
1. Build the components: `npm ci && npm run build:webpack`
2. In a test environment running the Newspack plugin, navigate to Newspack->Subscriptions.
3. Observe two Cards, each with a single Checkbox in it.
1. The max width of this component is set to 484px to match the widths in the Figma mockups. Is it appropriate for the Card to determine its own width? Or, should we be placing Cards in a container that defines the width? If the former, we might need to introduce a prop to control the width of the Card (e.g. `cardWidth=small|medium|large`).
2. The Header/Subheader described [here](https://github.com/Automattic/newspack-plugin/issues/18) could be worked into the Card component as parameters? 
3. In the Figma document, some of the Card examples have top and bottom padding of …
> Muriel-styled Card component.

- babel.config.js
- package-lock.json
- package.json
Mirroring changes in https://github.com/Automattic/newspack-blocks/pull/7, this PR bumps `@automattic/calypso-build` to 1.0.0-rc.3, removes an unnecessary dependency (`file-loader`), and removes the Babel config file. 
Closes # .
`npm ci && npm run build:webpack`
Verify no errors, then navigate to `/admin.php?page=newspack-subscriptions-wizard` and verify two `Card` components one with a simple checkbox and one with a checkbox with tooltip.
> Bump calypso-build to 1.0.0-rc.3. Remove file-loader and Babel config.

- assets/src/components/card/index.js
- assets/src/components/checkboxInput/index.js
- assets/src/components/infoButton/index.js
- assets/src/wizards/subscriptions/index.js
- includes/wizards/class-subscriptions-wizard.php
- includes/wizards/class-wizard.php
- webpack.config.js
Having extra entry points for style files is a bit weird TBH :grimacing: `calypso-build` supports `import`ing SASS files out of the box, so this PR suggests using that technique instead.
Can be a first step towards dropping the webpack config altogether (which ironically will make adding back a babel config less messy. And adding a babel config is one way to fix failing tests).
> Build: Simplify style build stack

- package.json
Updates master with [the change from this PR](https://github.com/Automattic/newspack-plugin/pull/29#issuecomment-490535220), so everyone has access to working unit tests before that PR is merged.
The previous version used the `node` environment, which simulates a node server. This caused issues because browser variables like `window` were not defined and some Gutenberg components expect that variable. The default `jsdom` environment simulates a browser, and meets our needs much better.
To test:
1. Run unit tests.
2. Check out #29 and run unit tests.
> Use jsdom environment when running jest tests.

- assets/src/components/checkboxInput/index.js
The restyled components should extend `Component`, not the component we  are restyling. I think it was a happy accident that extending `CheckboxControl` actually worked in this case, but we run into trouble when doing the same with other components, e.g. `Button`.
1. Execute `npm run build:webpack`
2. Observe that the checkbox components in `Newspack/Subscriptions` look and act as they did before.
> Fix: Checkbox input should extend Component, not CheckboxControl.

- assets/src/components/checkboxInput/style.scss
- includes/class-newspack.php
- includes/wizards/class-subscriptions-wizard.php
- webpack.config.js
This PR implements the suggestions from https://github.com/Automattic/newspack-plugin/pull/25#pullrequestreview-232478568 . The PR was merged since those were non-blocking suggestions, and I'm opening this PR before I forget about them.
Specifically:
- Use sass color variables instead of literal colors.
- Move inclusion of Wizard class to classes that extend it instead of the main Newspack class.
- Remove unnecessary module from webpack config.
The `package.json` dependencies mentioned in the review, we will re-approach down the line as part of a bigger dependency clean-up effort. There are some other dependencies @jeffersonrabb has mentioned we may be able to remove, but including unnecessary dependencies doesn't affect our product at the moment, so let's investigate that later.
> Minor tweaks

- assets/src/components/formattedHeader/formattedHeader.test.js
- assets/src/components/formattedHeader/index.js
- assets/src/components/formattedHeader/style.scss
- assets/src/wizards/subscriptions/index.js
- assets/src/wizards/subscriptions/style.scss
Closes #18 .
Adds the FormattedHeader component. The code is strongly influenced by [the Calypso component of the same name.](https://github.com/Automattic/wp-calypso/blob/master/client/components/formatted-header/index.jsx) I've also made a couple tweaks to the Subscriptions demo page, for better demoing.
I'll remove the Do Not Merge label and add tests to this as soon as the tests are working again. :)
1. `npm ci` `npm run build:webpack`
2. Navigate to the Subscriptions screen.
> Formatted header component

- assets/src/components/card/card.test.js
- assets/src/components/card/index.js
- assets/src/components/card/style.scss
- assets/src/components/checkboxControl/index.js
- assets/src/components/checkboxControl/style.scss
- assets/src/components/formattedHeader/formattedHeader.test.js
- assets/src/components/formattedHeader/index.js
- assets/src/components/formattedHeader/style.scss
- assets/src/components/infoButton/index.js
- assets/src/components/infoButton/style.scss
- assets/src/components/textControl/index.js
- assets/src/components/textControl/style.scss
- assets/src/wizards/subscriptions/index.js
This PR standardizes the naming conventions for the components following these rules:
- Use the same JS class name as the Gutenberg component for Murielized components when applicable.
- Use the `muriel-` prefix for HTML classes.
In addition to making it easier to offer these components as stand-alone components in the future, this should make naming things easier and won't require getting creative with component names.
To test:
1. `npm ci`, `npm run build:webpack`, `npm run test`.
2. Go to the Subscriptions page. Observe nothing is broken or unstyled.
> Standardize naming conventions

- assets/src/components/card/index.js
- assets/src/components/card/style.scss
- assets/src/components/checkboxControl/index.js
- assets/src/components/checkboxControl/style.scss
- assets/src/components/formattedHeader/index.js
- assets/src/components/formattedHeader/style.scss
- assets/src/components/imageUpload/index.js
- assets/src/components/imageUpload/style.scss
- assets/src/components/infoButton/index.js
- assets/src/components/infoButton/style.scss
- assets/src/components/textControl/index.js
- assets/src/components/textControl/style.scss
- assets/src/shared/js/muriel-classnames.js
- assets/src/shared/scss/_muriel-component.scss
- Utility that combines component classNames, adding "muriel-component" to each
- If className is set on the component itself, it will be included in React rendering. 
- Global stylesheet for all components.
- Normalized top/bottom margins for all components.
- `is-centered` class
Closes #44
2. Navigate to `/admin.php?page=newspack-subscriptions-wizard`.
3. Observe that all components look and behave as before.
4. Observe vertical space between Text Inputs.
5. Edit `/assets/wizards/subscriptions/index.js`. Try adding `className` attributes to any of the components and in browser web inspector observe that the classes are set on the rendered components.
> Shared Component Styles

- assets/src/components/button/index.js
- assets/src/components/button/style.scss
We're now using `murielClassnames()` as introduced in #57 and we don't need to set the margin in our component styles for the button because the shared component styles handle that.
2. Navigate to `/admin.php?page=newspack-subscriptions-wizard`
3. Observe that all components look and behave as before.
> Switch to using shared Muriel styles and murielClassnames()

- assets/src/components/button/button.test.js
- assets/src/components/button/index.js
- assets/src/components/button/style.scss
- assets/src/components/textControl/index.js
- assets/src/components/textControl/style.scss
- assets/src/wizards/subscriptions/index.js
- package.json
Updated the TextControl's CSS width from hard-coded pixel value to a percentage-based value.
The TextControl are demoed in the Subscription Wizzard. One can change the value of `.muriel-card`'s `max-width` value by using the Inspector, and check that the component styling changes accordingly and behaves properly.
> TextControl's CSS width changed from hard-coded px to percentage-based

- assets/src/components/select-control/index.js
Related #64 
This PR fixes issues caused by destructuring assignment in the select component render. Props that are destructured need to be passed on to the base component, otherwise the base component won't have the information.
1. Before applying this patch, go to the components demo. Observe that the first select has 'First' as the selected variable, even though the code says 'Second'. Observe that the disabled select is not truly disabled:
2. Apply this patch. Go to the components demo. Observe that the first select has 'Second' and the disabled select is actually disabled:
> Fix prop issues in select component

- assets/src/components/checkbox-control/style.scss
- assets/src/wizards/componentsDemo/index.js
Related #64 
This PR adds styling for the 'help' text on checkboxes.
Here is the design for this:
Without the CSS in this PR, here is what it would look like:
2. Go to Components Demo. Examine the new 'Checkbox w/Help' element I've added:
> Style 'help' text for checkboxes

- assets/src/components/text-control/style.scss
- assets/src/wizards/componentsDemo/index.js
Related #64 
The styles in the stylesheet were only getting applied to inputs with the 'text' type. I've removed the restriction, so all types of inputs (number, password, etc.) will get the styles.
Here is what the input looked like before the change:
2. Go to Components Demo and observe number input there is styled:
* [ x] Have you added an explanation of what your changes do and why you'd like us to include them?
> Style number/password/etc. inputs

- phpcs.xml
Related #64 
- Removes the JS check from PHPCS. 
- We have prettier working nicely, and having two linters for JS code style seems excessive. Keeping rules for the two linters in sync would be difficult (so the lint rules don't conflict) .
- PHPCS is not designed to handle React. The linter cannot handle code like `<div foo={ bar }>` and our codebase generates hundreds of lines of errors similar to the following:
```
FILE:newspack/wp-content/plugins/newspack-plugin/assets/src/wizards/componentsDemo/index.js
------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 330 ERRORS AND 75 WARNINGS AFFECTING 129 LINES
----------------------------------------------------------------------------- …
```
> Remove js from phpcs check

- assets/src/wizards/subscriptions/index.js
- assets/src/wizards/subscriptions/style.scss
- assets/src/wizards/subscriptions/views/editSubscriptionScreen.js
- assets/src/wizards/subscriptions/views/manageSubscriptionsScreen.js
- includes/class-newspack.php
- includes/wizards/class-subscriptions-wizard.php
- includes/wizards/class-wizard.php
* [x Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
Closes #53 .
Supersedes #15.
Supersedes #64 .
This implementation of the subscriptions wizard does so with all of the state pulled up into the main wizard class, as per @jeffersonrabb's suggestion. I think it was a good suggestion, and this seems easier to maintain and follow the code logic.
1. `npm ci; npm run clean; npm run build:webpack`
2. Go to Newspack > Subscriptions and use the wizard.
> Subscriptions Wizard

- assets/src/components/action-card/index.js
- assets/src/components/action-card/style.scss
- assets/src/components/index.js
- assets/src/wizards/componentsDemo/index.js
This PR adds a new component, `ActionCard`, which can be used any time there is a series of similar items in a wizard. The initial use case will be for the plugin installer, but it's designed to be swapped in to Subscriptions Wizard, Ad Wizards, and many others. The `ActionCard` component takes the following parameters:
`title`: Primary text  display.
`description`: Secondary text display.
`notification`: Optional notification text.
`notificationLevel`: The severity/type of notification (error|warning)
`actionText`: Text for the action button on the right  side.
`secondaryActionText`: Text for the secondary action  button (e.g. Delete)
`image`: Optional path for image to be displayed at the far left.
`imageLink`: Optional URL to link the image to.
`onClick`: Click handler for primary …
> Action Card Component

- assets/src/wizards/subscriptions/style.scss
- assets/src/wizards/subscriptions/views/manageSubscriptionsScreen.js
This PR implements the new `ActionCard` component in the Subscriptions Wizard. This is simply a UI swap, and there should be no change to existing functionality.
Closes # .
1. You'll need the required plugins installed (WooCommerce, WooCommerce Name Your Price, WooCommerce Subscriptions).
2. Checkout this branch.
3. `npm ci && npm run clean && npm run build:webpack`
4. Navigate to Newspack->Subscriptions (`/wp-admin/admin.php?page=newspack-subscriptions-wizard`). 
5. Add several subscriptions (if you don't have already). 
6. Verify that you see the title, price, and image on the list page.
7. Verify that Edit and Delete buttons work as expected.
> Subscriptions Wizard w/ActionCard

- assets/wizards/checklist/index.js
- assets/wizards/dashboard/index.js
- assets/wizards/dashboard/style.scss
- assets/wizards/dashboard/views/dashboardCard.js
- assets/wizards/dashboard/views/tier.js
- includes/class-checklists.php
- includes/class-newspack.php
- includes/class-wizards.php
- includes/wizards/class-components-demo.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-subscriptions-onboarding-wizard.php
- includes/wizards/class-subscriptions-wizard.php
- includes/wizards/class-wizard.php
Closes #56 .
Sorry for YAGPR (Yet Another Giganto Pull Request 😄). The components are somewhat woven together, and I didn't feel that the architecture could be properly evaluated or communicated if it was split into a bunch of smaller PRs.
This pull request implements dashboard and checklist handling and ties everything together into one (mostly) functional application.
Architecture:
- The Dashboard is a stand-alone area that can render anything into a card (checklists, links, etc.). Under the hood, it's just a 1-screen wizard. See `assets/wizards/dashboard` and `includes/wizards/class-dashboard.php`.
- Checklists are managed and rendered in a centralized way, so we don't need to make a bunch of different independent checklist handlers. Checklists are defined and routed in …
> Dashboard + Checklist + Cohesiveness 

- assets/wizards/subscriptionsOnboarding/index.js
- assets/wizards/subscriptionsOnboarding/style.scss
- assets/wizards/subscriptionsOnboarding/views/locationSetup.js
- assets/wizards/subscriptionsOnboarding/views/paymentSetup.js
This PR addresses some of the feedback brought up in https://github.com/Automattic/newspack-plugin/pull/86#issuecomment-500985705 and https://github.com/Automattic/newspack-plugin/pull/86#pullrequestreview-248192737.
Specifically, the following changes are implemented:
- Removed the Skip and Cancel links from the wizard.
- Adjust the link to the Stripe API info so it displays more like a tip:
2. Go to the Subscriptions Onboarding wizard (first item in Memberships checklist). Observe the skip/cancel links are removed, and the Stripe settings screen should look like the above screenshot.
> Couple small tweaks to Subscriptions Onboarding wizard

- includes/wizards/class-dashboard.php
This PR simply adds the Newspack logo to the admin menu.
2. Observe gear icon has been replaced by Newspack icon as pictured here:
> Newspack Logo In Admin Menu

- assets/wizards/subscriptions/views/manageSubscriptionsScreen.js
- assets/wizards/subscriptionsOnboarding/index.js
- includes/class-checklists.php
- includes/class-wizards.php
- includes/wizards/class-wizard.php
Closes #98 .
This PR adds links back to the checklist in the following places:
- Plugin installer
- Subscription management screen
- Automatic redirect when finished with Subscriptions Onboarding wizard
It also makes URLs for checklists/wizards/dashboard available in a JS variable for future wizards to use.
2. Deactivate WooCommerce, go to Subscriptions Onboarding wizard. Verify the link to return to the checklist works.
3. Go through the Subscriptions Onboarding wizard. Verify you are redirected to the checklist when the wizard is completed.
4. Verify the "I'm done adding" link takes you back to the checklist.
> Add 'return to checklist' links where needed

- includes/wizards/class-subscriptions-onboarding-wizard.php
Originally noticed/doicumented while testing #109. 
The logic that validates the Stripe keys was flawed. When Test Mode is enabled and valid test keys are entered, it would throw an error if valid publish keys were not also entered. That is incorrect behavior, as publish keys should not be validated if test mode is active.
0. Go to the Stripe setup in the Subscriptions Onboarding wizard. Enable Stripe.
1. Uncheck Test Mode, delete any values in the live key inputs, recheck Test Mode, enter some values for test keys. Save. It should save without throwing an error.
2. Check Test mode, delete any values in the test key inputs, uncheck Test Mode, enter some values for live keys. Save. It should save without throwing an error.
3. Verify errors are still thrown when a required field is missing …
> Fix key validation logic in Stripe setup

- assets/wizards/componentsDemo/index.js
- includes/api/class-plugins-controller.php
- includes/class-plugin-manager.php
- tests/unit-tests/plugin-manager.php
This PR improves the handling for plugins that can't be installed by Newspack because the plugin URL's aren't public. This could be premium plugins, Site Kit, etc. Attempting to install one of those plugins through the API or Plugin_Manager will fail and provide a useful error about where to get the plugin.
Plugins without `Download` info in the `Plugin_Manager` are plugins that cannot be installed. Information about where to get the plugin is pulled from the plugin's `PluginURI` info.
2. In the Components Demo, try and install Site Kit. Observe it fails with a useful error:
In the future once the plugin installer component is fine-tuned to be more user friendly, we can probably hide the "Use" button and just display a "This plugin can't be …
> Improved handling for plugins that Newspack can't install

- assets/components/src/button/style.scss
- assets/components/src/checkbox-control/style.scss
- assets/components/src/image-upload/style.scss
- assets/components/src/progress-bar/style.scss
- assets/shared/scss/_muriel-component.scss
This PR switches to the Newspack color scheme for components. 
Primary: `#2a7de1`
Hover: `#4f8cdd`
Active: `#3166ae`
2. Navigate to Components Demo (`/wp-admin/admin.php?page=newspack-components-demo`)
3. Observe color changes on `<Button>`, `<ImageUpload>`, `<ProgressBar>`, and `<CheckboxControl>` components.
> Mighty Blue

- assets/components/src/handoff/index.js
- assets/wizards/componentsDemo/index.js
- includes/api/class-plugins-controller.php
- includes/class-plugin-manager.php
@philipjohn has noted that in some cases a `Handoff`s will need to go to a specific page within a plugin's dashboard, e.g. the AdSense area of Google Site Kit. This PR addresses this concern by supporting an optional `editLink` prop which will override the default link. Also, if the `<Handoff>` element has content, this will be used in place of the default `Manage {Plugin Name}`. 
For example:
```
<Handoff
className="is-centered"
plugin="wordpress-seo"
isPrimary
editLink="/wp-admin/admin.php?page=wpseo_dashboard#top#features"
>
{ __( 'Specific Yoast Page' ) }
</Handoff>
```
2. Install Yoast SEO plugin.
3. Navigate to `Newspack->Components Demo` (`/wp-admin/admin.php?page=newspack-components-demo`
4. Observe "Specific Yoast Button" in …
> Handoff: Edit Link and Button Text Overrides

- includes/class-handoff-banner.php
- includes/wizards/class-dashboard.php
This PR adjusts the priorities of the Newspack menu and notice to make the menu item higher up and the notice not be blocked by Site Kit:
`3` is the best menu position, so there isn't a way of getting above Jetpack since we're after them alphabetically.
The disclaimer about the Site Kit priority tweak is that they could theoretically change their priority to `-10001` and we could have a notice priority arms race on our hands. :)
1. Observe Newspack is up near the top of the admin menu.
2. Click the 'Manage Site Kit' handoff in the Components Demo. Observe our notice is present on Site Kit admin pages.
> Tweak notice and menu priorities

- includes/wizards/class-subscriptions-onboarding-wizard.php
Closes #123
This PR fixes a bug where validation errors would be thrown if Stripe is disabled and the key fields are empty. It does this by only requiring non-empty key fields when Stripe is enabled.
2. Go to Subscriptions Onboarding wizard.
3. On the Stripe settings, toggle it enabled and delete any existing key information you see. Toggle it disabled. Save. It should save properly. 
4. Go to the wizard again. Toggle it enabled. Save. It should throw an error about missing keys.
> Only validate API key fields if Stripe is enabled

- assets/components/src/with-wizard-screen/index.js
The action button has been moved outside the `<Card>` in Wizard Screens.
Closes #129 .
2. View any Wizards and verify that the button appears where it should.
> Action Button Below Card

- assets/components/src/plugin-installer/index.js
- assets/wizards/componentsDemo/index.js
The Setup Wizard installs plugins using different UI from the normal `PluginInstaller` component. It uses a `ProgressBar`, and installation begins automatically rather than requiring a `Button` click. To avoid code duplication, this PR brings this UI and functionality to the `PluginInstaller` component if it has the `asProgressBar` prop. Also, the `Use All` `Button` is hidden until plugin data has been retrieved, which will remove the flash of incorrect UI that appears in cases where the component determines that all plugin requirements have been met and hides itself.
2. Deactivate and remove these plugins: WooCommerce, AMP, Yoast, Site Kit
3. Navigate to `Newspack->Components Demo`
4. Click `Show Plugin Installer w/Progress Bar`.
5. …
> Alternate Plugin Installer UI

- assets/components/src/button/style.scss
- assets/wizards/handoff-banner/style.scss
- includes/class-handoff-banner.php
Per a suggestion from @sonjaleix this PR adds margins around the Handoff banner based on this screenshot:
2. Navigate to `Newspack->Components Demo`
3. Click any of the `Handoff` buttons.
4. Observe the new banner styles.
> Handoff Banner Style Change

- assets/components/src/card/style.scss
- assets/components/src/checklist/index.js
- assets/components/src/checklist/style.scss
This PR implements the Muriel grid through width and padding styles in the `Card` component at a variety of breakpoints. Because  all Newspack Wizards are contained in `Card`s this effectively enforces the grid for all of our UI. The one exception was the `Checklist` component, which is why this PR contains changes to wrap it in a `Card` like everything else. 
1. `npm ci && npm run clean && npm run  build:webpack`
2. Navigate to `Newspack->Components Demo` 
3. Verify correct widths of all elements at all breakpoints (0-660px, 660px-1024px, 1024px+). 
Note: the Muriel Grid Chrome extension is useful for testing: https://chrome.google.com/webstore/detail/muriel-grid/heabkjiofmaphebjodoflpglpkdojpmg?hl=en
> Muriel Grid WIP

- includes/wizards/class-wizard.php
This PR simply adds the Wizard ID as a class on the containing element. Previously it had been added only as an `id`. This will allow for slightly easier/nicer CSS scoping.
1. Verify there are no visible changes.
2. Inspect the containing element of wizards and verify that the `id` is also one of the classes.
> Wizard Container Class

- assets/components/src/plugin-installer/index.js
- assets/components/src/plugin-installer/style.scss
- assets/components/src/with-wizard/index.js
- assets/wizards/componentsDemo/index.js
This PR improves the plugin installer loading UI in a few ways:
1) Previously wizards with required plugins always defaulted to the `/` route after plugin installation. This has been reworked here so that a wizard can begin  on a deeper route but still perform plugin installation check.
2) Even if all plugins have been installed, there will be a flash of the "Required plugins" header before the initial plugin data is retrieved. Replacing `onComplete` with a more sophisticated `onStatus` event makes it possible to hide this header.
3) "Retrieving plugin information" UI with `Spinner` added to `PluginInstaller`.
1. On `master` branch navigate directly to `/wp-admin/admin.php?page=newspack-subscriptions-onboarding-wizard#/stripe`. Observe a flash of the `Required plugins` header. Observe …
> Improved Plugin Loading Flow

- assets/wizards/setup/index.js
Following the merge of https://github.com/Automattic/newspack-plugin/pull/140 the Set Up Wizard will no longer advance to the fourth screen. This is because 140 changes `PluginInstaller`'s completion even from `onComplete` to `onStatus`, but the Set Up Wizard did not implement this change.
1. On `master`, try the Set Up Wizard. Observe you cannot advance to the fourth screen with the Jetpack and Site Kit cards. The Plugin Installer progress bar will fill all the way but the button will remain disabled.
2. Branch switch to `fix/set-up-loading-issiue` and repeat the Wizard. This time you should be able to advance to the fourth screen.
> Fix Set Up Wizard Plugin Installer Completion Event

- assets/wizards/dashboard/style.scss
Adds hover state to non-disabled dashboard cards.
Closes #144.
2. Navigate to Newspack dashboard.
3. Hover over Reader Revenue and Advertising cards. Verify and assess hover state.
> Dashboard Hover State

- includes/wizards/class-components-demo.php
This PR makes it so that the Components Demo link in the admin menu is only visible if `WP_DEBUG` is enabled.
1. In your `wp-config.php` add `define('WP_DEBUG', true);` if it's not already there. You should see a link to the Components Demo in the admin menu.
2. Change `WP_DEBUG` to `false`. You should not see a link to the Components Demo in the admin menu.
3. Delete the `WP_DEBUG` line entirely. You should not see a link to the Components Demo in the admin menu.
> Only show Components Demo if WP_DEBUG is enabled

- assets/components/src/index.js
- assets/components/src/wizard-pagination/index.js
- assets/components/src/wizard-pagination/style.scss
- assets/wizards/setup/index.js
This PR adds the `WizardPagination` component and uses it in the Set Up Wizard. The component will render a BACK button in the upper left corner and "Page {n} of {total}" UI in the upper right corner. 
`WizardPagination` should be added anywhere within a `HashRouter`. The use of `withRouter` will cause errors if used outside of a router. The component requires one prop: `routes`. This should be an array of the page routes, in order. In an earlier iteration (https://github.com/Automattic/newspack-plugin/pull/113) I played with deriving the array of routes programmatically, but recent work on the plugin requirements handling illustrated that there will be `Routes` found that should not be included in pagination, so I opted to specify them manually.
One UI question for @sonjaleix: the …
> Wizard Pagination

- assets/wizards/checklist/index.js
- assets/wizards/subscriptions/index.js
- assets/wizards/subscriptionsOnboarding/index.js
- includes/api/class-wizards-controller.php
- includes/class-api.php
- includes/wizards/class-wizard.php
- tests/unit-tests/api-wizards-controller.php
This PR adds functionality for marking a wizard complete, and endpoints also. I've updated the Checklist to handle this and added completion tracking for the 2 subscription wizards. In the API there is a `newspack/v1/wizards/{slug}` endpoint for getting a wizard's info/status and a `newspack/v1/wizards/{slug}/complete` endpoint for marking a wizard as complete.
2. Go to the Reader Revenue checklist.
3. Go through the Subscriptions Onboarding wizard. After the last Save, observe it gets marked complete in the checklist.
4. Go through the Subscriptions wizard. Save at least one subscription. Observe it gets marked complete in the checklist.
After this milestone's work is complete I'd like to consolidate the existing and new endpoints into one simple …
> Checklist completion

- includes/class-newspack.php
With testing beginning of Newspack onboarding flows it's useful to have a temporary way to reset all Newspack options. This branch introduces a way to  do this by adding `&reset_newspack_settings=1` to a wp-admin URL.   
2. Go through the Set Up Wizard completely, which sets an option that unlocks the Dashboard. Populate some of the fields along the way.
3. On the dashboard, add `&reset_newspack_settings=1` to the end of the URL and load the page.
4. Verify this deletes all Newspack options, which then returns you to the Set Up Wizard and makes the dashboard inaccessible again. As you go through Set Up any fields you had populated should be blank again.
> Reset Newspack

- assets/components/src/button/style.scss
Removes white background and outline when tertiary buttons are clicked.
Closes #151 .
1. Go to any wizard.
2. Click and hold the button at the bottom that returns to the checklist or dashboard.
3. Verify there is no longer a white background and border on this button.
> Fix Tertiary Button Focus State 

- assets/components/src/with-wizard-screen/index.js
- assets/shared/scss/_muriel-component.scss
- assets/wizards/performance/index.js
- assets/wizards/performance/style.scss
- assets/wizards/performance/views/add-to-homescreen/index.js
- assets/wizards/performance/views/add-to-homescreen/style.scss
- assets/wizards/performance/views/index.js
- assets/wizards/performance/views/intro/index.js
- assets/wizards/performance/views/offline-usage/index.js
- assets/wizards/performance/views/push-notifications/index.js
- includes/class-newspack.php
- includes/class-plugin-manager.php
- includes/class-wizards.php
- includes/configuration_managers/class-configuration-manager.php
- includes/configuration_managers/class-configuration-managers.php
- includes/configuration_managers/class-progressive-wp-configuration-manager.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-performance-wizard.php
This PR introduces the Performance Wizard. This wizard names [Progressive WP](https://wordpress.org/plugins/progressive-wp/) and [PWA](https://wordpress.org/plugins/pwa/) as dependencies, and configures Progressive WP for Save To Homescreen, Offline Usage, and Push Notification features. In addition to normal Wizard activity, this adds a few other things:
- `withWizardScreen` has a `noCard` option. In this option the screen is not wrapped in a `Card` which allows for multi-Card layouts like the first screen of the wizard.
- The configuration manager updates another plugin's options, that are serialized in a single option.
- The configuration manager gets and updates one field which is part of core—the Site Icon.
Note: Newspack does not yet have a Muriel-ized Toggle control, so I'm using …
> Performance Wizard

- assets/components/src/action-card/index.js
- assets/components/src/action-card/style.scss
- assets/components/src/card/style.scss
- assets/wizards/checklist/index.js
- includes/class-checklists.php
This PR establishes an alternate, simpler style for checklists. A simple checklist is just a collection of `ActionCard`s, each of which is fully clickable. The cards also have a right-pointing arrow instead of action text. This is meant to be used for checklist screens where the idea of completing items in order doesn't apply. 
2. Navigate to the Advertising checklist.
3. There will be only one item in the checklist. 
4. Observe the new style, verify the entire card is clickable, verify hover state.
> ActionCards Checklist Style

- assets/components/src/wizard-pagination/index.js
- assets/wizards/setup/index.js
This PR fixes a bug that caused the Set Up Wizard's `PluginLoader` to incorrectly report completion. The loading bar will also be hidden on the fourth screen (which is only accessible after all plugins are loaded.)
2. Delete some plugins, and run the Set Up Wizard.
3. Verify that the button on the third screen remains disabled until plugins are loaded, and becomes enabled after they are done.
4. On the fourth screen, verify there is no loading bar anymore.
> Set Up Wizard Loading Fixes

- includes/configuration_managers/class-progressive-wp-configuration-manager.php
- includes/wizards/class-performance-wizard.php
This PR adds the ability to persistently enable/disable the Add to Homescreen and Push Notification features of the PWA wizard. It's not really possible to disable the offline support feature as far as I can tell.
1. Disable the Add to Homepage toggle when going through the wizard. Observe it persists on refresh. Go to `/wp-admin/admin.php?page=progressive-wordpress`, and observe it's marked 'disabled'. Do the same thing for the toggle 'enabled'.
2. The toggle on the Offline Usage screen doesn't do anything.
3. Enable/Disable the toggle for Push Notifications screen like in step 1.
> Functionality for enabling/disabling modules in PWA wizard where possible

- .gitignore
- composer.json
- composer.lock
- package.json
Releases can now be accessed at https://github.com/Automattic/newspack-plugin/releases.
How the Releases work:
- when a `tag` is added to a commit and pushed to the origin repo, GitHub automatically creates a new Release and attaches two files to it -- `Source code (zip)`, and `Source code (tar.gz)`,
- we can then edit this newly created Rlease and upload our built archive to it,
- and the expected name for the build archive is `newspack-plugin.zip`
Since we're defining `newspack-plugin.zip` as the name for the archive (and making sure we upload it), we/ll always have access to the current build archive via this link:
https://github.com/Automattic/newspack-plugin/releases/latest/download/newspack-plugin.zip
(explained here https://help.github.com/en/articles/linking-to-releases).
Closes …
> Script create release package

- assets/components/src/plugin-installer/index.js
This PR switches the endpoint `PluginInstaller` uses from `/newspack/v1/plugins/{plugin-slug}/activate` to `/newspack/v1/plugins/{plugin-slug}/configure`. The configure endpoint will install, activate, and finally run the plugin's Configuration Manager's `configure()` method. At this point, the only actual change here is that AMP will be initially set to `Standard` mode on installation.
1. If AMP is installed, go to AMP's settings page and set Mode to "Reader" or "Transitional". 
2. From the plugins page, uninstall AMP.
3. Go to Newspack->Set Up and run through the wizard. 
4. Return to the AMP settings page and verify that mode is now "Standard."
> Configure Plugins After Install

- assets/components/src/with-wizard/index.js
- assets/components/src/with-wizard/style.scss
- assets/wizards/subscriptions/index.js
- assets/wizards/subscriptionsOnboarding/index.js
- assets/wizards/subscriptionsOnboarding/views/locationSetup.js
Closes #76 .
This PR adds functionality for handling loading to the `withWizard` component. While loading the screen is overlayed with an element that prevents users from clicking on anything and a loading UI is displayed. I've implemented this UI based on the [Material design guidelines for indeterminate progress bars](https://material.io/design/components/progress-indicators.html#) and the Muriel designs for progress bars. They're currently not available as a stand-alone component, but if that's desired let me know.
To make usage simple, I've defined a new `apiFetch` method on `withWizard` that automatically handles loading UI. Usage is the same as `apiFetch`, you just load up `apiFetch` from `withWizard` instead of `@wordpress/api-fetch`. It can handle multiple concurrent API calls, …
> Loading UI and use loading UI in Subscriptions wizards

- includes/wizards/class-google-ad-manager-wizard.php
Fixes mangled Ad Unit titles when there's an `x` in them, e.g. "Ad Unit 300x60" 
Closes https://github.com/Automattic/newspack-blocks/issues/51
Before:
After:
1. On `master` branch, navigate to Google Ad Manager Widget, and create an Ad Unit. Name it "Ad Unit 300x200" and Save.
2. Observe that the title contains raw ASCII code.
3. Switch to this branch, run `npm ci && npm run clean && npm run build:webpack`
4. Refresh the page. Observe the title displays correctly.
This fix will also apply to the Ad Unit Select control in the Google Ad Manager block: https://github.com/Automattic/newspack-blocks/pull/39
> Fix Ad Unit Titles

- assets/wizards/googleAdManager/index.js
- assets/wizards/googleAdManager/views/editAdUnitsScreen.js
- assets/wizards/subscriptions/index.js
- assets/wizards/subscriptions/views/editSubscriptionScreen.js
*  [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
Closes #136  .
This PR updates the Subscriptions and Ad Manager wizards to match the changes in #136: When editing there are "Save" and "Cancel" buttons, and when managing there are "Add" and "Back to checklist" buttons.
2. Go to Subscriptions and Ad Manager wizards and verify things look good and still work.
> Tweak Subscriptions and Ad Manager wizard buttons to better match designs.

- assets/wizards/googleAdManager/index.js
- assets/wizards/googleAdSense/index.js
- assets/wizards/googleAdSense/views/adSenseSetup.js
- assets/wizards/googleAnalytics/index.js
- assets/wizards/googleAnalytics/views/googleAnalyticsSetup.js
- assets/wizards/performance/index.js
- assets/wizards/setup/index.js
This PR updates the existing wizards that don't have loading handling yet to use `withWizard`'s loading handling. As part of this work, I had to do some minor refactoring around the Site Kit handoff wizards to make them official wizardScreens instead of loose conglomerations of components. 
There should be loading UI in all the wizards where needed after this PR.
Go through the following wizards and observe loading UI when a screen loads or is saved:
1. AdSense wizard
2. Ad Manager wizard
3. Analytics wizard
4. Performance wizard
5. Setup wizard
> Sprinkle some loading throughout the wizards

- assets/components/src/with-wizard/index.js
- assets/wizards/dashboard/style.scss
- assets/wizards/dashboard/views/tier.js
This PR fixes a couple lingering style issues from the Muriel Grid implementation:
- Align/size dashboard cards to the grid
- Align/size the required plugins installer to the grid
2. Go to dashboard. Verify things look nice at all breakpoints. Verify things match to grid at all breakpoints.
3. Go to a wizard with a required plugin that you don't have active. Verify the required plugins screen matches the grid nicely.
> Fix Grid style issues

- assets/wizards/googleAdManager/index.js
- includes/class-plugin-manager.php
- includes/configuration_managers/class-configuration-managers.php
- includes/configuration_managers/class-newspack-ads-configuration-manager.php
- includes/wizards/class-google-ad-manager-wizard.php
In https://github.com/Automattic/newspack-ads/pull/4 the `newspack-gam` plugin has been renamed `newspack-ads`. This PR implements this name change in the Newspack Plugin.
Complete testing instructions found here: https://github.com/Automattic/newspack-ads/pull/4
> Switch newspack-gam to newspack-ads.

- assets/components/src/with-wizard/index.js
This addresses a React warning. In `withWizard` the plugin requirements `<Route>` is wrapped by a `<Grid>` component, which leads to this warning in the console:
```
react-dom.165d5c53.js:500 Warning: React does not recognize the `computedMatch` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `computedmatch` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in div (created by Grid)
in Grid (created by _temp)
in Switch (created by GoogleAdManagerWizard)
in Router (created by HashRouter)
in HashRouter (created by GoogleAdManagerWizard)
in GoogleAdManagerWizard (created by _temp)
in div (created by _temp)
in _temp
```
This PR moves the `<Grid>` component into the `<Route>`'s …
> Move <Grid> wrapper inside the plugin requirements route's render.

- assets/components/src/action-card/index.js
- assets/components/src/action-card/style.scss
- assets/wizards/componentsDemo/index.js
This PR adds an optional toggle to the left side of `ActionCard`. This is a UI pattern @sonjaleix has been using instead of checklists. The first use is in the Advertising wizard. 
There are two new `ActionCard` props:
- `toggleChecked`: The state of the toggle.
- `toggleOnChange`: An `onChange` handler for the toggle. The `ToggleControl` will only be rendered if `toggleOnChange` is set.
Note that `toggleOnChange` takes precedence over `image`. If both are set, the toggle will be rendered and the image will not. 
2. Navigate to Components Demo and observe the new example `ActionCard` with toggle.
> Action Card Toggle Control

- assets/components/src/index.js
- assets/components/src/tabbed-navigation/index.js
- assets/components/src/tabbed-navigation/style.scss
- assets/components/src/with-wizard-screen/index.js
This PR creates a `<TabbedNavigation>` component and implements it in `withWizardScreen`. This will be a common navigation style used in most (if not all) wizards.
Tabbed Navigation isn't actually used in any Wizards in this PR, so the best way to test is to add the following prop to both Wizard Screens in the Subscription Onboarding wizard and give it a try. You should see results like the screenshot above:
```
tabbedNavigation={ [
{
label: __( 'Step 1' ),
path: '/',
exact: true,
},
{
label: __( 'Step 2' ),
path: '/stripe',
},
] }
```
> Tabbed Navigation

- assets/components/src/index.js
- assets/components/src/toggle-group/index.js
- assets/components/src/toggle-group/style.scss
- assets/wizards/componentsDemo/index.js
Creates `<ToggleGroup>` component. This component is a title and description with a toggle to the left. The children of the element are hidden unless the toggle is checked. The use case for this component is the Advertising Wizard view where ad placements are switched on and defined:
1. `npm ci && npm run clean &&  npm run build:webpack`
2. Navigate to the Components Demo
3. Verify the appearance of the toggle group at the top. Toggle the switch and verify that additional content is revealed.
> Toggle Group

- assets/components/src/action-card/index.js
- assets/components/src/action-card/style.scss
- assets/wizards/componentsDemo/index.js
Action Cards will often be used to list plugins and products, and in some cases we'll need to indicate a variety of special statuses for these e.g.: PREMIUM, REQUIRES UPGRADE, etc. This PR introduces a `badge` prop on the `ActionCard` component, which adds such a badge.
Closes # .
1. Navigate to Components Demo.
2. Observe `ActionCard` example with badge.
> Action Card Badges

- includes/wizards/class-components-demo.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-donations-wizard.php
- includes/wizards/class-google-ad-manager-wizard.php
- includes/wizards/class-google-adsense-wizard.php
- includes/wizards/class-google-analytics-wizard.php
- includes/wizards/class-performance-wizard.php
- includes/wizards/class-reader-revenue-onboarding-wizard.php
- includes/wizards/class-setup-wizard.php
- includes/wizards/class-subscriptions-wizard.php
With the Gutenberg plugin installed, `wp-api-fetch` is not always loaded which causes Newspack wizards to fail. The bug can be hard to see since other other plugins load it, so the recommended testing flow involves removing all plugins except Newspack and Gutenberg. 
Closes #198 .
1. Keeping Newspack on `master`, install the Gutenberg plugin and disable all other plugins except for Newspack & Gutenberg.
2. Navigate to any Wizard. You should see a Javascript error and the wizard freezes on the loading screen. 
3. Switch Newspack to `fix/api-fetch-dependency`
4. Try all wizards. They should all load successfully.
> Add API Fetch Dependency To Wizards

- includes/class-checklists.php
- includes/wizards/class-components-demo.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-donations-wizard.php
- includes/wizards/class-google-analytics-wizard.php
- includes/wizards/class-mailchimp-wizard.php
- includes/wizards/class-newsletter-block-wizard.php
- includes/wizards/class-performance-wizard.php
- includes/wizards/class-reader-revenue-onboarding-wizard.php
- includes/wizards/class-setup-wizard.php
- includes/wizards/class-subscriptions-wizard.php
- includes/wizards/class-wizard.php
This PR adjusts and refactors the admin menu in a variety of ways:
- All unified wizards are now included. As of now this is only Performance and Advertising, but soon it will be all feature areas.
- The first item has been renamed "Dashboard" to avoid the duplication of Newspack.
- If Setup has not been completed the submenu will show only Setup.
Note: Because of these changes, when viewing a Checklist page or an older non-unified Wizard (e.g. Reader Revenue), the Newspack admin menu will not be illuminated and the submenu will not be shown. We shouldn't worry about this problem since both of these structures will be removed shortly. Example:
Closes #197.
1. Checkout the branch (no npm build necessary)
2. Click on Newspack in the admin menu. You should see Dashboard, Setup, Advertising, …
> Show Feature Areas In Admin Menu

- assets/components/src/button/button.test.js
- assets/components/src/button/index.js
- assets/components/src/button/style.scss
This PR makes a few adjustments to the styling of the `Button` component based on feedback from the Muriel team, described [here](https://github.com/Automattic/newspack-plugin/issues/177). 
_Note: The approach to centering `Button`s has been refactored. Originally centering was achieved by applying the `is-centered` class, which set the button's display to `block` and left/right margins to auto. The PR removes widths for the component, so this became problematic. Originally I tried setting the `Button` width to `fit-content`, but later removed this approach because of [insufficient browser support](https://caniuse.com/#feat=intrinsic-width). In the new approach, `Button`s with the `is-centered` class will be wrapped in a `<div>` with `text-align: center;`, which feels like a better …
> Button Component Styling

- assets/components/src/plugin-installer/index.js
- assets/components/src/plugin-installer/style.scss
- assets/components/src/with-wizard-screen/style.scss
This PR contains a series of UI improvements to the `PluginInstaller` component, described in https://github.com/Automattic/newspack-plugin/issues/187.
- Individual plugin install links have been removed. Now, the only action is the `Install` button at the bottom, which installs all of them.
- Uninstall UI has been removed. (@sonjaleix this was not requested in the issue but I assumed that the thinking would be identical as for removing individual plugin installation UI)
- Blue checkbox UI indicates success, replacing the words "In Use."
Closes #187.
1. `npm run build:webpack`
2. Navigate to Components Demo page and try out the example Plugin Installer.
3. Go to WordPress plugins page and deactivate or uninstall some of the plugins in the example, and try it again.
4. Bonus: Uninstall …
> Plugin Installer UI Improvements

- assets/components/src/index.js
- assets/components/src/secondary-navigation/index.js
- assets/components/src/secondary-navigation/style.scss
- assets/components/src/tabbed-navigation/style.scss
- assets/components/src/with-wizard-screen/index.js
Adds `SecondaryNavigation` component for second row of navigation which will be necessary in certain Wizards. 
This work is based on the following mockup:
Screenshot of actual implementation:
@sonjaleix I chose the name Secondary Navigation arbitrarily—is there a better name?
As with the [Tabbed Navigation PR](https://github.com/Automattic/newspack-plugin/pull/194), there isn't a use in an existing Wizard, so the best testing strategy is to add a secondary navigation to one Wizard and try it out.
1. Check out the branch. 
2. In `assets/wizards/advertising/index.js`, add the following attribute to the `<Placements>` element:
```
secondaryNavigation={ [
{
label: __( 'First Page' ),
path: '/google_ad_manager',
},
{
label: __( 'Selected Page' ),
path: '/ad-placements',
},
{
label: __( 'Third …
```
> Secondary Navigation

- assets/wizards/donations/index.js
The build can fail with the following error due to the uppercase D:
> ERROR in ./assets/wizards/donations/index.js
Module not found: Error: Can't resolve './views/DonationSettingsScreen' in '/home/philipjohn/vagrants/newspack/www/newspack/public_html/wp-content/plugins/newspack-plugin/assets/wizards/donations'
@ ./assets/wizards/donations/index.js 23:0-68 190:31-53
This change fixes that by making sure the reference has a lowercase 'd'
> Donations: Fix typo in dependency reference

- includes/class-newspack.php
- includes/wizards/class-setup-wizard.php
This is my first contribution, so please let me know if I’m making mistakes in the process. I’ll try to be as descriptive as possible.
The issue #226 is caused by the following:
class_wizard.php, on line 58, inside add_page() function is creating the submenu only for admin users, since the calling class “class-setup-wizard.php” is sending a capability of “install_plugins”.
The current code (class-setup-wizard.php) is trying to call the “hide_non_setup_menu_items()” function from all type of users, but only the admin users have the submenu created. This means that the $submenu global (which is declared inside the add_submenu_page() function from wp_admin/inclues/plugin.php) only exists for admins, hence the notice generated for users below admin level. (“Notice: Undefined index: …
> Fix #226: Prevent conflictive function from being called by users below admin level.

- includes/class-admin-plugins-screen.php
- includes/class-plugin-manager.php
The solution I propose is to add a flag to the premium plugins in the $managed_plugins array (class-plugin-manager.php) and use that flag to disable the Install button (class-admin-plugins-screen.php) on plugins marked as premium.
Closes #119  .
Follow the same steps proposed in the issue to reproduce the bug:
1. Uninstall WooCommerce Subscriptions (if it was already installed). 
2. Go to Plugins screen.
3. The WooCommerce Subscriptions Install button should be disabled.
> Fix #119: Disable Install button on premium plugins.

- includes/configuration_managers/class-site-kit-configuration-manager.php
- includes/wizards/class-advertising-wizard.php
Closes #211 
The underlying issue was that Site Kit keeps a list of active (but not necessarily configured) modules, and only registers/loads the settings screen for active modules. I've added methods to the Site Kit configuration manager to allow us to programmatically activate/deactivate Site Kit modules, and updated the wizard to use these.
1. In the advertising wizard, enable the AdSense toggle and click configure. Follow the handoff to the AdSense settings, which should now load correctly.
2. Disable the AdSense toggle in the advertising wizard. Go to the Site Kit connected services and observe AdSense is not in the list any more.
> Fix AdSense handoff issues

- includes/class-donations.php
This PR makes 2 small changes necessary for NRH checkout support:
- Adds a filter for modifying the checkout page redirect.
- Makes the `remove_donations_from_cart` method public because it's handy and useful for other integrations (like NRH checkout integration).
1. Add the following code somewhere:
```
add_filter( 'newspack_donation_checkout_url', function($url){ return site_url(); } );
```
2. Use the Donate block, observe you get redirected to the home page upon form submission.
> Enable alternate Donation form checkout locations.

- includes/class-admin-plugins-screen.php
- includes/class-plugin-manager.php
Adds a dismiss-able warning-level notification to Newspack dashboard pages listing unsupported plugins that are installed and active. 
1. Install and activate one or more plugins that are not supported by Newspack. 
2. Navigate to any page within the Newspack dashboard.
3. Observe notification about these plugins:
4. When no unsupported plugins are active, observe that the notification is not displayed.
5. Observe the notification is not displayed on non-Newspack pages.
6. Plugin names should be links to the plugin's page if one is available.
> Unsupported Plugin Notification

- assets/wizards/advertising/views/placements/ad-picker/index.js
- includes/wizards/class-advertising-wizard.php
This PR addresses a situation where only one Ad Service is enabled and because of this the service cannot be selected, making it impossible to view the Ad Unit select. This addresses the problem in two ways:
- If only one Ad Service is enabled, the data returned by the API will have that service automatically selected for all placements.
- The first item in the Select form elements is no longer disabled. This means it is possible to make a selection when there is only one item. It also means the Ad Unit can be unset, which was previously impossible.
1. `npm run build:webpack`
2. Navigate to Advertising Wizard.
3. Turn on only Google Ad Manager. 
4. Click Global Settings tab, switch on one or more placements.
5. Observe that the Ad Provider select is automatically set to Google Ad Manager …
> Ad Picker Improvements

- includes/class-donations.php
Closes #242  . See that issue for backstory.
This PR makes it so that the created/updated price for the 'once' frequency is 12 * the monthly frequency.
1. [Check out the companion PR to this](https://github.com/Automattic/newspack-blocks/pull/69).
2. Re-save the donation settings, or save them the first time if you haven't saved them yet.
3. Go to the Donate landing page, observe Once tab in the editor is 12 * monthly price. Go to Donate landing page in the frontend, observe Once tab in the frontend is 12 * monthly price. Click to make a one-time donation, observe the correct value gets added to the cart.
> Update 'once' donation price logic

- assets/wizards/setup/index.js
- includes/class-plugin-manager.php
- includes/configuration_managers/class-configuration-managers.php
- includes/configuration_managers/class-newspack-theme-configuration-manager.php
- includes/util.php
This PR adds the Newspack Theme to the list of plugins and takes care of handling it as an unusual case. The theme is installed as part of the Setup Wizard. The PR also includes a stub of a configuration manager for the theme, which at present only sets the colors to be default (which is  the theme default anyway). This configuration manager will eventually be the main interface between the Site  Design wizard and the Theme. The PR also contains some minor UI/text changes to the Setup Wizard to indicate that the theme is being installed as well as plugins.
1. Check out this branch, run `npm run build:webpack`
2. Deactivate and delete the theme.
3. Run through the Setup Wizard. 
4. Verify that the theme has been installed and is the active theme.
> Install The Newspack Theme

- assets/components/src/action-card/index.js
- assets/components/src/handoff/index.js
- assets/wizards/componentsDemo/index.js
This PR adds Handoff support to Action Cards, allowing the primary button to be configured as a handoff link to another plugin. The `ActionCard` component now takes optional `handoff` and `editLink` parameters. `handoff` should be the slug of the plugin to handoff to, and `editLink` optionally allows setting the exact URL to go to which is useful if you wish to target a specific page within the plugin's dashboard.
1. Check out the theme, run `npm run build:webpack`
2. Navigate to `Components Demo` (`/wp-admin/admin.php?page=newspack-components-demo`)
3. Observe two new `ActionCard` examples, as shown in the screenshot above. 
4. Clicking `Configure` in the first should lead to Jetpack's main dashboard.
5. Clicking `Configure` in the second should lead to the Jetpack Setting page.
6. In …
> Action Card: Handoff Functionality

- assets/components/src/with-wizard/index.js
This PR makes the Newspack logo at the top of Wizards into a link back to the Dashboard.
1. `npm run build:webpack`
2. Navigate to Wizards, click the logo at the top.
3. Verify these link to the Dashboard.
> Logo Link To Dashboard

- assets/wizards/setup/index.js
Add Newspack Blocks as a required plugin to be installed by the Setup Wizard.
1. Switch to this branch, run npm run build:webpack
2. If already installed, deactivate and delete Newspack Blocks
3. Run through the Setup Wizard.
4. Verify that Newspack Blocks plugin is installed and activated.
> Add Newspack Blocks As Required Plugin

- assets/wizards/setup/index.js
We kept the Gutenberg plugin out of the Setup wizard due to a few conflicts with the AMP plugin (https://github.com/ampproject/amp-wp/pull/3100 and https://github.com/ampproject/amp-wp/issues/2870). Now that these are resolved, Gutenberg plugin should be required. 
1. Switch to this branch, run `npm run build:webpack`
2. If already installed, deactivate and delete the Gutenberg plugin
3. Run through the Setup Wizard.
4. Verify that Gutenberg plugin is installed and activated.
> Add Gutenberg As Required Plugin

- assets/components/src/handoff/index.js
The `Handoff` component makes an API request to retrieve data about the plugin it is handing off to. If the component is removed before the request returns, the following warning is seen in the console:
```
backend.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
in Handoff (created by _class)
```
It's just a warning, but worth fixing. This PR uses the approach described here to resolve: https://www.robinwieruch.de/react-warning-cant-call-setstate-on-an-unmounted-component
1. On `master` branch, connect Jetpack (if not already connected), then go to the Setup Wizard and click through to the Jetpack …
> Fix Handoff React State Update When Unmounted

- assets/components/src/plugin-installer/index.js
- assets/components/src/with-wizard-screen/index.js
- assets/wizards/setup/index.js
- assets/wizards/setup/views/installation-progress/index.js
Fixes a few issues with the Setup wizard that caused sporadic installation failures. The issues relate to the rendering of the `InstallationProgress` view which contains the `PluginInstaller` component. In the `Welcome` route (`/`) `InstallationProgress` isn't rendered at all. Then, in all subsequent views it's rendered hidden, with one exception: if installation is not yet complete the `Newsroom` view's Continue button leads to a visible version of the `InstallationProgress` screen. Due to problems in the handling of the `hidden` prop, this visible version of `InstallationProgress` caused `PluginInstaller` to re-mount, which led to two competing plugin installation API calls at the same time. In this situation the first API request succeeds, but the second one fails because the plugin …
> Fixes To Setup Wizard Plugin Installation

- assets/wizards/setup/index.js
- includes/wizards/class-dashboard.php
This is the first of a few PRs that stubs out the remaining disabled Wizards with very basic functionality. This one enables the Site Design card, which links directly to the Customizer.
Blocked by https://github.com/Automattic/newspack-plugin/pull/249.
1. Check out the branch, run `npm run build:webpack`
2. Navigate to Dashboard, click Site Design.
3. Verify you are taken to the Customizer.
4. Click the X above the Customizer left panel, and verify you  are returned to Newspack.
> Site Design Wizard: Stub

- assets/wizards/syndication/index.js
- assets/wizards/syndication/views/index.js
- assets/wizards/syndication/views/intro/index.js
- includes/class-newspack.php
- includes/class-plugin-manager.php
- includes/class-wizards.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-syndication-wizard.php
This is a stub of the Syndication Wizard. It adds the [Facebook Instance Articles](https://wpvip.com/plugins/facebook-instant-articles/) and [Publish To Apple News](https://wordpress.org/plugins/publish-to-apple-news/) plugins, which are both dependencies of the Wizard. The UI consist of two Action Cards each with a Handoff to one of the two plugins. 
Blocked by https://github.com/Automattic/newspack-plugin/pull/247
1. Check out the branch, run `npm run build:webpack`
2. Navigate to the Newspack Dashboard, and click the Syndication card.
3. Observe the Search Engine Optimization wizard, as shown in the screenshot.
4. Click Configure for each Action Card, and verify you are taken to the appropriate plugin with a Newspack Handoff banner at the top of the screen.
> Syndication Wizard: Stub

- assets/components/src/action-card/index.js
- assets/wizards/seo/index.js
- assets/wizards/seo/views/index.js
- assets/wizards/seo/views/intro/index.js
- includes/class-newspack.php
- includes/class-wizards.php
- includes/wizards/class-dashboard.php
- includes/wizards/class-seo-wizard.php
This is a stub of the SEO Wizard with basic functionality: two Action Cards, one for Yoast and one for Jetpack. 
Blocked by https://github.com/Automattic/newspack-plugin/pull/247
1. Check out the branch, run `npm run build:webpack`
2. Navigate to the Dashboard and click on the SEO card. 
3. Observe two Action Cards like the screenshot.
4. Click `Configure` links for both and verify you are taken to the Yoast and Jetpack dashboards, with the Newspack Handoff Banner at the top.
> SEO Wizard: Stub

- includes/class-admin-plugins-screen.php
- includes/class-plugin-manager.php
This plugin adds to the unsupported plugin notification. If required plugins are not installed and activated, these will be listed in the notification, in this syntax:
"The following plugins are required by Newspack but are not active: "
If the Newspack Theme is not active this will be described too, in this syntax:
"The Newspack Theme is not currently active."
If required plugins are missing the notification will use error UI (red) otherwise warning (orange). 
The current list of supported plugins is found [here](https://github.com/Automattic/newspack-plugin/blob/add/missing-plugin-notifications/includes/class-plugin-manager.php#L43-L196) and required plugins [here](https://github.com/Automattic/newspack-plugin/blob/add/missing-plugin-notifications/includes/class-plugin-manager.php#L24-L3 …
> Notifications For Missing Required Plugins, Theme

- includes/class-amp-enhancements.php
- includes/class-newspack.php
Closes https://github.com/Automattic/newspack-issues/issues/18
This PR introduces an `AMP_Enhancements` class so we can make small tweaks to third party plugins for better AMP-compatibility. The DocumentCloud plugin repo hasn't seen any action or releases in years, so AMP compatibility is not likely to be fixed at the source. 
A class for third-party plugin AMP-compatibility tweaks seems like an easier solution to maintain than having separate plugins for AMP-compatibility (e.g. DocumentCloud-AMP, Broadstreet-AMP, MailChimp-AMP, etc.). If you disagree, let me know; I'm open to all ideas.
1. [Follow steps to reproduce from this issue](https://github.com/ampproject/amp-wp/issues/3142) and verify everything looks good in AMP.
> Introduce AMP Enhancements class and fix DocumentCloud AMP compatibility

- includes/class-plugin-manager.php
Fixes bug causing PHP warnings if required plugins are uninstalled.
Closes https://github.com/Automattic/newspack-plugin/issues/265
1. Deactivate and uninstall AMP (or Jetpack/Sitekit/Gutenberg/PWA)
2. Navigate to Newspack Dashboard.
3. Observe that there are no PHP warnings.
4. Observe the Missing required plugins notification.
> Fix PHP Warnings

- includes/configuration_managers/class-jetpack-configuration-manager.php
- includes/configuration_managers/class-site-kit-configuration-manager.php
The Setup Wizard requires that both Jetpack and Site Kit be installed and connected. If either does  not meet these conditions, the user cannot proceed past the final two screens of the setup Wizard. This creates a pain point in local development, where the site often does not have a public URL. Without a public URL neither Jetpack nor Site Kit can be connected. 
In this branch, if the `WP_DEBUG` flag is true, the check no longer requires that JP/SK be connected. Installation is still required, but not connection.
Jurassic Ninja instances have `WP_DEBUG` set to true, so this is an ideal way to test.
1. Check out this branch and create a release `npm run release`
2. Spin up a new Jurassic Ninja instance https://jurassic.ninja/
3. Without activating Jetpack, go to the Plugins page and …
> Developer Mode: Skip Site Kit and Jetpack Connected Checks

- includes/class-amp-enhancements.php
See https://github.com/ampproject/amp-wp/pull/3209
I've kept the AMP_Enhancements class because of https://github.com/Automattic/newspack-plugin/pull/267, and we'll likely still need it for other situations.
> Remove DocumentCloud AMP compatibility tweak because it's fixed in AMP

- assets/wizards/analytics/views/intro/index.js
Changes the plugin slug to Google Site Kit, not the Apple News plugin.
The plugin handoff component incorrectly points to the Apple News plugin, rather than the Google Site Kit plugin. This PR fixes that.
> Google Analytics: Fix plugin handoff

- assets/components/src/checkbox-control/style.scss
* Set the same height/width for the Dashicon as the actual checkbox
* Reposition the Dashicon so it sits perfectly on top of the checkbox
* Add a focus state to the checkbox to overwrite the default colour
Closes #295
1. Check out the branch and execute `npm run build:webpack`
2. Go through the Setup Wizard, and stop on screen 3 where there are 4 checkboxes at the bottom.
3. Click on one to check.
4. Observe the appearance of check.
5. Reduce browser to mobile width.
> Fix Dashicon height/width and position when checkbox is checked

- includes/class-plugin-manager.php
In https://github.com/Automattic/newspack-theme/pull/559, Laurel added support for Co-Authors Plus to the theme. This PR adds Co-Authors plus to the list of supported plugins, so that our endorsement of this plugin as our preferred solution is documented.
1. Go to Plugins screen.
2. Install and activate Co-Authors Plus through the Newspack supported plugins section of the Plugins screen.
> Add Co-Authors Plus as a supported plugin

- assets/components/src/wizard-pagination/index.js
- assets/components/src/wizard-pagination/style.scss
- assets/wizards/setup/index.js
* Rename "Page" to "Step"
* Use a button isLink instead of a link for the Back button
* Have Step and Back on top of each other
* Define a max-width on the wrapper based on the Grid
__Before:__
__After:__
1. Switch to this branch and run `npm run build:webpack`
2. (Re)start the set up of the plugin
3. Do you see the new Back / Step x of y?
> Move the Wizard Pagination to the bottom and add new style

- assets/components/src/formatted-header/index.js
- assets/components/src/formatted-header/style.scss
- assets/components/src/with-wizard-screen/index.js
- assets/wizards/setup/index.js
I added an icon option to the Formatted Header.
I added different icons depending on the Step during the setup.
__Before:__
__After:__
1. Switch to this branch and run `npm run build:webpack`
2. (Re)start the set up of the plugin
3. Do you see the icon next to the title?
> Add an icon option to the Formatted Header + Add icons for the setup

- assets/components/src/with-wizard/index.js
- assets/components/src/with-wizard/style.scss
I'm adding a div around the Newspack Logo in the Wizard. This allows us to avoid having a full-width link.
1. Switch to this branch and run `npm run build:webpack`
2. (Re)start the set up of the plugin
3. Inspect the logo. Do you see a `<div class="newspack-logo-wrapper">` around the link?
> Add a wrapper around the `NewspackLogo`

- assets/wizards/advertising/index.js
- assets/wizards/analytics/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/engagement/index.js
- assets/wizards/health-check/index.js
- assets/wizards/performance/index.js
- assets/wizards/readerRevenue/index.js
- assets/wizards/seo/index.js
- assets/wizards/syndication/index.js
I'm adding a header icon (next to the header text) to all the different wizard screens:
* Advertising
* Analytics
* Components Demo
* Engagement
* Health Check
* Performance
* Reader Revenue
* SEO
* Syndication
_Icons are based on Material_
1. Switch to this branch and run `npm run build:webpack`
2. Go through the different screens in the plugin
3. Do you see an icon next to the title that matches it?
> Add header icons to the different wizard pages

- assets/components/src/select-control/style.scss
- assets/components/src/text-control/style.scss
- assets/wizards/setup/views/about/style.scss
With WordPress 5.3 and the introduction of some extra CSS for the forms, our inputs looked broken.
I'm overwriting this with default settings.
__Before:__
__After:__
1. Load a Newspack site without WP 5.3, check setup, step 2 or 3 -- Inputs should look fine.
2. Now do the same but on a site with WP 5.3, it should look broken now (like my screenshot above)
4. Check setup, step 2 or 3 -- Does it still look broken? It shouldn't 😊
> Fix input and select by resetting value added by WordPress 5.3

- includes/class-plugin-manager.php
- includes/configuration_managers/class-configuration-managers.php
- includes/configuration_managers/class-publish-to-apple-news-configuration-manager.php
Added in configuration manager for Apple News to save the default Apple News settings into the database upon install.  This then eliminates the PHP Warning message on post edit screen.
* [ X ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [ X ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ X ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
Closes #311 .
1. Using a clean install of Newspack
2. Install Syndication plugins, Apple News …
> Apple News Configuration Manager #311

- includes/class-plugin-manager.php
This plugin has been ready for a little while, and there is solid demand for it. Adding it to our list of plugins makes our preferred image credit plugin known and makes it easy to install and activate the plugin.
1. Go to Plugins screen. Install and activate the plugin from the "Newspack Image Credits" entry in the Newspack plugins section.
> Add Newspack Image Credits to managed plugins

- includes/class-plugin-manager.php
This PR adds Newspack Popups to the supported plugins list now that it's ready for prime time.
1. Install and activate Newspack Popups through the Newspack section of the Plugins screen.
> Add Newspack Popups to supported plugins

- includes/class-plugin-manager.php
This PR adds Newspack Media Partners to the list of managed plugins for easy installation and maintenance.
1. Install and activate Newspack Media Partners through the Plugins screen.
2. (optional, if you want to see the plugin in action) You can create a new media partner at Posts > Media Partners. Give it a logo and a URL using the custom fields. On a post, assign the media partner. View on the frontend and you should see the logo injected into the content.
> Add Newspack Media Partners to supported plugins

- assets/components/src/index.js
- assets/components/src/notice/index.js
- assets/components/src/notice/style.scss
- assets/wizards/componentsDemo/index.js
This PR adds a new component: Notice. It can be used like so:
`<Notice noticeText={ __( 'This is an error notice.' ) } isError />`
* Supports: isError, isSuccess and isPrimary
* Content is displayed via `noticeText`
It will display a Material Icon (Success, Error, Info -- default ) next to it. Color of the SVG will depend of the "is" status (isError -- red, isSuccess -- green, isPrimary -- primary color)
2. Check the Components demo. Do you see the Notices?
> Notice: Add new component to the list available

- assets/components/src/index.js
- assets/components/src/waiting/index.js
- assets/components/src/waiting/style.scss
Similar to #324, I'd like to introduce a new component.
The goal is to replace `<Spinner />` from Core with an animated Material Icon that will match with the rest of the icons used throughout the plugin.
This component can be used like so:
`<Waiting isRight>`
* Supports: isRight, isLeft -- depending on which side there's text next to it.
__Before:__
__After:__
2. You can replace `<Spinner />` in Action Card if you want to see it in action and check the Components Demo (note: it won't be perfectly aligned, but that's something I will fix, either in a separate PR or in #322)
> Waiting: Add new component to the list available

- includes/class-newspack.php
This PR removes WordPress notifications from Newspack admin screens. The notifications significantly compete with the blue bar at the top, and this is even more noticeable in the redesign work occurring in https://github.com/Automattic/newspack-plugin/pull/322. A typical Newspack user is not likely to spend much of their time in the Newspack plugin (they will mostly be in the editor) so we can assume that important notices will be seen elsewhere. There is precedent  for this in other plugins such as Site Kit. 
This PR introduces one regression in that the Newspack unsupported plugins warning is no longer shown. In a separate PR let's find an alternate way to display this information that fits within the plugin's UI, cc:  @thomasguillot.
Before:
After:
cc: @pablohoneyhoney  …
> Suppress Notifications

- assets/components/src/text-control/index.js
- assets/components/src/text-control/style.scss
- assets/wizards/readerRevenue/components/money-input/style.scss
As part of the redesign of the plugin (see #322) I reworked/simplified the `TextControl` to behave in a similar way as Core, with the Newspack styles.
__Before:__
__After:__
I also took the opportunity to rework the Money Input by having the currency next to the input.
__Before:__
__After:__
_Note: I'm aware of a margin issue in the location setup. I plan to fix this in #322._
1. Check the Components Demo, Setup, Reader Revenue. You should see the current text inputs
3. Recheck the different pages. Do you see the new text inputs?
> TextControl: Update the component to simplify it and mostly rely on BaseComponent with custom styles

- assets/components/src/checkbox-control/index.js
- assets/components/src/checkbox-control/style.scss
- assets/components/src/info-button/index.js
- assets/components/src/info-button/info_24px.svg
- assets/components/src/info-button/style.scss
For both components, I'm removing the use of Muriel/Dashicon in favour of Material Icons. Plus a few visual fixes:
* Info Button:
* Use flexbox instead of absolute positioning
* Checkbox Control:
* Update font-size and line-height
* Update margins of elements within the checkbox container
__Before:__
__After:__
1. Best way to see the changes are via the Components Demo. Check the Checkboxes card.
3. Notice the new style.
> Update Checkbox Control and Info Button components with Material Icons

- assets/components/src/checkbox-control/style.scss
Replicated the Material style of the checkbox but with a border instead so we can add a hover state and it feels similar to `ToggleControl`.
By only having an SVG when the checkbox is checked we also offer a better support for browsers not supporting it (the tick when checked will be missing but at least the checkbox will be blue)
Finally, we remove Muriel colors.
2. Go to a page where we have checkboxes (e.g. Setup - Newsroom)
> Use less SVG for the Checkbox Control styles

- includes/class-plugin-manager.php
This PR re-arranges some variables to prevent passing in a variable by reference. This prevents an issue where installing a Newspack plugin from the Plugins screen throws an error like to following:
```
Notice: Only variables should be passed by reference in /srv/users/user55ac21bf/apps/user55ac21bf/public/wp-content/plugins/newspack-plugin-master/includes/class-plugin-manager.php on line 664
Warning: Cannot modify header information - headers already sent by (output started at /srv/users/user55ac21bf/apps/user55ac21bf/public/wp-content/plugins/newspack-plugin-master/includes/class-plugin-manager.php:664) in /srv/users/user55ac21bf/apps/user55ac21bf/public/wp-includes/pluggable.php on line 1265
Warning: Cannot modify header information - headers already sent by (output started at …
```
> Fix "Only variables should be passed by reference" warnings

- assets/components/src/wizard-pagination/index.js
- assets/components/src/wizard-pagination/style.scss
- assets/wizards/setup/index.js
- assets/wizards/setup/style.scss
Move the `WizardPagination` back to the top but with better handling of small screens and add Material Icon to the back button.
__Before (small screen):__
__Before (large screen):__
__After (small screen):__
__After (large screen):__
2. Run the Setup Wizard.
3. Does the Pagination sits at the top? Any issues?
> Move the wizard pagination to the top (like it used to be)

- assets/components/src/formatted-header/style.scss
- assets/components/src/with-wizard/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/seo/index.js
- assets/wizards/syndication/index.js
* Formatted Header: Add top/bottom margin to component + fix `subHeaderText` font-size and line-height
* With Wizard: Add an icon to the "Required plugin" `FormattedHeader`
* Components Demo: Update `subHeaderText`
* SEO: Update `headerText` and `subHeaderText`
* Syndication: Update `subHeaderText`
2. Check every of the plugin.
3. Do we have an icon and a subheader for every `FormattedHeader` we use? Does it look broken?
> Update the Formatted Header and make sure every Wizard Pages have `iconHeader` and `subHeaderText`

- assets/components/src/index.js
- assets/components/src/select-control/style.scss
- assets/components/src/text-control/style.scss
- assets/components/src/textarea-control/index.js
- assets/components/src/textarea-control/style.scss
- assets/wizards/advertising/views/ad-unit/index.js
- assets/wizards/advertising/views/header-code/index.js
Adds a new component of `TextareaControl` to the list. It's using `BaseComponent` and it visually matches `TextControl`.
Updated the margin when multiple form elements (input/select) are following each other.
And updated the Advertising pages to make sure they use our `TextareaControl`
1. Only place with the `TextareaControl` is in the Advertising Wizard.
2. You should see the default WordPress style.
4. Now it should look more like an input.
> Textarea Control: Add new component to the list, using `BaseComponent`

- assets/components/src/card/style.scss
Links used inside the Card component should be using the primary color and not Core's default blue.
1. Go to a page where there's a link. A good example is Engagement > Newsletter ("Set up Mailchimp on WordPress.com"
2. The link should be using WordPress's blue (#0073aa)
4. The link should now be using Newspack's primary color (#3366ff)
> Card: Make sure links are using the primary color

- assets/components/src/button/style.scss
* Remove dark background and use a slightly less dark one.
* Update the border and color accordingly
* Focus box-shadow to use Primary color
* Make sure transitions work
__Before:__
__After:__
1. Go to components demo. Check the isTertiary button. It should be very dark, almost black.
3. It's now using a lighter grey background.
> Button: Rework the tertiary button

- assets/components/src/checklist/index.js
- assets/components/src/info-button/index.js
- assets/components/src/notice/index.js
- assets/components/src/plugin-installer/index.js
- assets/components/src/task/index.js
- assets/components/src/waiting/index.js
- assets/components/src/with-wizard/index.js
- assets/components/src/wizard-pagination/index.js
- assets/wizards/advertising/index.js
- assets/wizards/analytics/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/dashboard/style.scss
- assets/wizards/dashboard/views/dashboardCard.js
- assets/wizards/engagement/index.js
- assets/wizards/health-check/index.js
- assets/wizards/performance/index.js
- assets/wizards/readerRevenue/index.js
- assets/wizards/seo/index.js
- assets/wizards/setup/index.js
- assets/wizards/syndication/index.js
- includes/wizards/class-dashboard.php
- package-lock.json
- package.json
Since the icons used around the plugin are coming from Material, I thought it would make sense to add `material-ui` as a dependency.
That way we can simply import the icon that we need instead of relying on SVG and Path.
I've removed all the different icons that were being displayed via `import { SVG, Path } from '@wordpress/components';` and replaced them with `import *Icon from '@material-ui/icons/*';`
2. Check all the pages
3. Do you see the icons everywhere (Title, checkboxes, notices etc...)?
> Add Material UI package to the dependencies and update all SVG to use icons from `@material-ui/icons`

- assets/components/src/action-card/style.scss
This PR improves the accessibility and makes sure that the secondary button on an action card is always visible.
1. Go to the Components Demo. Check an action card with a 2ndary button. You should only see the button on hover.
3. Refresh the Components Demo. Do you now see the 2ndary button?
> Action Card: Always display secondary button and remove unused CSS

- assets/components/src/with-wizard/index.js
This PR removes the Spinner component that is not being used.
2. Check if the plugin works as expected.
> With Wizards: Remove unused WordPress component

- assets/components/src/notice/style.scss
Adding a background colour to the `Notice` component depending on its status helps with differentiation over regular text.
1. Go to Components Demo (or any setup pages with a Notice)
3. Check that you see the Notice like in thee screenshot above
> Notice: Add background colour depending on status

- assets/components/src/button/style.scss
- assets/components/src/image-upload/index.js
- assets/components/src/image-upload/style.scss
- assets/wizards/componentsDemo/index.js
- assets/wizards/performance/views/intro/index.js
* Use Material Icon for add/remove image
* Uses `isTertiary` button
1. Go to Performance > Site Icon
2. The current button is easily missable as it doesn't look like a button.
4. Do you see a `isTertiary` button with an icon? Does the button work?
> Image Upload: Update component to use Newspack's `Button`

- assets/wizards/readerRevenue/index.js
- includes/class-plugin-manager.php
- includes/configuration_managers/class-configuration-managers.php
- includes/configuration_managers/class-laterpay-configuration-manager.php
- This PR adds support for LaterPay in Reader Revenue, it updates the plugins appearance color based on current primary and secondary color based on customizer.
Closes https://github.com/Automattic/newspack-plugin/issues/205 
- Please check following videos for detailed information on testing.
- Test on Default theme ( Twenty Nineteen ) - [video](https://drive.google.com/open?id=10G7lHTluxVb8V59j3tqz2-9omWiwuvGR)
- Test on NewsPack theme - [video](https://drive.google.com/open?id=1xxT9sT61UCxLGdYa2sIwuHxSz-WCQDpB)
- Make sure AMP Website Mode	is set to **Transitional**,  as the plugin doesn't support AMP yet, so the test would have to be done on non AMP post/page.
> Add support for LaterPay

- assets/components/src/card/style.scss
- assets/components/src/select-control/style.scss
- assets/wizards/advertising/views/placements/ad-picker/index.js
- assets/wizards/advertising/views/placements/ad-picker/style.scss
* Use flexbox to display select-control in 2 columns on larger screens
* Reduce default label content since it's redundant and we already have the label to describe what it is
* Card: Make sure `strong` is always using the bold font-weight
* Select Control: Make sure it's always being displayed at 100% 
Closes #346.
2. Check the Ad Picker. On small screens and large screens. Does it still look broken?
> Fix the ad picker select layout margins

- includes/class-admin-plugins-screen.php
- includes/class-plugin-manager.php
As Newspack develops feature plugins we're finding there's an awkward zone where the plugin is being installed and used on staging sites, but is not fully ready for a release. If the plugin has not been whitelisted in the plugin manager class there's a strange situation where the Health Check screen will flag a Newspack product as unsupported, which is weird. On the other hand, if the plugin has been whitelisted it will appear on the main plugin screen, which suggests it is fully released.  To work around this situation, this PR adds a `Quiet` param for plugins, which causes the plugin to be whitelisted but not appear on the plugins screen unless it has been installed. The Newspack Content Converter has been added to the whitelist with this setting.
1. On `master` install the [Newspack …
> Plugin "Quiet" Mode

- includes/class-plugin-manager.php
> Fix typo in newspack-content-converter plugin URL

- assets/wizards/readerRevenue/index.js
See https://github.com/Automattic/newspack-plugin/issues/205#issuecomment-570650796
It doesn't make sense to force people to install LaterPay in order to use the WooCommerce-based Reader Revenue features. LaterPay should have its own flow (design TBD; discussed in the above comment).
1. Go to Reader Revenue wizard. Observe you can access it without installing LaterPay.
> LaterPay shouldn't be a required plugin for WC integration

- assets/components/src/plugin-installer/index.js
Closes #334 .
From reported issue description.
1. Disable one of the syndication plugins
2. Go to Newspack > Syndication
3. Verify the button text is as expected
```
Test Suites: 3 passed, 3 total
Tests:       11 passed, 11 total
Snapshots:   0 total
Time:        14.411s
Ran all test suites.
```
> Make sure the installer wizard button text is based on plugin status

- assets/components/src/with-wizard/style.scss
- includes/class-newspack.php
- includes/class-settings.php
- includes/wizards/class-components-demo.php
- includes/wizards/class-setup-wizard.php
- Adds a "Reset" checkbox in Newspack->Settings, which will clear all Newspack options and redirect to the Setup Wizard.
- Adds links in Newspack->Settings to Setup Wizard and Components Demo.
- Removes Components Demo from the Admin Menu.
- Removes Setup from the Admin Menu if it has been completed.
Closes https://github.com/Automattic/newspack-plugin/issues/310
1. Navigate to Settings->Newspack.
2. Click "Reset Newspack," then Save Changes.
3. Observe you are redirected to the Setup Wizard and all Newspack options are cleared. This can be verified by checking the database (`SELECT * FROM wp_options WHERE option_name LIKE 'newspack%'`) or by noting that the Newspack Admin menu only contains Setup.
4. Complete the Setup Wizard.
5. Observe Setup is no longer in the Admin menu after it has …
> Reset Button, Menu Visibility

- includes/class-plugin-manager.php
This PR adds [Organic Profile Block](https://wordpress.org/plugins/organic-profile-block/) to the managed plugins list. This is by far the best author profile block plugin I've found for a number of reasons:
- It's stand-alone: No bloat or extra unnecessary blocks we need to deal with.
- It's clean: It doesn't add a bunch of promo materials and upsells to the admin.
- It's flexible: Since it doesn't require existing WP users, it can be used for all sorts of purposes: biographic info in articles, staff list, advisor list, etc.
1. Install and activate Organic Profile Block through the Newspack Plugins screen area.
2. On a post or page, add one or more Profile blocks.
3. You should see something like this on the frontend:
We may want to add a couple lines of CSS to the Newspack theme to …
> Add Organic Profile Block to managed plugins

- includes/class-plugin-manager.php
This PR adds Newspack Supporters to the list of managed plugins. This plugin should be widely useful for a variety of sites, especially nonprofits.
1. Install and activate Newspack Supporters through the Plugins screen.
2. If you want to test the plugin, [instructions are at the repo](https://github.com/Automattic/newspack-supporters).
3. Live demo is available at https://hechingerreport-newspack-2.mystagingwebsite.com/supporters/
Screenshot:
> Add Newspack Supporters to managed plugins

- assets/components/src/button/style.scss
- assets/components/src/modal/style.scss
- assets/components/src/with-wizard-screen/style.scss
- assets/components/src/wizard-pagination/style.scss
#314 # All Submissions:
Since Gutenberg 7.2.0, our Buttons are now "broken":
* Gutenberg removed the use of `is-button`
* Gutenberg added `is-secondary`
* Gutenberg added extra hover check (`&:not(:disabled):not([aria-disabled="true"]):not(.is-default):hover)
* Gutenberg removed `components-icon-button` in Modal
This PR fixes it.
Question: What shall we do regarding backward compatibility?
1. Make sure you have the latest version of Gutenberg (7.2.0)
2. Check the plugin and notice the buttons, they should look smaller and hover shouldn't display the correct color.
3. Disable Gutenberg and check again... it should look fine.
4. Switch to this branch and re-enable Gutenberg
5. Check the plugin again. It should look like step 3, aka fine.
> Button: Fix style missing since Gutenberg 7.2.0

- assets/components/src/action-card/index.js
- assets/wizards/advertising/views/adsense/index.js
- assets/wizards/engagement/views/commenting/index.js
- assets/wizards/engagement/views/newsletters/index.js
For the Engagement screens, replace the Dashicon with `Notice`.
For the Adsense screen, simply remove the import since it's not being used.
And also, remove the Dashicon from the `Action Card` and use `actionText` instead of `actionDisplay`
2. Check the Engagement screen. Do you see the notice when looking at the Newsletter tab (when connected to Mailchimp).
3. Check any action cards.
> Remove Dashicon component in Action Card and Wizards Screens

- assets/components/src/modal/style.scss
- assets/components/src/notice/index.js
- assets/components/src/notice/style.scss
- includes/class-plugin-manager.php
* Use `RawHTML` component instead of simple `span` to return the content of a Notice
* Fix links style in the Modal
* Update the error message of the Plugin Manager with a direct link to the plugin
__Before:__
__After:__
1. Disable WooCommerce Name Your Price. Then go to Reader Revenue.
2. Click on Install. You should see an error with no link, just plain text
```Newspack can not install this plugin. You will need to get it from http://www.woocommerce.com/products/name-your-price/ and install it manually.```
3. Switch to this branch. And refresh the page.
4. Try to install again.
5. You can also test by switch the branch of newspack-ads to `update/gam-interface` and try to load the Advertising Wizard (see screenshots above).
> Use `RawHTML` instead of span to return the noticeText

- assets/components/src/action-card/index.js
- assets/components/src/button/style.scss
- assets/components/src/modal/style.scss
- assets/components/src/with-wizard-screen/style.scss
- assets/components/src/wizard-pagination/style.scss
- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/ad-unit/index.js
- assets/wizards/advertising/views/ad-unit/style.scss
- assets/wizards/advertising/views/adsense/index.js
- assets/wizards/advertising/views/header-code/index.js
- assets/wizards/engagement/views/commenting/index.js
- assets/wizards/engagement/views/newsletters/index.js
- includes/class-plugin-manager.php
- includes/configuration_managers/class-newspack-ads-configuration-manager.php
- includes/wizards/class-advertising-wizard.php
This PR needs to be tested in tandem with https://github.com/Automattic/newspack-ads/pull/15. The two together bring a number of improvements to the Google Ad Manager integration. 
- Users no longer need to copy and paste raw code from the GAM dashboard, which was an awkward and tedious task.
- There is no longer a requirement that the user have the `unfiltered_html` capabilitiy.
- The risk of breaking a site by pasting slightly incorrect code is now removed.
- These changes pave the way for future iterations where Newspack synchronizes programmatically with a Google Ad Manager account.
- Users can now assign multiple sizes to a single Ad Unit.
- There's now a Widget. Ad Units can be placed in three ways: 1) pre-defined ad placements, 2) Gutenberg block, 3) Widget.
Ideally testing takes …
> Ad Wizard Improvements

- assets/components/src/with-wizard/index.js
- assets/components/src/with-wizard/style.scss
- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/ad-unit/index.js
- assets/wizards/advertising/views/ad-unit/style.scss
- assets/wizards/advertising/views/header-code/index.js
- includes/configuration_managers/class-newspack-ads-configuration-manager.php
- includes/wizards/class-advertising-wizard.php
In order to get visual feedback when clicking a button, this PR adds back the loading animation.
Go to the advertising wizard. And toggle the different ads providers
> Wizard: (Re)add loading animation

- assets/components/src/index.js
- assets/components/src/modal/style.scss
- assets/components/src/web-preview/index.js
- assets/components/src/web-preview/style.scss
- assets/wizards/componentsDemo/index.js
Adds the `WebPreview` component, which previews a website in an iFrame, with UI to resize to Desktop/Tablet/Phone sizes.
1. Navigate to Settings->Newspack, and click "Components Demo" in the footer.
2. In the `Web Previews` card, click `Preview Newspack Blog`.  
3. Observe an overlay appears with the Newspack Blog iFramed within. There should be a `Waiting` component visible until the site loads.
4. Try clicking the three device icons and observe changes to the dimensions of the website.
5. Click `Close`, observe the overlay disappears.
> WebPreview Component

- includes/class-plugin-manager.php
Fixes an issue Steve and I encountered while testing the Ads integration. On a fresh Jurassic.Ninja site, installing Newspack Ads through the Ads wizard causes a fatal error every time the screen is loaded.
```
2020-01-14T22:15:06+00:00 CRITICAL Uncaught Error: Call to undefined method Newspack_Ads_Model::get_network_code() in public/wp-content/plugins/newspack-plugin-3/includes/configuration_managers/class-newspack-ads-configuration-manager.php:43
```
1. Install the latest Newspack Plugin release on a fresh Jurassic.Ninja site. Go to the Advertising wizard, install the required Newspack Ads plugin through the wizard, observe you get a fatal error and are kicked back to the dashboard whenever the page is loaded.
2. Delete the Ads plugin, modify the URL of the download to the one from this …
> Install latest version of Newspack Ads from Newspack

- assets/components/copy-styles.js
- assets/components/package.json
It's been abut 8 months since the last published release of newspack-components. This PR updates the release script to make publishing work properly with the changes that have taken place since then.
~1. In this repo, `cd assets/src/components; npm install;`.~
1. In this repo, `cd assets/components; npm install;`. [Edited to fix path]
2. `npm publish --dry-run` to see what would be published.
3. In a separate repo where you want to use the components, [get the latest version of the npm package](https://www.npmjs.com/package/newspack-components).
4. Try something like this to verify the components can be used in third-party applications:
```
import { TextControl, Button, Card } from 'newspack-components';
import { Component, render } from '@wordpress/element';
class PackageTest extends …
```
> Update components publish script

- assets/components/src/action-card/index.js
- assets/components/src/notice/index.js
- assets/components/src/notice/style.scss
- assets/components/src/plugin-installer/index.js
- assets/components/src/with-wizard/index.js
- includes/class-plugin-manager.php
Makes `RawHTML` as an option.
Can be set by adding `rawHTML` to a Notice.
__Before:__
__After:__
1. If a notice uses something like `ExternalLink` as part of its content. It will look broken (see screenshot above).
2. Switch to this branch. And check all the notices.
> Fix the Notice RawHTML object conflict

- assets/components/src/button/style.scss
Gutenberg 7.2.0 introduced new classes for the buttons.
Sites not running the latest version of Gutenberg (or simply WP) will see "broken" buttons. This PR adds the old classes used by the buttons.
__Before:__
__After:__
_Note: there's still an issue with isLarge/isSmall/isTertiary but we don't use these during the setup so it's not too much of an issue._
1. Disable Gutenberg
2. Check the Setup wizard.
4. Refresh the Setup wizard.
5. You can do the same with the Components Demo for example.
6. Re-enable G7.2.0 and check if everything is still looking ok.
> Button: Fix styles when Gutenberg 7.2.0 is not yet installed

- includes/class-plugin-manager.php
The old Site Kit zip URL from Google's site installs Site Kit version `1.0.0-rc.3`. It doesn't look like they've continued updating that URL since Site Kit was released on WPORG. This PR updates the Site Kit location to WPORG so we install the latest version.
1. Download the file at `https://sitekit.withgoogle.com/service/download/google-site-kit.zip` or install Site Kit through Newspack without this PR. Observe it's version `1.0.0-rc.3`.
2. Apply this patch. Install Site Kit through Newspack. Observe it's version `1.2.0`.
> Install Site Kit from WPORG

- assets/components/src/category-autocomplete/index.js
- assets/components/src/form-token-field/index.js
- assets/components/src/form-token-field/style.scss
- assets/components/src/index.js
- assets/wizards/engagement/index.js
- assets/wizards/engagement/views/index.js
- assets/wizards/engagement/views/popups/index.js
- assets/wizards/engagement/views/popups/style.scss
- includes/configuration_managers/class-configuration-managers.php
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-engagement-wizard.php
~Adds a basic Pop-ups screen to Engagement Wizard, which requires installation/activation of the Newspack Pop-ups plugin. Must be tested with https://github.com/Automattic/newspack-popups/pull/34.~
This PR ads a Pop-Ups screen to the Engagement Wizard, which does the following:
- Manages installation of the Newspack Popups plugin.
- Allows selection of the Sitewide Default Pop-up, which is the popup that will potentially be shown on all pages, not just category pages. 
- UI to add category filters to Pop-ups.
- Button to create a new Popup.
The PR also introduces a Newspack-styled `FormTokenField` component and a Category Autocomplete component based largely on the Autocomplete Tokenfield component in Newspack Blocks (https://github.com/Automattic/newspack-blocks/blob/master/src/components …
> Engagement Wizard: Pop-Ups

- includes/class-starter-content.php
Fixes the homepage markup generated by the Starter Content Wizard so that Columns are not invalidated. 
Closes https://github.com/Automattic/newspack-plugin/issues/393
1. On a local instance, delete all Posts and Pages.
2. On `master` run through the Setup Wizard, including Starter Content.
3. Navigate to Pages->Homepage, verify the column blocks are invalid.
4. Switch to this branch, repeat steps 1-2.
5. Navigate to Pages->Homepage, verify the column blocks work properly and are not invalidated.
> Fix Starter Content Homepage Column Blocks

- newspack.php
The version was bumped to `alpha.15`, however we released `alpha.16` last week. This PR updates it to the actual next version.
> Bump version for release

- includes/class-plugin-manager.php
Whitelists the Password Protected plugin, which is typically used on staging sites before launch: https://wordpress.org/plugins/password-protected/
1. If Password Protected is installed, de-activate and delete it.
2. Check out `add/password-protected-plugin`. 
3. Navigate to Plugins admin page. 
4. Observe "Password Protected" is listed as a Newspack-supported plugin.
5. Install Password Protected.
6. Navigate to Newspack->Health Check and verify it is not listed there.
> Whitelist Plugin: Password Protected

- assets/components/package.json
Bump the version number of the components so we can update the NPM package: https://www.npmjs.com/package/newspack-components
> Newspack Components: Bump version number to update npm

- includes/class-newspack.php
- includes/class-plugin-manager.php
- includes/class-theme-manager.php
- includes/util.php
- tests/unit-tests/theme-manager.php
This PR moves theme management into a dedicated class (`Theme_Manager`), and adds functionality to install and activate the five Newspack child themes. 
There is now a test for installing each child theme, so in theory running tests may be all you need. To test theme installation in PHP, add this snippet to `newspack.php`:
```
add_action(
'init',
function() {
\Newspack\Theme_Manager::install_activate_theme( 'newspack-theme' );
}
);
```
Then, refresh the Themes page (you will actually need to refresh twice because the newly installed theme won't show as installed until the next request). Try this with all child themes and verify each is installed an activated successfully:
`newspack-theme`, `newspack-scott`, `newspack-nelson`, `newspack-katharine`, `newspack-sacha`, `newspack-joseph`
> Child Theme Installer

- assets/components/src/web-preview/index.js
- assets/wizards/componentsDemo/index.js
1. Renders the modal in a div appended to the body, this way there is more control over layering and the modal will always be on top of the admin UI. As it was before has worked fine in components preview, but when used in editor sidebar (https://github.com/Automattic/newspack-popups/pull/36) the modal was below the admin UI.
2. A new prop is introduced: `renderButton`. This lets the caller of this component render it's own button. This was used in https://github.com/Automattic/newspack-popups/pull/36 to disable the button until the post is saved. In general it enables total control over the `WebPreview`'s trigger styling (e.g. it might be a link, not a button).
1. Open components preview 
2. Click the "Preview Newspack Blog" button 
3. Observe that a model opens, and is placed towards …
> WebPreview: layering fix; renderButton prop

- includes/configuration_managers/class-woocommerce-configuration-manager.php
Closes #408 
The logic that turns the list of countries and states into a flat list had 2 situations that were being accounted for: when a country has no list of states and when a country has a list of states. There was a third scenario that wasn't being accounted for: when a country has *an empty* list of states (with info provided by WooCommerce). This PR tweaks the logic so that things work correctly in all 3 scenarios.
1. Go to Reader Revenue wizard and set an address in Germany:
2. Go to WooCommerce settings and verify everything saved correctly:
> Fix Reader Revenue select for countries with no states defined

- includes/class-amp-enhancements.php
- includes/class-plugin-manager.php
Closes https://github.com/Automattic/newspack-issues/issues/111.
MC4WP is used by multiple publishers, and it offers a lot of flexibility that we don't have with the Jetpack MailChimp block, like support for multiple newsletters. This PR adds AMP-compatibility to the plugin following @westonruter's [notes](https://wordpress.org/support/topic/form-error-on-2-pages/) I discovered in my research.
I'll offer this as a PR to the MC4WP repo also, because it would be better to have this enhancement upstream, but this PR is here for general review and in case they don't want it.
1. Install MC4WP via Newspack Plugins. Add your API key in the settings.
2. Create a form and add it to a page with the mc4wp shortcode.
3. In AMP and non-AMP mode try out the form. You should get the same look and …
> MC4WP support

- assets/components/src/index.js
- assets/components/src/plugin-installer/style.scss
- assets/components/src/plugin-toggle/README.md
- assets/components/src/plugin-toggle/index.js
- assets/components/src/plugin-toggle/style.scss
- assets/components/src/waiting/style.scss
- assets/wizards/componentsDemo/index.js
- assets/wizards/handoff-banner/style.scss
- includes/class-plugin-manager.php
Adds a component that allows toggling the installation of multiple plugins. The plugin has a [README](https://github.com/Automattic/newspack-plugin/blob/3a0dc567d90bc69de5b6c26876c851936fb1ccbc/assets/components/src/plugin-toggle/README.md) describing the use in more detail.
1. Checkout and build this branch.
2. On main Plugins page, deactivate WooCommerce and Instant Articles for WP.
3. Navigate to the Components Demo (Settings->Newspack then click on Components Demo link at the bottom).
4. Toggle WooCommerce on. After installation, the page should reload revealing the WC item in the left nav. The text to the right should read "Configure" and should be a Handoff link to WooCommerce.
5. Toggle Instant Articles for WP on. Verify the page does NOT reload. The text to the right should be …
> Plugin Toggle Component

- includes/class-starter-content.php
A few light improvements to Starter Content:
- Titles will now be longer (7-14 words).
- Titles will not have periods in them.
- Only the first letter of titles will be capitalized.
- The One-Column Wide template will no longer be used.
Closes https://github.com/Automattic/newspack-plugin/issues/413
1. In a local instance, delete all Posts.
2. Checkout the branch.
3. Navigate to the Set-Up Wizard (Settings->Newspack then click link at the bottom).
4. Step through the wizard and generate Starter Content.
5. View the posts that were created and verify the changes to title and template described above are accurate.
> Starter Content Improvements

- assets/components/src/action-card/index.js
- assets/components/src/action-card/style.scss
- assets/components/src/button/style.scss
- assets/wizards/engagement/index.js
- assets/wizards/engagement/views/popups/components/popup-action-card/index.js
- assets/wizards/engagement/views/popups/components/popup-action-card/style.scss
- assets/wizards/engagement/views/popups/index.js
- assets/wizards/engagement/views/popups/style.scss
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-engagement-wizard.php
This PR is redo of the Pop-up management UI in the Engagement Wizard. 
At the top is a notice bar which will indicate if there are inactive popups. An inactive popup is one which has no categories assigned and is not the sitewide default.
The Manage Pop-ups area has an `ActionCard` for each popup. The sitewide default (if there is one) will be at the top. Each lists the name and whether it is Sitewide Default, Inactive, or has categories assigned. Colors on the left indicate this status as well (blue = sitewide, green = in use, gray = inactive). The three dots on the right display a menu where the sitewide default state can be set along with Edit and Delete links. The categories icon (upside down triangle) reveals Category Filtering area, where categories can be assigned or removed. The …
> Engagement Wizard Popups Screen: ActionCard UI

- assets/components/src/action-card/style.scss
Sets the text-align of the Action Card right region to right (and make sure child items are inheriting this) as it can look a bit strange with the right whitespace when the text is on multiple lines and is left-aligned.
__Before:__
__After:__
1. Go to Newspack Components `wp-admin/admin.php?page=newspack-components-demo` 
2. Check the "Instant Articles for WP" Pluggin Toggle
4. Refresh the Newspack Components
5. "Configure Instant Articles" should be aligned to the right now
> Fix Action Card right region text align

- composer.json
- composer.lock
with [1.5.0 release](https://github.com/xwp/wp-dev-lib/releases/tag/1.5.0), there's no need to use the fork
> Use official xwp/wp-dev-lib

- assets/components/src/web-preview/style.scss
Make sure the "Loading..." text is vertically aligned with the spinner when the Web Preview component is loading the iframe.
__Before:__
__After:__
1. Check the Site Design Wizard
2. Click on "View demo"
3. Notice the spinner is not vertically aligned with the "Loading..." text
5. Refresh page and click on "View demo" again
> Web Preview: align items to the center when waiting

- assets/wizards/site-design/views/theme-mods/index.js
- assets/wizards/site-design/views/theme-mods/style.scss
We don't need to display the Author bio's "Length" setting if the Author bio isn't enabled. This PR moves the "Length" setting inside the ToggleGroup that controls the display of the Author bio.
__Before:__
__After:__
1. Navigate to Site Design > Settings
2. Notice the "Length" setting in the Author bio section. It's always displayed whether the Author bio toggle is on or off.
4. Refresh the page and check if the "Length" setting is only displayed when the Author bio is enabled.
> Only display author bio length setting when author bio is set to show

- includes/configuration_managers/class-site-kit-configuration-manager.php
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
In the latest version of Site Kit, `apply_filters( 'googlesitekit_modules_data', [] )` will return module info regardless of connection status. This PR updates the connection check to work nicely with this change.
1. You probably want to spin up a Jurassic Ninja site so the Site Kit connection will work correctly.
2. Go to `/wp-admin/admin.php?page=newspack-setup-wizard#/configure-google-site-kit` and verify it says you're not connected. Click the handoff button and connect Site Kit.
3. When you are finished connecting and return back to the setup screen, it should say you are connected.
* [ x] Have you written new tests for your changes, as applicable?
> Update Site Kit connection check for latest SK version

- assets/wizards/payment/index.js
- assets/wizards/payment/views/payment-method/index.js
- composer.json
- composer.lock
- includes/class-newspack.php
- includes/class-settings.php
- includes/wizards/class-payment-wizard.php
- Adds support for using Stripe test or live mode, using `NEWSPACK_STRIPE_MODE` constant.
- Displays last four digits of the current card. 
- Improved Wizard loading.
- Remove unused Stripe Composer dependency.
Full testing instructions in https://code.a8c.com/D39657
Addition (3/2/2020):
To reset subscription/customer data, navigate to Settings->Newspack. Check `Reset Managed Newspack Subscription` and click Save Changes. This will clear out the persisted customer and subscription IDs, allowing a switch from test->live mode without fatals. The checkbox should only be visible if `NEWSPACK_STRIPE_PLAN` and `NEWSPACK_STRIPE_MODE` constants are set in `wp-config.php`.
> Support Stripe Mode (Live/Test)

- assets/wizards/health-check/index.js
- assets/wizards/health-check/views/configuration/index.js
- assets/wizards/health-check/views/index.js
- assets/wizards/health-check/views/plugins/index.js
- includes/configuration_managers/class-amp-configuration-manager.php
- includes/wizards/class-health-check-wizard.php
Adds a second view to the Health Check wizard which shows:
- Is AMP in Standard Mode?
- Is Jetpack connected?
- Is Site Kit connected?
Adds tabs to the wizard to support second view.
Closes https://github.com/Automattic/newspack-plugin/issues/473
1. Disconnect Jetpack. Go to Jetpack Dashboard (`/wp-admin/admin.php?page=jetpack#/dashboard`), under Site connection click "Manage site connection," click Disconnect.
2. Disconnect Site Kit. Navigate to Site Kit dashboard (`/wp-admin/admin.php?page=googlesitekit-splash`). Click your name in the upper right corner, select Disconnect.
3. Switch AMP to Transitional or Reader mode. Navigate to `/wp-admin/admin.php?page=amp-options`, select Template Mode other than Standard, Save.
4. Navigate to Newspack Health Check Wizard.
5. Verify there are two …
> Health Check Configuration View

- includes/configuration_managers/class-site-kit-configuration-manager.php
Closes #468. This PR updates the module deactivation to use the updated option key first introduced in #395. There was a mismatch between the option names, because it looks like Site Kit is using underscores now for the option name instead of dashes.
1. Activate AdSense via Ads wizard.
2. Deactivate AdSense via Ads wizard.
> Fix Site Kit module deactivation

- assets/wizards/support/views/chat/index.js
In order for HEs to know that they're dealing with a Newspack customer, an "event" will be sent at the beginning of the chat. Events are used for messages like "user is navigating to billing page", but here we'll use this feature to "mark" a Newspack customer. 
Also, the "user info" is added here for convenience. It has a link to the site, as well as some browser information. 
1. Follow the testing outline from #466 
2. See that at the beginning of the chat, user info and a `[ Newspack customer  ]` message are prepended.
> Support: send initial info on chat start

- includes/api/class-plugins-controller.php
- includes/api/class-wizards-controller.php
- includes/class-profile.php
- includes/util.php
- includes/wizards/class-advertising-wizard.php
- includes/wizards/class-engagement-wizard.php
- includes/wizards/class-health-check-wizard.php
- includes/wizards/class-payment-wizard.php
- includes/wizards/class-performance-wizard.php
- includes/wizards/class-reader-revenue-wizard.php
- includes/wizards/class-seo-wizard.php
- includes/wizards/class-setup-wizard.php
- includes/wizards/class-support-wizard.php
In WP 5.4, [REST API route matching is slightly tweaked to improve performance](https://core.trac.wordpress.org/ticket/48530). With this change, all of the Newspack API routes were giving `{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}` errors.
Some digging revealed that we have a bunch of namespaces, confusing the matcher:
This PR standardizes all of the API endpoints into one `newspack/v1` namespace, resolving the issue:
1. Install WP 5.4 RC1. Navigate to any wizard that uses the REST API. Observe the 404 error when the API call goes out.
2. Apply this patch. Navigate to wizards. Observe issue is resolved. No other behavior should be changed. Wizards should work as normal.
3. This patch shouldn't cause issues using WP …
> Standardize REST API namespace usage

- assets/components/src/card/style.scss
- assets/wizards/payment/views/payment-method/index.js
- assets/wizards/payment/views/payment-method/style.scss
Add "Taxes included where applicable" message to Managed Newspack Wizard.
cc: @Philanco 
1. Add these constants to `wp-config.php`, activating subscription to a test mode product:
```
define( 'NEWSPACK_STRIPE_PLAN', 'plan_Gn7gT348Snozc7' );
define( 'NEWSPACK_STRIPE_MODE', 'test' );
```
2. Navigate to Newspack->Managed Newspack. 
3. Verify there is a tax message in italics.
4. Go through subscription flow using [Stripe test cards](https://stripe.com/docs/testing). 
5. Verify the message is also beneath the `ActionCard` about active subscription.
> Tax Included Message

- assets/components/src/button/style.scss
- assets/components/src/color-picker/style.scss
Since Gutenberg 7.7 we have a box-shadow around the buttons which doesn't fit with Newspack style. This PR simply removes it.
1. Go to the components demo `wp-admin/admin.php?page=newspack-components-demo`
2. At the bottom, notice the style of the buttons (hover and not)
4. Refresh components demo
> fix: button box-shadow since Gutenberg 7.7

- assets/wizards/setup/index.js
There are a number of plugins to configure in order to get Newspack setup. The language stood out to me so I'm proposing to correct it.
Closes # .
1. Setup Newspack
2. Reference language on Step 3.
3. Profit
> Fixes grammar in Step 3 of setup

- includes/class-starter-content.php
- includes/raw_assets/markup/body.txt
- includes/raw_assets/markup/title.txt
The Setup Wizard's Starter Content generation relies on randomness to generate an authentic set of content, with categories, titles, content, images, and layout all chosen randomly. As @adekbadek noted in https://github.com/Automattic/newspack-plugin/pull/459#issuecomment-592942122, this will be problematic for e2e testing. This branch introduces deterministic starter content that should render identically every time. The flag to use this approach is a `wp-config` flag (`WP_NEWSPACK_DETERMINISTIC_STARTER_CONTENT`). As the specifics of our e2e testing implementation become clearer, we may need to change this to an environment variable. 
1. Delete all posts and categories. 
2. Run the Starter Content Wizard (`/wp-admin/admin.php?page=newspack-setup-wizard#/starter-content`)
3. Screenshot …
> Deterministic Starter Content

- includes/configuration_managers/class-newspack-ads-configuration-manager.php
- includes/wizards/class-advertising-wizard.php
**This PR should be tested with https://github.com/Automattic/newspack-ads/pull/26.**
This half of the feature has the handling for the global ad slots with ad suppression.
1. Testing instructions at https://github.com/Automattic/newspack-ads/pull/26
> Integrate ad suppression with global ad settings

- includes/wizards/class-seo-wizard.php
A slash was missing in REST API URL of SEO wizard.
1. Go to SEO wizard
2. There should be no error
> Fix: broken REST URL in SEO wizard

- includes/class-handoff-banner.php
This is the only place where the wizards' JS is used outside of the actual wizards.
Closes #493 
1. Go to components demo, "Handoff Buttons" section, click "Manage AMP"
2. Observe redirection to AMP settings
3. Observe a handoff banner at the top of the page
> Fix handoff: enqueue shared JS in handoff

- .eslintrc.js
- assets/components/src/style-card/index.js
- assets/wizards/setup/index.js
- assets/wizards/setup/views/starter-content/index.js
- assets/wizards/site-design/views/theme-selection/index.js
- includes/class-starter-content.php
- includes/wizards/class-setup-wizard.php
- includes/wizards/class-wizard.php
This PR introduces an optimisation of starter content creation by parallelising requests. 
This PR also introduces a couple of changes to enable E2E testing:
- handling `id` attribute on `StyleCard` and using it on theme selection cards
- using URL query param instead of option to achieve deterministic content for E2E
- using the same image for all E2E posts
- hardcoded post publication date for E2E posts
1. Visit `/wp-admin/admin.php?page=newspack-setup-wizard#/starter-content` and create some starter content. Is should be faster than than before, but other than that with no changes.
2. Set `WP_NEWSPACK_DETERMINISTIC_STARTER_CONTENT` env var to `1` (e.g. `define( 'WP_NEWSPACK_DETERMINISTIC_STARTER_CONTENT', '1' );` in `wp-config.php`)
3. Run the starter content again. It should create …
> Starter content: parallelise post creation; tweaks for handling E2E

- includes/wizards/class-health-check-wizard.php
This way the Health Check data can be retrieved via WP CLI: 
```
wp eval "echo json_encode(\Newspack\Health_Check_Wizard::retrieve_data());"
```
I assume we don't consider this data sensitive.
1. Set AMP mode to Standard.
1. Run `wp eval "echo json_encode(\Newspack\Health_Check_Wizard::retrieve_data());`
2. Observe that a JSON string is printed, with the data used by the Health Check wizard, and `"amp":true` inside, e.g.: 
```
{"unsupported_plugins":[],"configuration_status":{"amp":true,"jetpack":true,"sitekit":true}}
```
4. Navigate to Health Check wizard - it should report that AMP is ok.
5. Change AMP mode to Transitional
6. Run the command from step 2. again - is should now output `"amp":false`
7. Navigate to Health Check wizard - it should report that AMP is misconfigured.
> Expose Health Check data to external PHP code

- assets/components/src/card/index.js
- assets/components/src/card/style.scss
- assets/wizards/componentsDemo/index.js
- assets/wizards/dashboard/index.js
- assets/wizards/dashboard/style.scss
Adds 2 icons in the header to change the view of the dashboard: List or Grid.
2. Go to Newspack > Dashboard. Do you see the 2 icons at the top?
3. Change the view to Grid
4. Go to a different page then come back to the Dashboard. Do you still see the Dashboard as a grid?
> Add grid view option to the Dashboard

- assets/components/src/button/style.scss
- assets/components/src/color-picker/style.scss
- assets/components/src/modal/style.scss
- assets/components/src/toggle-control/style.scss
- assets/components/src/wizard-pagination/index.js
- assets/components/src/wizard-pagination/style.scss
- assets/wizards/dashboard/index.js
- assets/wizards/dashboard/style.scss
If you use an admin colour scheme, then it will affect the buttons throughout our plugin.
This PR adds extra classes to make sure Newspack colours are always applied to the Newspack components.
This PR also updates buttons against our blue background (welcome wizard + dashboard) to use Primary buttons instead of a custom isLink
_Note: issue noticed when publisher shared screen with us -- didn't seem to bother them 😅_
1. Go to Users > Your Profile.
2. Select an admin colour scheme other than the default one.
3. Go to Newspack Components Demo `wp-admin/admin.php?page=newspack-components-demo`
4. Notice the disaster 😱 (e.g. screenshot above)
5. Switch to this branch.
6. Refresh the demo page.
7. It should be much better! 😎
> Fix admin color scheme conflict with Newspack buttons

- assets/components/package.json
- assets/components/src/web-preview/style.scss
Update mobile preset to 320px wide, which is the smallest mobile size conventionally supported and therefore more useful for previewing. 
Also updates the iframe's background to white. Some websites have transparent background and browsers default to white then.
1. Open Newspack components preview, trigger a WebPreview in "Web Previews" section
2. Change preset to mobile, observe that the iframe is now 320px wide
> Change mobile preset width of WebPreview

- assets/components/package.json
[`newspack-components`](https://www.npmjs.com/package/newspack-components) are still released the old-school way, so this needs to be updated.
> Chore: bump version in components

- includes/class-plugin-manager.php
Whitelists the Newspack Newsletters plugin.
1. Verify Newspack Newsletters appears in the Plugins list under Newspack.
2. Install and activate Newspack Newsletters.
> feat: whitelist newspack newsletters plugin

- assets/wizards/popups/index.js
- includes/wizards/class-popups-wizard.php
Currently previewing Inline Pop-ups in the Pop-up wizard doesn't work. This is because the post to preview over is set by the Pop-ups plugin, and is available only in the editor. This branch makes the same data available to the Pop-ups Wizard. 
1. On `master`, navigate to the Inline tab of the Pop-ups Wizard.
2. Click the three dots by any Pop-up and choose Preview.
3. Verify the page comes up Not Found.
4. Switch to this branch and repeat 1-2.
5. Verify the pop-up previews over the most recent post.
> fix: previewing for inline popups in wizard

- assets/wizards/popups/components/popup-action-card/index.js
- assets/wizards/popups/components/popup-popover/index.js
- assets/wizards/popups/index.js
- assets/wizards/popups/views/popup-group/index.js
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-popups-wizard.php
Adds a drafts section in the Popups Wizard to view/edit/delete/publish draft popups. Test with https://github.com/Automattic/newspack-popups/pull/119. 
1. Create two new Pop-ups, one inline and one centered. Save but don't publish them.
2. Navigate to Newspack->Pop-ups. Verify you see the Pop-ups in the Drafts section of the respective tabs.
3. Verify setting the Filter to "Draft" shows only these Pop-ups.
4. Click the triple dots on the right for one of the Popups, click Publish.
5. Verify the Popup is published and moves out of the Drafts area.
> feat: popup wizard ui for draft popups

- assets/wizards/popups/index.js
- includes/class-plugin-manager.php
- includes/wizards/class-popups-wizard.php
We're renaming "Pop-ups" -> "Campaigns" (discussion in `pamTN9-15s-p2`). This PR changes the name everywhere it's visible in the UI. No class/function/variable names are changed yet. These will be handled in separate PRs, to mitigate risk and ease testing.
Test along with https://github.com/Automattic/newspack-popups/pull/118.
1. Click "Campaigns" in the admin menu, create a new Campaign. 
2. Verify the name change has been made everywhere.
3. Go to Newspack dashboard, verify name change.
4. Go to Newspack Campaign wizard, verify name change everywhere.
5. Go to Plugins screen, verify name change.
> refactor: rename pop-ups->campaigns

- assets/components/src/action-card/index.js
- assets/components/src/action-card/style.scss
- assets/components/src/card/style.scss
- assets/components/src/plugin-installer/index.js
- assets/wizards/componentsDemo/index.js
This allows to create a "skinny" version of the Action Card and Plugin Installer, with less padding and smaller font-sizes.
2. Check the components demo
3. Try to create a new Action Card and/or Plugin Installer and use the `isSmall` prop
> Add small action card and plugin installer

- assets/wizards/popups/components/popup-action-card/index.js
- assets/wizards/popups/views/popup-group/index.js
- assets/wizards/popups/views/popup-group/style.scss
Adds the `isSmall` prop to the Popup Action Card. I also removed the `<hr />`s to save some space.
1. Navigate to Newspack > ~Pop-ups~ Campaigns
3. Refresh and notice the differences
> Update popup action card to use small style

- assets/wizards/popups/components/popup-action-card/index.js
In the Campaigns wizard, use "(no title)" for `ActionCard` titles if the campaign has no title.
Closes https://github.com/Automattic/newspack-plugin/issues/528
1. Create one or more Campaigns and leave the title blank.
2. Navigate to Campaigns Wizard, observe placeholder title.
> fix: handle empty title for campaigns

- assets/components/src/with-wizard/index.js
This checks `requiredPlugins.length` and outputs "Required plugins" if it's greater than 1.
Closes #453 .
1. Enter the Reader Revenue wizard setup
2. I multiple plugins are need it should say "Required plugins" else it will say "Required plugin"
> pluralize plugin in revenue wizard if needed

- assets/wizards/support/views/chat/index.js
- includes/wizards/class-support-wizard.php
Validate WPCOM token before starting Happychat. The token might become invalid due to expiration or because the user disconnected the app.
1. On branch master:
2. Visit support wizard (`/wp-admin/admin.php?page=newspack-support-wizard#/chat`) and authenticate, unless already authenticated. If you see a "InvalidTokenError" skip the next two steps. 
3. If authenticated successfully, head over to [your WPCOM security settings](https://wordpress.com/me/security/connected-applications) and disconnect the support app. 
4. Now after reloading the Newspack Support wizard, you should see the "InvalidTokenError"
4. Switch to this branch (and rebuild JS)
5. Reload the Newspack Support wizard window, instead of the error there should be a prompt to authenticate with WPCOM – do that 
5. The …
> Support: validate token before starting chat

- assets/wizards/popups/views/popup-group/index.js
A duplicate React key in the drafts section of the Campaigns Wizard led to duplicate `ActionCard`s under some circumstances. 
Closes https://github.com/Automattic/newspack-plugin/issues/536
1. On `master` create at least one inactive overlay campaign and one inactive inline campaign.
2. Create at least one draft (unpublished) overlay campaign and one draft inline campaign.
3. In the Newspack Campaigns Wizard, toggle between the Overlay and Inline tabs several times. Observe that the Inactive ones multiply each time, creating unexpected duplication.
4. Switch to this branch, reload the Campaigns Wizard, repeat the toggling.
5. Observe the Overlay and Inline screens remain the same no matter how many times you toggle between the two.
> fix: duplicate key

- .circleci/config.yml
A tweak in CI config. If the `test-php` CI job is passing here, then this fix works.
> Fix: php testing on CI

- includes/class-newspack.php
- includes/class-settings.php
- includes/wizards/class-support-wizard.php
As it says on the tin. The [auth](https://developer.wordpress.com/docs/oauth2/) scope change makes for a simpler UI, without the blog selection.
1. Authenticate with WPCOM to enable support features
2. Go to Settings->Newspack. Check 'Remove WPCOM Token' and save changes
3. Observe the option is gone, as there's no token now
3. Go back to Support wizard, authenticate again
3. Observe that the WPCOM auth screen does not prompt for blog selection, as it was before
3. Complete auth and observe that the support wizard features are active
> Support: token removal UI & auth scope change

- includes/class-analytics.php
Adds handling of submit and ini-load analytics events in non-AMP context. Also, adds filtering the events array so that there are only unique events (by id). 
Note: some of this code is taken from #557, thanks @dkoo ;) 
1. Add an inline campaign, insert the top Subscribe pattern from "Newspack Patterns"
1. Use the `newspack_analytics_events` filter to add reporting of `submit` and `ini-load` events, like so: 
```php
add_filter(
'newspack_analytics_events',
function ( $evts ) {
return array_merge( 
$evts, 
[
[
'id'             => 'campaignLoaded',
'on'             => 'ini-load',
'element'        => '.newspack-inline-popup',
'event_name'     => 'Load Event Name',
'event_label'    => 'Load Event Label',
'event_category' => 'Load Event Category',
],
[
'id'             => 'formSubmitSuccess', …
```
> Analytics: add non-AMP submit, ini-load events handling

- assets/components/package.json
I've published a new version of `newspack-components` on npm.
> Chore: update newspack-components' version

- assets/wizards/readerRevenue/index.js
- assets/wizards/readerRevenue/views/index.js
- assets/wizards/readerRevenue/views/revenue-main/index.js
- assets/wizards/readerRevenue/views/salesforce/index.js
- assets/wizards/readerRevenue/views/salesforce/style.scss
- includes/class-newspack.php
- includes/class-salesforce.php
- includes/class-webhooks.php
- includes/util.php
- includes/wizards/class-reader-revenue-wizard.php
Adds a Salesforce config view to the Reader Revenue wizard which allows admin users to connect a Salesforce org via the SF [OAuth 2.0 web server flow](https://help.salesforce.com/articleView?id=remoteaccess_oauth_web_server_flow.htm&type=5).
When the Newspack site is successfully connected to a Salesforce org, a WooCommerce webhook is generated which will trigger a data sync every time a donation order is created. This webhook is deleted if the Salesforce config is reset.
When an order is created, the webhook fires a request which includes order and billing details. This data is then synced to the connected Salesforce org via the Salesforce REST API. Lead records are looked up by email address and if there's an existing Lead record in SF, donor details are added to that record. If there …
> SalesForce integration

- assets/wizards/readerRevenue/index.js
- assets/wizards/readerRevenue/views/revenue-main/index.js
This should be a very quick one—text in the wizard should talk about contacts, not leads.
> fix: mop up a couple of remain instances of "lead" in text

- includes/wizards/class-advertising-wizard.php
Closes #571 .
This PR makes it so that toggling off Google Ad Manager integration in the Ads wizard will actually disable the integration. Previously, it would do nothing.
0. Verify you can reproduce #571 before testing this PR.
1. https://github.com/Automattic/newspack-ads/pull/46 is a companion PR that needs to be checked out in addition to this one.
2. Set up a global ad and an ad block.
3. Toggle the GAM integration on in the Newspack Advertising wizard. Observe ads:
4. Toggle the GAM integration off. Observe no ads:
> Make GAM toggle work correctly

- includes/class-analytics.php
non-interaction parameter was not handled in non-AMP visibility event reporting implementation.
This PR fixes that.
1. Ensure newspack-popups is on `fix/bounce` branch ([PR #168](https://github.com/Automattic/newspack-popups/pull/168)) and this repo is on `master`
2. Load a page with a campaign in non-AMP mode, scroll so that the campaign is visible
3. Observe that the `Seen` event is reported without `ni` parameter (which means non-interaction)
4. Switch to this branch, repeat step 2
5. Observe that the `Seen` event is reported with the `ni` parameter of value `1`
> fix(analytics): non-interaction handling

- includes/class-analytics.php
NTG article milestone events were reported for all pages, incl. homepage. This PR fixes it.
Also, there was an unnecessary bit of code that appended `ni` parameter to event reporting for non-interaction event handling. This is not needed, since non-interaction events are marked by `non_interaction` key in event definition.
1. On `master`, visit homepage and scroll to bottom.
2. Observe that NTG article milestone events were reported.
3. Switch to this branch, repeat 1. 
3. Observe that the NTG milestone events were not reported. 
3. Visit a single article and scroll to the bottom, observe NTG article milestone events being sent.
> Fix: report milestone events for articles only

- includes/class-analytics.php
This is a quick one. The User Interaction NTG category covers a few event triggers, but only this one is currently possible to implement in an AMP site. 
Closes #561.
1. Ensure that commenting is enabled in WP Settings > Discussion.
2. While not logged in, view a post that allows commenting.
3. Open the Dev Tools > Network tab. Filter requests by the term "NTG user".
4. Fill out the comment form and submit it. After form submission but before the page reloads with the comment displayed, you should see a Google Analytics request being sent that looks like this: https://www.google-analytics.com/collect?v=1&_v=j83&aip=1&a=515809510&t=event&_s=7&dl=http%3A%2F%2Fnewspack-dkoo.ngrok.io%2Fmy-best-post%2F&ul=en-us&de=UTF-8&dt=My%20best%20post%20-%20Newspack&sd=24-bit&sr=2560x1440&vp=2089x1338&je=0 …
> Add NTG event trigger for user comment submission

- assets/components/package.json
- assets/components/src/index.js
- assets/components/src/with-wizard/index.js
To prepare withWizard for usage outside on the Newspack Plugin, some tweaks are needed:
- Export `Router` with `newspack-components`
- Enable `withWizard` usage without `newspack_urls` variable
- `withWizard` – link logo to Newspack site by default when used outside of plugin
1. Nothing should change in the plugin, so just a smoke test is needed
> withWizard tweaks

- assets/wizards/analytics/index.js
- assets/wizards/analytics/views/configuration/index.js
- assets/wizards/analytics/views/configuration/style.scss
- assets/wizards/analytics/views/index.js
- assets/wizards/analytics/views/plugins/index.js
- includes/class-analytics.php
- includes/class-plugin-manager.php
- includes/wizards/class-analytics-wizard.php
Report post categories as a custom GA dimension. 
1. Make sure Site Kit is configured and Analytics service connected. There should be **no** custom dimensions set up (if there are, create a new Analytics Account in GA and switch to it in Site Kit settings)
1. Visit the Analytics wizard in Newspack plugin, observe a new tab: "Configuration". It should list a single custom dimension (it was created behind the scenes) `[Newspack] Article Category`, and this dimension should be set as the category dimension:
2. Visit an article which has a category
2. Observe that all events reported have a `cd1` parameter with value of categories slugs (comma-separated)
2. Visit that article in non-AMP version as well, observe 3. again
3. After a while visit the GA web UI. Go to Behaviour->Site Content->All …
> Analytics: report category to GA

- includes/class-plugin-manager.php
Fixes a regression that caused Newspack to always think Site Kit was installed, which broke the Setup flow.
1. Spin up a new Jurassic Ninja instance.
2. Run `npm run build && npm run release:archive` on this branch to generate a build.
3. Install the build on the JN instance.
4. Step through the Setup Wizard, including Jetpack and Site Kit connection.
5. Verify the flow works correctly.
> fix: allow newspack to install site kit

- assets/wizards/analytics/index.js
- assets/wizards/analytics/views/configuration/index.js
- assets/wizards/analytics/views/configuration/style.scss
- assets/wizards/analytics/views/index.js
- assets/wizards/analytics/views/plugins/index.js
- includes/class-analytics.php
- includes/wizards/class-analytics-wizard.php
PR #588 was reverted because of two issues:
1. Some local-testing-related code that was erroenusly included – fixed by #598
2. Lack of handling of authentication error when requesting GA data
This PR reintroduces code from #588, with issue 2 handled
1. Everything in #588, plus:
2. Log in to WP admin as a user which did not authenticate with Site Kit
3. Visit Analytics wizard, observe an error notice being shown.
> Add category reporting back, with unauthenticated user handling

- includes/class-salesforce.php
- includes/class-webhooks.php
This updates the Salesforce data sync to create [Opportunity](https://help.salesforce.com/articleView?id=opportunities.htm&type=5) records for each line item in a successful WooCommerce order. Opportunities are linked to a Contact via an intermediate [OpportunityContactRole](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_opportunitycontactrole.htm).
1. Follow [these instructions](https://newspack.pub/support/reader-revenue/salesforce/) to connect a Salesforce org to your Newspack site. (If you don't have a Salesforce org, [sign up for one here](https://developer.salesforce.com/signup))
2. Ensure that you have all required WooCommerce plugins and the Subscriptions extension fully set up for testing. Make sure you have Check payments enabled and/or Stripe …
> Sync WC order transactions to Salesforce opportunities

- .circleci/config.yml
- .distignore
- bin/release-archive.js
- package.json
Change release ZIP file structure, so that it matches the structure used by WPORG plugins
1. Run `npm run release:archive`
1. Observe the release zip has version from the `package.json` in the file name – `newspack-plugin-0.0.0.zip`
2. Install the plugin on a fresh site, confirm that it works as before
> Build: change release zip structure

- assets/wizards/dashboard/style.scss
Adds a pseudo-element to the wizard when in grid view to avoid an empty space in the middle due to the use of `justify-content: space-between`
This fixes a pet peeve of mine that's completely visual.
After installing and building this branch, go to the Newspack dashboard and enable the "grid" view mode.
Before this branch:
After this branch:
Because we're using a pseudoelement with no height, it shouldn't affect the rendering if the last column has one or three cards, or when displayed as a single column in smaller viewports.
> fix empty space in three-column wizard grid

- assets/wizards/analytics/views/configuration/index.js
- includes/class-analytics.php
- includes/wizards/class-analytics-wizard.php
This fixes issues introduced in #588, which were not caught and fixed in #600. 
There are two issues fixed by this PR:
1. Insufficient authorisation scopes detection. #588 added an auth scope, but did not add checking if the user has re-authorised after the update
2. User mismatch handling. It's possible that a user is authenticated with Site Kit, but does not have the correct Analytics module permissions. To account for that and any other edge case scenarios, the listing dimensions call to the Analytics Service was wrapped in a try/catch block.
1. On a fresh site, install version [`1.14.2`](https://github.com/Automattic/newspack-plugin/releases/download/v1.14.2/newspack-plugin.zip) of the plugin
2. Set up Site Kit, with Analytics
3. Install version …
> Fix Site Kit connection error handling

- includes/class-salesforce.php
Passes along the 'country' property to the Salesforce contact. Also some minor refactoring to clean up some deeply nested vars.
Passes the `country` property from the WooCommerce order data to the Salesforce Contact data. Also some minor refactoring to clean up some deeply nested array vars.
Closes #607.
1. Ensure that Salesforce is connected and Contact/Opportunity syncing is active.
2. Make a donation from the Donation block. In the checkout page, set the country to something other than United States, for ease of testing. (I selected United Kingdom and entered `PO1-3AX` as a valid UK postcode).
3. In Salesforce, look up the contact by the email address you used for the transaction.
4. In the Details tab, under Mailing Address, note the country code. It should match the country you …
> feat: sync country code of WooCommerce order to Salesforce contact

- includes/class-admin-plugins-screen.php
This PR improves the output of the WP CLI `plugins` commands by not including uninstalled Newspack-approved plugins. Those plugins don't really make sense to show in the CLI, and it's impossible to distinguish those listings from regular, installed, inactive plugins.
1. Before applying this patch, run `wp plugins list`. Observe uninstalled, [Newspack-approved plugins](https://github.com/Automattic/newspack-plugin/blob/master/includes/class-plugin-manager.php#L41-L417) are listed at the bottom:
2. Apply this patch. Run `wp plugins list`. Observe uninstalled, Newspack-approved plugins are not listed:
3. Go to the Plugins page. Verify uninstalled, Newspack-approved plugins are still listed under the Newspack plugin:
> Don't list uninstalled Newspack-approved plugins when using WP CLI

- .distignore
- package.json
Another release-related issue (caused by #610): due to how rsync parses the ignore file, the `src` directories in `vendor` were excluded in the zip too. We just a vendor package for starter content generation, so this was hard to catch. This PR fixes that.
1. Create a release
2. Test on a fresh site – go through the setup wizard, observe starter content being created
> Prevent vendor contents exclusion in zip

- .distignore
- package.json
A new release. #610 broke the startup content generation, because `src` directory inside of `vendor` was not included in the zip. #619 fixed that.
> Release Aug 04 bis bis

- includes/amp-enhancements/class-newspack-cookie-notice-amp-markup.php
- includes/amp-enhancements/class-wp-gdpr-cookie-notice-performance.php
- includes/class-amp-enhancements.php
- includes/class-plugin-manager.php
This PR improves server-side performance of the WP GDPR Cookie Notice plugin. Previously in AMP mode, it would fire an un-cacheable ajax call on every request to determine whether to show the cookie notice. This change removes that call and makes it so that the cookie notice will be indiscriminately shown for users that haven't accepted it.
I've also added WP GDPR Cookie Notice to the list of managed plugins, since it was missing and it's our approved cookie notice solution.
0. Install and activate WP GDPR Cookie Notice. If you don't have `https` on your local environment, you'll need to modify [this line](https://github.com/felixarntz/wp-gdpr-cookie-notice/blob/master/src/cookie-notice/class-cookie-notice-amp-markup.php#L64) to `'checkConsentHref' =>  str_replace( 'http:', '', …
> Remove un-cacheable ajax call in AMP mode from WP GDPR Cookie Notice

- package.json
`semantic-release` config update which will enable [prereleases](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#pre-release-branches).
> Enable alpha builds

- .circleci/config.yml
#623 updated the `semantic-release` config, but I forgot to also update CircleCI config, so that `semantic-release` would actually be ran on the `alpha` branch
> Handle alpha builds on CI

- assets/components/src/consts.js
- assets/components/src/text-control/index.js
- assets/components/src/text-control/style.scss
- assets/components/src/with-wizard/index.js
- assets/wizards/analytics/index.js
- assets/wizards/analytics/style.scss
- assets/wizards/analytics/views/custom-dimensions/index.js
- assets/wizards/analytics/views/custom-dimensions/style.scss
- assets/wizards/analytics/views/custom-events/index.js
- assets/wizards/analytics/views/index.js
- includes/class-analytics.php
- includes/wizards/class-analytics-wizard.php
Adding custom events insertion UI. Only `click` and `submit` events are handled: 
- `visibility`, `ini-load` require the element to be AMP element,
- `scroll` requires some more UI for scroll parameters, can be implemented later.
Design considerations:
1. This is an advanced feature, misuse of which can brake sites – we may wanna add some warning there
2. Some fields in the form are not required, not sure if we have an established pattern for that
3. The "Active" field is of a different kind, maybe it should be displayed differently in the form? 
Closes #601
1. Open the Analytics Wizard, observe a new tab – "Custom Events"
2. Add a custom event, e.g. a click on `#search-toggle`
3. Visit the front end (as non-logged-in user), oberve the event being sent on action (look for requests to …
> Add custom events adding UI

- includes/class-webhooks.php
Adds `permission_callback` to `register_rest_route` calls, as it's a required argument in WP 5.5
1. Verify that the Salesforce sync works as before – by making a donation and checking of donor data made it so SF
> Add permission callbacks (required in WP 5.5.)

- assets/components/src/index.js
- assets/wizards/engagement/index.js
- assets/wizards/engagement/views/index.js
- assets/wizards/engagement/views/related-content/index.js
- assets/wizards/engagement/views/related-content/style.scss
- includes/configuration_managers/class-jetpack-configuration-manager.php
- includes/wizards/class-engagement-wizard.php
Adds a new tab for Related Content to the Engagement wizard with a new setting that lets publishers restrict the age of content shown by Jetpack's Related Posts module.
Adds a new option to the Engagement wizard that lets publishers set a maximum age (in months) for posts shown by Jetpack's Related Posts module.
Closes #621.
1. In Jetpack traffic settings (https://[SITE URL]/wp-admin/admin.php?page=jetpack#/traffic), ensure that the Related Posts module ("Show related content after posts" option) is DISABLED.
2. Visit the Newspack Engagement wizard. Observe a new tab called "Related" fourth from the left. Click the tab.
3. In the wizard screen, observe the action card saying to enable Related Posts in Jetpack:
4. In Jetpack traffic settings, ENABLE the Related Posts module.
5. Go back to …
> Add related posts age setting

- assets/wizards/analytics/views/custom-events/index.js
Prevents raw HTML from being displayed in a Notice text.
1. On `master`, simulate an unsatisfied scopes error*
2. Observe the Notice in Custom Events section of Analytics wizard displays raw HTML
4. Observe the Notice displaying a link
\* e.g. set `$unsatisfied_scopes` to `[1]` [here](https://github.com/Automattic/newspack-plugin/blob/1535c9fc4e76daad91912294f10e06254c30bdfa/includes/wizards/class-analytics-wizard.php#L285)
> Fix notice in Analytics wizard

- assets/wizards/dashboard/index.js
The current default view is set to List but it's getting quite long now and the Grid view allows users to quickly scan the different cards without having to scroll. So this PR sets the Grid view to the default view.
2. Clear localStorage `localStorage.clear();`
3. Navigate to Newspack > Dashboard
> Update dashboard default view to grid

- includes/class-plugin-manager.php
Adds "quiet" support for Yoast Premium and Yoast News.
1. Verify Yoast Premium and Yoast News do not appear on the plugins list.
2. Install and activate both plugins.
3. Verify both plugins now appear on the plugins list under Newspack, with the em-dash before the name like all other managed plugins.
4. Verify the plugins do not appear in the Newspack Health Check.
> feat: quiet support for yoast premium and yoast news

- includes/class-donations.php
- includes/class-salesforce.php
Closes #636
Also fixes two tiny issues: 
1. Checking of webhook exists before removing it
2. Removal of setting `HasOptedOutOfEmail` on a SF Contact. It looks like it would never be set, because an object in `$data['meta_data']` array would never have `mailchimp_woocommerce_is_subscribed` key – it would be the value of such object's `value` key. Moreover, if this field is not configured in SF, [a contact will not be created](https://www.petefreitag.com/item/730.cfm). Open for discussion, though. cc @dkoo 
1. Using a Donate block on a page which has at least one tag and a category, make a donation (e.g. set up a Campaign w/ Donate block)
2. Observe the tags and categories are added to the WC order ("Custom Fields" section of Order details)
3. Observe the Opportunity in SF (on a single …
> Append categories, tags data to WC order; sync w/ SF

- includes/class-amp-enhancements.php
Addresses the issue described in https://github.com/ampproject/amphtml/issues/30176, where in AMP Standard mode Site Kit adds a query param to all internal links. This branch implements the fix described in https://github.com/ampproject/amphtml/issues/30176#issuecomment-690804114
cc: @westonruter 
1. On a site in AMP Standard mode, with Google Analytics connected through Site Kit, keep Newspack plugin on `master` branch.
2. Click around the site, observe `?_gl=123456789...` style query param appears momentarily when arriving at a new URL on the site.
3. Apply this branch. Observe the behavior is gone.
> fix: override site kit _gl query param behavior

- assets/wizards/analytics/style.scss
- assets/wizards/analytics/views/custom-dimensions/index.js
- includes/class-analytics.php
- includes/wizards/class-analytics-wizard.php
Add additional custom dimensions.
1. On a site with GA configured, visit Analytics wizard, Custom Dimensions tab
2. Observe that a custom dimension in the table has a select with five options – four custom dimensions and a "none" option
3. If there are less than four custom dimensions, add some using the form in "Create a new custom dimension" section
4. Set the custom dimensions to their roles, so that all roles are covered
5. Visit an article as a non-logged in user – observe the custom dimensions are reported with correct values (look for a request to a `/collect` endpoint) as `cdN` parameters, where `N` is the index of the custom dimension
6. In the settings, observe that duplicate roles for custom dimensions are not possible (if dimension A is set to role X, setting dimension B to …
> Add author, word count, publish date custom dimensions

- includes/wizards/class-seo-wizard.php
This PR fixes an issue where Yoast would not output `og:image` tags on certain posts. Here is the underlying cause:
1. We're not generating intermediate image thumbs any more (those have been offloaded to the Jetpack image CDN), so only the original full-size image gets uploaded.
2. Therefore, Yoast only finds the full-size image when generating `og:image` tags.
3. Yoast has a max size limit of 2MB for images.
4. Yoast can't know the file size of an image as served from Photon and is unaware of Photon in general, so it checks the original, full-size image size to determine whether the image is under the size limit. The Photon image is resized and compressed, so the size of the original and Photon-served image are wildly different.
5. Yoast thinks the image is too big to use for the …
> Ignore Yoast weight limit to prevent missing `og:image` tags

- assets/wizards/popups/components/popup-popover/index.js
- assets/wizards/popups/views/popup-group/index.js
Fixes small edge case errors
1. Create two campaigns, a one a draft and one in test mode 
2. In Campaigns Wizard, observe that neither has the "Sitewide default" toggle in the options popover
3. Assign a category to the draft campaign, observe there is no error and the category is assigned
4. Repeat 3. with the test mode campaign
> Fix: campaigns-wizard: prevent edge case errors

- assets/components/package.json
- assets/components/src/autocomplete-tokenfield/index.js
- assets/components/src/autocomplete-tokenfield/style.scss
- assets/components/src/index.js
As suggested in https://github.com/Automattic/newspack-listings/pull/1#discussion_r492030845, adds the AutocompleteTokenfield component from the Homepage Posts block to newspack-components. This component provides an autocomplete search input field for use in the block editor.
After this PR is released and the NPM package updated, we should be able to remove the code from the `newspack-listings` and `newspack-blocks` repos and import the component from NPM instead.
Not sure how to test the NPM package functionality until this PR has been merged and the package updated on NPM, but you can test that the component works by importing it to an existing editor component in this repo and adding it to the render output, something like this:
```
<AutocompleteTokenField
key="test"
tokens={ [] } …
```
> feat: add AutocompleteTokenfield component

- includes/class-plugin-manager.php
There have been a few recent incidents where bleeding edge features in the Gutenberg plugin caused issues on Newspack sites. This PR removes it from the list of supported plugins, which reduces the risk of a customer creating problems by installing the plugin accidentally.
1. Verify Gutenberg does not appear under Newspack on the Plugins page.
> feat: remove gutenberg from list of managed plugins

- includes/class-salesforce.php
- includes/class-webhooks.php
Brought to our attention by TRNN, this is a requirement for them to use the roll-up reports they use to track donations.
Makes some changes to the Salesforce sync functionality to make the synced data work better with NPSP roll-up reports, as requested by TRNN.
1. Ensure that you have a Salesforce developer account connected to your Newspack site ([instructions here](https://newspack.pub/support/reader-revenue/salesforce/)).
2. Make a donation through the Donate block and make sure to fill in all contact info in the checkout form.
3. Log into Salesforce and go to **Sales Console > Opportunities** to find the data synced from WooCommerce. Click on the Opportunity that corresponds to your order, then click the **Details** tab.
4. Confirm that the "Stage" for the opportunity is set to …
> fix: salesforce opportunities should be set to closed/won instead of new

- includes/class-salesforce.php
Increases the timeout limit of Salesforce API requests to 30 seconds, from the default of 5.
This should help avoid intermittent timeout errors due to slow request roundtrips with Salesforce that result in unsynced or partially synced data.
Also shouldn't noticeably affect front-end or admin performance because the requests are triggered by webhooks.
1. Test the Salesforce donation sync functionality and watch the webhooks logs in **WooCommerce > Status > Logs**. 
2. There shouldn't be any timeout errors on sync attempt.
> fix: increase timeout of Salesforce API requests to 30s

- includes/class-newspack.php
- includes/class-starter-content.php
If the Newspack plugin is managed as a composer dependency, the Composer path might not align with the main plugin path. This pull requests maintains current behavior while adding a way to specify which directory is used for the Composer autoload file.
> Allow Composer path to be overridden

- includes/wizards/class-popups-wizard.php
Makes the Campaigns Wizard use the preview post URL determined by `newspack-popups` plugin
1. Switch to `add/preview-post-expose` branch of `newspack-popups` ([PR pending](https://github.com/Automattic/newspack-popups/pull/291))
2. Observe the previews triggered in campaigns wizard are using the latest not-password-protected, not-campaigns-disabled post
> Use newspack-popups' preview post link getter

- assets/components/src/action-card-sections/index.js
- assets/components/src/select-control/style.scss
- assets/wizards/popups/components/popup-popover/index.js
- assets/wizards/popups/components/popup-popover/style.scss
Fixes two layout issues.
1. On `master`, visit the Campaigns Wizard
2. Observe that if there are no active campaigns, the filter selection will not be rendered
3. Observe that in the popover menu for an overlay campaign, the test mode toggle is rendered on top of sitewide default toggle:
4. Switch to this branch, observe both issues fixed
> Fix layout issues in Campaigns Wizard

- assets/wizards/popups/views/segmentation/SingleSegment.js
UI for newsletter- and donor-based segmentation (https://github.com/Automattic/newspack-popups/pull/294).
1. Create a new segment in Campaigns Wizard, Segmentation tab
2. Observe two new sections – "Newsletter", "Donation"
3. Create segments using these options and test if campaigns are acting accordingly
_Note: you might need to bypass HTTPS check on a local instance, to make WC webhook succeed:_
```
add_filter(
'http_request_args',
function ( $r ) {
$r['sslverify'] = false;
return $r;
}
);
```
> Campaigns Wizard: add segment options for subscriptions, donations

- assets/wizards/popups/index.js
- assets/wizards/popups/views/popup-group/index.js
- includes/wizards/class-popups-wizard.php
Adds information about segment in Campaigns Wizard card
1. Assign a segment to a campaign
2. Observe that it's name is displayed as part of the description of a list item in Campaigns Wizard
> Campaigns Wizard: display segment name in campaign card

- includes/amp-sanitizers/class-amp-sanitizer-gam.php
- includes/class-amp-enhancements.php
- includes/wizards/class-advertising-wizard.php
This PR creates the basic infrastructure for AMP Plus — an approach where AMP Dev Mode is used to add non-AMP features to AMP pages. The resulting page will be invalid AMP and therefore excluded from the AMP cache and Google search results carousel, however nearly all of the performance advantages of AMP are still present (tree-shaking, minification, various JS libraries, etc). 
The first experiment is Google Ad Manager. The integration allows use of non-AMP Ad Manager embeds in an AMP page. 
1. Switch Newspack Ads to this branch: https://github.com/Automattic/newspack-ads/pull/81
2. Edit `wp-config.php` and add this line:
```
define( 'NEWSPACK_AMP_PLUS_CONFIG', [ 'gam' ] );
```
3. Add some GAM ads to the site. 
4. Put AMP plugin in Standard mode.
5. Visit a page on the site, append …
> feat: allow gam scripts in amp pages

- assets/wizards/popups/views/segmentation/SingleSegment.js
- assets/wizards/popups/views/segmentation/style.scss
Currently the donation segmentation will work only if the site uses WC checkout. This PR adds a text to clarify that in the Campaigns Wizard.
1. Visit Campaigns Wizard, Segmentation tab
2. Observe a note in the "Donation" section
> Campaigns segmentation: add a note about donation segmentation working only with WC checkout

- assets/wizards/popups/views/segmentation/SingleSegment.js
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-popups-wizard.php
Display segment reach – what percentage of recorded audience the segment covers.
Do not merge before https://github.com/Automattic/newspack-popups/pull/324 is merged.
1. Switch Campaign plugin to `add/segment-size` branch (https://github.com/Automattic/newspack-popups/pull/324)
1. Visit the Campaigns Wizard's Segmentation tab and edit or create a segment
2. Observe the segment reach is displayed above the buttons section
3. Make some changes to the segment, observe the reach is updated dynamically, and that the update does not block the UI
> Campaigns Wizard: display segment reach

- assets/wizards/analytics/views/custom-dimensions/index.js
- assets/wizards/popups/views/analytics/Chart.js
- includes/class-analytics.php
- includes/wizards/class-analytics-wizard.php
**For testing https://github.com/Automattic/newspack-popups/pull/325**
Allows other plugins to report custom dimensions and add their config to Newspack Analytics Wizard. 
1. Follow the testing steps in https://github.com/Automattic/newspack-popups/pull/325
> Allow adding external custom dimensions

- .gitignore
- assets/wizards/advertising/index.js
- assets/wizards/analytics/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/dashboard/views/dashboardCard.js
- assets/wizards/engagement/index.js
- assets/wizards/health-check/index.js
- assets/wizards/popups/index.js
- assets/wizards/readerRevenue/index.js
- assets/wizards/seo/index.js
- assets/wizards/setup/index.js
- assets/wizards/site-design/index.js
- assets/wizards/support/index.js
- assets/wizards/syndication/index.js
- assets/wizards/updates/index.js
This PR is a follow-up of #712. Here I update the different wizards icons to G2
1. Check the different wizards
3. Check the wizards once again, you should see the updated icons (and match the Dashboard)
> Update Wizards icons to use G2

- assets/components/src/radio-control/style.scss
Changes the style of the radio from Material to Gutenberg
2. Check the different wizards if the checkboxes are being displayed properly (the only one I can think of is Site Design...)
> Update radio style to match Gutenberg

- assets/components/src/checkbox-control/style.scss
Changes the style of the checkbox from Material to Gutenberg
2. Check the different wizards if the checkboxes are being displayed properly
> Update checkbox style to match Gutenberg

- includes/class-analytics.php
Closes #716.
1. Create a post, assign multiple categories to it
1. Disable Yoast plugin
1. Ensure there is a custom dimension assigned to report post category in Analytics Wizard
2. View post in an incognito session (not logged in), observe a `pageview` event is sent to GA*, observe all categories are sent as a comma-separated list 
3. Enable Yoast plugin, edit the post and choose a primary category 
4. Again view the post, observe the primary category is the only one reported 
\* in network tab in devtools, filter by "pageview"
> Analytics: report single category if primary category is set

- assets/components/src/info-button/index.js
- assets/components/src/info-button/style.scss
Update the `InfoButton` icon to use Gutenberg instead of Material
1. Check the components demo, there's a checkbox with the `InfoButton`
3. Do you see a new icon?
> Update info button icon to use Gutenberg

- assets/components/src/action-card/style.scss
- assets/components/src/checkbox-control/style.scss
- assets/components/src/text-control/style.scss
- assets/components/src/textarea-control/style.scss
- assets/components/src/toggle-control/style.scss
- assets/components/src/toggle-group/style.scss
- assets/wizards/site-design/views/theme-mods/style.scss
Avoid forcing the height of a toggle component to 24px, adds a margin top and bottom. Also, reduces margin between Form components, including toggles.
2. Check the different wizards
> Update toggle group and toggle control vertical alignment

- assets/wizards/popups/index.js
Fixes a bug introduced in #691 
1. On `master`, remove all overlay campaigns
2. Visit the Campaign Wizard, observe admin screen crashing
3. Switch to this branch & rebuild
4. Observe the admin screen displaying a "No Overlay Campaigns have been created yet." message
> Fix: empty section in Campaigns Wizard

- assets/components/src/with-wizard-screen/index.js
- assets/components/src/with-wizard-screen/style.scss
- includes/class-newspack.php
- includes/class-plugin-manager.php
- includes/configuration_managers/class-configuration-managers.php
- includes/configuration_managers/class-jetpack-configuration-manager.php
- includes/configuration_managers/class-site-kit-configuration-manager.php
- includes/wizards/class-wizard.php
- every plugin will be considered active and configured in debug mode
- added a notice in WP Admin when debug mode is active
1. Go to Settings->Newspack and ensure "debug mode" is disabled
2. Deactivate "Publish to Apple News" plugin
3. Visit the Syndication wizard, observe required plugins screen will prevent you from any configuration
4. Go to Settings->Newspack and enable "debug mode"
5. Visit the Syndication wizard, observe that you can see the configuration links ("Configure")
6. Observe an orange notice above the wizard header, informing about the active debug mode
> Improve debug mode

- assets/components/src/radio-control/style.scss
The correct font-size/line-height wasn't being applied.
1. Check a wizard with radio control (e.g. Site Design > Settings)
3. Notice the change on the labels
> Fix RadioControl label font size and line height

- assets/components/src/action-card/index.js
- assets/components/src/notice/index.js
- assets/components/src/notice/style.scss
- assets/wizards/componentsDemo/index.js
* Remove Material icons and use Gutenberg's instead (missing "warning" but using similar to error for now)
* Remove `isPrimary` prop
* Add `isHelp` prop
* Increase text contrast against background
2. Check the different Wizards for notices
> Update Notice component

- assets/components/src/with-wizard/style.scss
- assets/wizards/updates/index.js
This PR updates the loading state animation. Moving away from the thin Material loading bar and instead using something fairly similar to Gutenberg with a "skeleton" loading.
_Note: there's an issue with the Updates Wizard where the plugin requirement overwrites the loading... not sure what's going on cc @jeffersonrabb_
2. Navigate through the different Wizards (including the Setup)
> Update is-loading animation

- assets/wizards/popups/views/segmentation/SingleSegment.js
- assets/wizards/popups/views/segmentation/style.scss
_Note: merge only after https://github.com/Automattic/newspack-popups/pull/352 is merged._
Adds UI for session read count segmentation.
1. Switch to `add/session-read-count-segment` branch of `newspack-popups` (https://github.com/Automattic/newspack-popups/pull/352)
2. Visit the Campaigns Wizard, segmentation tab, observe a new segmentation criterion – "Articles read in session"
3. Create a segment using that criterion, with a min of 2 and max value of 4 set 
4. Create a campaign and assign it to the new segment
5. Visit site in a fresh incognito session. Observe the campaign is displayed only on the 2nd, 3rd, and 4th (different) post visits
> Campaigns Wizard: handle session read count segmentation

- includes/class-plugin-manager.php
Adds Newspack Listings as a whitelisted plugin for easy manual installation. Happy to take feedback on the description copy.
1. Check out this branch and run `npm run release:archive`.
2. Install and activate the .zip that's generated in `/assets/release/newspack-plugin.zip` to a new test site.
3. Complete the onboarding steps as usual (can skip the Jetpack and Site Kit setup).
4. Go to **Plugins** and verify that Newspack Listings is listed and can be installed with a button click.
> chore: add Newspack Listings as a whitelisted plugin

- assets/components/src/popover/style.scss
- assets/wizards/popups/components/popup-popover/style.scss
See title.
Closes #762
1. Enable Gutenberg 9.6.2
2. Go to Campaigns, click on the "More" button
3. Popover should be narrow
5. Click on the "More" button
6. Popover should be fine.
7. Disable Gutenberg
8. Test the popover again
> Add min-width to popover and fix alignment

- assets/components/src/category-autocomplete/index.js
- assets/components/src/category-autocomplete/style.scss
- assets/components/src/form-token-field/style.scss
The helper text underneath the `CategoryAutocomplete` component is confusing and doesn't accurately describe the behavior of the component (`Separate with commas or the enter key.`). This text is [hard-coded into the Gutenberg component](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/form-token-field/index.js#L660-L669), so for now the best way to resolve this is to hide it with CSS.
1. Build from this branch, verify the helper text is gone. This can be done by viewing the category filtering in the Campaigns Wizard.
> feat: hide the confusing help text in category autocomplete field

- assets/wizards/popups/components/popup-action-card/index.js
- assets/wizards/popups/components/popup-popover/index.js
- assets/wizards/popups/views/popup-group/index.js
Converts `PopupGroup`, `PopupPopover`, and `PopupActionCard` to stateless components. This branch is a pure refactor and there should be no functional changes whatsoever.
Verify the Campaigns Wizard Overlay and Inline tabs function exactly as they did before.
> refactor: campaign view and components rewritten as stateless components

- assets/components/src/web-preview/index.js
- assets/wizards/popups/components/segmentation-preview/index.js
- assets/wizards/popups/utils.js
- assets/wizards/popups/views/preview/index.js
This branch introduces `SegmentationPreview`, a new component in the Campaigns Wizard. The component combines logic from the `Preview` view and the `useStateWithPersistence` utility function, which will make it easier and more semantically clear to add the "view-as-segment" feature in multiple places. This also has the slight advantage of setting `localStorage` variables just before previewing, and unsetting them after the preview has been closed. 
This is a refactor, there should be no visible changes.
1. Verify the Preview feature in Campaigns Wizard works exactly as it did before. Test with no segment, segment set, segment + single campaign group, segment + multiple campaign groups.
2. Verify the `WebPreview` works normally in other contexts, e.g. the Site Design wizard.
3. Bonus: …
> feat: segmentation webview

- assets/wizards/popups/components/popup-action-card/index.js
- assets/wizards/popups/components/popup-popover/index.js
- assets/wizards/popups/views/popup-group/index.js
- includes/wizards/class-popups-wizard.php
Adds a `SelectControl` to each campaign's popover for choosing the segment.
1. Create a few segments. 
2. In Campaigns Wizard, click the three dots on the right of each `ActionCard`. Observe UI to pick Segment.
3. Set the Segment, verify the change is made.
> feat: segment picker in campaign popover

- assets/components/src/form-token-field/style.scss
- assets/wizards/popups/views/segmentation/SingleSegment.js
- assets/wizards/popups/views/segmentation/style.scss
Instead of some custom CSS, the layout now relies on Grid. I also added Card and use InfoButton for the descriptions to even the section titles.
After:
Before:
1. Add new segment
3. Add new segment
> Update the new segmentation wizard style to use Grid and Card

- assets/wizards/popups/views/segmentation/SingleSegment.js
- assets/wizards/popups/views/segmentation/index.js
Addresses the issue described in https://github.com/Automattic/newspack-plugin/issues/773 where the list of segments isn't updated after adding a new one.
Closes https://github.com/Automattic/newspack-plugin/issues/773
1. On `master`, create a new segment, name it and save. Observe the new segment does not appear in the list.
2. Switch to this branch and repeat. Observe the list updates correctly.
> Fix/segments UI update

- assets/wizards/popups/views/popup-group/index.js
- assets/wizards/popups/views/popup-group/style.scss
Hides the label and increases the font of the select, so it looks almost like a page title as opposed to a standard select
1. Navigate to campaigns
2. Notice the new Groups select
> Update style of the group's select control in the campaign wizard

- assets/components/src/action-card/index.js
- assets/components/src/action-card/style.scss
- assets/wizards/popups/components/popup-action-card/index.js
- assets/wizards/popups/views/segmentation/SegmentsList.js
Link the titles of Campaign Wizard `ActionCard`s to edit pages. 
Closes https://github.com/Automattic/newspack-plugin/issues/791
1. Navigate to the Campaigns Wizard. 
2. Click the title of any Campaign `ActionCard`, observe you are taken to the Campaign's edit page.
3. Navigate to the Segmentation tab, click the title of any `ActionCard`. Observe you are taken to the segment's edit page.
> feat: linked titles in campaigns wizard action cards

- assets/components/src/action-card/style.scss
- assets/components/src/popover/index.js
- assets/components/src/popover/style.scss
- assets/wizards/popups/components/popup-action-card/index.js
- assets/wizards/popups/components/popup-action-card/style.scss
- assets/wizards/popups/components/popup-popover/primary.js
- assets/wizards/popups/components/popup-popover/secondary.js
- assets/wizards/popups/components/popup-popover/style.scss
- assets/wizards/popups/views/popup-group/index.js
- assets/wizards/popups/views/segmentation/SegmentsList.js
This PR moves the Category filtering and Group selection to a Popover instead of a "toggle down".
It also moves the Frequency and Segmentation to that same Popover.
So we have 2 distinct Popovers now: "Settings" and "More".
1. Navigate to campaigns
2. Notice the Cog and the Dotted icon
3. Test both Popovers
> feat: taxonomy, segment and placement to popover

- assets/wizards/popups/components/popup-popover/secondary.js
- assets/wizards/popups/views/popup-group/style.scss
- assets/wizards/popups/views/segmentation/SegmentsList.js
- assets/wizards/popups/views/segmentation/style.scss
This PR adds visual balance between the Campaigns and Segmentation wizrads
1. Check both wizards
> Small visual update to the campaign and segmentation wizards

- assets/components/src/popover/style.scss
- assets/wizards/popups/views/popup-group/index.js
- assets/wizards/popups/views/popup-group/style.scss
Test along with Automattic/newspack-popups#374.
This PR adds a Popover to the "Add New" button that lets users pick which type of Campaign they want to create.
Closes https://github.com/Automattic/newspack-plugin/issues/790
1. Navigate to Campaigns
2. Click on the "Add New" button
3. Create every type of Campaign possible and check if it passed the correct settings in the editor
> feat: popover to choose type of new campaign

- assets/wizards/popups/components/segmentation-preview/index.js
Removes unused LocalStorage implementation as @adekbadek pointed out in https://github.com/Automattic/newspack-plugin/pull/770#issuecomment-757755549.
Verify preview functionality works as it did before.
> chore: remove unused localstorage implementation

- assets/wizards/popups/components/popup-action-card/index.js
- assets/wizards/popups/components/popup-popover/index.js
- assets/wizards/popups/views/popup-group/index.js
- includes/wizards/class-popups-wizard.php
Adds Manual Placement UI to the Campaigns Wizard. Test with https://github.com/Automattic/newspack-popups/pull/373
> feat: support manual-only placement

- includes/class-donations.php
- includes/class-salesforce.php
If using the Newspack/WooCommerce checkout flow and Salesforce, allows any UTM params on the referring post URL to be passed through to the WooCommerce checkout page and then to the Salesforce Opportunity. UTM params are parsed and stored in the "Lead Source" field on the Salesforce Opportunity records. UTM params are only added to Lead Source if they exist in the referrer URL.
Also slightly changes handling of the referrer categories and tags: previously, if the referring post or page had no categories or tags, the "Post Categories" and "Tags" would still be added to the Lead Source field with a value of `none`. Now, to match handling of the UTM params, if there are no post categories or tags, these are omitted from the Lead Source field.
Closes #781.
1. Check out this branch. Make sure …
> feat: pass UTM params to Salesforce opportunities

- assets/wizards/readerRevenue/views/salesforce/index.js
- includes/wizards/class-reader-revenue-wizard.php
Adds a warning when Salesforce integration webhook is not configured.
1. Ensure your SF connection is properly set up in Reader Revenue wizard
2. Break the webhook by deleting it (`wp-admin/admin.php?page=wc-settings&tab=advanced&section=webhooks`)
3. On `master`, verify there's no error in Reader Revenue wizard
4. Switch to this branch, observe an error notice about the missing webhook
5. Reset the SF connection, verify there's no error displayed
> Salesforce: handle missing webhook

- assets/wizards/popups/components/segmentation-preview/index.js
- assets/wizards/popups/views/segmentation/SingleSegment.js
Follow instructions in https://github.com/Automattic/newspack-popups/pull/395
> Use "all" in view-as spec

- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/placements/index.js
- includes/wizards/class-advertising-wizard.php
Adds a new pre-defined sticky ad slot to the Advertising wizard. Test alongside https://github.com/Automattic/newspack-theme/pull/1208.
Closes https://github.com/Automattic/newspack-theme/issues/1199.
1. Check out this branch and run `npm run build`.
2. Go to **Newspack > Advertising** and make sure you have the relevant plugins and service providers configured to display ads.
3. Go to **Global Settings** and confirm there's a new slot for Sticky Ad:
4. Enable the Sticky Ad slot and choose a provider and ad unit for the slot.
5. View the front-end of the site in both AMP and non-AMP mode. The unit should render in a fixed container at the bottom of the viewport. Note that the ad slot will render based on its ad unit, so it will only appear if the unit is filled.
6. Test the "close" button …
> feat: add a sticky ad slot to the Advertising wizard

- assets/components/src/hooks/index.js
- assets/components/src/hooks/usePrompt.js
- assets/components/src/index.js
- assets/wizards/popups/views/segmentation/SingleSegment.js
Improves segmentation UI in Campaigns Wizard. Closes #710
1. Visit the Campaigns Wizard, segmentation tab
2. Observe that the subscriber and donor sections are using selects instead of checkboxes (#710)
3. Use the subscriber and donor sections to edit or create a segment, observe the results are as expected
4. Observe the "Save" button is disabled when there are no changes to the segment
5. Observe that after changes are made to a segment, a prompt will be displayed when trying to navigate away or reloading the page, before saving the changes
> Segmentation UI improvements

- assets/components/src/hooks/usePrompt.js
- assets/wizards/popups/views/segmentation/SingleSegment.js
Fixes a bug where the "Save" button can never become enabled when creating a new segment. Also enables the "Save" button if changing only the title on an existing segment—this allows segments to be renamed without changing any config options.
Lastly, fixes a bug in which trying to save a segment before any history changes are made can result in a JS console error. To replicate this on `master`:
* Edit any segment and immediately refresh the page so the initial render is the single segment page.
* Make the segment dirty by changing any config option.
* Click "Save" and observe a console error that prevents the segment from being saved: `SingleSegment.js:161 Uncaught TypeError: unblock is not a function`
* Note that this bug occurs intermittently, and only occurs if you haven't navigated to …
> fix: bug preventing new segments from being savable

- assets/wizards/popups/views/segmentation/SingleSegment.js
UI for adding a referrer-based segmentation. 
Do not merge before https://github.com/Automattic/newspack-popups/pull/415 is merged.
1. Switch Campaign plugin to `add/segmentation-negative-referrrer` branch (https://github.com/Automattic/newspack-popups/pull/415)
1. Create a new segment, observe a new section – "Referrer exclusion"
2. Set the referrer to `google.com`
3. Edit or create a campaign, assign the new segment to it
4. Verify the campaign is displayed when site is visited in a fresh session
5. Spoof the referrer by editing [this line](https://github.com/Automattic/newspack-popups/blob/0493d8db6e3609d95a0409359e1515b5f46259ad/includes/class-newspack-popups-inserter.php#L425) in `class-newspack-popups-inserter.php`
6. Observe that the campaign is not displayed now
7. Create a …
> Campaigns wizard: handle negative referrer segmentation

- assets/wizards/popups/components/popup-popover/secondary.js
- assets/wizards/popups/utils.js
- assets/wizards/popups/views/popup-group/index.js
Breaking this out to a smaller PR so it's not blocked by the larger segment precedence features.
Cherry-picks the fix from #832 that hides the "Uncategorized" category from all Campaigns UI. Because the Campaigns plugin basically ignores this category, it's meaningless to show it for campaigns, and kind of annoying to see since WP automatically adds it to any post that is published without assigning any categories.
1. On `master`, assign the "Uncategorized" category to a campaign (or publish a new campaign without assigning any categories—it will be automatically assigned).
2. In the Campaigns tab, observe that the campaign appears with the "Uncategorized" category in the action card and the category autocomplete field.
3. Check out this branch, run `npm run build`. Confirm that the …
> feat: hide "Uncategorized" category from Campaigns UI

- assets/components/src/with-wizard/index.js
In the wizard, hides the footer component while in a loading state. Closes #834.
Confirm that #834 is not replicable.
> fix: hide footer while loading to prevent overlap

- assets/components/package.json
- assets/wizards/popups/views/settings/index.js
Closes https://github.com/Automattic/newspack-popups/issues/377
Also a version bump to [`newspack-components`](https://www.npmjs.com/package/newspack-components) is included in this PR, but I ended up not using the new version in `newspack-popups` since there were too many changes.
1. Switch `newspack-popups` to branch `add/donor-from-page`
2. Visit the Campaign Wizard, settings tab
3. Observe a new setting - "Donor landing page"
4. Set a page to act as a donor landing page (a "Thank you for donation" page)
5. Create two campaigns, one targeted at donors (A), other at non-donors (B)
6. Visit the site in a new session, observe the B campaign is shown
7. Visit the donation landing page 
8. Observe that campaign A is now shown
9. Deactivate Newspack plugin and verify that you can edit the …
> Campaigns wizard: handle donor landing page setting

- assets/components/src/button-group/style.scss
This PR applies the correct border-radius to the various buttons within the group and fixes the position on focus/hover/pressed
1. Find a `ButtonGroup` (e.g. SEO > Separator)
2. Notice how "broken" it looks, mostly the border-radius for mid-children
4. Refresh your Wizard
> Fix button group style

- includes/popups-analytics/class-popups-analytics-utils.php
In version 1.25.0 of the Site Kit plugin, a way of getting profile ID [was removed](https://github.com/google/site-kit-wp/issues/2507). This PR changes it to use a supported way.
1. On `master`, set Site Kit to version 1.25.0
2. Observe the Campaign Wizard's Analytics view is erroring out
4. Observe the Analytics view loading
5. Switch Site Kit to an earlier version, observe the view still loading as expected
> Fix Site Kit integration

- assets/wizards/popups/components/segment-group/index.js
- assets/wizards/popups/components/segment-group/style.scss
- assets/wizards/popups/utils.js
- assets/wizards/popups/views/campaigns/index.js
- assets/wizards/popups/views/segments/SegmentsList.js
Makes the descriptions for segment action cards in the Segments tab (and segment container headers in the Campaigns tab) more useful. Instead of showing the creation date, it now summarizes the configuration for each segment. This could get slightly redundant if the segments are named after the intended use, but I find it really useful to be able to see at a glance what each segment is without having to visit the edit screen.
Segments tab:
Campaigns tab:
Also creates a link from the segments' names in the Campaigns tab to each segment's edit page, for added convenience.
~Question: I tried to make the descriptions as terse as possible so as not to visually muddy the UI, but in some cases the phrasing differs from the option labels—should we ensure that the option names match?~ I think we …
> feat: add segment descriptions to Campaigns and Segments tabs

- assets/wizards/popups/components/segment-group/index.js
- assets/wizards/popups/components/segment-group/style.scss
2 small changes to the campaigns wizard:
* The "Add New Prompt" button is now full width
* The border around a segment is slightly darker to differentiate it from a prompt.
1. Check the campaigns wizard
3. Refresh wizard
> Increase segment border colour and increase add prompt button width

- includes/class-nrh.php
A small change in Site Kit 1.25.0 breaks the cross domain tracking handling on AMP pages. This PR resolves it.
1. Install Site Kite 1.24.0 (e.g. `wp plugin install google-site-kit --version=1.24.0 --force`) and switch `newspack-plugin` to `master`. Put the site in AMP Transitional mode.
2. Set Reader Revenue wizard to News Revenue Hub, use an organization ID from a production site.
3. Add Donate block to a post.
4. View the post (non-AMP), choose a price, click to submit the form. Observe `_gl` parameter with a long random string in the URL.
5. Do the same in non-AMP. Observe there are two identical `_gl` parameters (a Site Kit bug).
6. Upgrade Site Kit to 1.25.0.
7. Repeat the non-AMP flow. Observe there is no longer a `_gl` parameter. 
8. Switch `newspack-plugin` to this branch, try the …
> fix: change in how to retrieve property id from site kit

- assets/wizards/popups/components/segment-group/index.js
- assets/wizards/popups/components/segmentation-preview/index.js
- assets/wizards/popups/views/campaigns/index.js
Along with https://github.com/Automattic/newspack-popups/pull/438, fixes previewing logic when previewing prompts within a single campaign, when previewing active prompts, or when previewing unassigned prompts.
Currently, when previewing a segment within a campaign, you will see all prompts assigned to that segment, even if they're not in the currently viewed campaign.
Also fixes a minor bug where the "Unassigned" option disappears if you're viewing the Campaigns tab while filtered by a campaign, even if there are unassigned prompts.
1. Create several ~campaigns~ (doh) prompts of all types (inline, overlay, above-header) and assign to a campaign. Make sure at least one prompt is unpublished (draft, pending or scheduled).
2. In the Campaigns tab, filter the view by your campaign.
3. …
> fix: preview functionality by campaign/group

- assets/wizards/popups/components/prompt-popovers/secondary.js
- assets/wizards/popups/utils.js
Partial solution to https://github.com/Automattic/newspack-popups/issues/447. Currently the "Uncategorized" category is suppressed in the Campaigns Wizard, although prompts bearing this category will behave in unexpected ways, most notably by failing to appear pages/posts unless the post also happens to be categorized "Uncategorized." This PR removes the logic so that "Uncategorized" will be visible just like any other category. Ideally we can find a stronger solution that prohibits or ignores this category, but for now this is a good first step because the user will be aware of the undesired category assignment and will be able to remove it.
1. In the Campaigns Wizard, add "Uncategorized" category to a prompt. 
2. Observe it is visible in the gear icon `PopOver` and in the `ActionCard` …
> fix: display uncategorized category in campaigns wizard

- includes/class-nrh.php
We've started seeing reports that clicking on the site logo leads to a redirect loop. This seems to be because the linker includes two domains `checkout.fundjournalism.org` as well as the site's domain. Because the site domain is included, the linker param is appended to links, and seems to cause  redirect loop on the home. This is generally reproducible in Safari, and Mobile Safari, but not Chrome. I haven't been able to establish a reliable way to reproduce the issue, but the change should be pretty benign. 
Verify the `linker` param no longer includes the site's URL.
> fix: don't include site domain in linker

- includes/wizards/class-advertising-wizard.php
Adds a container element wrapping the sticky ad so it can be controlled via theme CSS.
Follow testing instructions in https://github.com/Automattic/newspack-theme/pull/1253.
> fix: only show sticky ad at mobile viewports

- assets/wizards/popups/views/segments/SegmentsList.js
- assets/wizards/popups/views/segments/style.scss
Fixes a duplication bug with segments resulting from the sort UI.
If you try to re-sort the segments list (either by dragging and dropping or by clicking the up/down arrow buttons) while a sort request is already in progress, it results in a malformed segments list with duplicate segment items. The duplicated items will have the same ID and configuration, so renaming or deleting one copy will result in the same action being applied to its copies.
This fix can't remedy the bad segments if the issue has already happened, but it will prevent the issue from happening going forward. The only fix for the issue if it's already happened is to delete all bad segment copies and rebuild them from scratch.
1. On `master`, go to Newspack > Campaigns > Segments and create several segments.
2. Re-sort …
> fix: duplication of segments when dragging while re-sorting

- assets/wizards/popups/views/segments/SegmentsList.js
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-popups-wizard.php
Along with https://github.com/Automattic/newspack-popups/pull/455, adds server-side validation of segmentation sort request params. This should prevent most instances of bad client-side data being persisted in the options table. If the Popups API endpoint returns an error, display the error in the UI.
Closes #882.
Confirm that you can no longer replicate the issue described in #882 either by deleting or adding segments in one tab but not the other.
If you try to sort with outdated data, the error messaging should look like this:
Note that it's still possible to have two tabs open, re-sort in tab 1, then re-sort in tab 2, and have tab 2's sort order override tab 1's. But that's much less of a problem in my mind than creating malformed lists, deleting segments that had been previously …
> feat: validated segmentation sort and error handling

- assets/wizards/popups/components/segment-group/index.js
- includes/wizards/class-wizard.php
- package-lock.json
- package.json
On preview, replace the Client ID cookie, so that a preview session is a fresh session.
1. Use `try/view-as-cookie-spoofing` branch of `newspack-popups` (https://github.com/Automattic/newspack-popups/pull/458)
2. Use the campaign/segment preview feature. Dismiss a campaign permanently and ensure you've seen another one, which is set to "once" frequency
3. Navigate the site in preview window, observe that the two prompts are not visible anymore
4. Close the preview, open it again - observe the prompts are visible again
5. Close the preview, logout, and visit the site - the prompts should behave as in a new session
> Replace CID cookie on preview triggering

- assets/components/src/footer/index.js
- assets/components/src/footer/style.scss
- assets/components/src/with-wizard/index.js
- assets/components/src/with-wizard/style.scss
- assets/wizards/setup/index.js
- assets/wizards/setup/style.scss
The new `simple` prop added to `Footer` allows wizards to use the `Footer` without all the links and only display the logos of WordPress.com and Google News Initiative.
This is particularly useful for the Onboarding. Currently the `Footer` is being suppressed which is not ideal. With this PR we now have the 2 logos at the bottom.
1. Go through the Onboarding. Notice there isn't a Footer like on any other Wizard
3. Go through the Onboarding again, notice the logos at the bottom (no links)
4. Check a different wizard and see if you have the different links in the footer
> Update the Footer to support a simpler style

- assets/components/src/checkbox-control/index.js
- assets/wizards/popups/views/settings/index.js
Fixes settings reading.
1. On `master`, visit the Campaigns Wizard, Settings tab
2. Observe that the "Enable non-interactive mode" setting is not displaying an on state after turning on
3. Switch to this branch, observe the issue is resolved
> Campaigns Wizard: fix settings reading

- assets/wizards/popups/views/segments/style.scss
Fixes a CSS issue introduced in #870 
1. On `master`, visit Campaigns Wizard, Segments tab
2. Observe the draggable cards have wrong spacing
3. Switch to this branch, rebuild, observe the draggable cards looking as they should
> Fix card styling

- includes/class-newspack.php
- includes/class-patches.php
Addresses an issue that has come up a few times on Newspack sites, where an inbound link from a newsletter contains a UTM parameter with spaces encoded as plus signs. WordPress rewrites the URL replacing the plus with `%20`. Edge cacheing sees the two URLs as identical, therefore creating a redirect loop. The problem manifests to the end user as failed page loads on mobile when tapping a newsletter link.
Core issue: https://core.trac.wordpress.org/ticket/51733#ticket.
We can leave this fix in place for Newspack sites until there's a more permanent solution. 
Many thanks to @aidvu for the fix!
1. On `master` navigate to a URL like: `https://mysite.com/?test=a+b+c`. Observe the URL is rewritten to `https://mysite.com??test=a%20b%20c`.
2. Switch to this branch, repeat. Observe the URL is not …
> fix: possible redirect loop when plus sign in query param

- assets/components/src/hooks/useObjectState.js
- assets/components/src/hooks/useObjectState.test.js
Fixes a bug & adds tests for `useObjectState` hook.
1. On `master`, visit Campaigns Wizard and edit a segment
2. Observe that after adding a single category in category affinity criteria, it cannot be removed
3. Switch to this branch, observe the categories can be added and removed as expected
> Fix categories handling in segment settings

- assets/wizards/setup/views/welcome/index.js
- includes/class-starter-content.php
Closes #899 
Closes #903 
Closes #904
1. On a new site, add two categories: "Opinion", "Health"
2. Install the plugin, but don't do the setup just yet. Install & activate Newspack theme.
3. Add a custom logo via Customizer
4. Open the setup wizard. Observe that starter content creation is optional. Uncheck this option and install Newspack
5. Observe no starter content created
6. Go through the installation step again, this time with starter content creation
7. Observe starter content created, but original categories intact - all created categories have prefixed slugs
8. Observe the logo (in Customizer) intact 
9. Remove starter content (first enter debug mode by setting `WP_NEWSPACK_DEBUG` constant)
10. Observe the starter content removed and original categories unaffected
> Fix starter content issues

- .circleci/config.yml
Something in the newest (5.6.51) version causes the image to fail with a `MYSQL_PASSWORD cannot be used for the root user` error.
1. Observe latest `test-php` job on `master` branch failing 
2. Observe the job succeeding on this branch 👇
> CI: change MySQL version

- assets/wizards/setup/index.js
- assets/wizards/site-design/views/main/index.js
Slipped through the cracks in #892 
1. Visit the onboarding, design step (`/wp-admin/admin.php?page=newspack-setup-wizard#/design`)
2. Click "Finish"
3. Observe being redirected to the plugin dashboard
> Redirect to dashboard after onboarding complete

- .gitignore
- assets/components/src/with-wizard/style.scss
- assets/wizards/analytics/views/custom-events/index.js
- assets/wizards/popups/views/analytics/index.js
- assets/wizards/popups/views/analytics/utils.js
- includes/class-analytics.php
- includes/popups-analytics/class-popups-analytics-utils.php
- phpunit.xml
- tests/unit-tests/popups-analytics.php
Closes #911.
1. On `master`, concoct a big GA config by [enabling NTG events](https://newspack.pub/support/analytics/#ntg-tagging), adding some custom events, and then making it so a ton of prompts is included on a page. You can also inflate the config size by setting a super long title on one of the prompts.
2. Visit a page and observe https://github.com/ampproject/amphtml/issues/32911 - if the GA config is larger than 10kB, the request to `https://www.googletagmanager.com/gtag/amp` should fail, triggering a `Error rewriting configuration` error. Observe the GA events triggered by prompts being loaded, seen, and dismissed, are not sent (query network requests with `collect`)
3. Switch to this branch and also `add/leaner-ga-config` on `newspack-popups`
4. Observe the issues from pt. 2 are …
> Leaner GA config

- includes/class-plugin-manager.php
This PR removes WooCommerce One Page Checkout from the Newspack distribution. Once this change is shipped, One Page Checkout would no longer appear on the list of plugins included with Newspack. 
**Why remove One Page Checkout?**
Because no Newspack publishers are using it, and it's therefore not needed. 
Originally, we were thinking of having the Donate product page also be the Checkout page, but we didn't end up needing that since we created the Donate Block instead. 
Because WooCommerce One Page Checkout is a premium WooCommerce extension, it cannot be auto-updated. Its removal will make Newspack a little lighter and nimbler. 
Install the Newspack plugin and verify that One Page Checkout no longer appears as a plugin listed under Newspack (with the &mdash; prefix.)
> Remove WooCommerce One Page Checkout from Newspack distribution

- tests/unit-tests/popups-analytics.php
Fixes failing unit tests related to new Campaigns analytics helpers. Because [this util relies on relative time](https://github.com/Automattic/newspack-plugin/blob/master/includes/popups-analytics/class-popups-analytics-utils.php#L56) ("today"), while the unit tests have hard-coded dates, the tests will fail unless the tested event dates are relative to today.
1. On `master`, run `phpunit` to run PHP unit tests. Observe two failing tests with output that looks something like this:
```
There were 2 failures:
1) Newspack_Test_Popups_Analytics::test_report_generation_legacy
Report has expected shape.
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
Array (
'report' => Array (
0 => Array (
-            'date' => '2021-03-20'
+            'date' => '2021-03-19'
'value' …
```
> test: fix failing analytics tests due to hard-coded dates

- includes/popups-analytics/class-popups-analytics-utils.php
In #914, the GA report fetching was [changed to accommodate both legacy and new event category](https://github.com/Automattic/newspack-plugin/pull/914/files#diff-dcf593d710ae2fbb84ba284a1878a96389c35e092f59c5fd1cda39942dafb9fcL27-R30), but the [operator on the event category](https://github.com/Automattic/newspack-plugin/pull/914/files#diff-dcf593d710ae2fbb84ba284a1878a96389c35e092f59c5fd1cda39942dafb9fcR117) query was not updated, which results in a bad query.
The error would cause no events to show up after the latest release.
1. Visit the Campaigns Wizard, Analytics screen
2. You should see both old and new events on the chart
> Fix Campaigns Analytics reporting

- includes/wizards/class-analytics-wizard.php
Due to some recently discovered issues around GA configuration size limit (https://github.com/Automattic/newspack-plugin/pull/914), NTG events reporting should be opt-in, so that by default the GA config is smaller. 
1. Visit Analytics Wizard, Custom Events tab on a fresh Newspack site
2. Observe the "News Tagging Guide custom events" setting is **disabled**
3. Visit the site in incognito, observe the NTG events are not sent*
4. Enable the setting
5. Observe the events are sent
\* Search Network tab in Devtools for `collect` requests
> Analytics: NTG events reporting disabled by default

- includes/class-plugin-manager.php
Adds Google Web Stories plugin to supported plugins list: https://wp.stories.google/
1. Observe Web Stories is on the list of supported plugins, verify installation.
> feat: add web stories to supported plugin list

- README.md
- assets/components/src/global-notices/index.js
- assets/wizards/dashboard/index.js
- assets/wizards/dashboard/style.scss
- composer.json
- composer.lock
- includes/class-newspack.php
- includes/class-nrh.php
- includes/google/class-google-oauth.php
- includes/google/class-google-services-connection.php
- includes/popups-analytics/class-popups-analytics-utils.php
- includes/wizards/class-analytics-wizard.php
Adds an OAuth2 authentication flow, as a preparation for the upcoming GAM integration.
Currently, Site Kit's authorisation is reused to access user's GA data. Site Kit does not support the scopes necessary to access GAM data, so Newspack has to roll its own authorisation for this purpose.  
UI: I have made it very lightweight purposefully, since this PR is quite large as it is. The UI should probably live in some kind of settings view. cc @thomasguillot 
1. Nothing should change unless the necessary environment variables are present, so have a look at the Dashboard, Campaigns Analytics, and Analytics wizard - everything should work as before
2. Create a [Google OAuth2 app](https://support.google.com/cloud/answer/6158849?hl=en). Set `<test-site->/wp-admin/admin.php?page=newspack` (e.g. …
> Add Google OAuth2 authentication flow 

- includes/google/class-google-oauth.php
Fixes an issue with Google OAuth, where even though refresh token was stored, it was not used to refresh credentials.
Two scenarios have to be handled here - if a user authorises the app for the first time, they will receive a refresh token (allowing them to connect after the access token expires). Otherwise, they will receive only an access token, which will expire after a certain amount to time. 
1. Revoke access to the OAuth2 app on your [Google permissions page](https://myaccount.google.com/permissions) and remove credentials (`_newspack_google_oauth` user meta) from the DB 
2. Complete the oauth flow (#935) to ensure the happy path is covered
4. Remove credentials from the DB, observe the oauth flow can be completed again
3. Revoke access in Google permissions page, observe the oauth …
> Fix credentials refreshment in Google OAuth2

- includes/class-newspack.php
- includes/scheduled-post-checker/scheduled-post-checker.php
Pulls in code from the separate [Newspack Scheduled Post Checker plugin](https://github.com/Automattic/newspack-scheduled-post-checker) and integrates it into this main Newspack plugin. After this releases the separate repo can be scheduled (hah) for deprecation.
Note that the integrated version of the code is namespaced and has a slightly different constant name, so that it won't cause conflicts if a site already has the separate plugin installed and activated.
Closes #939.
1. On `master`, install and activate the [Newspack Scheduled Post Checker plugin](https://github.com/Automattic/newspack-scheduled-post-checker).
2. Using WP CLI, verify that the cron job is scheduled to run every five minutes: `wp cron event list --hook=newspack_scheduled_post_checker`
3. Check out this branch. …
> feat: integrate Newspack Scheduled Post Checker into main plugin

- includes/class-patches.php
Closes #946 
This PR integrates with Yoast to display the guest author in the `twitter:data1` tag which Slack uses in its previews. For the second part of #946 (Integrating CAP with Yoast schema data), there's [an open issue at the CAP repo](https://github.com/Automattic/Co-Authors-Plus/issues/710), so it should be handled in CAP at some point (hopefully soon now that Yoast is adding a filter in the next release for modifying the data).
1. Before applying this patch, add a guest author to a post and view the page source. In the `<meta name="twitter:data1" content="AUTHORNAME">` tag, you should see the name of the "real" post author, not the guest author.
2. Apply this patch. Refresh the page. In the `<meta name="twitter:data1" content="GUESTAUTHORNAME">` you should see the name of the …
> Use guest authors in Slack preview when needed

- includes/popups-analytics/class-popups-analytics-utils.php
- tests/unit-tests/popups-analytics.php
https://github.com/Automattic/newspack-popups/pull/535 changed how Campaigns events were sent to GA, ostensibly just reverting the encoding. But the slight change in event label broke the display of Campaigns Analytics.
1. Test on an instance connected to a GA that has all three possible event formats (I know 🤦‍♂️) - from before encoding (~before March 2021), encoded (~April 2021), and current (after May 4th)
2. Observe that you can see some events from all three periods (that the events sent differently are interpreted correctly)
> Campaigns Analytics tweak

- includes/class-patches.php
This PR adds a menu link for managing reusable blocks. Reusable blocks are an important part of many publishers' workflow, so this link should be widely useful. h/t @gamebits for the suggestion.
1. In WP Admin > Posts menu section, there should now be a link for Reusable Blocks with all the reusable blocks:
> Add menu link to manage reusable blocks

- assets/components/src/with-wizard/style.scss
This is a tiny PR that changes a few things for `loading-quiet`
1. Reduces the height of the loading bar to 8px
2. Increases the time of the animation to 1.25s
3. Makes sure the correct `margin-left` is applied when user collapses the admin menu sidebar
1. Open any wizard
2. Change `newspack-wizard__is-loaded` to `newspack-wizard__is-loaded newspack-wizard__is-loading-quiet`
3. Collapse the sidebar menu
4. See error
5. Switch to this branch
6. Refresh wizard and reapply class
7. Error should be fixed
> fix: loading quiet anim time/height and margin when admin menu is folded

- assets/components/src/autocomplete-tokenfield/index.js
- assets/components/src/autocomplete-with-suggestions/index.js
- assets/components/src/autocomplete-with-suggestions/style.scss
- assets/components/src/index.js
- assets/wizards/componentsDemo/index.js
- includes/wizards/class-components-demo.php
Adds a new component to the Newspack Components library, which is an extension of the `AutocompleteTokenfield` that also renders a list of suggestions to choose from. Takes functions as props for fetching suggestions, fetching saved tokens, and what to do when the `AutocompleteTokenfield` value changes.
This UI pattern is something that @thomasguillot has suggested for several features in progress, including this [Author Profile block](https://github.com/Automattic/newspack-blocks/issues/723) (not yet begun) and the Newspack Listings [parent/child UI](https://github.com/Automattic/newspack-listings/pull/43).
After this lands, we'll want to push a new version of the package to the NPM library.
It's somewhat hard to test this as an NPM package, but you can test within the Newspack Plugin. …
> feat: add an AutocompleteWithSuggestions component for reusability

- assets/components/src/progress-bar/index.js
- assets/components/src/progress-bar/style.scss
Small PR to fix the border radius on the Progress Bar.
You can notice the issue when a Progress Bar is using a label/fraction.
1. Check components demo
2. Notice the small bug
4. Refresh demo
5. Bug should be gone
> Fix progress-bar radius when using headings

- assets/components/package.json
#952 added a new component to the `newspack-components` package which has since been published to NPM. This PR bumps the version number to match the published package.
* 1.5.0 includes the new `AutocompleteWithSuggestions` component
* 1.5.1 is no different, but was published as part of trying to fix build issues when importing the component to a different repo
Note that repos that import components from the NPM package and update to 1.5.X may need to explicitly run `npm install --save @babel/runtime` if that package isn't a first-class dependency, due to a bug [described in this thread](https://github.com/babel/babel/issues/11318#issuecomment-602410789).
No functional changes in this PR, so no testing required.
> chore: bump NPM version number for newspack-components

- includes/wizards/class-support-wizard.php
The sanitisation used for the WPCOM token stripped `%` characters, which may appear in tokens. This fixes it by switching to a more idiomatic sanitisation method.
1. Reset your WPCOM token and reauthorise WPCOM in Support wizard
2. Everyhing should go smoothly
> Fix WPCOM token saving

- includes/class-plugin-manager.php
Replaces WP User Avatar (recently renamed to ProfilePress and _massively_ altered) with the much simpler Simple Local Avatars plugin by 10up as our recommendation.
> Replace WP User Avatar with Simple Local Avatars

- includes/class-plugin-manager.php
This PR adds Reusable Blocks Extended as a supported plugin.
1. On the Plugins screen under Newspack, install and activate Reusable Blocks Extended using the entry there
2. You should have a new Reusable Blocks screen:
> Add reusable blocks extended as supported plugin

- assets/components/src/toggle-group/style.scss
- assets/components/src/with-wizard-screen/style.scss
- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/placements/ad-picker/index.js
- assets/wizards/advertising/views/placements/ad-picker/style.scss
- assets/wizards/advertising/views/placements/index.js
- includes/wizards/class-advertising-wizard.php
- languages/newspack-plugin.pot
This PR replaces the `ToggleGroup` used in Global Settings with `ActionCard` to create a more balanced with less white space Wizard.
This is inspired by the Services step of the Onboarding
2. Navigate to Advertizing > Global settings
3. Test all the various placements and check if it's saved correctly by checking your front-end
> Update Advertizing's Global Settings and use ActionCard

- assets/wizards/popups/components/prompt-popovers/secondary.js
- assets/wizards/popups/utils.js
- includes/wizards/class-popups-wizard.php
Closes https://github.com/Automattic/newspack-popups/issues/538.
Follow testing instructions in https://github.com/Automattic/newspack-popups/pull/547.
> feat: reinstate manual-only placement option

- assets/components/src/action-card/index.js
- assets/wizards/advertising/views/ad-units/index.js
- assets/wizards/advertising/views/services/index.js
#870 changed the `ActionCard` component so that if it receives an `href` prop, it renders an `ExternalLink` to that `href` value. This resulted in a few Ads dashboard components rendering external links to internal UI pages, which is an annoying admin experience (clicking each link opens a new tab instead of loading the next view in a single-page app experience as expected). This change invokes the `Router` to turn those links into internal routes instead of external links.
1. In Newspack > Advertising, confirm that the Google Ad Manager action card no longer has the external link icon next to the "Configure" link:
2. Confirm that clicking on either "Configure" or the "Google Ad Manager" title loads the GAM view with the list of ad units directly in the same tab, without refreshing the …
> fix: prevent external links from ad dashboard UI

- assets/components/package.json
Now that #975 has been published to NPM as v1.6.0, we should bump the version number in the repo to match.
No functional changes.
> chore: bump newspack-components NPM version

- assets/components/src/action-card/index.js
- assets/components/src/action-card/style.scss
- assets/components/src/plugin-installer/style.scss
- assets/wizards/componentsDemo/index.js
In preparation of an upcoming redesign of the "Integrations" screen, I've added a checkbox icon on the left hand side of the ActionCard.
`checkbox="checked"` or `checkbox="unchecked"`
Also, minor update on the grey border for ActionCard/PluginInstaller
2. Check Demo components
> Add checkbox prop to ActionCard

- assets/components/src/button/style.scss
- assets/wizards/popups/components/segment-group/icons.js
- assets/wizards/popups/components/segment-group/index.js
Small PR to update the icons used in the "Add New Prompt" modal. At the moment it's based on Material. We've now moved away from it and are using Gutenberg's.
1. Go to Newspack > Campaigns
2. Click the "+" to add a new prompt, see the old icons
4. Refresh Wizard and click once again on the "+"
5. Observe the new icons
> Update "add new prompt" icons to match Gutenberg style

- includes/class-plugin-manager.php
Unlisting the organic-profile-block plugin, because:
1. It has [a bug](https://github.com/Invulu/organic-profile-block/issues/11) that hurts performance severely
2. Newspack Blocks [now features the Author Profile block](https://github.com/Automattic/newspack-blocks/pull/763)
The organic-profile-block plugin should not be listed in the the plugins view, unless installed.
> feat: remove organic-profile-block from supported plugins

- includes/class-plugin-manager.php
Updates the URL and plugin slug for the Distributor plugin so that it can be installed from the Plugins dashboard with a single click. **Note:** the plugin slug needed to be updated to `distributor-stable` instead of just `distributor` because that's the name of the stable built plugin .zip file as provided by 10up.
1. On `master`, go to your Plugins dashboard page. Look for "Distributor" and click "install." Observe that the installation fails with an error message.
2. Check out this branch, refresh Plugins, try again. Confirm that the plugin installs correctly now. 
3. Go to Distributor > External Connections and attempt to connect to Newspack.pub using the Username/Password protocol and the automated wizard. (Must be logged into Newspack.pub to do this)
4. Test that you can push …
> fix: distributor plugin URL and slug in plugins whitelist

- includes/class-donations.php
This PR implements a small change @tmmbecker discovered to improve order status in WooCommerce. By making the products both "Virtual" and "Downloadable", orders will be in "Completed" status after checkout instead of "Processing" status. This makes more sense, because a donation doesn't really require any further processing once checkout has happened.
1. Go to WP Admin > Products. If you have any existing Donate products, delete them (make sure you actually delete them, not just trash them)
2. Go to Newspack > Reader Revenue and Save the screen (this will re-create the Donation products if needed):
3. Go to WP Admin > Products. Verify the "Downloadable" box is checked on the newly-created products:
4. Purchase a donation. Go to WooCommerce > Orders. Verify the status is "Completed":
5. Go …
> Make auto-created donation products "downloadable" for better checkout

- includes/class-patches.php
This PR fixes an issue where under certain circuimstances, sharing a post to FB previews the post as a card that just says "301 Redirect". See https://wp.me/pamTN9-2NT
1.  You'll need an Atomic site to test.
2. Use the FB debugger to scrape a post. Verify no redirect warnings are shown and the post's `og:url` field has `http` not `https`.
> Use` http` `og:url` for consistency

- assets/components/src/notice/style.scss
- assets/wizards/popups/components/prompt-action-card/index.js
- assets/wizards/popups/components/prompt-popovers/primary.js
- assets/wizards/popups/index.js
- assets/wizards/popups/views/campaigns/index.js
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-popups-wizard.php
Improves the UI for duplicating prompts according to https://github.com/Automattic/newspack-popups/issues/560. When duplicating a prompt from the Campaigns dashboard, you are now presented with a modal with the opportunity to rename the duplicate before creating it, an option to close the modal or edit the duplicate after it's created, and a notice if the duplicate is created without a campaign (which would cause it to be visible in the dashboard only under the "unassigned" filter).
See testing instructions in https://github.com/Automattic/newspack-popups/pull/564.
> feat: prompt duplication UI in a modal in the Campaigns wizard

- includes/oauth/class-google-oauth.php
Fixes a credentials refreshing bug. The old access token was used after refreshing credentials, instead of the newly issued one.
1. Complete the Google OAuth flow, ensure a refresh token has been issued*
2. Wait for at least an hour, so that the current access token expires
3. Reload the Newspack dashboard, observe the "Google Connection" tile is still displaying your email address.
\* [Revoke permissions](https://myaccount.google.com/permissions) & remove the `_newspack_google_oauth` user meta.
> fix: use the new token after refreshing

- includes/class-patches.php
Prevents deletion of pages which are considered "essential" to Newspack sites, if they exist. This includes:
* The homepage
* The blog posts page
* WooCommerce pages: My Account, Shop, Cart, Checkout, View Order, Terms, and Privacy Policy
After this change, no one (not even super admins) will be able to delete the above pages. In order to delete an essential page, another page must be assigned the essential role first.
**Note:** An alternative idea is to make this a standalone plugin in the [custom code repo](https://github.com/Automattic/newspack-custom-code) instead of baking it into the main plugin. I'm open to discussing both options.
1. Check out this branch. Go to Pages and verify that for all of the pages outlined above, they no longer have a "Trash" link allowing them to be …
> feat: prevent accidental deletion of essential pages

- assets/components/src/card/style.scss
- assets/components/src/handoff/index.js
- assets/components/src/modal/style.scss
- assets/components/src/notice/style.scss
- assets/components/src/with-wizard/index.js
- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/placements/index.js
- assets/wizards/analytics/views/custom-events/index.js
- assets/wizards/componentsDemo/index.js
- assets/wizards/popups/components/prompt-action-card/index.js
- assets/wizards/popups/components/prompt-popovers/primary.js
- assets/wizards/popups/components/segment-group/index.js
- assets/wizards/popups/components/segment-group/style.scss
- assets/wizards/popups/index.js
- assets/wizards/popups/views/campaigns/index.js
- assets/wizards/popups/views/campaigns/style.scss
- assets/wizards/popups/views/segments/style.scss
- includes/class-donations.php
- includes/class-patches.php
- includes/class-plugin-manager.php
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/oauth/class-google-oauth.php
- includes/wizards/class-advertising-wizard.php
- includes/wizards/class-popups-wizard.php
I noticed the `Modal` felt slightly off, especially with the header and the various paddings. This PR restyle it to use a 64px padding around it. It also moves the title more inline with the content. For buttons, we are now using a `buttonsCard`.
I had to reorganise things in the Campaigns to make sure the changes were not breaking the "Add New Prompt" modal. And as an added bonus, I've tweaked the "Add New Prompt" modal to something similar to what was suggested in #861 
1. Check the various Modals (Components Demo, Campaigns, Analytics -- Custom Events, etc...)
3. Test again
> Update the style of the Modal component

- includes/wizards/class-analytics-wizard.php
Since #944 resolves the issue of too large GA config payload on AMP sites, the change from #924 can be reveted.
1. Install Newspack on a new site, configure Site Kit w/ Google Analytics
2. Observe the NTG events reporting, in Analytics wizard -> Custom Events, is on by default
3. Observe the NTG events (e.g. article read to 50%) are sent to GA account linked via Site Kit
> feat(ga-events): make NTG events reporting enabled by default

- includes/class-plugin-manager.php
Closes #1031
1. Install a non-standard Newspack plugin, such as "Newspack RSS Enhancements" 
2. Visit the Health Check wizard
3. Observe the plugin is not flagged as unsupported
> fix: prevent newspack plugins from being flagged as unsupported

- assets/wizards/syndication/views/intro/index.js
This PR updates the slug for Distributor to `distributor-stable`.
1. Navigate to Newspack > Syndication
2. Notice the empty `ActionCard` at the bottom, trying to load
3. Switch to this branch and refresh the Wizard
4. You should be able to (de)activate Distributor now!
_Note: The toggle doesn't seem to work (cc @adekbadek or @dkoo)... I get a `newspack_plugin_not_active` error_
> Apply correct plugin slug for Distributor in the Syndication Wizard

- assets/components/src/modal/style.scss
- assets/components/src/web-preview/index.js
With WP 5.8 just around the corner, the style for our `Modal` component was broken (using 5.8-RC2-51407).
This PR updates the style to make sure they look OK in 5.8
1. Make sure you are using WP 5.8
2. Navigate to a page where we have a modal (eg. components demo, campaigns)
3. Open the modal... it should look broken
5. Refresh page and reopen the modal
> Fix modal style in WordPress 5.8

- includes/wizards/class-reader-revenue-wizard.php
- includes/wizards/class-seo-wizard.php
Remove CSS missing for SEO and Reader Revenue wizards.
> Remove missing wizard CSS

- assets/wizards/handoff-banner/index.js
- assets/wizards/handoff-banner/style.scss
- includes/class-handoff-banner.php
- languages/newspack-plugin.pot
This PR removes the white background when displaying a handoff banner to focus on Newspack's blue. I also reduced some of the paddings so it takes a little bit less space on the screen
1. Go to a Wizard with a handoff button (e.g Newspack > Engagement > Recirculation > Jetpack Related Posts > "Configure")
2. Click on the button
3. Notice the banner
5. Refresh page -- you should see the new banner
> Simplify handoff banner style

- assets/wizards/engagement/views/newsletters/index.js
Closes #1044.
Our checkbox component does not seem to support being in a grid with other controls that contain label structure. For that reason, this PR proposes we use 1 column grid for this form.
I've also changed the form to a more generic approach. This allows integrating the latest "manual" provider and the "Public Newsletter Posts Slug" field.
1. Switch to this branch and run `npm run build`
2. Visit the Engagement wizard and verify the new grid, updated provider options, and "Public Newsletter Posts Slug" field.
> fix(engagement-wizard): grid columns and provider selector

- assets/wizards/popups/components/prompt-action-card/index.js
- assets/wizards/popups/index.js
- assets/wizards/popups/utils.js
- assets/wizards/popups/views/analytics/Info.js
- includes/popups-analytics/class-popups-analytics-utils.php
- includes/wizards/class-popups-wizard.php
- tests/unit-tests/popups-analytics.php
Closes #993 
1. On an instance with Site Kit & GA configured, and some Campaigns-related data already reported, visit the Campaigns Wizard
2. Observe a spinner next to each prompt, and then GA-derived data 
3. If a prompt was active on the site, viewability should be visible
4. If a prompt has a form (most commonly, a newsletter signup form), conversion rate should be visible 
5. If there was an error when fetching the data, an info icon with info in the tooltip should be displayed - this can be checked by logging as another admin, who did not connect Site Kit
1. On `master`, browse around the Campaigns Wizard and observe a lot of duplicated requests to WP REST API `/categories` endpoint
2. Switch to this branch, observe no duplicated requests to `/category` endpoint
> Campaigns Wizard: display GA-derived insights

- assets/components/src/select-control/index.js
- assets/components/src/select-control/style.scss
- assets/components/src/text-control/index.js
- assets/components/src/text-control/style.scss
- assets/wizards/componentsDemo/index.js
- assets/wizards/handoff-banner/style.scss
Adds a new `isSmall` prop to `TextControl` and `SelectControl` (for now) so we can use slightly smaller inputs throughout the plugin (I plan to use this in Campaigns at first)
It also updates the Components demo, including translatable strings for all our demo components
And there's a tiny fix on the handoff banner for the buttons (some plugins, e.g. AMP, modify the font-family for the button component and if affects the banner)
2. Check the components demo
> Add isSmall prop to text-control and select-control

- includes/class-stripe-connection.php
Fixes a fatal error. If Stripe is unable to fetch webhooks, the following is thrown:
```
PHP Fatal error:  Uncaught Error: Class ‘Newspack\WP_Error’ not found in /wordpress/plugins/newspack-plugin/1.50.0/includes/class-stripe-connection.php:122
```
1. I just threw an exception inside the `try` block to verify this.
> fix: namespace wp_error correctly

- includes/class-stripe-connection.php
Adds the same fix as #1070 to other instances of `WP_Error`, and ensures that webhooks are listed only if the donation platform is NRH.
1. Set the Reader Revenue platform to NRH and verify webhooks are listed in the Reader Revenue Wizard, Stripe Settings section
2. Set the platform to Newspack, observe that [this line](https://github.com/Automattic/newspack-plugin/blob/311a84cdde5239f020ec15cf0d33fd406076cb9f/includes/class-stripe-connection.php#L95) is not executed
> fix(stripe): error namespace, listing webhooks condition

- assets/components/src/category-autocomplete/index.js
- assets/components/src/form-token-field/index.js
- assets/components/src/form-token-field/style.scss
- assets/components/src/settings/SettingsCard.js
- assets/components/src/settings/style.scss
- assets/wizards/popups/components/settings-modal/index.js
- assets/wizards/popups/views/segments/SingleSegment.js
This PR reorganises the `Modal` in Newspack > Campaigns, including the `Grid` and the various paddings. I've also updated the `FormTokenField` (and `CategoryAutocomplete`) to allow label and help text to be hidden like other Gutenberg components (e.g. `TextControl`)
1. Go to Campaigns, click on the filter link -- notice the Modal
2. Switch to this branch and refresh wizard
3. Open the Modal again
4. Check if Campaigns > Segments (add new or edit) looks broken (it shouldn't!)
> Reorganize campaigns settings modal

- includes/popups-analytics/class-popups-analytics-utils.php
- includes/wizards/class-analytics-wizard.php
Update Google imports namespace compatibility with latest version (1.38.0).
Closes #1080.
1. Update the Site Kit plugin to the latest version (1.38.0)
2. In the master branch verify that the pages **Analytics** and **Campaigns -> Analytics** return an error.
3. Switch to this branch and verify that the pages are working and you can also create a custom dimension on the Analytics page.
> fix: update Google imports namespace

- includes/configuration_managers/class-woocommerce-configuration-manager.php
Removes redundancy of disabling AMP on WC pages. AMP disabling was added in a more robust way in #1058.
1. Set up Newspack on a new site 
2. Make a donation on the front-end, observe the "Payment Info" section is interactive
> chore: remove redundant AMP disabling on WC pages

- assets/wizards/handoff-banner/style.scss
- includes/class-handoff-banner.php
At the moment, when redirected to wp-admin via a handoff button, if the screen has help tabs, they will be hidden. For some reason `count( $screen->get_help_tabs() )` doesn't return the correct number anymore.
This PR simplifies it and only uses css
1. Navigate to a screen with an handoff button (e.g. Syndication)
2. Click on one of the buttons
3. Once redirected, check the banner (do you see the "Screen Options" button?)
5. Refresh
> Fix handoff banner style when admin has meta links

- includes/wizards/class-engagement-wizard.php
Remove missing CSS from the Engagement wizard.
1. In the master branch, run `npm run clean && npm run build`
2. Visit the Engagement page and observe the PHP warning and 404 error on the browser for the CSS file
3. Switch to this branch and refresh
> fix: remove missing CSS from Engagement wizard

- includes/class-pwa.php
This PR updates our PWA config to work better with the latest versions of the PWA plugin. Previously, we were throwing a lot of these errors/deprecation notices:
`
WP_Service_Worker_Caching_Routes::register was called <strong>incorrectly</strong>. The plugins configuration key is obsolete. Define Workbox plugin configuration at the top level
`
The latest version of PWA provides [a default offline browsing config out-of-the-box](https://github.com/GoogleChromeLabs/pwa-wp/wiki/Service-Worker#offline-browsing), and it's the same config we had in here, so I've just removed our config, and we'll use the default config. 
In the new version of PWA, offline browsing can be enabled/disabled using a checkbox on the Reading settings screen. So that people don't have to go into their settings and …
> Update PWA config to use defaults

- assets/components/src/button/style.scss
- assets/components/src/tabbed-navigation/style.scss
- assets/wizards/popups/components/prompt-action-card/style.scss
- assets/wizards/popups/views/segments/SegmentsList.js
- assets/wizards/popups/views/segments/style.scss
Use `:focus-visible` for TabbedNavigation, Quaternary and isLink instead of `:focus`. It looks better without compromising on accessibility.
This PR also fixes a misalignment with the popover for campaigns and segments.
1. Play with TabbedNavigation
2. Go to Newspack > Campaigns and check the popover (use `:focus` to see issue with menu items)
4. Repeat 1 and 2, using your mouse then your keyboard
> Update focus/focus-visible on buttons (+ small fix)

- includes/class-pwa.php
This PR fixes an issue that appeared after https://github.com/Automattic/newspack-plugin/pull/1094: for a lot of sites, people were not getting the latest homepage when visiting the site. 
This is because the default PWA config has a 2-second network timeout, where if a page takes longer than 2 seconds to load, PWA will serve the offline-cached page. This default is there as encouragement for sites to make their pages fast, but it seems too heavy-handed for our users. :) This PR increases the timeout to 44 seconds, which is one second before the PHP process will timeout on our infrastructure.
h/t @westonruter 🙌 
1. You'll need a site with valid HTTPS to test this PR, otherwise PWA won't work.
2. Add this code snippet somewhere:
```
// Wait 5 seconds.
add_action( 'init', function(){ …
```
> Increase PWA network timeout limit

- assets/wizards/popups/components/prompt-popovers/primary.js
Closes https://github.com/Automattic/newspack-popups/issues/597 
1. On `master`, observe prompt duplication in Campaigns wizard is not working
2. Switch to this branch, rebuild, observe it's working
> fix(campaigns-wizard): prompt duplication

- assets/wizards/advertising/index.js
- assets/wizards/advertising/views/ad-units/index.js
- includes/wizards/class-advertising-wizard.php
Allows the advertising wizard to accept multiple GAM network codes as a comma-delimited string, as specified by MCM.
Closes https://github.com/Automattic/newspack-ads/issues/157.
See testing instructions in https://github.com/Automattic/newspack-ads/pull/169.
> feat: allow multiple GAM network codes

- includes/class-newspack.php
A lightweight plugin management restriction.
1. Create a second admin user and verify they can access the WP Admin plugins screen
2. Add the `NEWSPACK_ALLOWED_PLUGIN_EDITORS` config variable, with `[<first-admin-login>]` as value
3. Verify that the first admin can still access the plugins screen
4. Verify that the second admin can't
5. Remove the config variable, verify that both users can access the plugins screen
> feat: plugin screen access restriction

- includes/class-newspack.php
The current implementation to restrict plugin access to specific users is causing the following warning in some admin screens:
```
PHP Warning:  Invalid argument supplied for foreach() in wp-admin/includes/plugin.php on line 1758
```
This is likely due to anonymous access to the admin area through the API. This access fires the `current_screen` action but not other protected features, such as menu pages. The attempt to `remove_menu_page()` executes a `foreach()` on `null`.
This PR checks for logged-in users and non-0 user IDs before executing the plugin area restrictions.
It also adds other plugin screens ("edit" and "add new") to the redirectable screens. 
1. Add the `NEWSPACK_ALLOWED_PLUGIN_EDITORS` config variable, with `[<your-username>]` as value
2. In the master branch, access the …
> fix: stricter plugin area restriction

- assets/wizards/readerRevenue/views/stripe-setup/index.js
- includes/class-stripe-connection.php
- includes/wizards/class-reader-revenue-wizard.php
Closes #1116.
1. On `master`, choose Stripe as the Reader Revenue platform after clearing any Stripe keys*
2. Observe a fatal error (#1116)
3. Switch to this branch, observe an error message in Reader Revenue -> Stripe Settings
4. Provide the Stripe keys, but invalid ones
5. Observe another error message 
6. Provide valid keys
7. Observe the UI without errors
\* `newspack_stripe_data` option and the Stripe keys in WooCommerce settings
> fix(stripe): error handling

- includes/class-newspack.php
Closes #1124.
Observe the block-based widget editing is turned off, with or without the Classic Widgets plugin.
> feat: disable block-based widget editing

- includes/oauth/class-google-oauth.php
- includes/oauth/class-wpcom-oauth.php
- tests/unit-tests/oauth.php
The OAuth saga continues. With this approach, the OAuth proxy is hosted on an arbitrary site, not wordpress.com. 
1. Define `NEWSPACK_GOOGLE_OAUTH_PROXY` in the site's environment, ensure WPCOM is authorised (visit the Support wizard to check)
2. To start afresh and get a `refresh_token`, remove Newspack from [authorised Google apps](https://myaccount.google.com/permissions)
3. Also, remove the `_newspack_google_oauth` user meta, if it exists
4. Visit the Newspack dashboard and complete the OAuth flow by clicking on the "Google Connection" tile
5. Check back after at least an hour to see if the token will be refreshed - you should still see "Authorized Google as <email-address>" on the "Google Connection" tile
6. Test some re-authentication scenarios by re-doing steps 2 or 3 (separately) …
> feat(oauth): use a self-hosted proxy for authenication

- includes/wizards/class-setup-wizard.php
Closes #1106
1. Install the plugin on a new site
2. In the Setup wizard, on the Services step, do not enable Reader Revenue
3. Finish the setup, observe that WooCommerce plugin has not been installed
4. On a different new site (or visit the Setup wizard again*), enable Reader Revenue during setup
5. Observe WooCommerce has been installed
\* by going directly to `/wp-admin/admin.php?page=newspack-setup-wizard#/services`
> fix(setup): install WC only if Reader Revenue is enabled

- includes/class-plugin-manager.php
The standalone Newspack Image Credits plugin has been rolled into the main plugin in https://github.com/Automattic/newspack-plugin/pull/1147 and should no longer be installed separately. This PR removes it from the list of approved/supported plugins.
> Removes Newspack Image Credits

- assets/components/src/with-wizard-screen/index.js
Wizard screens navigation using react-router is not restoring scroll position, which can be confusing.
This PR implements "scroll to top" to every pathname change for components `withWizardScreen`.
1. In the master branch, visit the Newspack Ads dashboard
2. Click on the Google Ad Manager "Configure", scroll down and click on the "Back to advertising options" button
3. Observe your scroll is not at the top of the page after the screen change
4. Switch to this branch, run `npm run build`
5. Repeat steps and observe you have been scrolled top, a more predictable behavior.
> fix: restore scroll for wizard screens navigation

- assets/wizards/engagement/views/commenting/index.js
This PR replaces `PluginInstaller` with `PluginToggle` so it looks similar to the Syndication Wizard for example.
2. Make sure Newspack Debug is set to `false`
3. Navigate to Newspack > Engagement > Commenting
4. Play with the various toggles and check in wpadmin > Plugins if it worked
> Simplify commenting settings

- assets/wizards/health-check/index.js
- assets/wizards/health-check/views/configuration/index.js
- includes/configuration_managers/class-amp-configuration-manager.php
Health Check fix.
1. On `master`, deactivate AMP
2. Visit Health Check wizard, Configuration tab - observe the AMP status says that AMP is in Standard mode
3. Switch to this branch, observe the AMP status says that the AMP plugin is not active
4. Activate AMP plugin, observe the AMP status displaying correctly
> fix(health-check): AMP status

- assets/components/src/with-wizard-screen/index.js
Avoids the use of the `useLocation` hook from #1157 in order to avoid an occasional crash due to using a hook inside a higher-order component.
1. On `master`,  navigate to `https://<siteurl>/wp-admin/admin.php?page=newspack-setup-wizard#/settings` and observe a JS crash with the following error: https://reactjs.org/docs/error-decoder.html/?invariant=321
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```
2. …
> fix: react router crash from useLocation in HOC

- assets/components/src/action-card/index.js
- assets/components/src/action-card/style.scss
- assets/wizards/componentsDemo/index.js
Allow an action card to have multiple badges.
Observe "Example Fourteen" from the image:
1. Check out this branch and run `npm run build`
2. Visit the `newspack-components-demo` page
3. Observe the unaltered "Example Ten" works as expected and the "Example Fourteen" displays multiple badges from an array.
> feat: multiple badges for action card

- assets/wizards/popups/views/segments/SingleSegment.js
Fixes a bug.
1. On `master`, create or edit a segment in Campaigns Wizard
2. Observe that the "Articles read in session" -> "Max" setting is not editable
3. Switch to this branch, observe the setting is editable
> fix(campaigns-wizard): segmentation configuration

- assets/wizards/advertising/components/ad-unit-size-control/index.js
- assets/wizards/advertising/index.js
- assets/wizards/advertising/style.scss
- assets/wizards/advertising/views/ad-unit/index.js
Implements an Ad Unit Size Control component to allow the selection of standardized ad units sizes as specified at https://github.com/Automattic/newspack-ads/issues/187.
Closes https://github.com/Automattic/newspack-ads/issues/187
1. Check out this PR and run `npm run build`
2. Visit the Advertising dashboard, edit an existing Ad Unit that has a size outside the range specified at https://github.com/Automattic/newspack-ads/issues/187
3. Observe the select element with selected `Custom` value, along with the previous values preserved
4. Create a new ad unit and add a new size, attempt to select different sizes and save
5. Edit the newly created ad unit, select `Custom` size and save with a random width and height
6. Refresh and confirm the value is saved.
> feat(ads): standardize ad unit sizes

- .circleci/config.yml
As seen on https://github.com/Automattic/newspack-ads/pull/214, recent changes made to `circleci/php` resulted in our builds fail due to an incompatibility with our `node-sass` dependency.
[`circleci/` images are being deprecated and will lose support starting December 2021](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034). We should start moving towards maintained images.
This PR implements the use of `cimg/` images.
CI tasks must pass.
> fix: update ci images

- includes/class-analytics.php
Add NTG social event analytics for Reddit and Telegram. These are also used quite often by publishers and are supported by Jetpack.
1. Check out this PR
2. Enable Reddit and Telegram in Jetpack sharing configuration
2. Click on Reddit and Telegram icon on post/page to see event sent to analytics
> Add NTG social event for reddit and telegram

- includes/configuration_managers/class-configuration-managers.php
- includes/configuration_managers/class-parsely-configuration-manager.php
This PR automates some of the Parse.ly setup. The main field we need filled automatically is the Site ID field, then Parse.ly should "just work" on our sites.
The easiest way to test is probably this:
1.  Add the following code snippet somewhere:
```
add_action( 'init', function(){
$request = new WP_REST_Request( 'POST', '/newspack/v1/plugins/wp-parsely/configure' );
$response = rest_do_request( $request );
} );
```
2. Refresh the page. Parse.ly will likely crash on this first request because [the way it's built can't really handle if the plugin is activated after plugins have loaded](https://github.com/Parsely/wp-parsely/blob/develop/wp-parsely.php#L45-L51). Not sure if it's worth worrying about it, as it crashes after the configuration manager has run and seems like it needs a tricky …
> Parse.ly config manager

- includes/class-analytics.php
Handles a quick of a possible Site Kit setup – if GTM module is connected, Analytics module will no so what Newspack relies on it to do. In other words, Analytics module might be _activated_, but not _active_.
1. Set up a site with Site Kit, connecting both Analytics & Google Tag Manager modules
2. Visit a page which has AMP disabled
3. Observe `gtag is not defined` errors in the JS console
4. Switch to this branch, observe no errors shown.
> fix: disable Newspack events if Site Kit's GTM module is active

- .circleci/config.yml
> ci: fix WP version at 5.8.1 until the PHPUnit changes are addressed

- assets/components/package.json
BREAKING CHANGE: changes export method of components modules from CommonJS to ES modules.
Version bump of Newspack Components. Instead of a minor version bump, I think this new release warrants a major version bump, as compared to the last release (v1.6.1) it updates many NPM packages as well as switches the module exports from CommonJS modules to ES modules. This can be a potentially breaking change in itself, especially for older browsers.
Nothing to test here, just a semver bump.
> chore: update NPM package version

- assets/components/src/button-card/style.scss
- assets/components/src/button-group/style.scss
This PR simplifies the focus/pressed style of the `ButtonCard` and `ButtonGroup`, removing the `$primary-050` background colour and simply using a tick `$primary-500` border
2. Go to the Dashboard or the Components Demo screen
3. Test the various `ButtonCard`s
4. Go to Site Design
5. Test the various `ButtonGroup`s
> Update button-card and button-group focus/pressed style

- assets/wizards/advertising/views/ad-units/index.js
The presence of errors shouldn't affect the display of the connected network code. This PR ensures the network code visibility if it exists on the connection data and changes the error message to a broader context.
1. On the `newspack-ads` plugin, modify the line 478 on `class-newspack-ads-gam.php` to always throw the exception
2. While on master, visit the `Advertising -> Google Ad Manager` wizard and observe the network code is not visible
3. Check out this branch, run `npm run build`, refresh and observe the network code is displayed regardless of error
> fix(ads): network code visibility

- assets/components/src/plugin-settings/SettingsSection.js
Fix the `<PluginSettings.Section />` when the `active` property is `null`, meaning it shouldn't display the toggle button. Also sets the grey header regardless of the `active` value.
Follow instructions at https://github.com/Automattic/newspack-ads/pull/224 and observe section has the correct layout.
> fix: plugin settings section toggle on `null` active

- package-lock.json
- package.json
https://github.com/Automattic/newspack-plugin/pull/1264 did build on CI, but after merging [did not](https://app.circleci.com/pipelines/github/Automattic/newspack-plugin/2793/workflows/434a0801-4b1f-4ce5-9589-0b47547472eb/jobs/12686) with a ` @typescript-eslint/experimental-utils not accessible from eslint-plugin-jest` error. This PR reverts this change.
> revert: "chore(deps-dev): bump @typescript-eslint/eslint-plugin"

- assets/components/src/section-header/style.scss
- assets/wizards/advertising/views/suppression/index.js
- assets/wizards/engagement/views/related-content/index.js
- assets/wizards/site-design/views/main/style.scss
- assets/wizards/site-design/views/theme-settings/style.scss
This PR reduces the gap between a `SectionHeader` (except if it has `noMargin`) and whichever component is next (except for another `SectionHeader`) to 16px, allowing a better "[principle of proximity](https://uxdesign.cc/how-to-enhance-your-design-with-the-gestalt-principles-of-proximity-a7828452058b)".
2. Navigate through all the various screen
> Reduce section-header margin when followed by another component

- assets/components/package.json
Add missing `moment-range` dependency to Newspack Components, so it can be used as an imported package. Also bumps Newspack Components to v2.0.3.
No functional changes.
> fix: add moment-range to newspack-components dependencies

- includes/reader-revenue/class-stripe-connection.php
#1187 added a check to prevent currency mismatch, but the variable name is wrong on two lines.
Smoke test or make a donation with Stripe as payment provider.
> fix(stripe): variable name

- .github/dependabot.yml
We've had Dependabot running for a week now and it's been working as intended. Most of the open PRs now are pretty minor updates, so I think we can safely bump down the frequency of checks to weekly to reduce the noise a bit. 
Nothing to test, purely workflow-related.
> chore: reduce frequency of dependabot checks

- assets/components/src/select-control/style.scss
- assets/wizards/componentsDemo/index.js
Add support for `multiple` to `SelectControl`
Closes #1252
2. Go to Components Demo
> Add multiple support for select-control

- assets/components/src/plugin-settings/SettingsSection.js
The plugin settings section is not handling boolean/checkbox options properly. The resulting control is a text input due to the missing `type="checkbox"` attribute.
Follow steps at https://github.com/Automattic/newspack-ads/pull/246
> fix: plugin settings checkbox

- .github/workflows/auto-merge.yml
Should help make Dependabot PRs more automated. Will automatically merge minor and patch update PRs if all CI jobs pass. Major updates will still require a manual review and merge.
h/t @yogeshbeniwal for the idea.
Closes #1323.
Nothing to test. Once merged, we should be able to see the workflow in action in the Actions tab.
> chore: implement auto-merge for dependabot minor/patch updates

- assets/components/src/action-card/style.scss
- assets/components/src/notice/style.scss
- assets/components/src/style-card/style.scss
- assets/components/src/with-wizard-screen/style.scss
- assets/components/src/wizard/style.scss
Small design update to the badges, making them less round with background colour, similar to how new wpcom badges are. Also update the notice background colour to behave fairly similarly.
2. Check components demo
3. Check site design
> Update badge design and notice

- assets/wizards/advertising/views/ad-units/index.js
- includes/configuration_managers/class-newspack-ads-configuration-manager.php
- includes/wizards/class-advertising-wizard.php
Handles a user connection that has multiple GAM accounts and the ability to choose which should be used by Newspack Ads.
See https://github.com/Automattic/newspack-ads/pull/251
> feat(ads): handle multiple GAM accounts

- .github/workflows/auto-merge.yml
#1332 implemented an auto-merge workflow to automatically merge minor and patch update PRs from Dependabot. However, this workflow is [broken](https://github.com/Automattic/newspack-plugin/runs/4428099886?check_suite_focus=true) because the workflow does not grant the necessary write permissions to merge PRs. More details here: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
This PR updates the workflow to run on the suggested `pull_request_target` event, which grants write permissions to actions, but also only runs if the pull request has a "dependencies" label applied, which would indicate that the PR has been opened by a privileged user (in this case, Dependabot). This should guard against [potential …
> chore: fix auto-merge worfklow to grant write permissions

- .github/workflows/auto-merge.yml
The [auto-merge saga](https://github.com/Automattic/newspack-plugin/issues/1323) continues. #1332 implemented auto-merging for minor and patch PRs from Dependabot, and #1341 fixed write permissions for the auto-merge action. However, something is still [missing](https://github.com/Automattic/newspack-plugin/pull/1347#issuecomment-988379465):
I believe this error is happening because the workflow uses the default [`secrets.GITHUB_TOKEN`](https://docs.github.com/en/actions/security-guides/automatic-token-authentication), which by default doesn't grant push permissions. Instead, we need to use a [personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) with `public_repo` push permissions that has been created by a user with push …
> fix: use access token instead of default token

- assets/wizards/popups/index.js
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-popups-wizard.php
Applies the preview-related changes from https://github.com/Automattic/newspack-popups/pull/732 to the Campaigns wizard previewing functionality as well.
With https://github.com/Automattic/newspack-popups/pull/732 checked out, smoke test previewing various segments (including "Everyone") and singular prompts from the Campaigns wizard. All prompts should be previewable as expected.
> fix: use new shortened preview query keys form Campaigns

- assets/wizards/advertising/views/placements/index.js
Adds the checkbox for toggling "Stick to top" for https://github.com/Automattic/newspack-ads/pull/265
Instructions are at https://github.com/Automattic/newspack-ads/pull/265
> feat(ads): stick to top placements

- .github/workflows/auto-merge.yml
The Dependabot auto-merge action is working, but it results an a slightly annoying double comment because of the way we've configured the action. Currently, the auto-merge action is running twice because it's run every time the PR gets labeled, as long as the labels include the `dependencies` label. Auto-merge approves the PR, which results in our other workflow adding a `[Status] Approved` label which in turns triggers the auto-merge action again. `dependencies` still exists as a label on the PR, so the auto-merge action executes again.
This PR attempts to eliminate the second execution by only running if a Dependabot PR has the `dependencies` label and also doesn't have the `[Status] Approved` label.
Can't test, must let the robots do their thing.
> chore: only run auto-merge if the PR is not already approved

- includes/class-plugin-manager.php
- tests/unit-tests/api-plugins-controller.php
- tests/unit-tests/plugin-manager.php
Refactors a couple of unit tests to avoid a `Constant WP_UNINSTALL_PLUGIN already defined` error that results in a failing test suite:
- Most of these errors can be avoided by containerizing the test executions by setting `$preserveGlobalState = false` and `$runTestInSeparateProcess = true` on a unit test class; together, these will force PHPUnit to reset WP to a default state before running each test.
- The one test that still fails after doing this is `test_plugin_install_uninstall_wporg`, because it attempts to run `uninstall_plugin` after that method has already been run in the `setUp` method. I marked this test as skipped to let the suite pass, but left it in place so we can remove the skip once the bug is fixed in Core.
- Because the `plugin-manager` and `api-plugins-controllers` …
> test: refactor unit tests to avoid redefined constant errors

- .circleci/config.yml
- includes/oauth/class-google-oauth.php
- includes/oauth/class-oauth.php
- phpcs.xml
- tests/unit-tests/oauth.php
Fixes a bug introduced in https://github.com/Automattic/newspack-plugin/pull/1247 
PHPCS config & PHPUnit version were updated: to handle function types, and expecting a function to throw, respectively.
1. On `master`, configure Newspack to use Google OAuth via a proxy
2. Authenticate with Google 
3. Observe the access token can't be obtained*
4. Switch to this branch, observe the token can be obtained
\* e.g. edit the value of `_newspack_google_oauth` option, `expires_at` timestamp
> Fix Google token refreshing 

- includes/class-patches.php
`get_post_status` is used to check the validity of posts when preventing accidental page deletion
which time out on some publishers' sites. This replaces it with `get_posts` (used internally in
`get_post_status`) but does the work in this case.
It's a bit hard to reproduce this as it was raised on some publishers sites (e.g. CCP) on the users' list page. `users.php` time out due to the use of `get_post_status` to get the validity of a post when checking user capabilities.
Replacing `get_post_status` by `get_post` fix the timeout. Making sure the `users.php` loads correctly should be enough normally to test this.
> change how we check post validity when preventing page deletion

- includes/class-amp-enhancements.php
Adds handling of a special parameter, for debugging AMP issues. Specifically, this feature will be useful for debugging potential issues caused by AMP Plus mode, which works by marking certain scripts as "kept" in the AMP plugin.
1. Enable AMP Plus mode* and add the Streamlined Donate block** on a page
2. Visit the page, observe the Donate block behaving as expected
3. Append `?newspack-disallow-amp-kept` to the URL, reload the page
4. Observe the block is not interactive, because JS scripts were not loaded
\* Set `NEWSPACK_AMP_PLUS_ENABLED` env. variable to `true`
\** Set Stripe as the Reader Revenue platform
> feat(amp): enable disallowing explicitly kept scripts, for debugging

- includes/wizards/class-reader-revenue-wizard.php
I got a bit overzealous in #1429 with deleting REST API route handlers in the Reader Revenue wizard class. This resulted in accidentally deleting the endpoint for getting donation settings. This PR restores the missing endpoint.
1. On `master`, add a Donate block to a post or page. Observe that the block shows an error message and that the API request to the `/newspack/v1/wizard/newspack-donations-wizard/donation` endpoint fails with a `rest_no_route` error.
2. Check out this branch, refresh, confirm that the error no longer occurs and the Donate block renders correctly.
> fix: restore accidentally-deleted rest route

- includes/class-plugin-manager.php
Fixing the URL for the [AutomateWoo](https://woocommerce.com/products/automatewoo/) extension for WooCommerce; it currently points to [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/) instead.
> AutomateWoo linkfix

- assets/components/src/color-picker/style.scss
This PR updates the ColorPicker component to be ready for when WP 5.9 lands.
1. Update your WP install to 5.9
2. Go to Site Design and test the color picker (it should look slightly broken)
3. Update to this branch and refresh Site Design
4. Switch back your WP install to 5.8.3
5. Refresh Site Design and check if the color picker still works
> Fix Color Picker for WP 5.9

- assets/components/src/modal/style.scss
Small update the the margin/padding of the `Modal`'s header section
1. Update your WP install to 5.9
2. Go to Components Demo and open the modal (the header should look slightly broken)
3. Update to this branch and refresh Components Demo
4. Switch back your WP install to 5.8.3
5. Refresh Components Demo and check if the modal looks fine
> fix: modal header for WP 5.9

- includes/class-patches.php
Fixes a known 504 timeout on a publisher site that seems to be caused by the use of `get_post` in the capabilities check when checking whether an object can be safely deleted.
1. Ensure that special pages (privacy policy, homepage, blog posts page, etc.) still can't be deleted from the WP admin UI
2. Ensure that post lists, user lists, and other admin pages that show a lot of rows can still be viewed without triggering a 504 error
> fix: timeouts due to use of get_post when checking whether to allow deletion

- assets/wizards/engagement/views/newsletters/index.js
- assets/wizards/setup/views/services/index.js
This PR adds all the various Newsletter providers to the onboarding instead of restricting it to Mailchimp.
See https://github.com/Automattic/newspack-newsletters/pull/694
> Display all newsletter providers during the onboarding

- CHANGELOG.md
- includes/class-patches.php
- newspack.php
- package-lock.json
- package.json
Avoids displaying author archive pages for WP users that don't have one of the defined allowed roles, by default:
```
[
'administrator',
'editor',
'author',
'contributor',
]
```
This array of roles is filtered as `newspack_user_roles_with_author_archives` so other plugins can add/remove roles as needed.
Currently, WP will generate author archive pages for all WP users, including subscribers and WooCommerce customers, which most Newspack publishers won't want.
1. Create several users: a Co-Authors Plus guest author, an admin user, an editor user, an author user, a contributor user, and a subscriber user.
2. On `master`, view the author archives for each author type (hint: look at the "View" link in WP admin). Observe that the subscriber gets an author archive like all the others.
3. Check …
> hotfix: disable author archives for subscribers

- assets/other-scripts/salesforce/index.js
- includes/class-salesforce.php
~Not to merged before #1429.~ Ready for review! Extends the WooCommerce admin UI for orders to more conveniently show the orders' sync status with Salesforce, as well as allow admins to manually sync or resync single orders with a button click.
1. Set up a Salesforce connection on your test site (follow instructions on [this page](https://newspack.pub/support/reader-revenue/) to set up a connection, and DM me if you need a Salesforce dev account).
2. Make a test donation as a reader and wait a few minutes.
3. In WP admin > WooCommerce > Orders, find the order corresponding to your test donation.
4. In the Order Actions metabox, verify that you see a new "Salesforce sync status" message with the sync status of your order (will only appear if you have an active Salesforce connection). Also …
> feat(salesforce): ability to manually sync WC orders to salesforce

- includes/reader-revenue/class-stripe-connection.php
Closes #1469
Observe #1469 not reproducible anymore
---
- https://app.asana.com/0/0/1201720730387147
> fix(stripe): prevent webhook processing if platform is not Stripe

- assets/components/src/plugin-settings/SettingsSection.js
- assets/wizards/componentsDemo/index.js
Add support for multiple select (#1287) to the `<PluginSettings.Section />`. A field with `options` and `multiple=true` should render a multiple select.
1. Switch to this branch, visit the components demo
2. Confirm the multiple select is displayed on the example at the bottom of the page
3. Click on multiple values from the select and confirm on the console log the change event with the array values
> feat: support multiple control for plugin settings

- includes/class-amp-enhancements.php
- includes/class-jetpack.php
- includes/class-newspack.php
- includes/class-patches.php
Allow Jetpack Search module to work with AMP Plus.
~~Note that the non-instant search widget filters will continue to not work. Its inputs are controlled through a [hardcoded script](https://github.com/Automattic/jetpack/blob/4ef58afbaba5396902194e5af699c9fe3e520318/projects/packages/search/src/widgets/class-search-widget.php#L544-L595) that we are unable to hook into since it's printed through the widget output.~~
~~Update: d54fd510167de718a8fd3a507affa63001055980 adds full support to the non-instant search widget. It adds AMP Plus attribute to the main `jetpack-search-widget` script and ports a customized script to handle the [sorting controls](https://github.com/Automattic/jetpack/blob/4ef58afbaba5396902194e5af699c9fe3e520318/projects/packages/search/src/widgets/class-search-widget.php# …
> feat: enable AMP Plus for Jetpack Instant Search

- assets/components/src/plugin-settings/SettingsSection.js
- assets/components/src/plugin-settings/index.js
- assets/components/src/text-control/style.scss
- assets/wizards/popups/views/settings/index.js
- includes/configuration_managers/class-newspack-popups-configuration-manager.php
- includes/wizards/class-popups-wizard.php
Refactors the **Campaigns > Settings** wizard page to use the `PluginSettings` component. Requires https://github.com/Automattic/newspack-popups/pull/777.
1. Make sure your Campaigns repo is checked out with https://github.com/Automattic/newspack-popups/pull/777.
2. Visit **Newspack > Campaigns > Settings**.
3. Confirm you see the new settings UI:
4. Change various settings and save, then refresh the page. Confirm that settings are saved as expected.
> feat: use PluginSettings components for Campaigns wizard

- includes/class-patches.php
Fixes a bug introduced in #1474. On author archive pages, the query looks for the user's slug, which is a sanitized form of the user login. For many users slug and login name will look the same, but for users whose slug differs from the login, the fix in #1474 will not work.
1. Create a subscriber user with spaces in the login name (e.g. "Subscriber User"). Ensure they're not assigned as an author to any posts.
2. On `master`, view their archive page and observe that the page does NOT 404 as it should since #1474.
3. Check out this branch and confirm that their archive page now 404s as expected.
---
- https://app.asana.com/0/0/1201790554258200
> fix: lookup user by queried slug, not by login

- includes/configuration_managers/class-parsely-configuration-manager.php
Fixes an issue with Parse.ly config manager (#1207). Instead of checking if `Parsely` class has loaded, use WP core `is_plugin_active` function.
A full test would involve configuring the Parse.ly plugin via Newspack Manager, but I think the changes here is pretty self-explanatory.
> fix(parsely): configuring Parse.ly

- assets/components/src/tabbed-navigation/style.scss
- assets/components/src/with-wizard-screen/index.js
- assets/components/src/wizard/index.js
The TabbedNavigation will be fixed at the top of the screen.
2. Test every screens of the plugin
> Add sticky position to TabbedNavigation

- assets/components/src/with-wizard/style.scss
- assets/wizards/setup/style.scss
Fixes a bug introduced in #1496 (not yet released, but alpha should be updated with these changes).
Also the CSS for this Wizard is moved to the correct place. The only change after the cut-and-paste is line 15.
1. On `master`, visit the welcome screen of Setup wizard (`/wp-admin/admin.php?page=newspack-setup-wizard#/`)
2. Observe that navigation is visible
3. Switch to this branch, observe the navigation is not visible
> fix(setup-wizard): hide navigation on welcome screen

- .circleci/config.yml
For E2E testing, it'll be useful to be able to run tests against the `master` branch versions. For that, the distributable plugin files will have to be built and stored on CI environment.
Since this new job is filtered to be ran on `master` only, so it's not really testable. To verify that it works, I first pushed a commit with the config, before filtering – [visit CI's view of the corresponding build](https://app.circleci.com/pipelines/github/Automattic/newspack-plugin/3523/workflows/0e5d963a-e3af-4079-ae34-e2cf8ae68bbe/jobs/16101/steps), click on the "Artifacts" tab, observe the plugin ZIP is there, available for downloading:
> ci: build plugin files and store as artifact

- CHANGELOG.md
- includes/class-donations.php
- newspack.php
- package-lock.json
- package.json
Fixes the use of `array_intersect_key()` for ensuring the settings keys. The `$defaults` are passed as the first argument, so it always returns the default values instead of the saved settings.
1. While on master, visit the Reader Revenue -> Donations wizard and attempt to edit the "Suggested donations"
2. Observe the changes do not persist on the wizard without presenting any errors
3. Check out this branch and confirm the changes are saved and updated on the wizard
> fix(reader-revenue): return saved settings

- CHANGELOG.md
- includes/class-jetpack.php
- includes/class-patches.php
- newspack.php
- package-lock.json
- package.json
Allow Jetpack modules scripts to render in AMP Plus only when `NEWSPACK_AMP_PLUS_JETPACK_MODULES` constant is defined as `true`.
Also fixes the hook to allow `async`/`defer` script data tags, which was created as a class method but not hooked.
1. Check out this branch and with AMP Plus and Jetpack Instant Search toggled on, confirm the script does not render
2. Add `define( 'NEWSPACK_AMP_PLUS_JETPACK_MODULES', true );` to your `wp-config.php` and confirm the scripts render and Instant Search works as expected
3. Confirm the script tag contains the `async` attribute.
> fix(jetpack): modules scripts behind constant

- assets/components/src/action-card/style.scss
- assets/components/src/checkbox-control/style.scss
- assets/components/src/plugin-settings/SettingsSection.js
- assets/components/src/plugin-settings/index.js
- assets/components/src/plugin-settings/style.scss
- assets/wizards/advertising/components/placement-control/index.js
- assets/wizards/advertising/style.scss
- assets/wizards/advertising/views/placements/index.js
- assets/wizards/popups/views/settings/index.js
- assets/wizards/readerRevenue/views/salesforce/index.js
* Lightened `hasGreyHeader`
* Moved "Saved Settings" button to top region
* Updated the number of columns
* Removed `hasGreyHeader` from the placement's `ActionCard`s
* Updated `PlacementControl`'s label
__After__
__Before__
2. Go to the Ads Wizard
3. Test the Placements and Settings
4. Go to the Campaigns Wizard
5. Test the settings
> Update Ads and Campaigns ActionCards style

- includes/class-patches.php
This PR fixes an issue on all our sites running The Events Calendar. On those sites, sometimes the same date will show as the published date on all posts block items. I've tracked it down to [some excerpt processing that TEC does](https://github.com/the-events-calendar/the-events-calendar/blob/77910c9de7f5640064d4eef4eb4841a523f27719/src/Tribe/Views/V2/Template/Excerpt.php#L116) while trying to avoid an infinite loop. My understanding reading their source code is that the processing is mainly for the twentyseventeen theme, so shouldn't be an issue to unhook it.
1. Install and activate The Events Calendar (free version from wporg). In the Display settings, use 'Tribe Event Styles' and 'Default Events Template':
2. Set up a homepage with posts blocks **with excerpts toggled on**. Make sure …
> Fix posts block date issues when running The Events Calendar

- assets/wizards/handoff-banner/index.js
- includes/class-handoff-banner.php
Avoids a hard crash in the Site Kit Analytics UI when coming from the Newspack Analytics wizard. Unfortunately, the fix causes the Newspack banner to "return to Newspack" to be invisible, but it at least avoids the crash.
Closes #1529.
Test that #1529 is no longer reproducible with this branch, and that other `HandoffBanner` instances are unaffected/unchanged.
> fix(analytics): avoid Site Kit crash due to conflict with HandoffBanner

- includes/starter_content/class-starter-content-provider.php
Closes #1538.
Starter homepage still gets a meta assigned, so it's identifiable (and not re-created when re-running the setup). 
Observe #1538 not reproducible.
> fix(starter-content): prevent starter homepage deletion

- includes/class-starter-content.php
Closes #1134.
Makes `header_solid_background` and `header_simplified` theme mods `false` by default, as they are in the Theme:
- [`header_solid_background`](https://github.com/Automattic/newspack-theme/blob/f3b2347f3c9c9622738394093dc25f8dfa945311/newspack-theme/inc/customizer.php#L75-L82)
- [`header_simplified`](https://github.com/Automattic/newspack-theme/blob/f3b2347f3c9c9622738394093dc25f8dfa945311/newspack-theme/inc/customizer.php#L93-L100)
Observe #1134 is not reproducible
> fix(design): header defaults in line with the theme

- includes/class-patches.php
Changes the capability needed to access the Posts > Reusable Blocks menu item from `read` to `edit_posts`, so that Subscriber-level users can't see it.
Changes the `add_submenu_page` on line 84 to use `edit_posts` instead of `read` capability.
1. Log into a Subscriber account.
2. The "Posts" menu item in the WordPress dashboard should be absent.
> Fix/Reusable Blocks menu item minimum capability

- includes/class-patches.php
Fixes some issues caused by a bad conflict resolution after the last post-release job.
Ensure the plugin builds and that the fixes from #1541 and #1518 are intact. Also that all CI jobs below are passing. 👇
> fix: a bad merge after the last post-release job
